fix issue-1
akashic-games/akashic-cli pull request #10
Opened 2017-03-01 08:59 UTC by xtity

## このpull requestが解決する内容
* https://github.com/akashic-games/akashic-cli/issues/1
  * `akashic help export` や `akashic export --help` 等のコマンドが入力された時にメッセージを出すように修正しました
* .gitignoreに.vscodeを追加しました

## 破壊的な変更を含んでいるか?
なし

2017-03-01 09:57 UTC, xnv requested changes

2017-03-01 09:57 UTC, xnv commented on bin/akashic-export
> +`);
- これはスタイルの問題かもしれませんが、複数行文字列リテラルのためにコードのインデント構造を壊すのは抵抗があります……！　普通に複数回 `console.log()` するか、文字列配列を join() する (`["aaa", "bbb", ...].join("\n")`) するかしませんか……！
  - 参考: commander.js のヘルプ出力生成処理(joinしてます) 
https://github.com/tj/commander.js/blob/master/index.js#L1027
  - (伝統的にヒアドキュメントはインデント構造を破壊する構文でしたが、最近の Ruby なんかは `<<~` とか作りましたよね)
- このメッセージだけ見て使い方がわかるかどうか若干気になります。たとえば akashic-sandbox で --help を叩くとこんなのが出てくるので、 "Usage" みたいな出力もつけてこのぐらいの情報量にしませんか。

```
$ akashic-sandbox --help

  Usage: akashic-sandbox [options] <game path>

  Options:

    -h, --help                 output usage information
    -V, --version              output the version number
    --cascade <path>           path to contents to cascade
    -p, --port <port>          number of listen port. default 3000
    -s, --scenario <scenario>  scenario file
```

2017-03-01 10:52 UTC, xtity commented on bin/akashic-export
> +`);
> これはスタイルの問題かもしれませんが、複数行文字列リテラルのためにコードのインデント構造を壊すのは抵抗があります……！

なるほど…。
ヒアドキュメントを使わないというのは、なかなか強いご意見ですね。

このプロジェクトとは違って、例えば、SQLを扱うD層のクラスを考えた場合、
ヒアドキュメントが使えると実行するクエリがそのままコードに乗ったりするので、
クエリの確認のしやすさや、保守しやすさが結構上がると個人的には思っています。

加えて、文字列の連結や出力の連続実行も、
文字列連結によるオーバーヘッド、I/Oの回数増による性能面や、
そもそもどんな文字列を出力したいのかがひと目で分からなくなる面等が、
これも個人的にはやや気になってしまいます。

なので、ヒアドキュメント有りにできればしたい感があります。

> このメッセージだけ見て使い方がわかるかどうか若干気になります。たとえば akashic-sandbox で --help を叩くとこんなのが出てくるので、 "Usage" みたいな出力もつけてこのぐらいの情報量にしませんか。

上記のような出力はcommander.jsが使えれば楽なのですが、
当該ファイルではそれができないため、このようなメッセージにしました。

また、書き味としては下記を参考にしました。
https://github.com/akashic-games/akashic-cli-scan/blob/master/src/cli.ts

2017-03-01 13:22 UTC, lambdataro commented on bin/akashic-export
> +`);
個人的には xtity さんに同意で、ヒアドキュメントありにしたいです。
前もどこかで言ったことがありますが、実行時に動的に連結する意図が無いものをコード上で連結操作すると、書いた人の意図を読み取るのに苦労します。(例えば片方が変数等であればその限りではありませんが)

2017-03-01 13:23 UTC, lambdataro approved these changes

2017-03-02 02:56 UTC, kamakiri01 commented on bin/akashic-export
> +`);
個人的な読みやすさとしては、インデントが維持された上で、複数回のconsole.log()、join、あるいはヒアドキュメントなどで記述してもらいたいです。

自分の意見で書くと以下のような感じです。
```
} else if (type) {
    ["Usage: akashic  export [format] [options]",
    "Formats:", 
      "  html   convert runnable standalone",
      "  zip    cmpress zip archive"
    ].join("\n")
}
```

それはそれとしてakashic scan のTargetはもう少し利用者が理解しやすい出力を出してやるべきだと思います。
これについてはIssueを切っても良いかもしれません。

2017-03-02 04:27 UTC, xnv commented on bin/akashic-export
> +`);
> 上記のような出力はcommander.jsが使えれば楽なのですが、当該ファイルではそれができないため、このようなメッセージにしました。

commander.js を使ってちゃんと独立したコマンドにしていないのはこれまでの我々の手抜きなので、その影響を引き受けていただいて恐縮ではあるんですが、とはいえそれはユーザの責に帰すべきものではないと思います。特にこの箇所はヘルプメッセージであり、「楽すべきなのは実装者ではなく、ユーザであるゲーム開発者だ」というのは合意しておきたいです。

ちなみに参照されているのは akashic scan のコードは、 `akashic scan asset --help` で表示されるものですが、こうなります。

```
$ akashic scan asset --help

  Usage: asset [options] [target]

  Update 'assets' property of game.json

  Options:

    -h, --help       output usage information
    -C, --cwd <dir>  The directory incluedes game.json
    -q, --quiet      Suppress output

  Target:

    image
    audio
    script
    text
    all
```

2017-03-02 08:26 UTC, xnv commented on bin/akashic-export
> +`);
インデントを破壊するヒアドキュメントに関して、別でご相談して概ね議論は尽くせたかと思います。以下のように認識しました:

- メリット (実行時効率や一部状況における編集容易性など) とデメリット (インデントの破壊) がある選択である
- 本件は実行時パフォーマンスが問題になるシステムやユースケースではない
- 他方、デメリットの評価は感覚的にしかなりえない (インデントの破壊をまったく気にしない人も強く気にする人もいる)

……ということで、これは残念ながら最後は恣意的に決定せざるを得ない問題かと思います。独断になって恐縮ですが、「インデントを破壊しない」をこの akashic-cli のポリシーとさせていただきたいです。もちろん異なる技術的背景や慣習を持つシステム・レポジトリにおいてはこの限りではないと思っています。

2017-03-02 11:38 UTC, xtity commented
レビュー対応の反映が完了しました。

2017-03-03 09:27 UTC, xnv approved these changes

2017-03-07 07:04 UTC, merged