Enable strict for extra
akashic-games/akashic-cli pull request #1000
Opened 2022-02-02 03:55 UTC by ShinobuTakahashi

## 概要

akashic-cli-extra で strict を有効化します。

2022-02-02 13:54 UTC, kamakiri01 commented on packages/akashic-cli-extra/src/stat/stat.ts
>  function sizeOfAssets(param: StatSizeParameterObject, sizeResult: SizeResult): Promise<void>[] {
imo: 以下のようにすれば各case文の `asset!.path` から `!` を外せそうです。
```
	if (param.game.assets == null) return [];
	const assets = param.game.assets;
	const keys = Object.keys(assets) as (keyof typeof assets)[];
	return keys.map(key => {
		const asset = assets[key]!;
		switch (asset.type) {
```

2022-02-03 01:58 UTC, ShinobuTakahashi commented on packages/akashic-cli-extra/src/stat/stat.ts
>  function sizeOfAssets(param: StatSizeParameterObject, sizeResult: SizeResult): Promise<void>[] {
ありがとうございます。 ご指摘の方法で `!` case 文の `!` 外せました。

2022-02-03 02:57 UTC, xnv requested changes

2022-02-03 02:57 UTC, xnv commented on packages/akashic-cli-extra/src/stat/stat.ts
> +				throw new Error(`${asset!.type} is not a valid asset type name`);
必要でしょうか？　ここでダメなら [L193](https://github.com/akashic-games/akashic-cli/pull/1000/files#diff-4c0f06252b0088f9ad47c36c701ba397aa2a6d64fd3f4a7108cf839f6808511dR193) で引っかかっていそうですが。

2022-02-03 02:57 UTC, xnv commented on packages/akashic-cli-extra/src/stat/stat.ts
>  	if (param.game.assets == null) return [];
元からですがこれなんで戻り値 `Promise<void>` なのに `[]` を返すんですっけ……？

2022-02-03 02:57 UTC, xnv commented on packages/akashic-cli-extra/src/stat/stat.ts
>  function sizeOfAssets(param: StatSizeParameterObject, sizeResult: SizeResult): Promise<void>[] {
`const asset = assets[key]!;` した時点で `keyof` に関係なく `asset.path` できるのでは……？

2022-02-03 02:57 UTC, xnv commented on packages/akashic-cli-extra/src/stat/cli.ts
> +	const target = param.args!.length > 0 ? param.args![0] : "(empty)";
これ絶対あるんですっけ？ (commander の仕様とかに依存するのでは？)

ここで `!` できる (＝そもそも省略可能でない) なら型定義の方で `?` を外したいです。もし commander 由来とかで型定義の方がかえられないなら、省略される場合も踏まえて `param.args?.length` にしたいです。

2022-02-03 02:57 UTC, xnv commented on packages/akashic-cli-extra/src/modify/modify.ts
> +	const restoreDirectory = cmn.Util.chdir(param.cwd!);
これ都度 `!` をつけて回るのは安全でないので、型的にちゃんと「必ずある」ことを保証したいです。

init の `InitParameterObject` に対する [`NormalizedInitParameterObject`](https://github.com/akashic-games/akashic-cli/blob/master/packages/akashic-cli-init/src/init/InitParameterObject.ts#L59) と [`normalizeInitParameterObject()`)[https://github.com/akashic-games/akashic-cli/blob/master/packages/akashic-cli-init/src/init/InitParameterObject.ts#L64] と同じように、「正規化済み」の型を作ってそちらで処理しませんか。

2022-02-03 03:04 UTC, kamakiri01 commented on packages/akashic-cli-extra/src/stat/stat.ts
>  function sizeOfAssets(param: StatSizeParameterObject, sizeResult: SizeResult): Promise<void>[] {
確かに以下に整理できそうです。
```
	if (param.game.assets == null) return [];
	const assets = param.game.assets;
	return Object.keys(assets).map(key => {
		const asset = assets[key]!;
		switch (asset.type) {
```

2022-02-04 01:43 UTC, ShinobuTakahashi commented on packages/akashic-cli-extra/src/stat/stat.ts
>  function sizeOfAssets(param: StatSizeParameterObject, sizeResult: SizeResult): Promise<void>[] {
ありがとうございます。修正しました。

2022-02-04 01:43 UTC, ShinobuTakahashi commented on packages/akashic-cli-extra/src/stat/stat.ts
> +				throw new Error(`${asset!.type} is not a valid asset type name`);
ありがとうございます。不要のため削除しました。

2022-02-04 01:43 UTC, ShinobuTakahashi commented on packages/akashic-cli-extra/src/stat/stat.ts
>  	if (param.game.assets == null) return [];
こうなった経緯がわかりませんが、下記箇所の引数が `Promise<void>[]` となっているためかと思います。 
https://github.com/akashic-games/akashic-cli/blob/30f9a33f6ae68192d7cf4afa5bbe850c48c35ed9/packages/akashic-cli-extra/src/stat/stat.ts#L269

2022-02-04 01:43 UTC, ShinobuTakahashi commented on packages/akashic-cli-extra/src/stat/cli.ts
> +	const target = param.args!.length > 0 ? param.args![0] : "(empty)";
commander の定義では `args: string[];`  なので コマンド引数なくても空配列が返ります。
commons の型定義 `CliConfigStat` の方で `?` を外しました。

2022-02-04 01:43 UTC, ShinobuTakahashi commented on packages/akashic-cli-extra/src/modify/modify.ts
> +	const restoreDirectory = cmn.Util.chdir(param.cwd!);
型 `NormalizedModifyBasicParameterParameterObject` を定義し、その型を使うよう修正しました。

2022-02-04 02:07 UTC, xnv commented on packages/akashic-cli-extra/src/stat/stat.ts
>  	if (param.game.assets == null) return [];
いやすいません誤読でした。戻り値型 `Promise<void>` ではなく `Promise<void>[]` でしたね。 (それなら普通 `Promise.all()` でまとめそうなもんではという気がしますが、というか多分それで見間違いましたが、少なくとも矛盾はない)

2022-02-08 04:55 UTC, xnv approved these changes

2022-02-10 09:51 UTC, kamakiri01 approved these changes

2022-02-16 04:23 UTC, ShinobuTakahashi commented
最新の commons を取り込み CI が正常終了する事を確認済み

2022-02-16 04:23 UTC, merged