publish後に動作確認するためのスクリプトを作成
akashic-games/akashic-cli pull request #101
Opened 2019-06-18 23:51 UTC by dera-

### 概要
* publish後に一通りのakashic cliコマンドを実行して簡易的に動作確認するスクリプトを作成しました。
* また、その際に`akashic init`をユーザー入力無しで実行可能にする必要があったので、akashic-cli-initにユーザー入力せずにデフォルトの値でプロジェクトを作成するyesオプションを追加しました。

2019-06-19 12:24 UTC, xnv requested changes

2019-06-19 12:24 UTC, xnv commented on test/testAfterPublish.js
> +	shell.mkdir("-p", [`/tmp/${dirName}`, `/tmp/${dirName}/game`]);
Windows 環境で動作しないのではありませんか。 `fs.mkdtemp()` あたりを利用する必要があると思います。

2019-06-19 12:24 UTC, xnv commented on test/testAfterPublish.js
> +function exit(isSuccess) {
`exit()` で成功時に true を渡されると一瞬びっくりするので `quit()` とかにしておきませんか。(`process.exit()` に `true` だと異常終了扱いになるはずで、意味合いが逆転しているので……)

2019-06-19 12:24 UTC, xnv commented on test/testAfterPublish.js
> +// publish後にakashic-cliが一通り動作することを確認するためのスクリプト
- 「このリポジトリのコードをテストするのではなく、publish されたものを確認するスクリプトである点に注意」という注意を加えておきたいです。

2019-06-19 12:24 UTC, xnv commented on packages/akashic-cli-init/src/cli.ts
> +	.option("-y, --yes", "Generate project without user input");
initialize という他の箇所の語彙と generate が食い違ってしまっているのが気になります。 `Initialize without user input` にしておきませんか。

2019-06-19 12:24 UTC, xnv commented on test/testAfterPublish.js
> +	execSync(`${akashicCliPath} zip --strip --bundle`);
この辺、終了コードを確認することはできないでしょうか。

2019-06-19 12:24 UTC, xnv commented on test/testAfterPublish.js
> +function assert(actual, expected) {
あまりこだわるつもりはないんですが、 この辺 Node.js の `assert` 系関数では不足でしょうか。クリーンナップ処理は `process.on("exit", ...)` で書けそうに見えます。(非同期処理をするなら `beforeExit` になりそうですが、いずれにせよ)

2019-06-24 10:17 UTC, dera- commented on test/testAfterPublish.js
> +function exit(isSuccess) {
了解しました。関数名を修正しておきます

2019-06-24 10:17 UTC, dera- commented on test/testAfterPublish.js
> +// publish後にakashic-cliが一通り動作することを確認するためのスクリプト
追記しておきます

2019-06-24 10:18 UTC, dera- commented on packages/akashic-cli-init/src/cli.ts
> +	.option("-y, --yes", "Generate project without user input");
了解しました、修正しておきます。

2019-06-24 10:20 UTC, dera- commented on test/testAfterPublish.js
> +	shell.mkdir("-p", [`/tmp/${dirName}`, `/tmp/${dirName}/game`]);
windowsでも`/tmp`相当のディレクトリを使用したいだけなので`os.tmpdir()`を利用するように修正します

2019-06-24 10:24 UTC, dera- commented on test/testAfterPublish.js
> +	execSync(`${akashicCliPath} zip --strip --bundle`);
`execSync`だとできないですね。。`spawnSync`であれば終了コードも取得できるようですが、`spawnSync`に変更した方が良いでしょうか？
終了コードが0かそうでないかだけで判定できればよいのではと思って`execSync`を使用しているのですが、それだけだと不足な場合は`spawnSync`に変更します

2019-06-24 10:25 UTC, dera- commented on test/testAfterPublish.js
> +function assert(actual, expected) {
assert系の関数を使う用に修正します。またディレクトリの削除も`process.on("exit", ...)`で行うように修正します

2019-07-02 10:26 UTC, xnv commented on test/testAfterPublish.js
>  const dirName = "test-akashic-cli_" + Date.now();
これでも問題はほぼなさそうですが、 `fs.mkdtemp()` があるのでそちらを使いませんか。

2019-07-02 10:31 UTC, xnv commented on test/testAfterPublish.js
> +	execSync(`${akashicCliPath} zip --strip --bundle`);
あ、非 0 かどうかさえわかればいいんですが、非 0 の場合は例外が飛ぶんですね。私が勘違いしていました。

2019-07-02 15:15 UTC, dera- commented on test/testAfterPublish.js
>  const dirName = "test-akashic-cli_" + Date.now();
了解しました、そちらの利用を検討してみます

2019-07-03 05:42 UTC, xnv approved these changes

2019-07-05 04:49 UTC, kamakiri01 approved these changes

2019-07-05 06:57 UTC, merged