Enable "use strict" and Add Notification component
akashic-games/akashic-cli pull request #102
Opened 2019-06-19 04:11 UTC by yu-ogi

## このPullRequestが解決する内容
* `"use strict";` をユーザスクリプトに対して有効にします。
* エラー通知のためのコンポーネント `Notification` を追加します。

2019-06-19 04:13 UTC, yu-ogi commented on packages/akashic-cli-serve/src/client/store/NotificationType.ts
> +export type NotificationType = "warn";
`ExecutionMode` に倣って通知種別をこちらに定義しています。
現状 `"warn"` のみ対応します。

2019-06-19 04:14 UTC, yu-ogi commented on packages/akashic-cli-serve/src/client/view/atom/Notification.css
> +.notification-body-main {
sass を使えばもう少し構造的にかけそうですが、現状サポートしていないので css でべた書きしています。

2019-06-19 04:15 UTC, yu-ogi commented on packages/akashic-cli-serve/src/client/view/container/NotificationContainer.tsx
> +export class NotificationContainer extends React.Component<NotificationContainerProps, {}> {
名前が微妙ですが error をハンドルするコンポーネントを `NotificationContainer` と定義してみました。

2019-06-19 09:14 UTC, xnv requested changes

2019-06-19 09:14 UTC, xnv commented on packages/akashic-cli-serve/src/client/view/container/NotificationContainer.tsx
> +		this.props.notificationStore.show(
- store はあくまで表示用にして、storeの操作は operator を噛ませたいです (`operator.handleWindowError()` 、とか？)。こいつ自身は「エラーを operator に通知する」のを責務にしたいというか。
- store が show/hide といった view 直結の能動的な動詞を持っているのはやや違和感があります。あくまでも store に対してできるのは、「エラー情報を追加する」とかではありませんか。store が保持したエラー情報が、 show されるかどうかは、 store の責務ではないと思います。 (たとえば直前 3 つの通知以外は勝手に消えるような UI にするかもしれませんが、そのことは store が保持しているエラーデータとは独立でしょう)

2019-06-19 09:14 UTC, xnv commented on packages/akashic-cli-serve/src/client/view/container/NotificationContainer.tsx
> +			"エラーが発生しました",
warn とエラーが混在していて使い分けが気になります。

<strike>「コンテンツのエラー」は「serve にとっては警告にすぎない」ということなのではないかと思いますが、そうであれば、「コンテンツにエラーが発生しました」にしたいです。</strike> ……と書いていて気づきましたが、 window.addEventListener() で検知する以上どこ由来かは判断しにくいですね。諦めて error に揃えるのが自然だったりはしませんか。

2019-06-19 09:14 UTC, xnv commented on packages/akashic-cli-serve/src/client/view/container/NotificationContainer.tsx
> +export class NotificationContainer extends React.Component<NotificationContainerProps, {}> {
この名前に同意します。ただしコメントが欲しいです。

このコンポーネントの責務は、
1. notificatonStore の内容を表示する (`Notification` に流し込んで表示させる)
2. 表示した UI への操作を operator に通知する
3. window の error を監視して operator に通知する

で、この名前 `NotificationContainer` は 1 と 2 を表すのに適当な名前だと思います。 3 は「独立のコンポーネントを新設するほどの処理でもないので、手近なところに押し込んでいる」という形に思えます。

なので、 `addEventListener()` しているあたりに、コメントとして「このコンポーネントの責務とは少し違うが、適当な置き場もないのでここに置いておく」といった内容があると良さそうに思えます。

2019-06-19 09:14 UTC, xnv commented on packages/akashic-cli-serve/src/client/view/atom/Notification.css
> +.notification-body-main {
CSS のスコープ切れてるので全部に notification をつけて回らなくてもいいとは思います (こだわりません; コンポーネントが切れていれば複雑度が重複するような話ではないので)

2019-06-19 09:14 UTC, xnv commented on packages/akashic-cli-serve/src/client/store/NotificationStore.ts
> +	@observable isShown: boolean;
別コメントと少し重複しますが、 `isShown` レベルで表示内容と密結合するデータを持つなら `NotificationUiStore` にしたいです。 `NotificationStore` と呼ぶなら、それは表示とは独立な「通知されるべき情報の集合」の管理に終始すべきに思えます。(どちらがいい悪いではないですが、より抽象度が高いのが `NotificationStore` になると思います。)

2019-06-20 01:45 UTC, yu-ogi commented on packages/akashic-cli-serve/src/client/view/container/NotificationContainer.tsx
> +export class NotificationContainer extends React.Component<NotificationContainerProps, {}> {
https://github.com/akashic-games/akashic-cli/pull/102/commits/9c28792950e47b9bc0165572da7f9d5b87526071 上記の旨をコメント追加しました。

2019-06-20 01:48 UTC, yu-ogi commented on packages/akashic-cli-serve/src/client/view/container/NotificationContainer.tsx
> +			"エラーが発生しました",
https://github.com/akashic-games/akashic-cli/pull/102/commits/d9fe38cb86c1f718b78ac459e5eaf8eb338af7f2 error に修正しました。

2019-06-20 01:49 UTC, yu-ogi commented on packages/akashic-cli-serve/src/client/store/NotificationStore.ts
> +	@observable isShown: boolean;
https://github.com/akashic-games/akashic-cli/pull/102/commits/abc4f703988ebf619f27621f359860b4a1e9109b NotificationUiStore にリネームしました

2019-06-20 02:10 UTC, yu-ogi commented on packages/akashic-cli-serve/src/client/view/container/NotificationContainer.tsx
> +		this.props.notificationStore.show(
https://github.com/akashic-games/akashic-cli/pull/102/commits/abc4f703988ebf619f27621f359860b4a1e9109b すこし迷いましたが、通知は一つのみを前提として store には setActive(), setInactive() を新設し、 view からはそれを参照して show/hide を決めるように改めました。

2019-06-20 10:04 UTC, xnv approved these changes

2019-06-21 04:14 UTC, dera- approved these changes
labelの設定だけお願いします(おそらく`enhancement`？)

2019-06-24 01:21 UTC, merged