keep audio asset has offset param
akashic-games/akashic-cli pull request #1183
Opened 2022-12-05 13:24 UTC by kamakiri01

## このpull requestが解決する内容

scanコマンドでオーディオアセットをgame.jsonに反映する際に、既にgame.jsonのassetに書き込まれているオーディオアセットが `offset` 要素を持っている場合、そのオーディオアセットの更新をスキップします。
この修正により、オフセット位置指定されたおーディアセットの情報が意図せず上書きされないようになります。
関連: https://github.com/akashic-games/pdi-types/pull/28

## 破壊的な変更を含んでいるか?

- なし

2022-12-27 01:50 UTC, yu-ogi requested changes
* .m4a がスキャンできることを確認するためのテスト
* offset を指定していた場合はそれが引き継がれることを確認するためのテスト

は最低限欲しいです。

2022-12-27 01:50 UTC, yu-ogi commented on packages/akashic-cli-scan/spec/src/scanAssetSpec.ts
> +			},		]);
インデント確認ください。

2022-12-27 01:50 UTC, yu-ogi commented on packages/akashic-cli-scan/src/scanAsset.ts
> +			scannedAssets.push(...storeExistingAsset(scannedAudioAssets, definedAssets));
こちら下の `AssetModule.merge()` のロジックとして組み入れることは難しいでしょうか。コードのあちこちにマージのロジックが分散してしまうと、リファクタリングする前の akashic-cli-scan のように保守性が著しく落ちてしまうのでできれば一元化したいです。

例えば下の箇所で「`offset` があればそれを利用する (`storeExistingAsset()` 相当の処理を行う)」というように修正できないでしょうか。

https://github.com/akashic-games/akashic-cli/blob/ca36e9190d3b724db29a1dec1a5fbda97d86c0dd/packages/akashic-cli-scan/src/AssetModule.ts#L108-L116

2023-01-10 13:33 UTC, kamakiri01 commented on packages/akashic-cli-scan/spec/src/scanAssetSpec.ts
> +			},		]);
修正します。

2023-01-10 13:34 UTC, kamakiri01 commented on packages/akashic-cli-scan/src/scanAsset.ts
> +			scannedAssets.push(...storeExistingAsset(scannedAudioAssets, definedAssets));
ロジックをまとめることに異論ないです。
また、`AssetModule.merge()` の実装を見ると `...old,` で既に offset を引き継げるようなので、新しい実装を入れる必要はなさそうでした。

2023-01-11 04:08 UTC, yu-ogi commented on packages/akashic-cli-scan/src/scanAsset.ts
> +	textAssetFilter } from "./scanUtils";
こちら他と合わせて以下のようなインデントにしておきたいです。
```js
import {
  ...
} from "..."
```

2023-01-11 04:08 UTC, yu-ogi commented on packages/akashic-cli-scan/src/getAudioDuration.ts
>  		logger?.warn("[deprecated] " + path.basename(filepath) + " uses deprecated format. Use AAC instead of MP4(AAC).");
.m4a を deprecated と表現するのは妥当なのですかね?

2023-01-11 08:16 UTC, kamakiri01 commented on packages/akashic-cli-scan/src/getAudioDuration.ts
>  		logger?.warn("[deprecated] " + path.basename(filepath) + " uses deprecated format. Use AAC instead of MP4(AAC).");
m4aに出すのは妥当ではないですね…直します。

2023-01-11 08:16 UTC, kamakiri01 commented on packages/akashic-cli-scan/src/scanAsset.ts
> +	textAssetFilter } from "./scanUtils";
直します。
改行しているのは作業中に140字を超えていたためだと思いますが、今の記述はmax-lenの範囲に収まるので1行に均してしまおうと思います。

2023-01-12 01:46 UTC, yu-ogi approved these changes

2023-01-12 01:46 UTC, yu-ogi commented on packages/akashic-cli-scan/src/scanAsset.ts
> +import {scanAudioAssets, scanImageAssets, scanScriptAssets, scanTextAssets, scanVectorImageAssets,　textAssetFilter} from "./scanUtils";
こちら不要な差分かと思います。

2023-01-12 02:18 UTC, yu-ogi commented on packages/akashic-cli-scan/spec/src/scanAssetSpec.ts
> +		// AAC利用のwarnが2つ + duration差のwarnが1つ + アセット追加のログが1つ + Done!のログが1つ
あ、こちらも不要か思います。

2023-01-12 14:10 UTC, kamakiri01 commented on packages/akashic-cli-scan/src/scanAsset.ts
> +import {scanAudioAssets, scanImageAssets, scanScriptAssets, scanTextAssets, scanVectorImageAssets,　textAssetFilter} from "./scanUtils";
削除します。

2023-01-12 14:10 UTC, kamakiri01 commented on packages/akashic-cli-scan/spec/src/scanAssetSpec.ts
> +		// AAC利用のwarnが2つ + duration差のwarnが1つ + アセット追加のログが1つ + Done!のログが1つ
不要になってました。削除します。

2023-01-16 04:36 UTC, xnv approved these changes
コメント加えていますが approved.

2023-01-16 04:36 UTC, xnv commented on packages/akashic-cli-scan/src/getAudioDuration.ts
> +			logger?.warn("[deprecated] " + path.basename(filepath) + " uses deprecated format. Use AAC instead of MP4(AAC).");
`Use AAC or M4A instead of` にしたいです。

2023-01-16 04:36 UTC, xnv commented on packages/akashic-cli-scan/src/watchAsset.ts
>  }
どうせならこれもなくして `iamgeAssetFilter()` にしてしまいませんか。

2023-01-16 12:27 UTC, kamakiri01 commented on packages/akashic-cli-scan/src/getAudioDuration.ts
> +			logger?.warn("[deprecated] " + path.basename(filepath) + " uses deprecated format. Use AAC instead of MP4(AAC).");
修正します。

2023-01-16 12:34 UTC, kamakiri01 commented on packages/akashic-cli-scan/src/watchAsset.ts
>  }
そうですね、共通化します。

2023-01-17 13:26 UTC, merged