akashic-cli-initのランキング対応新市場コンテンツテンプレートの修正
akashic-games/akashic-cli pull request #124
Opened 2019-07-31 05:07 UTC by dera-

### 概要
akashic-cli-initのランキング対応新市場コンテンツテンプレートに対して以下の修正を行いました。
* sessionParameterとして共通乱数シード値を利用した乱数生成オブジェクト(random)を追加
  * 共通乱数シード値を受け取って乱数生成オブジェクトを生成する処理はほぼ一意に決まっているのでテンプレート内部で隠蔽した方が利便性があると判断しました
* sessionParameterから不要なプロパティ(playThreshold, clearThreshold)の削除

2019-07-31 05:33 UTC, yu-ogi commented on packages/akashic-cli-init/templates-src/game-shin-ichiba-ranking/src/parameterObject.ts
> +		random?: g.RandomGenerator;
- `param.sessionParameter` と `msg.data.parameters` で微妙に異なる仕様となり混乱しそうな気がしました。 
random generator を生成するなら `isAtsumaru` と同じ階層に含めてしまった方が良さそうに思います。
- `sessionParameter.randomSeed` が与えられなかった場合は `g.game.random` を利用しているので optional にはならないかと思います。

2019-08-01 05:25 UTC, xnv requested changes

2019-08-01 05:25 UTC, xnv commented on packages/akashic-cli-init/templates-src/game-shin-ichiba-ranking/src/parameterObject.ts
> +		random?: g.RandomGenerator;
同意です。 `random` は `param.random` にしておくのがいいと思います。(これも実は悩ましくて、ユーザから見た動作だけ考えるとむしろ `g.game.random` を上書きする方がしっくりくる可能性もあります)

2019-08-02 05:53 UTC, yu-ogi commented on packages/akashic-cli-init/templates-src/game-shin-ichiba-ranking/src/parameterObject.ts
> -		randomSeed?: number;
randomSeed は必要だと思います。

2019-08-02 06:05 UTC, dera- commented on packages/akashic-cli-init/templates-src/game-shin-ichiba-ranking/src/parameterObject.ts
> +		random?: g.RandomGenerator;
確かに、`param.sessionParameter`に存在しないものを追加するのも違う気がしますし、混乱を生みそうですね。。
こちら、`param.random`で乱数生成器を持つように変更しました(`g.game.random`を上書きした方がより手軽な感じはしますが、暗黙的な処理は混乱を生みそうな気もするのでこちらの方向で修正しました。)

2019-08-02 06:05 UTC, dera- commented on packages/akashic-cli-init/templates-src/game-shin-ichiba-ranking/src/parameterObject.ts
> -		randomSeed?: number;
あ、、確かに仰る通りですね。こちらは戻しておきます

2019-08-08 03:12 UTC, yu-ogi approved these changes
一点だけコメントしましたが approved です。

2019-08-08 03:12 UTC, yu-ogi commented on packages/akashic-cli-init/templates-src/game-shin-ichiba-ranking/src/_bootstrap.ts
> +			if (msg.data.parameters.randomSeed) {
randomSeed が 0 の時にスキップされてしまうので `msg.data.parameters.randomSeed == null` の方が適切かなと思いました。

2019-08-08 05:53 UTC, dera- commented on packages/akashic-cli-init/templates-src/game-shin-ichiba-ranking/src/_bootstrap.ts
> +			if (msg.data.parameters.randomSeed) {
了解しました、こちら修正しておきます。

2019-08-08 06:00 UTC, dera- commented on packages/akashic-cli-init/templates-src/game-shin-ichiba-ranking/src/_bootstrap.ts
> +			if (msg.data.parameters.randomSeed) {
あ、`msg.data.parameters.randomSeed !=null`ですかね

2019-08-28 05:09 UTC, xnv approved these changes

2019-08-30 04:11 UTC, merged