[WIP] --target-serviceオプション機能の追加
akashic-games/akashic-cli pull request #125
Opened 2019-07-31 10:21 UTC by ShinobuTakahashi

## 内容

**`--target-service` オプションの追加。**
- 最初に開いたブラウザを放送者としてjoinした状態で起動します。
- インスタンスの追加の場合は視聴者として非joinの状態で起動します。
- このオプションを付与した場合、join/leaveボタンは押下不可(disabled)となります。

**`--no-auto-start` と併用となるる場合**
- 最初に開いたブラウザを放送者(join状態)とするため、`New Instance` ダイアログの joinのチェックボックスはチェック状態とし編集不可(disabled)となります。
- インスタンスの追加の場合は視聴者(非join状態)とするため、`New Instance` ダイアログのチェックボックスは 非チェック状態とし編集不可(disabled)となります。

2019-07-31 10:23 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/README.md
> +npm run copy:agv
PRの内容とは関係ないが、気付いたので修正。

2019-07-31 10:27 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/client/store/StartupScreenUiStore.ts
> +	@observable isJoinDisabled: boolean;
@observable/@action である必要がない...  privateにしてget/setで済む気がしてきた。

2019-07-31 10:28 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/client/store/StartupScreenUiStore.ts
> +		this.isJoinDisabled = false;
`Operator.setCurrentPlay` で必ず値が設定されるので、storageに保存していない。

2019-08-21 09:08 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/client/operator/Operator.ts
> +				isJoin = this.previousPlay.joinedPlayerTable.has(store.player.id);
新規プレイボタンを押下した場合、直前playのjoin状態をを見てjoinさせるか判定

2019-08-21 09:09 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/client/operator/Operator.ts
> +						argument: params.argument,
この `argument` は親セッションから渡されたものをそのまま設定

2019-08-21 09:11 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/client/store/CoePluginEntity.ts
> +			};
親から渡された `this._argument` があればそのまま使用。

2019-08-21 09:28 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/client/view/organism/ToolBar.css
> +	align-items: start;
ツールバーが2段になった時、背景ボタンとdevToolボタンが縦長に伸縮するので、伸縮せず1段の大きさのままに修正。
不要なスペースも削除。

2019-08-21 09:35 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/server/index.ts
> +			`Starts in the specified service mode. arguments: ${Object.values(ServiceName).filter((v) => v !== "none")}`)
この英文で大丈夫でしょうか...確認お願いしたいです

2019-08-21 10:43 UTC, xnv requested changes

2019-08-21 10:43 UTC, xnv commented on packages/akashic-cli-serve/README.md
> +|`--target-service`|`-T`|ブラウザを開いた時、引数で指定したサービスのモードで開始します。|N/A|
デフォルト値 `N/A` になってますが、 `none` も指定できるようにして、それをデフォルト値として明記する方が実態に沿いませんか。

2019-08-21 10:43 UTC, xnv commented on packages/akashic-cli-serve/src/client/operator/Operator.ts
> +	private previousPlay: PlayEntity;
メンバ変数にしなくてもローカル変数で済みませんか？　もし無理なら、 `constructor` で初期化したいです。

2019-08-21 10:43 UTC, xnv commented on packages/akashic-cli-serve/src/server/index.ts
> +		if (!commander.autoStart) {
これ、targetService によってここの制約は変わるかもしれないので、一旦は NicoLive の時だけにしたいです。

2019-08-21 10:43 UTC, xnv commented on packages/akashic-cli-serve/src/server/index.ts
> +			`Starts in the specified service mode. arguments: ${Object.values(ServiceName).filter((v) => v !== "none")}`)
- `-T` を提案したの私な気がしますが、すいませんこうして見ると `-s` にしたくなってきました
   - T だと別の `--target-hogehoge` が出てくるかもしれない点
  - 使用頻度も高そうなので小文字でいい気がする点 (他に s で使いそうな機能があったら教えてください)
- 英文は、「サービスモード」という語を作るとまた説明が必要になりそうなので、単純に `Simulate the specified service.` ぐらいでどうでしょうか。

2019-08-21 10:43 UTC, xnv commented on packages/akashic-cli-serve/src/client/store/TargetServiceStore.ts
> +	createNicoLiveArgs(isBroadcaster: boolean) {
これここにあるメソッドなんですかね……？　やり場がない感じはすごくしますが、 store として考えてもいまいちですし、メンバ変数見てもいませんし、 `Operator` の隅に仮置きしておく方が落ち着くような気がします (っていう形で `Operator` はどうもごたつくんですが、それにしても)。

2019-08-21 10:43 UTC, xnv commented on packages/akashic-cli-serve/src/client/store/TargetServiceStore.ts
> +	get service(): ServiceType {
`targetService` を直接使えばいいのではないでしょうか。(targetService と service が両方あると使い分けに迷うと思います)

2019-08-21 10:43 UTC, xnv commented on packages/akashic-cli-serve/src/common/types/ServiceType.ts
> +export type ServiceType =
これ必要でしょうか？　型としては `ServiceName` と役割かなり重複していそうに見えますが……。(どちらを `ServiceType` と呼ぶかはともかく)

2019-08-21 10:43 UTC, xnv commented on packages/akashic-cli-serve/src/client/store/TargetServiceStore.ts
> +	@observable targetService: ServiceType;
これこれ以外に将来どんなメンバが増える想定でしょう……？　これしかないんだったら `Store` に直接この値持っていればいいかなという気もします。 `Store#appOptions.targetService` と実質的に値を二重管理してるのも引っかかりますし、もうなんだったら `Store` に `get targetService() { return this.appOptoions.targetService; }` をつけて済ませてもいいのではという気も。

2019-08-22 02:10 UTC, yu-ogi commented on packages/akashic-cli-serve/src/client/view/organism/ToolBar.tsx
> +import * as labelStyles from "../atom/ToolLabel.css";
呼び出し側が呼び出し元のコンポーネントのスタイルシートを適用するのは違和感がありますね。
`ToolLabel.tsx` から読み込むべきに思えますがいかがでしょう。

2019-08-22 02:10 UTC, yu-ogi commented on packages/akashic-cli-serve/src/common/types/ServiceType.ts
> + * nicoLive: ニコ生として起動する
`nicoLive` と `nicolive` で統一されていないみたいですがどちらでしょう。
(個人的には `nicolive` 派です。)

2019-08-22 02:10 UTC, yu-ogi commented on packages/akashic-cli-serve/src/client/store/TargetServiceStore.ts
> +	isNicoLiveService(): boolean {
(imo) target service が増えるたびにこちらの判定ロジック用のメソッドが増えるのも煩雑なので、利用側で `targetServiceStore.targetService === ServiceType.NicoLive` の判定を任せてしまっても良いように思いました。

2019-08-22 02:10 UTC, yu-ogi commented on packages/akashic-cli-serve/src/client/store/TargetServiceStore.ts
> +					advanceRequest: isBroadcaster ? true : false,
`advanceRequest: isBroadcaster` でよいのでは、と思いました。

2019-08-22 02:10 UTC, yu-ogi commented on packages/akashic-cli-serve/src/client/view/atom/ToolLabel.css
> +.tool-label-tareget-value {
target を typo しているようです。

2019-08-22 02:10 UTC, yu-ogi commented on packages/akashic-cli-serve/src/server/index.ts
> +			`Starts in the specified service mode. arguments: ${Object.values(ServiceName).filter((v) => v !== "none")}`)
せっかく enum に切り出しているので `.filter((v) => v !== ServiceName.None)}` としたいですね。

2019-08-22 02:10 UTC, yu-ogi commented on packages/akashic-cli-serve/src/client/store/Store.ts
> +			if (this.appOptions.targetService) {
こちらは常に真になりそうですがどのような意図でしょう。

2019-08-22 02:10 UTC, yu-ogi commented on packages/akashic-cli-serve/src/client/store/CoePluginEntity.ts
> +	argument?: any;
こちら語が紛らわしいので他と合わせて `instanceArgument` にしたいですね。

https://github.com/akashic-games/akashic-cli/blob/229ab5758b41876cb7b04189555966d9122b6c5f/packages/akashic-cli-serve/src/client/operator/Operator.ts#L18-L21

2019-08-22 04:28 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/server/index.ts
> +			`Starts in the specified service mode. arguments: ${Object.values(ServiceName).filter((v) => v !== "none")}`)
- オプションを `s` へ修正
- 英文とarguments部分のロジックを修正

2019-08-22 04:28 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/README.md
> +|`--target-service`|`-T`|ブラウザを開いた時、引数で指定したサービスのモードで開始します。|N/A|
デフォルト値が `none` なので 修正しました。

2019-08-22 04:29 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/client/operator/Operator.ts
> +	private previousPlay: PlayEntity;
ローカル変数で済みましたので修正しました。

2019-08-22 04:30 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/server/index.ts
> +		if (!commander.autoStart) {
`autoStart`オプションと併用時のエラー条件を、値が`nicolive`の場合に修正しました。

2019-08-22 04:32 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/client/store/TargetServiceStore.ts
> +	createNicoLiveArgs(isBroadcaster: boolean) {
これどこに置くべきか迷いました。仰るとおり、storeに置くべき内容ではないのですが、Operatorに置くと汚くなって行きそうだったのでstoreに置いてしまいました。
このstoreが不要になったため、Operatorへおきました。

2019-08-22 04:33 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/client/store/TargetServiceStore.ts
> +	get service(): ServiceType {
`TargetServiceStore` が不要となったため、`Store`の方で扱うよう修正しました

2019-08-22 04:33 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/common/types/ServiceType.ts
> +export type ServiceType =
`enum ServiceName` の名前を `enum ServiceType` へ変更し、 `type ServiceType` を削除しました。

2019-08-22 04:34 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/client/store/TargetServiceStore.ts
> +	@observable targetService: ServiceType;
`TargetServiceStore` が不要となったため、`Store`の方で扱うよう修正しました

2019-08-22 04:35 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/client/view/organism/ToolBar.tsx
> +import * as labelStyles from "../atom/ToolLabel.css";
`ToolLabel.tsx` の方で扱うようにしたので、削除しました。

2019-08-22 04:35 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/common/types/ServiceType.ts
> + * nicoLive: ニコ生として起動する
`nicolive` へ統一しました

2019-08-22 04:35 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/client/store/TargetServiceStore.ts
> +					advanceRequest: isBroadcaster ? true : false,
仰る通りです。修正しました。

2019-08-22 04:35 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/client/view/atom/ToolLabel.css
> +.tool-label-tareget-value {
`target` 修正しました

2019-08-22 04:37 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/client/store/Store.ts
> +			if (this.appOptions.targetService) {
`targetService` のデフォルト値がnull にしていた時があり、その修正忘れです。
この部分のロジックが変わったので削除しました。

2019-08-22 04:37 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/client/store/CoePluginEntity.ts
> +	argument?: any;
`instanceArgument` へ修正しました

2019-08-22 05:16 UTC, xnv commented on packages/akashic-cli-serve/src/server/index.ts
> +			`Simulate the specified service. arguments: ${Object.values(ServiceType).filter((v) => v !== ServiceType.None)}`)
いやそもそも none も指定できていいと思うので単に `Object.values(ServiceType)` だけでよいかと。

2019-08-22 05:17 UTC, xnv commented on packages/akashic-cli-serve/src/server/index.ts
> +			`Starts in the specified service mode. arguments: ${Object.values(ServiceName).filter((v) => v !== "none")}`)
そもそも none も指定できていいと思うので単に `Object.values(ServiceType)` だけでよいかと思いますね……。

2019-08-22 07:46 UTC, yu-ogi commented on packages/akashic-cli-serve/src/client/operator/Operator.ts
> +	private _createNicoLiveArgs(isBroadcaster: boolean) {
生成するのはあくまで instance argument なので `createInstanceArgumentForNicolive` (というようなニュアンス) にしたいですね。

2019-08-22 07:46 UTC, yu-ogi commented on packages/akashic-cli-serve/src/client/view/organism/ToolBar.tsx
> +	targetService: string;
型 `string` は意図通りでしょうか。

2019-08-22 07:46 UTC, yu-ogi commented on packages/akashic-cli-serve/src/client/view/atom/ToolLabel.css
> +.tool-label-target-service {
tool-label は atom (一番粒度の小さいコンポーネント) なので、 target service というサービス側用語を知っているべきでは無いように思えます。

2019-08-22 07:46 UTC, yu-ogi commented on packages/akashic-cli-serve/src/client/view/organism/ToolBar.tsx
> +					TargetService: <span>{props.targetService}</span>
厳密な意味では違うかもしれませんが、この部分はいわゆる [説明リスト](https://developer.mozilla.org/ja/docs/Web/HTML/Element/dl) のように見えました。

別でコメントしましたが、 `"tool-label-target-service"` というハードコーディングされたクラス名でスタイルシートを定義するよりも上記のような dom 構造にした上でスタイルを適用したほうが汎用的になりそうに思いましたがいかがでしょう。

```html
<dl>
    <dt>TargetService</dt>
    <dd>{props.targetService}</dd>
</dl>
```

```css
/* ToolLabel.css */

.tool-label dl dt {
	...
}
.tool-label dl dd {
	...
}
```

2019-08-22 10:54 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/client/view/organism/ToolBar.tsx
> +	targetService: string;
修正漏れです。 `ServiceType` に修正しました。

2019-08-22 10:54 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/client/operator/Operator.ts
> +	private _createNicoLiveArgs(isBroadcaster: boolean) {
`_createInstanceArgumentForNicolive()` へ変更しました。

2019-08-22 10:54 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/server/index.ts
> +			`Starts in the specified service mode. arguments: ${Object.values(ServiceName).filter((v) => v !== "none")}`)
`Object.values(ServiceType)` のみに修正しました。

2019-08-22 10:55 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/client/view/atom/ToolLabel.css
> +.tool-label-target-service {
css関連、別途ご相談させてください

2019-08-23 10:49 UTC, xnv requested changes

2019-08-23 10:49 UTC, xnv commented on packages/akashic-cli-serve/src/server/index.ts
> +			getSystemLogger().error("--no-auto-start and --target-service options can not be set at the same time.");
メッセージでも nicolive に言及する必要があると思います。

2019-08-23 10:49 UTC, xnv commented on packages/akashic-cli-serve/src/client/view/organism/ToolBar.tsx
> +import { ServiceType } from "../../../common/types/ServiceType";
`import` は「コアモジュール」「一般 node_modules」「内製の node_modules」「ローカルパス (ディレクトリが遠い方から)」の順で並べてあるので、合わせてもらえればと思います。(まあ、こういうのは徹底するなら自動化しちゃった方がいいと思いますが、一応)

2019-08-23 10:49 UTC, xnv commented on packages/akashic-cli-serve/src/client/view/organism/ToolBar.tsx
> +					TargetService: <span>{props.targetService}</span>
`dl` がベストかはともかく、ここからスタイル `optionClass` を流し込まないことに賛成します。このような外付けの style は、 `ToolLabel` の具体的な DOM 構造についてある程度知らないと使えないので、暗黙の密結合になると思います。

2019-08-23 10:49 UTC, xnv commented on packages/akashic-cli-serve/src/client/operator/Operator.ts
> +				isJoin = previousPlay.joinedPlayerTable.has(store.player.id);
これ、join してないインスタンス (window) から新規プレイボタンを押すと正常に動作しないのではありませんか。

2019-08-23 10:49 UTC, xnv commented on packages/akashic-cli-serve/src/client/view/container/ToolbarContainer.tsx
> +import { ServiceType } from "../../../common/types/ServiceType";
この辺も。

2019-08-26 02:55 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/server/index.ts
> +			getSystemLogger().error("--no-auto-start and --target-service options can not be set at the same time.");
`--no-auto-start and --target-service nicolive can not be set at the same time.`  と修正しました。

2019-08-26 02:55 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/client/view/organism/ToolBar.tsx
> +import { ServiceType } from "../../../common/types/ServiceType";
修正しました。

2019-08-26 02:55 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/client/view/container/ToolbarContainer.tsx
> +import { ServiceType } from "../../../common/types/ServiceType";
修正しました。

2019-08-26 02:55 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/client/operator/Operator.ts
> +				isJoin = previousPlay.joinedPlayerTable.has(store.player.id);
joinしていないインスタンスで、新規プレイボタン押下での正常動作は確認しています。

2019-08-26 08:00 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/client/view/organism/ToolBar.tsx
> +					TargetService: <span>{props.targetService}</span>
ToolLabelに`emphasizeBorder`プロパティを追加し、呼び出し元で枠線を強調する場合はtrueを設定し、ToolLabelで`emphasizeBorder`の値を見てclass を設定するよう修正しました。
また、子要素は `TargetService: <b>{props.targetService}</b>` とし、cssには `border-emphasize` のみ定義するように修正しました。

2019-08-26 08:17 UTC, yu-ogi approved these changes

2019-08-26 08:17 UTC, yu-ogi commented on packages/akashic-cli-serve/src/client/view/atom/ToolLabel.css
> +	border-color: #c1c1c1;
こちらの定数は他の箇所と合わせて [カスタムプロパティ](https://developer.mozilla.org/ja/docs/Web/CSS/Using_CSS_custom_properties) を利用すべきかと思います。

2019-08-26 08:36 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/client/view/atom/ToolLabel.css
> +	border-color: #c1c1c1;
カスタムプロパティを利用するよう修正しました。

2019-08-28 02:58 UTC, xnv commented on packages/akashic-cli-serve/src/client/operator/Operator.ts
> +				isJoin = previousPlay.joinedPlayerTable.has(store.player.id);
おっと失礼、ここは broadcast されてきて全員が実行するんですね。

2019-08-28 02:58 UTC, xnv approved these changes

2019-08-28 03:30 UTC, merged