akashic-cli-xxxモジュールのテストフレームワークをjestに変更 その3
akashic-games/akashic-cli pull request #129
Opened 2019-08-13 09:53 UTC by dera-

### 概要
* 以下のモジュールのテストフレームワークをjestに変更しました
  * akashic-cli-export-zip
  * akashic-cli-modify
  * akashic-cli-uninstall
  * akashic-serve

2019-08-13 09:57 UTC, dera- commented on packages/akashic-cli-modify/src/modify.ts
> +	const gameJsonPath = path.join(param.cwd, "game.json");
cwdがカレンディレクトリ以外の場合失敗する作りになっていてテストも落ちてしまっていたので修正しました(jasmineの時はなぜテストが通っていたのか不明ですが。。)。

2019-08-13 10:04 UTC, dera- commented on packages/akashic-cli-uninstall/spec/src/uninstallSpec.ts
> +			.catch(e => done());
やっていることは変わっていないのですが、このように記述しないとnode v8でテストが以下のようなエラーを出して落ちてしまうため修正しました。

2019-08-13 10:08 UTC, dera- commented on packages/akashic-cli-serve/package.json
> +    "test": "jest --forceExit && npm run lint",
jestではopenしっ放しのWebSocket等のコネクションがある場合テストが終了しないようになっているのですが、テストで使用している全コネクションの把握ができなかったので一旦`--forceExist`オプションを付けました

2019-08-14 04:09 UTC, kamakiri01 commented on packages/akashic-cli-uninstall/spec/src/uninstallSpec.ts
> +			.catch(e => done());
以下のエラー、についてログが残っていれば、コメントで残してもらえればと思います。

2019-08-14 04:09 UTC, kamakiri01 approved these changes

2019-08-14 10:42 UTC, dera- commented on packages/akashic-cli-uninstall/spec/src/uninstallSpec.ts
> +			.catch(e => done());
以下のようなログが出ました。
こちら、エラーというよりテストが落ちてしまうの方が正しいですね。と言ってもテストの書き方の問題だと思われるので、プロダクトコード自体には問題ありません。
```
 FAIL  spec/build/uninstallSpec.js
  ● uninstall() › handles npm failure

    Failed: "UninstallFail:tee"

      at Env.fail (node_modules/jest-jasmine2/build/jasmine/Env.js:775:61)
```

2019-08-14 11:43 UTC, xnv commented on packages/akashic-cli-serve/package.json
> +    "test": "jest --forceExit && npm run lint",
全コネクション把握できればいいなら `io()` の呼び出しをラップして数えればよいのではないでしょうか。SubscriberSpec.js はわかりませんが無効化されてますし、 SocketIoAMFlowManagerSpec.js の方はたぶん三つしかなさそうに見えます。

不可避なら仕方ないと思いますが、他の問題を隠蔽したりしそうな気もし、避けられるなら避けたいオプションに思えます。

2019-08-15 10:20 UTC, dera- commented on packages/akashic-cli-serve/package.json
> +    "test": "jest --forceExit && npm run lint",
SocketIoAMFlowManagerSpec.jsだけでなくSubscriberSpec.jsでもコネクションを開いていたのでcloseするように修正したところ`--forceExit`フラグ無しでテストが動作するようになりました

2019-08-15 10:24 UTC, dera- commented on packages/akashic-cli-serve/spec/server/SubscriberSpec.js
> +		ServerConfigMock.socket.close();
このファイルのテストを全て無効化しているのでトップのxdescribeの前でいきなりcloseしてもいいのではとも考えましたが、このテストを復活させた時にそれだと不便かと思ったので、トップのdescribeを有効にしてafterallを呼び出せるようにする方向で修正しました。若干、diffは多くなってしまいましたが。。

2019-08-16 07:38 UTC, xnv requested changes

2019-08-16 07:38 UTC, xnv commented on packages/akashic-cli-serve/spec/server/SocketIOAMFlowManagerSpec.js
> +				await socket.close();
途中で例外が発生しても閉じる必要があったりはしませんか。もしそうなら、 `finally` 節を設けてその中で `if (socket)` を確認したから `socket.close()` する必要があると思います。

2019-08-16 07:38 UTC, xnv commented on packages/akashic-cli-serve/spec/server/SubscriberSpec.js
> +		ServerConfigMock.socket.close();
うーん。次のことに違和感があります:
- このファイル内では `open()` したわけでもないものを突如 `close()` しているのは対称性に欠ける
- そもそも `SubscriberMock` を他の箇所で使うようになったらここで close されると順序によって他が壊れる

今の `SubscriberMock` が singleton なのは open/close といった状態の概念が必要なかったからで、それが必要となった今となっては

- `SubscriberMock` をクラス化して、テストではインスタンスを使う
- そのインスタンスは `beforeAll()` で `new` して `afterAll()` で `destroy()` する (その中で close する)

とする方が自然ではありませんか。

そしてそうすれば、今回の差分のようにテストを個別に無効化しなくても、トップだけ `xdescribe` にしている現状で自然に動作すると思います。

2019-08-16 09:50 UTC, dera- commented on packages/akashic-cli-serve/spec/server/SocketIOAMFlowManagerSpec.js
> +				await socket.close();
了解しました、そのように修正します。

2019-08-16 09:52 UTC, dera- commented on packages/akashic-cli-serve/spec/server/SubscriberSpec.js
> +		ServerConfigMock.socket.close();
確かに、シングルトンのSubscriberMockをいきなり1テストファイルでクローズするのは問題なので、SubscriberMockをクラス化する方向に修正します

2019-08-19 04:21 UTC, xnv approved these changes

2019-08-28 07:32 UTC, merged