add autoSendEvent for serve
akashic-games/akashic-cli pull request #130
Opened 2019-08-14 06:09 UTC by kamakiri01

## このpull requestが解決する内容

akashic serveコマンドで実行される動作環境に、sandbox.config.jsのAutoSendEvents機能を追加します。
この修正により、akashic-sandboxと同じように、playの起動時にイベントを送ることが出来るようになります。

### 概要

## 破壊的な変更を含んでいるか?

- なし

2019-08-14 06:10 UTC, kamakiri01 commented on packages/akashic-cli-serve/src/client/operator/Operator.ts
> +		await ApiClient.resumePlayDuration(play.playId);
PRの主旨からは逸れますが、awaitしていない箇所があったので追記しています。

2019-08-14 10:27 UTC, xnv requested changes

2019-08-14 10:27 UTC, xnv commented on packages/akashic-cli-serve/src/client/operator/Operator.ts
> +		if (contentLocator || plays.length !== 0) {
難しめの条件になってる気がしますが、単純に `_createServerLoop()` の中で済ませてしまうことはできないでしょうか？ (というか、単純に `!contentLocator && plays.length !== 0` のパスって「既に play があった」ケースがあるわけで、ここで投げてはまずいのではないでしょうか)

2019-08-14 10:27 UTC, xnv commented on packages/akashic-cli-serve/src/client/operator/Operator.ts
> +				this.play.sendEditorEvent();
`setEventEditContent()` せずにいきなり送信することもできそう、というかその方が自然なような気がしますが、エディタにコピーしたい動機はあるでしょうか。

2019-08-15 08:32 UTC, kamakiri01 commented on packages/akashic-cli-serve/src/client/operator/Operator.ts
> +				this.play.sendEditorEvent();
play.sendRegisteredEventを使うようにします。

2019-08-15 08:32 UTC, kamakiri01 commented on packages/akashic-cli-serve/src/client/operator/Operator.ts
> +		if (contentLocator || plays.length !== 0) {
setCurrentPlayの後に実行したいので、_createServerLoopの中は難しそうです。
_createServerLoopを読んだかのフラグを作って管理するようにします。

2019-08-15 11:33 UTC, xnv approved these changes
コメントつけましたが approved.

2019-08-15 11:33 UTC, xnv commented on packages/akashic-cli-serve/src/client/operator/Operator.ts
> +		let isCreatedServerLoop = false;
イベントを送信する条件は「server loop を作ったか」ではなく「 play を作ったかどうか」だと思いますから `isPlayCreated` の方が直截的ではないでしょうか。

2019-08-16 07:08 UTC, kamakiri01 commented on packages/akashic-cli-serve/src/client/operator/Operator.ts
> +		let isCreatedServerLoop = false;
直します。

2019-08-16 07:08 UTC, merged