enable sandbox.config.js, send autoSendEvents for export-html
akashic-games/akashic-cli pull request #146
Opened 2019-09-10 07:50 UTC by kamakiri01

## このpull requestが解決する内容

### 概要

akashic export htmlコマンドで出力されるコンテンツに、sandbox.config.jsのAutoSendEvents機能を追加します。
この修正により、akashic-sandboxと同じように、playの起動時にイベントを送ることが出来るようになります。

## 破壊的な変更を含んでいるか?

- なし

2019-09-10 07:51 UTC, kamakiri01 commented on packages/akashic-cli-export-html/src/app/cli.ts
> +	const filteredArgv = argv.filter(v => !/^(--strip)$/.test(v));
PRの本題ではありませんが、 `$ akashic export html -s sourceDir` の省略記法が使えない状態になっていました。

2019-09-26 03:36 UTC, xnv requested changes

2019-09-26 03:36 UTC, xnv commented on packages/akashic-cli-export-html/src/app/convertBundle.ts
> +		console.log("failed read sandbox.config.js, autoSendEvents disabled.");
指定してもいないオプションで failed, disabled と言われるのは違和感があります。この try 節全体を `if (options.autoSendEvents)` でくくってしまいませんか。

2019-09-26 03:36 UTC, xnv commented on packages/akashic-cli-export-html/src/app/convertNoBundle.ts
> +	var sandboxConfig = options.sandboxConfigJsCode;
利用箇所が見当たらないような？

2019-09-26 03:36 UTC, xnv commented on packages/akashic-cli-export-html/src/app/convertUtil.ts
> +	fs.accessSync(sandboxConfigJsPath);
これ、ここで失敗するならどうせ `readFileSync()` で失敗して例外になるので、不要だったりしませんか。(厳密には、ここで成功した直後 `readFileSync()` の前に削除される可能性すらあるので、通ったからといって `readFileSync()` が成功するとも限らない気がしますし)

2019-09-26 10:34 UTC, kamakiri01 commented on packages/akashic-cli-export-html/src/app/convertUtil.ts
> +	fs.accessSync(sandboxConfigJsPath);
readFileSyncのエラーを使うようにします。

2019-09-26 10:34 UTC, kamakiri01 commented on packages/akashic-cli-export-html/src/app/convertNoBundle.ts
> +	var sandboxConfig = options.sandboxConfigJsCode;
消し忘れです 🙇

2019-09-26 10:34 UTC, kamakiri01 commented on packages/akashic-cli-export-html/src/app/convertBundle.ts
> +		console.log("failed read sandbox.config.js, autoSendEvents disabled.");
確かに、却って使うとき困ると思います。if でくくります。

2019-09-30 04:07 UTC, dera- commented on packages/akashic-cli-export-html/src/app/convertNoBundle.ts
> +			options.autoSendEvents = false;
ここでfalseを渡した場合、テンプレート側でwindow.__akashic__.autoSendEventsには`"false"`が代入されるため、sandbox.js内の`if(window.__akashic__.autoSendEvents){~~}`の分岐処理が実行されてしまうと思われます。
おそらくエラーになることは無いと思いますが、この時点でautoSendEventは渡せていない想定なので、分岐処理が実行されないよう空文字列辺りを渡した方が無難なのではという気もしています。

2019-09-30 04:15 UTC, dera- commented on packages/akashic-cli-export-html/templates/template-export-html-v2/js/sandbox.js
> +			var autoSendEvents = (window.__akashic__.autoSendEvents === "true") ? sandboxConfig.autoSendEvents : window.__akashic__.autoSendEvents;
非常に細かい話ですが、`true`という名前のeventは仕様上autoSendEventsオプションからは指定できないという説明はどこかにあった方が良いのかなとは思いました。(このPRではなくマニュアルを作成する時の話のような気もしますが)

2019-09-30 11:14 UTC, kamakiri01 commented on packages/akashic-cli-export-html/src/app/convertNoBundle.ts
> +			options.autoSendEvents = false;
確かに"false" が入ると意図しない分岐に入りますね。直します。

2019-10-01 08:44 UTC, dera- approved these changes

2019-10-04 03:35 UTC, xnv requested changes

2019-10-04 03:35 UTC, xnv commented on packages/akashic-cli-export-html/templates/template-export-html-v2/js/sandbox.js
> +			var autoSendEvents = (window.__akashic__.autoSendEvents === "true") ? sandboxConfig.autoSendEvents : window.__akashic__.autoSendEvents;
いやなぜ文字列なのかの方が不可解なような？　`autoSendEvents === true` ではなく……？

2019-10-04 03:35 UTC, xnv commented on packages/akashic-cli-export-html/templates/template-export-html-v2/js/sandbox.js
> +		if (window.__akashic__.autoSendEvents) {
今更ですがこれだとイベント名 `""` が使えなくなるので、  `autoSendEvents === true || typeof autoAsendEvents === "string"` とかが無難かもしれません。

2019-10-04 03:35 UTC, xnv commented on packages/akashic-cli-export-html/src/app/convertBundle.ts
> +			options.autoSendEvents = "";
空文字列より false の方が明示的ではないでしょうか。(今のPRの状態だと、空文字列も無効扱いになってますが、そうするかどうかには議論の余地があると思います。false は明らかに無効扱いでしょう。)

2019-10-04 03:43 UTC, xnv commented on packages/akashic-cli-export-html/src/app/convertNoBundle.ts
> +			options.autoSendEvents = false;
空文字列はやめませんか。 events フィールドのキーとして「空文字列は使えない」という仕様をここで新たに作ることになります。(別に持ち込んで大して困る仕様でもありませんが、必要がない制約を設けるモチベーションがありません)

この問題の本質は、テンプレートに「文字列の  `"false"` が書き込まれる」ことではないでしょうか。ちゃんと boolean の `false` が書かれば問題ないのであれば、改修箇所はテンプレート書き込み部分であって、ここをどうこうするものではないように思います。

2019-10-07 13:40 UTC, kamakiri01 commented on packages/akashic-cli-export-html/src/app/convertNoBundle.ts
> +			options.autoSendEvents = false;
ectテンプレートに渡すため強制的に文字列化していましたが、 `JSON.stringify` を通してテンプレート側で変換できることが分かったため、ここでは `false` を渡すようにします。

2019-10-07 13:41 UTC, kamakiri01 commented on packages/akashic-cli-export-html/src/app/convertBundle.ts
> +			options.autoSendEvents = "";
false を渡すようにします。

2019-10-08 02:42 UTC, kamakiri01 commented on packages/akashic-cli-export-html/templates/template-export-html-v2/js/sandbox.js
> +		if (window.__akashic__.autoSendEvents) {
直します。

2019-10-08 03:00 UTC, xnv approved these changes

2019-10-08 05:55 UTC, merged