akashic-cli-serveでサーバーの状態をチェックするためのページを追加
akashic-games/akashic-cli pull request #170
Opened 2019-10-03 08:25 UTC by dera-

### 概要
* akashic-cli-serveにはサーバー側の状態を確認する手段がなかったのでそのためのページを追加しました
  * 暫定のページURLは`/debug/health-checker`

### やったこと
* サーバーの状態をチェックするためのページで以下の情報を表示
  * 各PlayのplayId、status、作成日時、最後にsuspend状態になった日時
  * 各Playに接続しているクライアントの情報(PlayerId, PlayerName, アクティブインスタンスかどうか)
* テンプレートエンジンect導入
* テンプレートを置くためのディレクトリとして`views`を追加
* (本案件とは関係ないが)サーバー側のPlayStoreが持っているplayIdをキーとする各オブジェクトをPlayEntityにまとめる対応

### 見ていただきたいところ
* ページに表示する情報に過不足ないか
* ページのURL
* PlayEntityにまとめる対応は妥当かどうか

2019-10-08 02:36 UTC, yu-ogi commented on packages/akashic-cli-serve/src/server/index.ts
> +	app.engine("ect", ect({root: path.join(__dirname, "..", "..", "views"), ext: ".ect"}).render);
views のディレクトリパスを上の行と二箇所で渡していますが、これは不可避なのでしょうか。

2019-10-08 02:36 UTC, yu-ogi commented on packages/akashic-cli-serve/src/server/route/DebugRoute.ts
> +	contentsRouter.get(`/health-checker`, createHandleToGetHealthChecker(params.playStore));
(imo) APIの死活監視としてのヘルスチェックという意味であるなら、er を付けない `health-check` や `health` の方がエンドポイントとしては一般的な印象を受けました。

2019-10-08 02:36 UTC, yu-ogi commented on packages/akashic-cli-serve/src/server/index.ts
> +	app.use("/debug/", createDebugRouter({ playStore }));
好みの問題もありそうですが、ヘルスチェック自体はデバッグ以外にも有効そうなので `health/status` というパスでもよいのでは、と思いました。

2019-10-08 03:48 UTC, xnv requested changes

2019-10-08 03:48 UTC, xnv commented on packages/akashic-cli-serve/views/health-checker.ect
> +<table border="1">
まあ一応 valid な HTML にしておきませんか。1行目に `<!doctype html>` を、あと `<title>` をつけとけばたぶん valid だと思います。

2019-10-09 06:34 UTC, dera- commented on packages/akashic-cli-serve/views/health-checker.ect
> +<table border="1">
あ、すみません。自動でvalidなものに変換されるものだと勘違いしていました。。こんな感じのvalidな形式に修正しようと思います。
```
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>~~~</title>
</head>
<body>
~~~
</body>
</html>
```

2019-10-09 06:37 UTC, dera- commented on packages/akashic-cli-serve/src/server/index.ts
> +	app.use("/debug/", createDebugRouter({ playStore }));
一般的なヘルスチェックには異常検知だったりレポート出力みたいな機能があるそうなので、`/helth/~~`でパスを作っておこうかと思います

2019-10-09 07:28 UTC, dera- commented on packages/akashic-cli-serve/src/server/index.ts
> +	app.engine("ect", ect({root: path.join(__dirname, "..", "..", "views"), ext: ".ect"}).render);
`app.set("views",~~~);`だけで行けそうななのでrootの方は削除しようと思います

2019-10-09 07:47 UTC, dera- commented on packages/akashic-cli-serve/src/server/route/DebugRoute.ts
> +	contentsRouter.get(`/health-checker`, createHandleToGetHealthChecker(params.playStore));
サーバー側のヘルスチェックページのパスは`/health-check/status`にしようかと思っているので、ここは`/status`に変更します

2019-10-10 01:46 UTC, yu-ogi commented on packages/akashic-cli-serve/src/server/tsconfig.json
> +    "noImplicitAny": false,
`ect` のためだけに全体の設定を変更するのは大げさのように思えます。
ect の利用側で `require()` して、該当箇所の ts-lint を無効にしたほうが健全のように思いますがいかがでしょう。

2019-10-10 01:46 UTC, yu-ogi commented on packages/akashic-cli-serve/src/server/domain/PlayStore.ts
> +export interface PlayEntity {
* これだけ他の entity と違い interface である理由は何でしょう。
* ファイルとして切り出さなくても問題ないでしょうか。

2019-10-10 06:12 UTC, dera- commented on packages/akashic-cli-serve/src/server/domain/PlayStore.ts
> +export interface PlayEntity {
このPlayEntityを追加で作ったモチベーションとしては、このStore内にplayIdをキーとするmapがいくつもあったのでそれを一纏めにしたかったんですよね。そのためプロパティを定義しておくだけで十分でメソッドの定義は必要ないのでinterfaceにした感じです。(これはどちらかというと命名の問題かもしれません。。)
classでもないですしPlayStore内でしか使わないものなので、今の所ファイルに切り出す必要はないのではと思ってます。

2019-10-10 10:10 UTC, dera- commented on packages/akashic-cli-serve/src/server/tsconfig.json
> +    "noImplicitAny": false,
仰る通りそのためだけにここを変えるのはあまりよろしくは無いですね。。
そもそも`ect`を利用するのであれば型の定義が必要ですが、`@types/ect`は存在しないのでこのような対応を行ってしまった感じです(でなければ型ファイルを作るという手段もありそうですが、それもどうかという感じです。。)
ですので、`ect`の代わりに`ejs`を利用するようにしてみようかと思います

2019-10-16 01:38 UTC, yu-ogi commented on packages/akashic-cli-serve/src/server/route/HealthCheckRoute.ts
> +	const contentsRouter = express.Router();
(nits) この変数名の意味がよくわからないです。

2019-10-16 01:38 UTC, yu-ogi commented on packages/akashic-cli-serve/views/health-check-status.ejs
> +            <td><%= info.lastSuspendedAt ? new Date(info.lastSuspendedAt).toString() : "" %></td>
(imo) このあたりについてですが、あまり view にロジックをもたせるべきではないように思いました。view 部分では基本的に表示することだけを責務とし、 controller で上のロジックを解決して上げたほうが役割が明確になりそうです。

2019-10-16 01:38 UTC, yu-ogi commented on packages/akashic-cli-serve/views/health-check-status.ejs
> +<title>サーバー側のヘルスチェック</title>
(imo) 表示している内容は「プレイの状態」であり「サーバの状態 (メモリやCPU使用量など?)」では無いように思えるのですが、このタイトルは妥当でしょうか。

2019-10-16 03:20 UTC, xnv commented on packages/akashic-cli-serve/src/server/domain/PlayStore.ts
> +export interface PlayEntity {
個人的にはさほどこだわりません (後からやって手戻りが大きいタイプの話ではないので) が、「必要になったら他に合わせて class にする・ファイルに切り出す」みたいなコメントだけつけておいてもいいかもしれません。

2019-10-16 04:12 UTC, dera- commented on packages/akashic-cli-serve/src/server/domain/PlayStore.ts
> +export interface PlayEntity {
了解しました。「今はメンバ変数だけで十分なのでintefaceにしているがメソッドが必要になったらclassにしてファイルに切り出す」といった感じの注釈的なコメントをつけておこうかと思います

2019-10-16 04:14 UTC, dera- commented on packages/akashic-cli-serve/src/server/route/HealthCheckRoute.ts
> +	const contentsRouter = express.Router();
あ、、コピペ元の変数名をそのまま使ってしまってました。。`healthCheckRouter`とかに変更しようと思います。

2019-10-16 04:15 UTC, dera- commented on packages/akashic-cli-serve/views/health-check-status.ejs
> +<title>サーバー側のヘルスチェック</title>
確かにこれはプレイの状態のほうが正しいですね。そのようにタイトルを変更しておこうかと思います。

2019-10-16 04:32 UTC, dera- commented on packages/akashic-cli-serve/views/health-check-status.ejs
> +            <td><%= info.lastSuspendedAt ? new Date(info.lastSuspendedAt).toString() : "" %></td>
確かにviewにロジックを持たせるべきではないはおっしゃる通りですが、その場合フォーマット済みの時刻の文字列をコントローラー側から渡すことになると思いますが、どのようなフォーマットで表示すべきかはview側で選ばせるようにしたほうが良いかと思われます。ですので、もし対応するのであればその旨をコメントアウトするくらいかと思ってます。

2019-10-16 07:02 UTC, xnv commented on packages/akashic-cli-serve/views/health-check-status.ejs
> +<title>サーバー側のヘルスチェック</title>
どうなんでしょう、例えば　HTTP サーバだったら「サーバの状態」として今の connection の数とか表示するのは別に変ではないのでは。サーバ ＝ サーバ機材、という前提は立てなくていいと思います。現状では「プレイの状態」としても正しいと思いますが、例えばこの後「ホストしてるコンテンツの情報」とか加えたら、「プレイの状態」というタイトルでは足りなくなると思いますし、サーバの状態でいいような気がします。

2019-10-16 07:28 UTC, yu-ogi commented on packages/akashic-cli-serve/views/health-check-status.ejs
> +<title>サーバー側のヘルスチェック</title>
たしかに「サーバの状態」は間違っていないように思えますね。失礼しました。
(少なくとも「ヘルスチェック」という文言は避けたほうが良さそうではありますが。)

2019-10-17 08:39 UTC, yu-ogi approved these changes

2019-10-17 14:50 UTC, xnv commented on packages/akashic-cli-serve/views/health-check-status.ejs
> +<title>サーバー側のヘルスチェック</title>
おっと、よくみたら「サーバの状態」じゃないんですね……。それはサーバの状態とは呼んでおきたいですね。

2019-10-17 14:50 UTC, xnv approved these changes
コメント書いてますが approved.

2019-10-21 06:34 UTC, dera- commented on packages/akashic-cli-serve/views/health-check-status.ejs
> +<title>サーバー側のヘルスチェック</title>
こちらサーバの状態というタイトルに修正しました

2019-10-21 10:30 UTC, merged