fix: server stopped to contents error
akashic-games/akashic-cli pull request #186
Opened 2019-11-06 03:29 UTC by ShinobuTakahashi

## 内容

コンテンツでエラーが起きた時に新規プレイボタンを押下した場合にサーバはエラーとなり、コンテンツを正しく修正してもずっとエラーのままとなる状態を修正

2019-11-06 03:32 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/client/operator/Operator.ts
> +		this.ui.hideNotification();
新規プレイボタン押下時に、前プレイで通知されているエラーを非表示へ

2019-11-06 03:55 UTC, xnv requested changes

2019-11-06 03:55 UTC, xnv commented on packages/akashic-cli-serve/src/server/route/ApiRoute.ts
> +	apiRouter.patch("/runners/:runnerId/:playId(\\d+)", createHandlerToPatchRunner(params.runnerStore));
ひとつの runner が複数の playId に紐づくことはありませんし、createAndStartRunner() の時点で runner に紐づいている playId は確定しているわけですから、ここで改めて指定させるのは不自然だと思います。

`RunnerStore` が、runner を作った時点で、 `RunnerManager` に頼らず自力で playId との対応づけを管理していれば済む話ではありませんか。

別案としては、 `rusumeRunner()` などが返している `playId` を、単に返さなくすることもできると思います。(利用者がいなければ)　これは「返せるから返しておいた」程度の値にすぎないのではないかと思いますが、いかがでしょう。

2019-11-06 04:45 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/server/route/ApiRoute.ts
> +	apiRouter.patch("/runners/:runnerId/:playId(\\d+)", createHandlerToPatchRunner(params.runnerStore));
仰るとおり `RunnerStore` がplayIdを知っていれば済むので、 `currentPlayId` を追加し修正しました。

2019-11-06 11:26 UTC, xnv requested changes

2019-11-06 11:26 UTC, xnv commented on packages/akashic-cli-serve/src/server/domain/RunnerStore.ts
> +	private currentPlayId: string;
いえ…… play が複数同時に存在する可能性は普通にある (現状ではないとしても) ので、これはさすがに避けたいです。 `private playIdTable: { [runnerId: string]: string }` みたいなメンバを抱えておいて、 `const playId = this.playIdTable[runnerId]` みたいに求められるようにしたいです。(`createAndStartRunner()` でプロパティ追加して `stopRunner()` で delete するような形になると思います)

2019-11-07 02:51 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/server/domain/RunnerStore.ts
> +	private currentPlayId: string;
> play が複数同時に存在する可能性
なるほどです。mapオブジェクトで管理するよう修正しました。

2019-11-08 02:32 UTC, xnv approved these changes

2019-11-08 02:53 UTC, xnv commented
approve しちゃいましたがコメントつけています + CI 落ちてるの確認お願いします。

2019-11-12 03:32 UTC, dera- approved these changes

2019-11-12 10:10 UTC, merged