replace deprecated module ect to ejs
akashic-games/akashic-cli pull request #190
Opened 2019-11-07 03:48 UTC by ShinobuTakahashi

## 内容

- deprecatedとなったモジュール `ect ` を `ejs` へ置き換え
- 不要となった `typings/ect.d.ts` の削除

2019-11-07 09:20 UTC, kamakiri01 approved these changes

2019-11-12 05:20 UTC, xnv commented on packages/akashic-cli-export-html/src/app/convertNoBundle.ts
>  function writeEct(assetPaths: string[], outputPath: string, conf: cmn.Configuration, options: ConvertTemplateParameterObject): void {
元から浮いた名前でしたが、 ECT なくなってこの名前はさすがに意味がとれないと思います。内容に準じた名前にしませんか。

2019-11-12 05:22 UTC, xnv commented on packages/akashic-cli-export-html/src/app/convertNoBundle.ts
> -	fs.writeFileSync(path.resolve(outputPath, "./index.html"), html);
処理が非同期になっていますが、処理待ちをする必要はないでしょうか？　この後の zip とかするとそのタイミングに間に合わないことがあるのではないかと危惧します。

2019-11-12 05:23 UTC, xnv requested changes
同期・非同期の問題は再現しにくいバグの温床になるのでぜひ避けたいです。

2019-11-12 09:39 UTC, ShinobuTakahashi commented on packages/akashic-cli-export-html/src/app/convertNoBundle.ts
>  function writeEct(assetPaths: string[], outputPath: string, conf: cmn.Configuration, options: ConvertTemplateParameterObject): void {
function名見落としていました。
この関数内でやる事はhtmlファイルの書き出しなので、`writeHtmlFile()` へ修正しました。

2019-11-12 09:39 UTC, ShinobuTakahashi commented on packages/akashic-cli-export-html/src/app/convertNoBundle.ts
> -	fs.writeFileSync(path.resolve(outputPath, "./index.html"), html);
`ejs.renderFile()` の callback引数をやめ、`await` にて処理を待つよう修正しました。

2019-11-13 10:47 UTC, xnv approved these changes

2019-11-14 02:06 UTC, merged