akashic-cli-serveにサーバーを止めるメソッドを追加
akashic-games/akashic-cli pull request #193
Opened 2019-11-08 06:20 UTC by dera-

### 概要
akashic-cli-serveにサーバーを止めるメソッド`close()`をserver/indexに追加

2019-11-08 06:43 UTC, dera- commented on packages/akashic-cli-serve/src/server/index.ts
> +	}
本来ならプロセスも止める必要があるのですが、`process.exit()`を使うとこのサーバーのプロセスだけでなくこのメソッドを利用しているスクリプトのプロセスも途中で止めてしまうので、プロセスを止める処理は書いてません。
問題がある場合は、このサーバーのプロセスだけ止める方法はないか検討します

2019-11-11 02:34 UTC, xnv requested changes

2019-11-11 02:34 UTC, xnv commented on packages/akashic-cli-serve/src/server/index.ts
> +	}
別で議論したいと思いますが、そもそもこの形で終了する機能というのは、「 `run()` を呼び出して起動する人向け」の API になっていると思います。にも関わらずグローバル変数を使ったことで、「 `run()` を二度呼ぶと破綻する」という、名前から予測できない挙動が持ち込まれてしまっていると思います。もしこの形の API を提供するのであれば、次のどちらかにしたいです。

- `run()`, `close()` (名前の対称性のなさもひっかかりますがさておき) を持つクラスを作る
- `run()` の戻り値として、 `close()` を持つオブジェクトを返す

2019-11-11 08:29 UTC, yu-ogi commented on packages/akashic-cli-serve/src/server/index.ts
>  export function run(argv: any): void {
外部から利用されることを想定しているなら、サーバの起動タイミングで resolve() する Promise を返すか、または callback を実行するようにしたいですね。

2019-11-14 08:15 UTC, dera- commented
修正内容を大きく変えたものを出しなおしますので、こちらのPRはクローズします

2019-11-14 08:15 UTC, closed without merging