Add allowed-external option
akashic-games/akashic-cli pull request #202
Opened 2019-12-03 10:35 UTC by ShinobuTakahashi

## 修正内容

外部アセットを許可するオプションを追加します。
-

2019-12-04 02:27 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/server/domain/RunnerStore.ts
> +export interface CreateAndStartRunnerParameterObject {
引数が多くなったのでObject化

2019-12-04 02:29 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/server/domain/RunnerStore.ts
> +	async createAndStartRunner(params: CreateAndStartRunnerParameterObject): Promise<RunnerV1 | RunnerV2> {
引数が多くなったので、object化

2019-12-04 05:06 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/client/api/ApiClient.ts
> +		`/api/runners/${contentId}`,
複数のコンテンツから、sandbox.config.js を取得するため `contentId` を追加。

2019-12-04 05:23 UTC, ShinobuTakahashi commented
headless-driverがまだpublishされていないので、specがエラーとなっています
取り込み後要確認

2019-12-04 05:55 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/README.md
> +|`--allowed-external`|`-a`|外部アセットを許可します。許可する値は sandbox.config.js から読み込みます。|N/A|
allowed-external の頭文字の `-a` にしました。

2019-12-04 06:12 UTC, ShinobuTakahashi commented
headless-driverがまだpublishされていないので、travis がbuildでエラーとなっています
local環境ではnpm linkで動作確認済みだが、取り込み後に要確認

2019-12-05 07:38 UTC, xnv requested changes

2019-12-05 07:38 UTC, xnv commented on packages/akashic-cli-serve/README.md
> +|`--allow-external`|`-a`|外部アセットを許可します。許可する値は sandbox.config.js から読み込みます。|N/A|
将来他のものをを allow するようなオプションをつける可能性なんかを考えると、 `-a` という名前はちょっと "強すぎる" かと思います。順当に行くと `-e` か `-E` ……ですが、多用されるオプションでもなさそうですし、いったんショートハンドなしにしませんか。(後から足すのは簡単ですが逆はそうでないので)

2019-12-05 07:38 UTC, xnv commented on packages/akashic-cli-serve/src/server/route/ApiRoute.ts
> +	apiRouter.post("/runners/:contentId", createHandlerToCreateRunner(params.playStore, params.runnerStore, params.targetDirs));
現実的にはかろうじて重複しないようですが、 `/runners/` の下につくのは `:runnerId` になっているので、ここで `:contentId` を使うべきとは思えません。 (POST /runner/3 と GET /runner/3 で異なるリソースを扱うのはおよそ直観的とは言いがたいでしょう。もしパラメータが必要ならクエリパラメータでとるとか、別の形にしたいです。

2019-12-05 07:38 UTC, xnv commented on packages/akashic-cli-serve/src/server/controller/RunnerController.ts
> +function createAllowedUrls(contentId: string, externalAssets: (string | RegExp)[] | null) {
戻り値型が抜けているようです。

2019-12-05 07:38 UTC, xnv commented on packages/akashic-cli-serve/src/server/controller/RunnerController.ts
> +		if (externalAssets === null) return null;
このパスでは環境変数を参照しないようですが、意図した挙動でしょうか。

2019-12-05 07:38 UTC, xnv commented on packages/akashic-cli-serve/src/client/api/ApiClient.ts
> +		`/api/runners/${contentId}`,
ちょっと背景が掴みきれていないんですが、ここで `contentId` (あるいは sandbox.config.js ？) を指定している点に、まず根本的な違和感があります。 headless-driver において Play はコンテンツを指定して生成されるかと思います ＝ Play はコンテンツを知っています。ここで引数に取らなくても、 playId から解決できるまたはできるようにすべきに思えます。

2019-12-06 02:15 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/server/route/ApiRoute.ts
> +	apiRouter.post("/runners/:contentId", createHandlerToCreateRunner(params.playStore, params.runnerStore, params.targetDirs));
仰る通りです。`Play` から `contentId` が取得できたため、削除しました。

2019-12-06 02:29 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/server/controller/RunnerController.ts
> +		if (externalAssets === null) return null;
はい。`null` は全てのアクセスを許可すため、他の値を見ないようにしていました。
環境変数が `null`の場合、`null` を返すパスとコメントを追加しました。

2019-12-06 02:30 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/README.md
> +|`--allow-external`|`-a`|外部アセットを許可します。許可する値は sandbox.config.js から読み込みます。|N/A|
短縮なしにしました。

2019-12-06 02:30 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/server/controller/RunnerController.ts
> +function createAllowedUrls(contentId: string, externalAssets: (string | RegExp)[] | null) {
修正しました

2019-12-06 02:31 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/client/api/ApiClient.ts
> +		`/api/runners/${contentId}`,
`Play` から `contentId` が取得できましたのでの、この修正を削除しました。

2019-12-06 03:53 UTC, xnv requested changes

2019-12-06 03:53 UTC, xnv commented on packages/akashic-cli-serve/src/server/controller/RunnerController.ts
> +	targetDirs: string[]
この引数は必要でしょうか。……というか、 sandboxConfig を読み込んで validation するために使われているようですが、その validation って runner を作るたびに走る必要があるでしょうか。起動時に一度チェックすれば済みそうですし、そうすればこの引数が増える必要もなさそうに見えます。

2019-12-06 10:28 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/server/controller/RunnerController.ts
> +	targetDirs: string[]
口頭でご相談させていただいて、起動時ではなく `ContentController#createHandlerToGetContents()` で `sandbox.config.js` を読み込むように修正しました。

2019-12-06 10:32 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/server/controller/ContentController.ts
> +import { sandboxConfigs, loadSandboxConfigJs } from "../domain/SandboxConfigs";
`sandbox.config.js` の読み込み、検証、データを保持する `server/domain/SandboxConfigs.ts` を新規作成。

2019-12-09 02:51 UTC, xnv requested changes

2019-12-09 02:51 UTC, xnv commented on packages/akashic-cli-serve/src/server/domain/SandboxConfigs.ts
> +}
Array を継承する必要はないような……？　配列が必要だとしても単に空配列で十分ではありませんか。

2019-12-09 02:51 UTC, xnv commented on packages/akashic-cli-serve/src/server/domain/SandboxConfigs.ts
> +export const sandboxConfigs = new SandboxConfigs();
二度 validateConfig()しないように値をキャッシュされているように読めますが、キャッシュした値を返すか読み直すかは `loadSandboxConfigJs()` が決めればいいことではありませんか。このファイルの外で「読み込み済みかそうでないか」を気にさせる必要はないと思います。

2019-12-09 02:51 UTC, xnv commented on packages/akashic-cli-serve/src/server/controller/ContentController.ts
> +			sandboxConfigs.init();
誰かが /api/contents/ を呼ぶたびに sandboxConfigs がリセットされて読み直されそうですが、これでいいんですっけ……。

2019-12-09 02:52 UTC, xnv commented on packages/akashic-cli-serve/src/server/domain/SandboxConfigs.ts
> +export const sandboxConfigs = new SandboxConfigs();
別にそう多発する処理でもないでしょうし、いったん「TODO: 読み込み直さなかった時は validation を省略する」とか書いて毎回 validateConfig() してもいいと思います。

2019-12-09 08:37 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/server/controller/ContentController.ts
> +			sandboxConfigs.init();
別途口頭でご相談させていただきましたが、SandboxConfigの読み込みタイミング/反映の問題は別タスクとしたため、削除しました

2019-12-09 08:37 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/server/domain/SandboxConfigs.ts
> +export const sandboxConfigs = new SandboxConfigs();
TODOコメントを追加しました。

2019-12-09 08:37 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/server/domain/SandboxConfigs.ts
> +}
別途口頭でご相談させていただきましたが、SandboxConfigの読み込みタイミング/反映の問題は別タスクとしたため、削除しました

2019-12-10 08:05 UTC, xnv commented on packages/akashic-cli-serve/src/server/domain/RunnerStore.ts
> +	contentId: string;
えっと。話が何か巻き戻ってしまった気もするんですが、 この `contentId` とか `targetDirs` とか必要ですか。 playId から引けるのではないでしょうか。

2019-12-10 08:44 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/server/domain/RunnerStore.ts
> +	contentId: string;
RunnerStoreでは、playStoreを持っていないため、`playId` からcontentIdを取得できません。
また、`targetDirs` に該当する情報をContentから現状取得できないため、`targetDirs`を渡し、TODOコメントを残しました。

2019-12-11 06:51 UTC, dera- approved these changes

2019-12-12 08:31 UTC, xnv approved these changes

2019-12-13 04:45 UTC, ShinobuTakahashi commented
headless-driverのマイナーversionが上がったため、package更新。
最新のheadless-driverを取り込み、travis-ciが通る事を確認。

2019-12-13 04:46 UTC, merged