akashic-cli-serveでplaylogを予め読み込んだplayを作成できるようにした
akashic-games/akashic-cli pull request #203
Opened 2019-12-04 14:50 UTC by dera-

### やったこと
* サーバー側でplaylogが書かれたjsonファイルを読み込むためのオプション`--playlogPath`を追加
  * このオプションで読み込めるのはplay1つ分のみ
* クライアント側で新たにplayIdとmodeというクエリパラメーターを追加
  * playIdにplaylogを読み込んでいるplayのidを、modeにreplayを指定してアクセスした場合そのplaylogがリプレイモードで再生されるようになっている

2019-12-05 03:08 UTC, yu-ogi commented on packages/akashic-cli-serve/src/server/index.ts
> +		const actualPath = path.join(process.cwd(), commander.playlogPath);
(imo) どちらかというと `absolutePath` の方が適切なのかなと思いました。

2019-12-05 03:08 UTC, yu-ogi commented on packages/akashic-cli-serve/src/server/domain/PlayStore.ts
> +	async loadPlaylog(playId: string, playlog: any): Promise<void> {
`playlog` には最低限 (このメソッド内で必要な分のみ) の型を付けておきたいです。

2019-12-05 03:08 UTC, yu-ogi commented on packages/akashic-cli-serve/src/server/domain/PlayStore.ts
> +		amflow.open(playId, e => {
ネストが深くなりすぎているので、 amflow のメソッドを Promise でラップしてあげても良さそうに思いました。

```javascript
...
try {
  await new Promise((resolve, reject) => amflow.open(playId, e => e ? reject(e) : resolve()));
...
} catch (e) {
  throw e;
}
...

```

2019-12-05 03:08 UTC, yu-ogi commented on packages/akashic-cli-serve/src/server/index.ts
> +		.option("-P, --playlog-path <playlogPath>", `Specify path of playlog-json. arguments: .`)
* (imo) `path` なのは自明のように思えるので `--playlog` でも十分かと思いました。
* (imo) そこまで多用するようなものでも無さそうなので、一旦はショートハンドはなくしてしまっても良いのではと思いました。(増やすより減らすほうが大事になるので)

2019-12-05 03:08 UTC, yu-ogi commented on packages/akashic-cli-serve/src/server/domain/PlayStore.ts
> +								amflow.sendTick(tick);
このメソッドの戻り値の `Promise` はここまでの処理を待たずに resolve してしまっても問題ないのでしょうか。

2019-12-05 03:08 UTC, yu-ogi commented on packages/akashic-cli-serve/src/client/operator/Operator.ts
> +		const query = queryString.parse(window.location.search);
このあたりの情報は store で保持しなくても問題ない (view に反映させる必要はない?) のでしょうか。

2019-12-05 17:11 UTC, dera- commented on packages/akashic-cli-serve/src/server/index.ts
> +		const actualPath = path.join(process.cwd(), commander.playlogPath);
仰る通りですね、こちら修正します。

2019-12-05 17:12 UTC, dera- commented on packages/akashic-cli-serve/src/server/domain/PlayStore.ts
> +	async loadPlaylog(playId: string, playlog: any): Promise<void> {
Playlogというinterfaceを同ファイル内に作成しました。

2019-12-05 17:15 UTC, dera- commented on packages/akashic-cli-serve/src/server/domain/PlayStore.ts
> +		amflow.open(playId, e => {
こちらPromiseでラップするように修正しました。

2019-12-05 17:17 UTC, dera- commented on packages/akashic-cli-serve/src/server/index.ts
> +		.option("-P, --playlog-path <playlogPath>", `Specify path of playlog-json. arguments: .`)
オプション名を`--playlog`に修正しました。`-P`を使いたいオプションが後からできることも考えうるのでショートハンドは使わない方向で修正しました。

2019-12-05 17:20 UTC, dera- commented on packages/akashic-cli-serve/src/server/domain/PlayStore.ts
> +								amflow.sendTick(tick);
open, authenticate, putStartPointをPromiseでラップして都度待つようにしました(sendについてはコールバック関数がないので待つことはできませんが)。

2019-12-05 17:23 UTC, dera- commented on packages/akashic-cli-serve/src/client/operator/Operator.ts
> +		const query = queryString.parse(window.location.search);
今回追加したplayIdとmodeはあくまでplaylogを流し込むためだけに暫定的に追加したもので、他で使う想定はありませんし最終的にはこのクエリ自体要らなくなるようにする予定なので、Storeで保持しておく必要はないかなぁと判断しました。

2019-12-06 03:43 UTC, yu-ogi commented on packages/akashic-cli-serve/src/server/index.ts
> +		.option("--playlog <playlog>", `Specify path of playlog-json. arguments: .`)
説明の `arguments: .` というのはどういう意味でしょう?

2019-12-06 03:43 UTC, yu-ogi commented on packages/akashic-cli-serve/src/server/domain/PlayStore.ts
> +				.then(() => {
ここは `.then(() => new Promise(..))` と記述するとネストが一つ減りそうですね。

または promise を AMFlow のメソッド単位で分割してしまっても良さそうです。

```javascript
await new Promise(() => amflow.open(..));
await new Promsie(() => amflow.authenticate(...));
...
```

2019-12-06 03:43 UTC, yu-ogi commented on packages/akashic-cli-serve/src/server/domain/PlayStore.ts
> +			throw e;
ただ単に e を投げているだけなので、実行側で例外をキャッチしているならここでの try-catch は無くても良さそうに思います。

2019-12-06 03:43 UTC, yu-ogi commented on packages/akashic-cli-serve/src/server/domain/PlayStore.ts
> +						playlog.tickList[2].forEach((tick: any) => {
こちらは `AMFlow#putStartPoint()` の `then()` 以降に実行したほうが、それぞれのメソッド処理を promise 単位で分けることができるのでわかりやすくなるかなと思いました。

```javascript
.then(() => new Promise((...) => amflow.authenticate(...)))
.then(() => new Promise((...) => amflow.putStartPoint(...)))
.then(() => {
    ...
    amflow.sendTick(tick);
})
```

2019-12-06 08:44 UTC, dera- commented on packages/akashic-cli-serve/src/server/index.ts
> +		.option("--playlog <playlog>", `Specify path of playlog-json. arguments: .`)
あ、、、defaultと書いていたつもりでしたが完全に間違えていました。。修正しておきます

2019-12-06 08:44 UTC, dera- commented on packages/akashic-cli-serve/src/server/domain/PlayStore.ts
> +				.then(() => {
仰る通りですね。こちら、そのように修正します

2019-12-06 08:44 UTC, dera- commented on packages/akashic-cli-serve/src/server/domain/PlayStore.ts
> +			throw e;
了解しました。ここのtry-catchは消しておきます

2019-12-06 08:45 UTC, dera- commented on packages/akashic-cli-serve/src/server/domain/PlayStore.ts
> +						playlog.tickList[2].forEach((tick: any) => {
なるほど、確かにそちらの方が可読性が上がりそうですね。そのように直しておきます

2019-12-09 02:27 UTC, yu-ogi commented on packages/akashic-cli-serve/src/server/index.ts
> +		.option("--playlog <playlog>", `Specify path of playlog-json. default: .`)
(imo) `<playlog>` という書き方だと json データをそのまま引数に渡すように見えてしまうので `<path>` という書き方のほうがわかりやすいかなと思いました。

2019-12-09 02:27 UTC, yu-ogi commented on packages/akashic-cli-serve/src/client/operator/Operator.ts
> +		if (params.isReplay) {
`params` は `| undefined` なので、下の行と同様に `params != null` の判定が必要そうです。

2019-12-09 02:27 UTC, yu-ogi commented on packages/akashic-cli-serve/src/client/operator/Operator.ts
> +			executionMode: params.isReplay ? "replay" : "passive",
こちらもですね。

2019-12-09 02:27 UTC, yu-ogi commented on packages/akashic-cli-serve/src/server/domain/PlayStore.ts
> +	async loadPlaylog(playId: string, playlog: Playlog): Promise<void> {
(imo) 処理を見ると `createAMFlowAndLoadPlaylog()` という感じですかね。
このあたりは `PlayStore` を利用する側でロジックをもたせてしまっても良さそうに思いました。
そうでないと `amflow` が行方不明になってしまいそうです。

以下は呼び出し側の責務としてしまっても良さそうに思いましたがいかがでしょう。
* token の作成
* amflow の作成
* play の作成
* playlog を差し込む

2019-12-09 02:27 UTC, yu-ogi commented on packages/akashic-cli-serve/src/server/domain/PlayStore.ts
> +			amflow.sendTick(tick);
(imo) このあたりをみると、playlog を読み込む機能は本質的には `AMFlowClient` 側 (`AMFlow#loadPlaylog()` ?) にあるのが適切なのかなとも思ってきました。

2019-12-09 07:45 UTC, dera- commented on packages/akashic-cli-serve/src/client/operator/Operator.ts
> +		if (params.isReplay) {
`params`が`undefined`も含むことを失念していました。。そのように修正しておきます。

2019-12-09 07:45 UTC, dera- commented on packages/akashic-cli-serve/src/client/operator/Operator.ts
> +			executionMode: params.isReplay ? "replay" : "passive",
こちらも同様に修正します。

2019-12-09 07:49 UTC, dera- commented on packages/akashic-cli-serve/src/server/index.ts
> +		.option("--playlog <playlog>", `Specify path of playlog-json. default: .`)
確かにそうですね。`<playlog>`を`<path>`に直しておきます

2019-12-09 07:53 UTC, dera- commented on packages/akashic-cli-serve/src/server/domain/PlayStore.ts
> +	async loadPlaylog(playId: string, playlog: Playlog): Promise<void> {
やっていることはまさにその通りですので、そちらにリネームしておきます > `createAMFlowAndLoadPlaylog`

それから、playの作成、tokenの作成、playlogの差し込みは外部から行うようにしようと思いますが、メソッド名的にamflowの作成はこのメソッドの責務としてもよいのではと思いました。

2019-12-09 08:03 UTC, xnv requested changes

2019-12-09 08:03 UTC, xnv commented on packages/akashic-cli-serve/src/client/operator/Operator.ts
> +				const target = plays.filter(play => play.playId === query.playId);
`filter` で探さなくても `store.playStore.player[playId]` で直接抜けそうです。

またそうすれば、この else の中で処理する理由もなくなりそうに思います。 `query.playId` があるパスを真っ先に処理して `if (query.playId != null) { ... } else if (contentLocator) { ... } else { ... }` の形にする方が straightforward ではないでしょうか (`contentLocator && !query.playId` という条件が単純化できます)。

2019-12-09 08:03 UTC, xnv commented on packages/akashic-cli-serve/src/server/index.ts
> +		.option("--playlog <playlog>", `Specify path of playlog-json. default: .`)
`default: .` とありますがデフォルト値があるんでしょうか。あるとしても `.` ではなさそうに思えます。

2019-12-09 08:03 UTC, xnv commented on packages/akashic-cli-serve/src/server/index.ts
> +		.option("--playlog <playlog>", `Specify path of playlog-json. default: .`)
これお願いしておいてなんですが、複数コンテンツの話が絡んでくるとわけがわからなくなりそうなので、 `--debug-` とか頭につけておきませんか。(最終的に指定するのは AMFlowStore 全体のダンプファイルとかになる気もしてきました)

2019-12-09 08:03 UTC, xnv commented on packages/akashic-cli-serve/src/server/index.ts
> +		// 現状指定されるplaylogは1つの想定なので、contentIdは必ず0になる
「contentId は必ず 0 になる」のではなく、「現状 playlog は一つしか受け取らない。それは contentId: 0 のコンテンツの playlog として扱う」という仕様決めの問題ではないでしょうか。

2019-12-09 08:05 UTC, dera- commented on packages/akashic-cli-serve/src/server/domain/PlayStore.ts
> +			amflow.sendTick(tick);
これについては大分悩みましたが、`loadPlaylog`といったopenからsendEventまでをラップしたメソッドをAMFlowClientに置くと今まで割かしプリミティブなメソッドだけを置いていたAMFlowClientの意味合いが変わってしまうのではと思ったので、今回はPlayStoreで定義しておく形にとどめたいです。
もし、playStoreを経由しない別箇所でもこのメソッドを必要とする場合が生じたならば、その時はAMFlowClient側に配置しようかと思います

2019-12-09 08:12 UTC, xnv commented on packages/akashic-cli-serve/src/server/domain/PlayStore.ts
> +	async loadPlaylog(playId: string, playlog: Playlog): Promise<void> {
えっと……。amflow を作っているのはこのメソッドの内部実装の話であって、外形的には AMFlow を作っているかはどうでもいいのでは (＝名前に現れるべきではないのでは) ありませんか。amflow は行方不明にするのではなく、ここで破棄すべきに思えます。

もし createAMFlow〜 と呼ぶなら戻り値が AMFlow でないと落ち着かないと思いますし、そうなると AMFlow の作成と playlog の流し込みを同時にやるメソッドになりますが、概念的によくわからない点が気になります。(play の作成時に playlog を与えるなら理解できますが)

2019-12-09 08:14 UTC, xnv commented on packages/akashic-cli-serve/src/server/domain/PlayStore.ts
> +	async loadPlaylog(playId: string, playlog: Playlog): Promise<void> {
loadPlaylog() とすると任意のタイミングで呼び出せそうですが、このメソッドの中身はそうなってはいなさそうなのもひっかります。上述のとおりプレイの作成時、 createPlay() のオプションに playlog が指定できるようにすることはできないでしょうか。

2019-12-09 08:23 UTC, xnv commented on packages/akashic-cli-serve/src/server/domain/PlayStore.ts
> +			amflow.sendTick(tick);
`SocketIOAMFlowClient#loadPlaylog()` にするなら、 open() 〜 authenticate() までは済んでいる前提で、 putStartPoint() と sendTick() をやるメソッドになると思います。

そしてそういうユーティリティは別に生えてもいいのでは。 interface `AMFlow` は primitive であるべきだと思いますが、実装である `SocketIOAMFlowClient` にユーティリティが生えるのは別にそんな不自然でもないように思います。(ただ putStartPoint() と sendTick() だけなら、メソッドにまとめるほど複雑な話でもなさそうなので、別にそうしたいというつもりはないです)

2019-12-10 04:29 UTC, yu-ogi approved these changes

2019-12-10 04:29 UTC, yu-ogi commented on packages/akashic-cli-serve/src/server/domain/PlayStore.ts
> +		playlog.tickList[2].forEach((tick: any) => {
細かいですが、おそらく型推論されていると思うのでわざわざ any にしなくても良さそうに思いました。

```javascript
playlog.tickList[2].forEach(tick => {
   ...
```

2019-12-10 05:39 UTC, dera- commented on packages/akashic-cli-serve/src/server/domain/PlayStore.ts
> +	async loadPlaylog(playId: string, playlog: Playlog): Promise<void> {
なるほど。。privateの`loadPlaylog()`メソッドにしておいて、createPlaylog()のオプションでplaylogが指定されたときに呼び出すようにしようと思います。
それと`loadPlaylog()`で生成されたamflowも即破棄するようにしておきます

2019-12-10 05:44 UTC, dera- commented on packages/akashic-cli-serve/src/server/domain/PlayStore.ts
> +			amflow.sendTick(tick);
putStartPoint() と sendTick()の2つのメソッドをラップした感じになるんですね。
SocketIOAMFlowClientに置くこと自体は不自然ではないということは分かりましたが、であれば仰る通り新しくメソッドを新設するほどの処理はしていないので今やっている通り各々のメソッドを外から呼ぶでよさそうですね

2019-12-10 05:45 UTC, dera- commented on packages/akashic-cli-serve/src/client/operator/Operator.ts
> +				const target = plays.filter(play => play.playId === query.playId);
ありがとうございます、そのように修正してみます

2019-12-10 06:02 UTC, dera- commented on packages/akashic-cli-serve/src/server/index.ts
> +		.option("--playlog <playlog>", `Specify path of playlog-json. default: .`)
特にデフォルト値はありませんね。。こちら削除しておきます。

2019-12-10 06:03 UTC, dera- commented on packages/akashic-cli-serve/src/server/index.ts
> +		.option("--playlog <playlog>", `Specify path of playlog-json. default: .`)
言われてみれば今の状態は1つのコンテンツにしかplaylogを指定できないので完成系ではないですね。。オプション名をそのように修正しておきます。

2019-12-10 06:07 UTC, dera- commented on packages/akashic-cli-serve/src/server/index.ts
> +		// 現状指定されるplaylogは1つの想定なので、contentIdは必ず0になる
仰る通りでした。。コメントもそのように修正しておきます。

2019-12-10 06:08 UTC, dera- commented on packages/akashic-cli-serve/src/server/domain/PlayStore.ts
> +		playlog.tickList[2].forEach((tick: any) => {
了解しました、そのように修正してみます

2019-12-10 07:35 UTC, xnv requested changes

2019-12-10 07:35 UTC, xnv commented on packages/akashic-cli-serve/src/server/domain/PlayStore.ts
> +export interface Playlog {
- モジュール名そのものを占有するほど一般的な形でもありませんし、 `DumpedPlaylog` ぐらいの名前にしておきませんか。
- 置き場所も src/server/common/types/ 下とかにしたいです (クライアントサイドでも使う時は src/common/types/ に移動することになると思いますが)

2019-12-10 07:35 UTC, xnv commented on packages/akashic-cli-serve/src/client/operator/Operator.ts
> +			play = target;
target という抽象的な名前の変数を介する必要はなくなっているかと思います。最初から `play` に代入すればよいのでは。

2019-12-10 07:35 UTC, xnv commented on packages/akashic-cli-serve/src/server/index.ts
> +		const playlog = require(absolutePath);
require() も try の中に入れたいです。 existsSync() したからといって次の瞬間ファイルが移動されていない保証はないので、 existsSync() せずに単にいきなり require() して失敗したらエラーにするでいいのではないでしょうか。

2019-12-10 07:35 UTC, xnv commented on packages/akashic-cli-serve/src/client/operator/Operator.ts
> +			play.handlePlayDurationStateChange(false, 0);
entity が持っている handle〜 というメソッドは、名前と呼び出され方を見ていただくとわかるのですが、何がしかの通知に対するハンドラを書いているつもりです。なんの通知でもないところでいきなりこのメソッドを呼び出すのは、周辺の前提を崩す可能性が高く慎重になるべきに思えます。

このメソッドに関して言えば、これはサーバが通知してくるプレイ状態と時刻を手元の local instance に反映するためのハンドラです。これを呼び出すならば、サーバサイドのプレイの状態がそれに対応するものになっているべきに思えます。というかむしろ、サーバサイドのプレイの状態をこれに対応するように変化させ、結果としてそれが通知されるというのがあるべき形ではないでしょうか。

サーバサイドの PlayEntity で create してloadPlaylog() した時、 サーバサイドの play の duraiton は引き続き 0 になってしまっていると思います。この値を正しく設定して `onPlayDurationChanged` を fire すると、結果としてまさにここの  `handlePlayDurationStateChange()` が呼ばれるはずなので、ここでどうこうするよりもサーバサイドの対応が必要そうに見えます。

この箇所で何かすることがあるとしたら、それは local instance の target time を 0 にすることで、それは`LocalInstanceOperator#seekTo()` (シークバー操作によるリプレイモードへの遷移) がやっていることに対応するはずです。

2019-12-10 11:48 UTC, dera- commented on packages/akashic-cli-serve/src/server/domain/PlayStore.ts
> +export interface Playlog {
了解しました。src/server/common下にtypesディレクトリを作成して同様の内容の`DumpedPlaylog`インターフェースを作成しました

2019-12-10 11:49 UTC, dera- commented on packages/akashic-cli-serve/src/client/operator/Operator.ts
> +			play = target;
確かにそうですね、直しておきます。

2019-12-10 11:53 UTC, dera- commented on packages/akashic-cli-serve/src/server/index.ts
> +		const playlog = require(absolutePath);
了解しました。そのように修正しておきます(移動されなくても中身がjsonとしてのシンタックスになっていない場合など失敗するケースが割とありますし。。)

2019-12-10 11:58 UTC, dera- commented on packages/akashic-cli-serve/src/client/operator/Operator.ts
> +			play.handlePlayDurationStateChange(false, 0);
クライアントでplayの時間を設定する処理を削除しました。代わりにサーバーサイドでdurationを設定してクライアントではそれを受け取るだけになるよう修正しました。

2019-12-12 08:29 UTC, xnv requested changes

2019-12-12 08:29 UTC, xnv commented on packages/akashic-cli-serve/src/server/domain/PlayStore.ts
> +		timeKeeper.origin = Date.now();
いや…… Akashic Engine の悪習で公開しちゃってますけど、およそ外部から代入するような値ではないと思います。setTime() するだけでは足りないでしょうか。もし足りないなら専用のメソッドを `TimeKeeper` に生やすべきでしょう。

2019-12-12 08:29 UTC, xnv commented on packages/akashic-cli-serve/src/server/domain/PlayStore.ts
> +		timeKeeper.pausedTime = playlog.tickList[1] * 1000 / playlog.startPoints[0].data.fps;
最終 tick の時刻はこの形では算出できないことがあります (TimestampEvent がついている場合)。 [sandbox の対応箇所](https://github.com/akashic-games/akashic-sandbox/blob/f6938d46019f48ebffc35873296955f929887d60/engine-src/v2/js/sandbox.js#L148-L165) を参考にしてもらえれば。

2019-12-12 16:31 UTC, dera- commented on packages/akashic-cli-serve/src/server/domain/PlayStore.ts
> +		timeKeeper.origin = Date.now();
今のところ、originとpausedTimeを更新するメソッドは`TimeKeeper`中に存在しないので、`setFinishedTime`という感じのメソッドを追加しようと思います

2019-12-12 18:53 UTC, dera- commented on packages/akashic-cli-serve/src/server/domain/PlayStore.ts
> +		timeKeeper.pausedTime = playlog.tickList[1] * 1000 / playlog.startPoints[0].data.fps;
ありがとうございます、結構算出方法が複雑なんですね。。最終tickの時間を取得するprivateメソッドを新たに追加してみます

2019-12-16 06:44 UTC, xnv commented on packages/akashic-cli-serve/src/common/TimeKeeper.ts
> +	}
よく見ると now() の origin を参照しているパスが問題なようですが、constructor で `Date.now()` いれてこの null チェックするパスなくしちゃえば、このメソッドを足さなくてもよかったりしませんか。

2019-12-16 08:02 UTC, dera- commented on packages/akashic-cli-serve/src/common/TimeKeeper.ts
> +	}
コード上問題なさそうですし、そのように対応して動作確認しても問題がなかったので、そのように修正しました。

2019-12-17 02:35 UTC, xnv approved these changes

2019-12-17 06:59 UTC, merged