Add Playlog dump function
akashic-games/akashic-cli pull request #210
Opened 2019-12-10 06:37 UTC by ShinobuTakahashi

## 修正内容

PlayLogのdump機能の追加。
PlayLog取得API (`/plays/${playId}/playlog`) の実行で、`playId` に対応したPlayLogデータをJSONファイルとしてダウンロードできる。
ダウンロードしたファイルは、Sandboxのリプレイで読み込み&リプレイ再生可能となる。

2019-12-10 06:43 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/client/operator/PlayOperator.ts
> +		}
値が空の場合は何もしない。
また、JSONパースエラーの場合、修正前のエラーが `A cross-origin error was thrown...` とよくわからないエラーメッセージとなっていたので、catchし、`SyntaxError...` と表示されるように修正

2019-12-10 06:45 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/server/controller/PlayController.ts
> -import { ContentParameters } from "@akashic/headless-driver";
未使用のため削除

2019-12-10 07:47 UTC, ShinobuTakahashi commented
headless-driverのAMFlowの修正がまだpublishされていないので、travisのビルドでエラーとなっています。
headless-driverのpublish後にtravisCI確認します

2019-12-10 08:06 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/server/controller/PlayController.ts
> +			const fileName = `playlog${playId}_${new Date().getTime()}.json`;
仮でダウンロードするファイル名を `playlog0_1575959245900.json` としました。
適切なファイル名あればお願いいたします

2019-12-10 10:04 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/server/domain/SocketIOAMFlowManager.ts
> +			delete this.connectionMap[connectionId].emitTick;
PlayLogの出力に必要な `playId`と`AMFlow` 以外を削除

2019-12-10 10:09 UTC, ShinobuTakahashi commented
headless-driverのAMFlowの修正がまだpublishされていないので、travisのビルドでエラーとなっています。
headless-driverのpublish後にtravisCI確認します

2019-12-10 10:14 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/server/controller/PlayController.ts
> +			const fileName = `playlog_${playId}_${Date.now()}.json`;
仮でダウンロードするファイル名を playlog_0_1575959245900.json のようにしました。
sandboxでは、1575959245900.json ですが、playIdに紐づくのでplayIdは入れたファイル名が良いと思いますが、適切な名前があればお願いします。

2019-12-10 10:25 UTC, xnv requested changes

2019-12-10 10:25 UTC, xnv commented on packages/akashic-cli-serve/src/server/domain/SocketIOAMFlowManager.ts
> +			delete this.connectionMap[connectionId].emitTick;
いや……さすがにつらいですね……？　そもそも SocketIOAMFlowManager の AMFlow を保持しておく必要があるでしょうか。必要になった時に headless-driver で新たに AMFlow と生成して使う方が簡単ではありませんか。(そんな初期化が激烈に重いものでもないでしょうし、高頻度で呼ばれるものでもないと思います)

2019-12-10 10:25 UTC, xnv commented on packages/akashic-cli-serve/src/server/controller/PlayController.ts
> +			const fileName = `playlog_${playId}_${new Date().getTime()}.json`;
`new Date().getTime()` よりも `Date.now()` の方が簡潔かと思います (余計にオブジェクトを作らなくて分無駄もないです)

2019-12-10 10:25 UTC, xnv commented on packages/akashic-cli-serve/src/client/operator/PlayOperator.ts
> +		}
cross-origin error ってここで関係してくるんですかね……？　https://ja.reactjs.org/docs/cross-origin-errors.html#source-maps sourcemap の問題とかだったらここで捌くよりビルドの設定変えた方が良さそうですが……。

2019-12-10 11:13 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/server/domain/SocketIOAMFlowManager.ts
> +			delete this.connectionMap[connectionId].emitTick;
仰る通り headless-driver側で保持しているのに、 `SocketIOAMFlowManager` での保持する理由がありませんでした。
必要な時にAMFlowを生成して使用するように修正しました。

2019-12-11 02:27 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/server/controller/PlayController.ts
> +			const fileName = `playlog_${playId}_${new Date().getTime()}.json`;
`Date.now()`に修正しました。

2019-12-11 09:14 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/client/operator/PlayOperator.ts
> +		}
JSONパースエラー時に、reactのwindowのエラーハンドリングの中で、引数のeventにerrorプロパティがない等の判断で、react はcross-originのエラーとしている。
なぜ、その様なeventObjectが渡るのかまでは調査していないが、try-catchにて`SyntaxError` を表示できる様に一旦修正。
TODOコメントにて、このパスには正常な値が渡ってくるようにする旨を追加。

2019-12-12 08:30 UTC, xnv approved these changes

2019-12-13 03:50 UTC, ShinobuTakahashi commented
dump機能追加のheadless-driverをpublishし、TravisCIが通る事を確認

2019-12-17 10:54 UTC, kamakiri01 approved these changes

2019-12-18 02:28 UTC, merged