define cli config types
akashic-games/akashic-cli pull request #217
Opened 2019-12-21 09:12 UTC by kamakiri01

## このpull requestが解決する内容

### 概要

各akashicコマンドのコマンドライン引数の型定義を、akashic-cli-commonsに移します。
この修正後、各akashicコマンドはcommonsの定義を参照するようになります。

また、各akashicコマンドのデフォルトのコマンドライン引数を定義する akashicConfig.jsonの定義と、このファイルの読み書きを実装します。

## 破壊的な変更を含んでいるか?

- なし

2019-12-24 06:03 UTC, kamakiri01 commented on packages/akashic-cli-commons/src/CliConfig/CliConfigurationFile.ts
> +}
diffファイル数が多いですが、型定義ファイルの移設が大半です。
実質的な修正点はこの箇所です。

2019-12-24 06:44 UTC, kamakiri01 commented on packages/akashic-cli-commons/src/CliConfig/CliConfigurationFile.ts
> +	export function read(confPath: string, callback: (conf: CliConfiguration) => void): void {
asyncにするか迷ったのですが、各コマンドのcli側もasyncにする必要があること・そちらのネストが浅いことからコールバックで返すようにしています。

2020-01-22 11:02 UTC, xnv requested changes

2020-01-22 11:02 UTC, xnv commented on packages/akashic-cli-commons/src/CliConfig/CliConfiguration.ts
> +		};
`akashic export html` の html 部分と `akashic scan asset` の assset の部分はユーザから見ると同じに見えますが、ここでは `exportHtml` と `scan.asset` に分離してしまっているのが気になります。

どっちに揃えるかは微妙な気もしますが、この形なら export.html になる方が妥当ですかねえ。

2020-01-23 06:53 UTC, kamakiri01 commented on packages/akashic-cli-commons/src/CliConfig/CliConfiguration.ts
> +		};
リポジトリ単位よりはコマンドのUI単位で分けたほうが良さそうです。export.html / zipに分けます。

2020-01-29 03:17 UTC, xnv approved these changes

2020-01-31 03:36 UTC, merged