Use cli config param
akashic-games/akashic-cli pull request #218
Opened 2019-12-24 06:20 UTC by kamakiri01

## このpull requestが解決する内容

### 概要
https://github.com/akashic-games/akashic-cli/pull/217 を使う実装のたたき台です。
game.jsonと同じディレクトリに `akashicConfig.json` がある場合、これを利用してコマンドラインオプションを補完します。

## 破壊的な変更を含んでいるか?

- なし

****

2019-12-25 04:56 UTC, kamakiri01 commented on packages/akashic-cli-export-html/src/app/cli.ts
> +		});
https://github.com/akashic-games/akashic-cli/pull/217 のマージ後利用できるようになります。
コマンド実行時のオプションで指定されればそれを使い、無ければ設定ファイルの設定を探し、それもなければコマンド内部のデフォルトパラメータを利用するようになります。

2020-01-22 11:07 UTC, xnv requested changes

2020-01-22 11:07 UTC, xnv commented on packages/akashic-cli-export-zip/src/cli.ts
> +			omitEmptyJs: commander["omitEmptyJs"] || conf.omitEmptyJs
これだとコマンドラインから `--no-omit-empty-js` を指定して値を `false` にした時に、無視して `conf.omitEmptyJs` の値が使われてしまうのではないでしょうか。全ての箇所で、 `||` ではなく「`undefined` かどうか」で分岐する必要があるはずです。(TS 3.7 なら `??` を使うこともできそうです)

特にデフォルトが falsy なオプションや `--no-` を使うオプションについて、動作確認をお願いしたいです。

2020-02-04 02:54 UTC, kamakiri01 commented on packages/akashic-cli-export-zip/src/cli.ts
> +			omitEmptyJs: commander["omitEmptyJs"] || conf.omitEmptyJs
`??` に修正、確認します。

2020-02-05 03:35 UTC, xnv approved these changes

2020-02-06 03:47 UTC, merged