fix: loading timing of sandboxConfig
akashic-games/akashic-cli pull request #223
Opened 2020-01-07 10:33 UTC by ShinobuTakahashi

## 修正内容

- sandbox.config.jsの読み込むタイミングを修正
-

2020-01-07 10:39 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/client/api/ApiClient.ts
> +	ContentGetApiResponse,
コンテンツ全てのレスポンスを返す既存の `ContentsGetApiResponse` を `ContentsGetAllApiResponse`へ変更。

2020-01-07 10:52 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/server/controller/RunnerController.ts
> -	targetDirs: string[]
`RunnerStoer#createAndStartRunner()` へ `targetDirs` を渡す必要がなくなったので削除

2020-01-07 10:54 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/server/domain/RunnerStore.ts
> -		const sandboxConfig = loadSandboxConfigJs(sandboxConfigDir);
ここで `sandbox.config.js` を読み込む必要がなくなったため削除

2020-01-09 07:47 UTC, dera- commented on packages/akashic-cli-serve/src/server/domain/SandboxConfigs.ts
> +			} else {
何もしないのであればこのelse文は必要ない気がしたのですが、後から処理の追加等の予定がある感じでしょうか？

2020-01-09 08:10 UTC, dera- commented on packages/akashic-cli-serve/src/server/route/ContentsRoute.ts
> +		sandboxConfigs.loadSandboxConfigJs(targetDirs[i], i.toString());
~Routeではルーティングのみを責務としたいので、できれば別の個所で`loadSandboxConfigJs`していただきたいです。(となるとindexな気がしますが、エントリポイントが多くなるのも微妙ではありますが。。)

2020-01-09 10:44 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/server/route/ContentsRoute.ts
> +		sandboxConfigs.loadSandboxConfigJs(targetDirs[i], i.toString());
仰る通りです。indexに追加するのもどうかと思いここに記述してしまいました。
一番最初にsandboxConfigを使う contents API (`ContentController#createHandlerToGetContents()`) でコメントを追加し、その中で loadするように変更しました。

2020-01-09 10:44 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/server/domain/SandboxConfigs.ts
> +			} else {
後で処理追加する予定もないので、elseのパスを削除しました。

2020-01-10 10:30 UTC, dera- approved these changes

2020-01-14 11:36 UTC, xnv commented on packages/akashic-cli-serve/src/server/domain/SandboxConfigs.ts
> +	static getInstance(): SandboxConfigs {
singleton パターンで実装されてますが、 JavaScript で文字通りの singleton やるモチベーションってあまりないのではありませんか。単純に モジュール内変数と関数をエクスポートすればいいのでは。

2020-01-14 11:49 UTC, xnv requested changes

2020-01-14 11:49 UTC, xnv commented on packages/akashic-cli-serve/src/server/domain/SandboxConfigs.ts
> +	loadSandboxConfigJs(targetDir: string, contentId: string): void {
- load したのに戻り値もなければコールバックもないのは不自然に思えます。
- load の後、いつ get できるのか判断できない・していないのも不具合の原因になりそうで気になります。(現状動いているのはたまたまではありませんか)
- そもそも、このモジュールのユーザから見て load と get を区別する利点はないように思えます。ユーザから見れば常に load() だけすればよいようにはできないでしょうか。「ファイルを監視するか逐次読み込み直すか」は、このモジュールの内部実装の問題にすぎないと思います。

2020-01-14 11:49 UTC, xnv commented on packages/akashic-cli-serve/src/server/controller/ContentController.ts
> +			sandboxConfig: {}
「load だけしておいて一旦ここでは空オブジェクトを返し、下で get する」というどうにも回りくどい処理になっていますが、別で書いたとおり load とget を統合すれば、この部分に差分は出ないのではないかと思います。

2020-01-16 10:46 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/server/controller/ContentController.ts
> +			sandboxConfig: {}
`loadSandboxConfigJs()` で戻り値が返るよう修正しました。

2020-01-16 10:46 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/server/domain/SandboxConfigs.ts
> +	static getInstance(): SandboxConfigs {
仰る通り、モジュール内変数&関数で事足りてしまいました。
class化するまでもなかったので、変数&関数で定義しなおしました。

2020-01-16 10:46 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/server/domain/SandboxConfigs.ts
> +	loadSandboxConfigJs(targetDir: string, contentId: string): void {
`loadSandboxConfigJs()` に戻り値を追加し、`load` も `get` もこの関数をだけでできるよう修正しました。

2020-01-21 07:08 UTC, xnv requested changes

2020-01-21 07:08 UTC, xnv commented on packages/akashic-cli-serve/src/client/operator/Operator.ts
> +		await this.store.contentStore.updateSandboxConfig(this.store.currentPlay.content.locator);
`content` から `locator` を抜き出して  `contentStore` に何かさせるよりも、 `ContentEntity#updateSandboxConfig()` を作って `this.store.currentPlay.content.updateSandboxConfig()` で済ませる方がシンプルではありませんか。

2020-01-21 07:08 UTC, xnv commented on packages/akashic-cli-serve/src/server/domain/SandboxConfigs.ts
> +export function loadSandboxConfigJs(contentId: string, targetDir?: string): SandboxConfig {
これ `contentId` 必要でしょうか。「sandbox.config.js を読み込む」という機能について、対象のファイルパス以外の情報が必要というのは直観的ではありませんし、キャッシュするなら `configPath` をキーにすればいいのでは。

2020-01-22 02:33 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/client/operator/Operator.ts
> +		await this.store.contentStore.updateSandboxConfig(this.store.currentPlay.content.locator);
仰る通りです。`ContentEntity#updateSandboxConfig()` に修正しました。

2020-01-22 02:33 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/server/domain/SandboxConfigs.ts
> +export function loadSandboxConfigJs(contentId: string, targetDir?: string): SandboxConfig {
`contentId` をキーにした理由として、`RunnerStore` に `targetDirs` を渡さないようにするためです。
ご相談させてください。

https://github.com/akashic-games/akashic-cli/blob/af90a87235f2848c59315919758a131f510e330e/packages/akashic-cli-serve/src/server/domain/RunnerStore.ts#L44

2020-01-22 09:46 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/server/domain/SandboxConfigs.ts
> +export function loadSandboxConfigJs(contentId: string, targetDir?: string): SandboxConfig {
ご相談し、`loadSandboxConfigJs()` を分解し getとloadを区別するようにする。

SandboxConfigs で `register()`, `get()`, `watchRequire()` の関数を定義し修正。

2020-01-24 08:34 UTC, xnv requested changes

2020-01-24 08:34 UTC, xnv commented on packages/akashic-cli-serve/src/server/domain/SandboxConfigs.ts
> +			const c = await new Promise((resolve) => {
await 必要でしょうか。resolve は同期的に呼ばれていそうなので、 Promise なしで書けそうです。その場合 `eventListener` の async も不要ではないかと思います。

2020-01-24 08:34 UTC, xnv commented on packages/akashic-cli-serve/src/server/domain/SandboxConfigs.ts
> +function watchRequire(configPath: string, callback: (content: SandboxConfig) => void): Promise<void> {
(`watchRequire()` は `SandboxConfig` に限らない汎用の名前として考えていたのですが、まあ validation しなきゃいけないのは確かですし直近他の用途があるでもないしいいかな……という気分になっています)

2020-01-24 08:34 UTC, xnv commented on packages/akashic-cli-serve/src/server/domain/SandboxConfigs.ts
> +		const watcher = chokidar.watch(configPath, { persistent: true });
誤って同じパスを二度 `register()` したら二重に `watch()` されないでしょうか。 `configs` に既にあったら `watch()` しない、といったロジックがある方がよさそうです。またタイミングの問題を考えると `watchRequire()` も同期メソッドにしてしまった方がいいかもしれません (`watchRequire()` してから戻り値の `Promise` が resolve される前にもう一度同じ引数を `watchRequire()` する状況だと、`configs` にまだ代入されていない)。

2020-01-24 08:34 UTC, xnv commented on packages/akashic-cli-serve/src/server/controller/ContentController.ts
> +	targetDirs.forEach((targetDir, idx) => sandboxConfigs.register(idx.toString(), targetDir));
`Promise` が返ってきているのに誰も resolve を待たないのは奇妙ではありませんか。(……と書きましたが、別で書いているとおり `register()` を同期にする方が良さそうに思えています。その場合ここはこれでよいはず)

2020-01-28 05:54 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/server/domain/SandboxConfigs.ts
> +			const c = await new Promise((resolve) => {
仰る通りです。await/async削除し修正しました。

2020-01-28 05:54 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/server/domain/SandboxConfigs.ts
> +		const watcher = chokidar.watch(configPath, { persistent: true });
`regiseter()` に多重登録チェックと、`watchRequire()` の戻りに `SandboxConfig` が戻るよう修正しました。

2020-01-28 05:54 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/server/controller/ContentController.ts
> +	targetDirs.forEach((targetDir, idx) => sandboxConfigs.register(idx.toString(), targetDir));
この箇所はこのままとし、SandboxConfigsの方を修正しました。

2020-01-29 03:48 UTC, xnv approved these changes

2020-01-30 02:18 UTC, merged