v3系のengineを利用しているコンテンツも動かせるよう対応(akashic-cli-serve, akashic-cli-export-html)
akashic-games/akashic-cli pull request #232
Opened 2020-01-21 12:33 UTC by dera-

**このPRはレビューの用途のみで作成したものですので、レビュー完了後はマージせずにクローズします**

### やったこと
#### akashic-cli-serve
* engine-filesV3系のダウンロードと更新もできるようにした

#### akashic-cli-export-html
* engine-filesV3系のダウンロードと更新もできるようにした
* v3系コンテンツを動かすためのソースをtemplates/template-export-html-v3以下に追加
  * ディレクトリ以下の内容はengineFilesとpackage.json以外templates/template-export-html-v2と同じ

2020-01-21 15:38 UTC, dera- commented
今テストが落ちている状態ですが、こちらはhttps://github.com/akashic-games/headless-driver/pull/108のpublish後にakashic-cli-serveが依存しているheadless-driverを更新すれば直る予定です

2020-01-29 13:35 UTC, xnv requested changes
関連 PR 含めて、動作確認が肝要かと思いますので、何を試して何ができたか一通り書き出しをお願いしたいです (akashic init したゲームを 3 系にして、sandbox で起動できた export html できた serve でも動作した、それぞれ 3 系にしかない機能が正しく動作した、など)

2020-01-29 13:35 UTC, xnv commented on packages/akashic-cli-export-html/templates/template-export-html-v3/js/logger.js
> +	game.logger.logging.add(onLogging);
v3 系は logger はもうないと思いますが、これ動いてますか？

2020-01-30 11:15 UTC, dera- commented on packages/akashic-cli-export-html/templates/template-export-html-v3/js/logger.js
> +	game.logger.logging.add(onLogging);
すみません。ロガーの動作確認はできてませんでしたね。。おそらく動作しないと思いますが、こちら確認します。

2020-02-03 09:26 UTC, dera- commented on packages/akashic-cli-export-html/templates/template-export-html-v3/js/logger.js
> +	game.logger.logging.add(onLogging);
まず動作確認の前にコードの調査をしたところ、この関数自体使われていなかったのでこのファイルは消してしまおうと思います。

2020-02-03 10:51 UTC, dera- commented
akashic-cli-serveとakashic-cli-export-htmlで以下のコンテンツを実行できるかをそれぞれ確認しました。またexport-htmlではbundleとno-bundle両方の検証を行っています。

* engine v3を利用したコンテンツ：https://github.com/dera-/akashic-sample-san
  * v3で新たに追加された`Game#localToGlobal()`を使用しています
* engine v2を利用したコンテンツ：https://github.com/akashic-contents/thiefBuster
* engine v1を利用したコンテンツ：https://github.com/dera-/block-shooter/tree/engine-v1

2020-02-05 12:53 UTC, xnv approved these changes

2020-02-06 02:06 UTC, yu-ogi approved these changes

2020-02-06 12:05 UTC, merged