RPGアツマールのマスターボリュームAPIモック機能とコンテンツの音量調整UIを作成
akashic-games/akashic-cli pull request #234
Opened 2020-01-28 11:33 UTC by dera-

### 概要
以下の機能を追加しました。
* RPGアツマールモックAPIにマスターボリューム調整APIに対応する機能
* コンテンツの音量調整UI
  * このUI自体はtarget-serviceオプションでatsumaruを指定していない時でも利用可能にしています

### やったこと
* コンテンツの音量調整UIコンポーネントを追加
* agv経由でコンテンツの音量取得・設定を可能にした。
  * AkashicGameViewWeb.d.tsにそれ用のメソッドを追加
* RPGAtsumaruApiをクラス化
  * コンテンツ情報等を内部で保持する必要ができたため

### このPRで対応していないこと
* コンテンツの音量調整UIのデザイン周り

2020-01-28 11:48 UTC, dera- commented on packages/akashic-cli-serve/src/client/atsumaru/RPGAtsumaruApi.ts
> +	close(): void {
アツマールAPIインスタンスを破棄する時に呼ぶ想定のメソッドです。ここでtrigger等の破棄を行っていきます

2020-01-28 11:50 UTC, dera- commented on packages/akashic-cli-serve/src/client/atsumaru/RPGAtsumaruApi.ts
> +	private targetContent: ServeGameContent;
今回はコンテンツの音量取得のためだけに内部で持っていますが、他にもコンテンツ情報が必要になってくるタイミングがありそうなのでこのクラス内部で持っていた方がいいのではと思い追加しました

2020-01-28 11:51 UTC, dera- commented on packages/akashic-cli-serve/src/client/atsumaru/RPGAtsumaruApi.ts
> +	volumeTrigger: Trigger<number>;
volume.change.subscribeで指定されたコールバック関数(もしくはObserver)を実行するためのtriggerです

2020-01-28 11:52 UTC, dera- commented on packages/akashic-cli-serve/src/client/atsumaru/RPGAtsumaruApi.ts
>  				return new Subscription();
すみませんが、Rxをよく理解しておらず空のsubscriptionのみを返すようにしているのですが、これだとやはり問題がありますでしょうか？

2020-01-28 11:56 UTC, dera- commented on packages/akashic-cli-serve/src/client/store/Store.ts
> +				(window as any).RPGAtsumaru = this._atsumaruApi;
RPGAtsumaruApiをクラス化してコンテンツ情報を渡すことを必須にしたことでRPGAtsumaruApiが生成される場所がここになり、グローバル変数RPGAtsumaruへの値代入もここで行うようにしたのですが問題がある場合は教えていただきたいです

2020-01-29 06:37 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/client/atsumaru/RPGAtsumaruApi.ts
>  				return new Subscription();
RxJs は全然知らず型定義しか見ていないので、間違ってたらすいません...

ここで return している `subscription` では、`unsubscribe()` した時に何も起きないはずです。
`Subscription` を返す場合、`Observerble#subscribe()` の返り値で良いと思います。

`const o =　Observable.create();` で監視対象を作成、
`return o.subscribe(observer)` 　その監視対象に `observer` (監視して変更通知する)を `subscribe()` (監視者の追加)
のような感じになるかと思いますが、RxJsよくわかっていませんので間違ってたら申し訳ありません...

2020-01-30 03:27 UTC, dera- commented on packages/akashic-cli-serve/src/client/atsumaru/RPGAtsumaruApi.ts
>  				return new Subscription();
ありがとうございます！Rxについての知識がなかったのでこちら勉強になりました。
ただ、別でご相談させていただきましたが、マスターボリュームの情報自体serve側で持っていて特に監視する必要もないものなので、今回はSubscriptionのモックを定義してそれを返すように対応しようかと思います。

2020-01-30 05:15 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/client/view/organism/Devtool.tsx
> +					["Instances", "Events", "EntityTree", "Atsumaru"].map(t => ({
仕様の確認となりますが、アツーマルのタブはオプション指定がない場合でも常時表示されるのでしょうか？

2020-01-30 05:15 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/client/atsumaru/RPGAtsumaruApi.ts
> +    remove(subscription: any): void;
この2行だけ、ソフトタブ(スペース)になっているようです。

2020-01-30 08:02 UTC, dera- commented on packages/akashic-cli-serve/src/client/atsumaru/RPGAtsumaruApi.ts
> +    remove(subscription: any): void;
お、ありがとうございます。IDEの設定ミスってた感じですかね。。こちら修正しておきます。

2020-01-30 08:07 UTC, dera- commented on packages/akashic-cli-serve/src/client/view/organism/Devtool.tsx
> +					["Instances", "Events", "EntityTree", "Atsumaru"].map(t => ({
そうですね。targetServiceでアツマールが指定されてなくてもタブだけ出して中身はdisableにする仕様にするつもりです。disableにしておいた方がtargetServiceで指定すれば使えるということがより分かりやすくなると思いますので(ただ、指定してすれば使えるようになることが今のデザイン的に分かりやすい感じにはなっていませんが。。)

2020-01-30 10:35 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/client/view/organism/Devtool.tsx
> +					["Instances", "Events", "EntityTree", "Atsumaru"].map(t => ({
承知しました。

2020-01-30 10:35 UTC, ShinobuTakahashi approved these changes

2020-01-30 10:38 UTC, ShinobuTakahashi commented
PRのタイトル `コンテンツの音量調整UI` となっていますが、コンテンツの音量は操作していないので、`コンテンツの` を削除しいただければと思います。

2020-01-30 10:44 UTC, ShinobuTakahashi commented
Approveしましたが、PRのタイトルや内容に `コンテンツの音量調整` (取得のみ) はしていないはずなので、タイトルや概要部分を修正していただければと思います。

2020-02-04 08:56 UTC, dera- commented
追加対応としてserveでfaviconを追加する対応を行いました。faviconとして公式ページで使われているものと同じものを使用しています(アイコンサイズだとAkashicという文字が見づらくマークだけの方が見やすいかと思いましたので)

2020-02-05 13:40 UTC, xnv requested changes

2020-02-05 13:40 UTC, xnv commented on packages/akashic-cli-serve/src/client/akashic/ServeGameContent.ts
> +	}
これ不要かと思います。

2020-02-05 13:40 UTC, xnv commented on packages/akashic-cli-serve/src/client/akashic/AkashicGameViewWeb.d.ts
> +		getMasterVolume(): number;
これも。

2020-02-05 13:40 UTC, xnv commented on packages/akashic-cli-serve/src/client/atsumaru/RPGAtsumaruApi.ts
> +			return this.targetContent.agvGameContent.getMasterVolume();
ここ、ゲームコンテンツの master volume を引いていますが、 この UI で指定された値 を返すものかと思います。

2020-02-05 13:40 UTC, xnv commented on packages/akashic-cli-serve/src/client/atsumaru/RPGAtsumaruApi.ts
> +					remove: (_subscription: any) => {}
この辺実装しませんか。 unsubscribe されたら volumeTrigger.remove() するとか。

2020-02-05 13:40 UTC, xnv commented on packages/akashic-cli-serve/src/client/atsumaru/RPGAtsumaruApi.ts
>  			return Promise.resolve();
これ console.log() か  window.alert() ぐらいしてあげてもいいかもしれないですね。

2020-02-05 13:40 UTC, xnv commented on packages/akashic-cli-serve/src/client/store/Store.ts
> +				(window as any).RPGAtsumaru = this._atsumaruApi;
この辺の代入、こんな感じでストア依存切り離して operator とか bootstrap のレイヤーでやりませんか。Store に atsumaru を意識させる必要はなさそうです。

```
interface RPGAtsumaruAPIParameterObject {
  getVolumeCallback: () => number;
}
         

class RPGAtsumaruAPI {
  constuctor(param: AtsumaruAPIParameterObject) {
    this._param = param;
  }
 
  getVolume() {
    return this._param.getVolumeCallback();
  }
} 
```

2020-02-07 08:52 UTC, dera- commented on packages/akashic-cli-serve/src/client/akashic/ServeGameContent.ts
> +	}
あ、すみません。。こちら完全に消すのを忘れていました。。消しておきます

2020-02-07 08:52 UTC, dera- commented on packages/akashic-cli-serve/src/client/akashic/AkashicGameViewWeb.d.ts
> +		getMasterVolume(): number;
了解しました

2020-02-07 09:07 UTC, dera- commented on packages/akashic-cli-serve/src/client/store/Store.ts
> +				(window as any).RPGAtsumaru = this._atsumaruApi;
了解しました。RPGAtsumaruAPIの方をそのように修正して`Operator#bootstrap()`で定義するように修正してみます

2020-02-07 09:08 UTC, dera- commented on packages/akashic-cli-serve/src/client/atsumaru/RPGAtsumaruApi.ts
> +			return this.targetContent.agvGameContent.getMasterVolume();
了解しました、こちらで教えていただいた方法で修正しようと思います。

2020-02-07 09:16 UTC, dera- commented on packages/akashic-cli-serve/src/client/atsumaru/RPGAtsumaruApi.ts
>  			return Promise.resolve();
了解しました。こちら引数の値をconsole.logで出力するようにしてみます

2020-02-07 09:17 UTC, dera- commented on packages/akashic-cli-serve/src/client/atsumaru/RPGAtsumaruApi.ts
> +					remove: (_subscription: any) => {}
unsubscribeのみ実装してみようと思います。他の２つについては今回の用途では不要に見えますのでこのままにしておこうと思っているのですが、どうでしょうか？

2020-02-07 12:24 UTC, xnv approved these changes
コメントつけましたが approved.

2020-02-07 12:24 UTC, xnv commented on packages/akashic-cli-serve/src/client/view/molecule/AtsumaruDevtool.tsx
> +	</div>;
インデント壊れてるの直したいです。

2020-02-10 03:52 UTC, dera- commented on packages/akashic-cli-serve/src/client/view/molecule/AtsumaruDevtool.tsx
> +	</div>;
完全に見落としてました。。ありがとうございます、こちら修正しておきます。

2020-02-10 04:24 UTC, merged