Add devtool for niconico
akashic-games/akashic-cli pull request #245
Opened 2020-02-12 09:20 UTC by ShinobuTakahashi

## 修正内容

**serve に `preferredSessionParameters` のdevツールの作成**
(機能はakashic-sandboxのdevTool-niconicoタブと同じ機能となる。)
- devToolに `Niconico`タブの追加

2020-02-12 09:22 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/client/akashic/AkashicGameViewWeb.d.ts
> +		scene(): ae.SceneLike;
`ac` となっていたので `ae` へ修正。 この修正に伴い、65行目の `children: ELike[];` を追加。

2020-02-12 09:42 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/client/akashic/ServeGameContent.ts
> +		this._store = store;
`game.tick()` を上書きし処理内で `store` を使うために追加。
ここに渡すため `Operator.ts`,  `LocalInstanceEntity.ts` ,  `PlayEntity.ts`にも `store` を追加しました。

2020-02-12 09:48 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/client/view/molecule/AtsumaruDevtool.tsx
> +				props.disabled && <p><b>このタブは現在無効になっています。有効にするためには起動オプションに --target-service atsumaru を指定する必要があります。</b></p>
実際の起動オプションの記述に変更しました。

2020-02-17 04:32 UTC, xnv requested changes
複数のコメントでバラバラに書いてしまったんですが、要点は非常に単純で:

**View は store の状態を表示に反映し、 UI 操作を operator に通知するだけ** にしたいです。可能な限り。

この PR の `NiconicoDevtool` はこの方針から外れてしまっています。「(a) タイマーをしかけて実際に止める」「(b) (UI に紐づいかない) イベント送信を要求する」「(c) totalTimeLimite の実効値を算出する」などの処理はいずれも、「UI を表示し、その操作を通知する」という view の役割を超えています。責務分担の見直しをお願いしたいです。

深く考えていませんが、 (a) は Operator か LocalInstanceOperator,  (b) は Operator のプレイ生成するあたり, (c) は store がやるべきことではないかという直感を持っています。

2020-02-17 04:32 UTC, xnv commented on packages/akashic-cli-serve/src/common/types/GameConfiguration.ts
> +	supportedModes?: Array<"single" | "ranking">;
`"multi"` もありえます。

2020-02-17 04:32 UTC, xnv commented on packages/akashic-cli-serve/src/client/view/molecule/NiconicoDevtool.tsx
> +		props.setStopGame(false);
これはどういう意図の処理でしょうか……？
view のコンポーネントが生成される時 (それは render に紐づくタイミングだと思います)、そのことが外部に何か影響をもたらすべきとはあまり思えません。

2020-02-17 04:32 UTC, xnv commented on packages/akashic-cli-serve/src/client/view/container/DevtoolContainer.tsx
> +				isStopGame: devtoolUiStore.stopGameOnTimeOut,
- `stopGameOnTimeout` が `useStopGameOnTimeout` と対応していない
- `stop〜` といかにも何かを実際に「止める」メソッドっぽい名前なのに boolean のフラグとして利用

さすがにつらいです。別でも書いてますが全体的に名前とプロパティの必要性を整理したいです。

2020-02-17 04:32 UTC, xnv commented on packages/akashic-cli-serve/src/client/view/molecule/NiconicoDevtool.tsx
> +			this.sendNicoEvent(this.totalTime);
この辺の処理、view がやるべきことではないと思います (ましてや mount タイミングに紐づける理由はもっとないでしょう)。イベント送信はプレイを作成した operator の責務ではないでしょうか。というか、view のこの箇所にあるということは、ブラウザウィンドウを複数開いたら全員がこの sendEvent() をしてきてしまいませんか？

2020-02-17 04:32 UTC, xnv commented on packages/akashic-cli-serve/src/client/view/molecule/NiconicoDevtool.tsx
> +				: niconicoConfig.preferredSessionParameters.totalTimeLimit;
game.json の内容 (store の値) から一義的に定まる値の算出ロジックは store に持たせるべきではありませんか。この view が gameJson の中身を全部見てるのも、やりたいことに対して「渡しすぎ」に思います。

2020-02-17 04:32 UTC, xnv commented on packages/akashic-cli-serve/src/client/view/stories/Devtool.stories.tsx
> +	.add("with-behavior", () => <TestWithBehaviour />)
このリポジトリ、この with-behavior は常に最後に置いてる (もっとも複雑で、恐らく storybook 本来の想定とは少しずれた) テストなので、何か加えるならこれの前にしませんか。

2020-02-17 04:32 UTC, xnv commented on packages/akashic-cli-serve/src/client/view/stories/Devtool.stories.tsx
> +					createFilledRectDumpItem(104),
entityTreeDevtool のテストからのコピかと思いますが、これはスクロールバーの表示がどうなるか確認するためにこんなに並べたものでしょう。この箇所のテスト上は全く表示されないので、こんなに要らない (空配列でよいぐらい) と思います。

2020-02-17 04:32 UTC, xnv commented on packages/akashic-cli-serve/src/client/view/molecule/NiconicoDevtool.tsx
> +		if (props.disabled) return;
この条件分岐はなくしたいです。この下の処理は恐らく、そもそも view が持つべきものではないからです。「view のコンポーネントの生成途中で」何かを中断せねばならない時点で、責務分担を疑いたいです。

2020-02-17 04:32 UTC, xnv commented on packages/akashic-cli-serve/src/client/view/molecule/NiconicoDevtool.tsx
> +	stopGame: () => void;
全体的に整理したいです。責務過剰な現状を改めて、store や operator に移すべき処理を移せば、だいぶ減るのではないかと思います。特に stop と名のつくものが多すぎる上に紛らわしいのが引っかかります (stopGame と setStopGame と isStopGame と useStopGameOnTimeout の関係を一目で読み取れる人間は多分いないでしょう)。

2020-02-17 05:04 UTC, dera- commented on packages/akashic-cli-serve/src/client/view/molecule/AtsumaruDevtool.tsx
> +				props.disabled && <p><b>このタブは現在無効になっています。有効にするためには起動オプションに --target-service atsumaru を指定する必要があります。</b></p>
ありがとうございます。こちらの方がユーザーから見て何をすればいいのか分かりやすいですね。

2020-02-17 05:45 UTC, dera- commented on packages/akashic-cli-serve/src/client/akashic/ServeGameContent.ts
> +		this._store = store;
すみませんが、akashicディレクトリ以下では極力Akashic Engineの世界に閉じた処理を行うようにしたいので、storeを参照する処理はあまりやりたくないです(GameViewManagerもですかね)。
ここで渡しているのはdevtoolUiStoreの持つ状態を変更するためだと思われるので、もしやるのであればそれらの処理を関数にしてここではその関数を受け取ってそれを実行するだけにしたいです。

2020-02-17 05:57 UTC, dera- commented on packages/akashic-cli-serve/src/client/operator/PlayOperator.ts
> +		event.forEach((pev: playlog.Event) => amflow.enqueueEvent(pev));
こういったロジックもOperator側ではなくStore側で持ちたいと考えていますので、PlayEntity辺りに定義していただきたいです。Operatorはどちらかというとあまりロジックを持たずViewとStoreの間の橋渡し的なものとして使っていきたいですので(現状は若干Operator側でロジックを持ってしまっていますが。。)

2020-02-28 03:45 UTC, ShinobuTakahashi commented
修正範囲が大きくなったためこのPRはクローズし、別PRにて、serverとviewにわけてPRだします

2020-02-28 03:45 UTC, closed without merging