atsumaruオプションでexport html実行時に、対象のruntime-versionがpreleaseバージョンの時警告を出す対応
akashic-games/akashic-cli pull request #257
Opened 2020-02-26 06:35 UTC by dera-

### 概要
* akashic-runtimeがprereleaseバージョンだとニコ生では動かないものになっている可能性があるので警告を出す対応をしました。
  * ニコ生上でなければ動きはするので、エラーにせず警告のみにとどめてます
  * まさしく今のv3系がそのようになっています。

### やったこと
* akashic-runtimeのバージョンが`*.*.*-*`といった形式になっていれば警告を出すようにしました
* ついでにatsumaruオプション実行時のv3系のテストも有効にしました

2020-02-26 08:04 UTC, xnv requested changes

2020-02-26 08:04 UTC, xnv commented on packages/akashic-cli-export-html/src/app/exportAtsumaru.ts
> +				if (gameJson.environment["akashic-runtime"]["version"].match(/\d+\.\d+\.\d+\-\w+/)) {
- マッチするかどうか確認するだけなら `.test()` の方が無駄がないです。
- `-` の前にバックスラッシュは不要では……？

2020-02-26 08:04 UTC, xnv commented on packages/akashic-cli-export-html/src/app/exportAtsumaru.ts
> +						"operation is not guaranteed because latest version of akashic-runtime is prerelease."
保証/guarantee は元々できませんしライセンス上もしてない (IS PROVIDED "AS IS") ので、文言を調整したいです。

``` `UNSTABLE: Akashic Engine v${/* sandbox-runtime 相当の値 */} (${/* akashic-runtime の値 */}) is in beta. The game exported MAY NOT WORK PROPERLY.`  ``` とかですかね……。

(まるっとなくなっていますが一応: "the" latest version で "a" prerelease ではないかと思います)

2020-02-26 12:51 UTC, dera- commented on packages/akashic-cli-export-html/src/app/exportAtsumaru.ts
> +				if (gameJson.environment["akashic-runtime"]["version"].match(/\d+\.\d+\.\d+\-\w+/)) {
了解しました、test関数に変更します。
すみません`-`のエスケープは必要なものかと勘違いしてました。。こちらも修正します。

2020-02-26 12:55 UTC, dera- commented on packages/akashic-cli-export-html/src/app/exportAtsumaru.ts
> +						"operation is not guaranteed because latest version of akashic-runtime is prerelease."
ありがとうございます、文言はそのように修正します。

そもそも保証するとはどこにも書かれてないので使うべきではなかったですね。。。あと、冠詞についても今後気を付けます。

2020-02-27 05:54 UTC, xnv requested changes

2020-02-27 05:54 UTC, xnv commented on packages/akashic-cli-export-html/src/app/exportAtsumaru.ts
> +						`UNSTABLE: Akashic Engine v${runtimeVersion} is in beta. The game exported may not work properly.`
`runtimeVersion` は akashic-engine のバージョンではないのでこの表記は避けたいです。Akashic Engine の厳密なバージョンを書いてもしょうがないからこそ、 `Akashic Engine v3 (3.0.0-beta.0)` みたいな形を揚げました (が、これすらも嘘っぽいですね。 `Akashic Engine v3 (akashic-runtime@3.0.0-beta.0)` の方が良さそう)。

2020-02-27 05:54 UTC, xnv commented on packages/akashic-cli-export-html/src/app/exportAtsumaru.ts
> +						`UNSTABLE: Akashic Engine v${runtimeVersion} is in beta. The game exported may not work properly.`
こちらは別にこだわりませんが、文中に大文字を混ぜるのは英文で強調する時の表現です。例えば [Apache 2.0 ライセンス](https://opensource.org/licenses/Apache-2.0) の「保証しない」という部分は次のように書かれています。

> Unless required by applicable law or agreed to in writing, Licensor provides the Work (...) on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied, including, without limitation, any warranties or conditions of TITLE, NON-INFRINGEMENT, MERCHANTABILITY, or FITNESS FOR A PARTICULAR PURPOSE.

2020-02-27 07:27 UTC, xnv approved these changes

2020-02-28 07:29 UTC, kamakiri01 approved these changes

2020-02-28 08:40 UTC, merged