Add devTool niconico
akashic-games/akashic-cli pull request #258
Opened 2020-02-28 04:01 UTC by ShinobuTakahashi

## 内容
serve に preferredSessionParameters 関連のdevツールを追加するため、APIの修正を行いました。

view側はこのブランチから切り出し修正を行いPRを別とします

2020-02-28 06:50 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/client/store/ContentStore.ts
> +		const gameJson = this._gameJsonTable[loc.contentId];
`ContentEntity` 生成にgameJsonが必要になったため、`_gameJsonTable` に保持しています。

2020-03-02 06:37 UTC, xnv requested changes

2020-03-02 06:37 UTC, xnv commented on packages/akashic-cli-serve/src/client/store/ContentEntity.ts
> +	gameJson: GameConfiguration;
「現状では表示に反映しないので observable はつけないでおく」みたいなコメントつけておきたいです。(本質的につかないだろうものと区別しておきたい)

2020-03-02 06:37 UTC, xnv commented on packages/akashic-cli-serve/src/client/store/ContentStore.ts
> +		const gameJson = this._gameJsonTable[loc.contentId];
ここでもし `gameJson` が見つかるなら、上の `this.contents.get()` が成功するはずなので、このパスには来ないのではないでしょうか？　このためだけに足したものなら、おそらく `this._gameJsonTable` は不要 (というか役立つシーンがない) ような気がします。

拡張性を見越した処理なのでここに来ることは現実にはあまりないような気がしますが、「 `gameJson` はないかもしれない」という前提で実装していただきたいです。(別案としては、このパスでは自分で解決する  (`url` から fetch して自力で parse()) ということもできますが、一旦そこまでしなくてもという印象です)

2020-03-02 06:37 UTC, xnv commented on packages/akashic-cli-serve/src/server/controller/ScriptAssetController.ts
> +	gameConfigs.register(index.toString(), baseDir);
これに巻き込まれて引数が増えるの、前もありましたがやはりどうにも違和感があります。いったんいいんですが「require() のキャッシュするモジュールのインターフェース (index でアクセスする点) と register() 箇所を見直す」って TODO コメントだけ残しておいていただきたいです。 (ちゃんと考えれば bootstrap する時点でこなせる気がします)

2020-03-02 09:29 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/client/store/ContentStore.ts
> +		const gameJson = this._gameJsonTable[loc.contentId];
> 拡張性を見越した処理
なるほど、理解しました。このパスまで到達するケースが不明でした。
仰る通り、`_gameJsonTable`が役にたつケースがないので削除しました。

2020-03-02 09:29 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/client/store/ContentEntity.ts
> +	gameJson: GameConfiguration;
コメント追加しました。

2020-03-02 09:29 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/server/controller/ScriptAssetController.ts
> +	gameConfigs.register(index.toString(), baseDir);
TODOコメント追加しました。

2020-03-02 11:39 UTC, xnv approved these changes

2020-03-03 11:03 UTC, dera- commented on packages/akashic-cli-serve/src/client/store/ContentStore.ts
> +import { GameConfiguration } from "../../common/types/GameConfiguration";
このオブジェクトはここで利用されていますでしょうか？もし利用されていなければ削除していただきたいです。

2020-03-03 11:06 UTC, dera- approved these changes
コメントしましたが、approveします

2020-03-04 01:31 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/client/store/ContentStore.ts
> +import { GameConfiguration } from "../../common/types/GameConfiguration";
ありがとうございます。未使用でしたので削除しました。

2020-03-16 02:54 UTC, merged