Add niconico to devTool
akashic-games/akashic-cli pull request #260
Opened 2020-03-04 02:50 UTC by ShinobuTakahashi

## 修正内容

**serve の devToolにniconicoタブを新規追加するため、viewを追加**
(機能はakashic-sandboxのdevTool-niconicoタブと同じ機能となります)

**その他修正**
`AkashicGameViewWeb.d.ts`の  `GameLike#scene()`の型が間違っていたので修正

2020-03-04 02:53 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/client/akashic/AkashicGameViewWeb.d.ts
> +		scene(): ae.SceneLike;
`ac` となっていたので `ae` へ修正。 この修正に伴い、65行目の `children: ELike[];` を追加。

2020-03-04 02:56 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/client/akashic/GameViewManager.ts
> +	startGameContent(content: ServeGameContent, tickHandler: (game: agv.GameLike) => void): Promise<void> {
akashicディレクトリ配下ではなるべくAkashic Engineの世界に閉じた処理にするため、関数を渡すように修正

2020-03-04 03:16 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/client/view/molecule/AtsumaruDevtool.tsx
> +				props.disabled && <p><b>このタブは現在無効になっています。有効にするためには起動オプションに --target-service atsumaru を指定する必要があります。</b></p>
実際の起動オプションの記述に変更しました

2020-03-04 07:02 UTC, dera- approved these changes

2020-03-05 09:12 UTC, xnv requested changes

2020-03-05 09:12 UTC, xnv commented on packages/akashic-cli-serve/src/client/akashic/GameViewManager.ts
> +	startGameContent(content: ServeGameContent, tickHandler: (game: agv.GameLike) => void): Promise<void> {
発想同意なんですが、どうせなのでもう一段汎用性を出して `ServeGameContent#onTick: Trigger<void>` にしませんか。そうすると生成時点 (ここ) で渡す必要もなくなりますし、ただ一つである必要もなくなると思います。

2020-03-05 09:12 UTC, xnv commented on packages/akashic-cli-serve/src/client/operator/Operator.ts
> +	}
この辺、 `Operator` 直下に持つよりも `DevtoolOperator` に持たせるほうが自然ではありませんか。

2020-03-05 09:12 UTC, xnv commented on packages/akashic-cli-serve/src/client/operator/Operator.ts
> +		const supportMode = this.store.devtoolUiStore.supportMode;
全体的に `supportMode` という名前は変えたいです。 `emulatingShinichibaMode` とかですかねえ。

たぶん supportedModes/サポートされているモード群 に由来して名付けられていると思いますが、この名前は game.json で名乗る「"このコンテンツによって" サポートされているモード」という意味です。コンテンツを "動かす側" である serve で、同じ support という語彙を使うとよくわからなくなります。

serve が mode を決めているわけですし、それは新市場の環境をエミュレートする (というほど完全に模擬してはいませんが) ためなわけですから、ここで扱う変数名としては `emulatingShinichibaMode` とかになるのではないかと思います。(`emulatingMode` でもいいんですが mode は非常に一般的な名詞なので、もう少し限定しておきたい)

2020-03-05 09:12 UTC, xnv commented on packages/akashic-cli-serve/src/client/operator/Operator.ts
> +		}, 1000 / fps);
setInterval() 必要でしょうか。 `ServeGameContent` から tick の度に通知を受け取れば、そこでチェックすればいいと思います。そもそもこの形だと、ここでタイマーをかけた後に replay に入られると変なところでゲームを止めてしまうのではありませんか。

2020-03-05 09:12 UTC, xnv commented on packages/akashic-cli-serve/src/client/store/DevtoolUiStore.ts
> +	@observable useStopGameOnTimeout: boolean;
英文として解釈しにくい (stop/停止 を use/使う とは……) のが気になります。 `showsEventList: boolean` に倣えば  `stopsGameOnTimeout` になるかと思います。

2020-03-05 09:12 UTC, xnv commented on packages/akashic-cli-serve/src/client/store/DevtoolUiStore.ts
> +	createTickHandler(targetService: ServiceType): (game: agv.GameLike) => void {
handler を作るのは store の責務ではないような……。しかも能動的に他を監視して自分の値を更新しているとなると、これは `DevtoolOperator` に置きたい気がします。

2020-03-05 09:12 UTC, xnv commented on packages/akashic-cli-serve/src/client/store/DevtoolUiStore.ts
> +			if (targetService !== ServiceType.Atsumaru && game.vars && game.vars.gameState) {
別の箇所のコメントにつながりますが、 `Trigger` にしておけば `targetSerivce` が合わなければそもそも handle しない、ということができて嬉しいですね。

2020-03-05 09:12 UTC, xnv commented on packages/akashic-cli-serve/src/client/store/DevtoolUiStore.ts
> +	initializeReamingTime(): void {
s/reaming/remaining/

2020-03-05 09:12 UTC, xnv commented on packages/akashic-cli-serve/src/client/store/DevtoolUiStore.ts
> +		storage.put({ remainingTime: this.remainingTime });
`storage` に入れる値ではないのでは。 `storage` はコンフィグ情報を保持するのが基本で、再計算できる・高頻度に書き換えるものを入れるものではない認識です。

2020-03-05 09:12 UTC, xnv commented on packages/akashic-cli-serve/src/client/store/DevtoolUiStore.ts
> +				: niconicoConfig.preferredSessionParameters.totalTimeLimit;
この辺のロジック、  `ContentEntity` に持たせる方が責務がすっきりすると思います (game.json から一意に決まる値なので)。このメソッドは単に `setTotalTimeLimit()` でいいmのではないでしょうか。

2020-03-10 08:26 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/client/operator/Operator.ts
> +	}
`DevtoolOperator` へ移動しました。

2020-03-10 08:27 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/client/operator/Operator.ts
> +		const supportMode = this.store.devtoolUiStore.supportMode;
仰る通り`mode`では意味が広すぎました。 `emulatingShinichibaMode` へ修正しました。

2020-03-10 08:28 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/client/operator/Operator.ts
> +		}, 1000 / fps);
`setInterval()` をやめ、tick内でゲーム停止処理を行うよう修正しました。

2020-03-10 08:28 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/client/store/DevtoolUiStore.ts
> +	@observable useStopGameOnTimeout: boolean;
`stopsGameOnTimeout` へ修正しました。

2020-03-10 08:28 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/client/store/DevtoolUiStore.ts
> +	createTickHandler(targetService: ServiceType): (game: agv.GameLike) => void {
`DevtoolOperator` へ移動しました。

2020-03-10 08:28 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/client/store/DevtoolUiStore.ts
> +			if (targetService !== ServiceType.Atsumaru && game.vars && game.vars.gameState) {
`Trigger` に修正し、`TargetService` の判定を外へ出し修正しました。

2020-03-10 08:28 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/client/store/DevtoolUiStore.ts
> +	initializeReamingTime(): void {
`remaining` へ修正しました。

2020-03-10 08:28 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/client/store/DevtoolUiStore.ts
> +		storage.put({ remainingTime: this.remainingTime });
削除し修正しました。

2020-03-10 08:29 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/client/store/DevtoolUiStore.ts
> +				: niconicoConfig.preferredSessionParameters.totalTimeLimit;
gameJsonから設定する値は `ContentEntity`に移し、メソッド名を `setTotalTimeLimit()` へ修正しました

2020-03-10 08:30 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/client/akashic/GameViewManager.ts
> +	startGameContent(content: ServeGameContent, tickHandler: (game: agv.GameLike) => void): Promise<void> {
関数を渡していた部分を削除し、Triggerで処理するよう修正しました。

2020-03-11 10:45 UTC, xnv requested changes

2020-03-11 10:45 UTC, xnv commented on packages/akashic-cli-serve/src/client/operator/DevtoolOperator.ts
> +		const currentRemainingTime = remaingTime - dur ;
残り時間/remainingTime から、現在のプレイ/currentPlay の  経過時間/duration を引くと「現在の残り時間」が求まる、というの、計算式としてあってますか……？　 直前の残り時間から「直前のフレームからの経過時間」を引くとか、 「totalTimeLimit」から現在のプレイの経過時間を引くならわかりますが。

2020-03-11 10:45 UTC, xnv commented on packages/akashic-cli-serve/src/client/operator/DevtoolOperator.ts
> +	stopGameOverTime  = (remaingTime: number ): void => {
- remaing -> remaining
- `number )` に余計な空白がありそうです、 lint 通っているでしょうか。
- `private` でよいのでは。 また `=` も使わず普通のメソッドとして書けばよさそうに見えます。(`=` のこの代入っぽい記法は `this` を bind するためのものです。普通に `this.〜` で呼び出すなら不要です)
- stop game over time/ゲームオーバー時間を止める、というのは処理の内容にそぐわないような……。 `pauseGameIfNeeded` とかでは (あるいは remaining time を更新している方に注目して `updateRemainingTime()` とか)。

2020-03-11 10:45 UTC, xnv commented on packages/akashic-cli-serve/src/client/store/ContentEntity.ts
> +	setTotalTimeLimit(): void {
set と呼ぶなら引数がほしいです。 `calculatePreferredTotalTimeLimit(): number` にして代入は呼び出し元でやりませんか。

2020-03-11 10:45 UTC, xnv commented on packages/akashic-cli-serve/src/client/store/DevtoolUiStore.ts
> +	@observable totalTimeLimit: string;
number にしませんか。同じ名前で string と number が混在するのはかなりつらい気がします。 input 要素から入ってくる関係で string にされているのではないかと予想しますが、それは view に閉じた話であるべきだと思います (＝ view が number に変換するべきに思えます)。

2020-03-11 10:45 UTC, xnv commented on packages/akashic-cli-serve/src/client/store/DevtoolUiStore.ts
> +	@observable remainingTime: number;
別コメントでも書きましたが、 totalTimeLimit と currentPlay.duration があればこの値は算出できるのではないでしょうか。(ここに値として持たず view の中で計算して求める方がいろいろシンプルだったりしませんか)

2020-03-11 10:45 UTC, xnv commented on packages/akashic-cli-serve/src/client/store/DevtoolUiStore.ts
> +		this.totalTimeLimit = storage.data.totalTimeLimit ;
セミコロン前に不要な空白があります。

2020-03-11 10:45 UTC, xnv commented on packages/akashic-cli-serve/src/client/store/ContentEntity.ts
> +	readonly defaultTotalTimeLimit = 85;
利用箇所がなさそうに見えます。

2020-03-11 10:45 UTC, xnv commented on packages/akashic-cli-serve/src/client/store/ContentEntity.ts
> +	setTotalTimeLimit(): void {
と書きましたが、 `preferredSessoinParameters` にして `calculatePreferredSessionParameters()` にしたい気もしますね (今後何か増える度に `ContentEntity` 直下の値が増えてくのもアレですし)

2020-03-11 10:45 UTC, xnv commented on packages/akashic-cli-serve/src/client/store/DevtoolUiStore.ts
> +		storage.put({ totalTimeLimit: this.totalTimeLimit });
totalTimeLimit をここで保存するのは何か奇妙なような……？　まず `this.totalTimeLimit` を書き換えていないパスで保存するのは不要でしょう。あと、input 要素で変更された時ちゃんと保存されるでしょうか。(そういう動作ではない……？)

2020-03-11 10:45 UTC, xnv commented on packages/akashic-cli-serve/src/client/operator/DevtoolOperator.ts
> +	addTickHandler = (): void => {
何回も呼べそうな名前なのがひっかかります。二度呼んでも大丈夫なようにハンドラの重複チェックしつつ  `setupNiconicoDevtoolValueWatcher()` とかそんな風に呼ぶのが実態を反映するのではないでしょうか。(pause までやるのがちょっと微妙ですが……)

2020-03-12 10:35 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/client/operator/DevtoolOperator.ts
> +		const currentRemainingTime = remaingTime - dur ;
`remainingTime` を totalTimeLimitとして使用していました。
わかりづらいので、`remainingTIme` -> `totalTimeLimit`, `totalTimeLimit` -> `totalTimeLimitInputValue` として修正しました。
残り時間の計算式としては、`totalTimeLimit` から現在のプレイ経過時間を引く計算をしています。

2020-03-12 10:36 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/client/operator/DevtoolOperator.ts
> +	stopGameOverTime  = (remaingTime: number ): void => {
誤字,余計な空白修正しました。
関数を`private updateRemainingTime()`へ修正しました。

2020-03-12 10:36 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/client/store/ContentEntity.ts
> +	setTotalTimeLimit(): void {
`calculatePreferredSessionParameters()` に変更しました。
`ContentEntity` では`preferredSessoinParameters` を返すようにし、DevToolUiStoreで `preferredTotalTimeLimit` を持つように修正しました。

2020-03-12 10:36 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/client/store/DevtoolUiStore.ts
> +	@observable totalTimeLimit: string;
型をnumberに view側で変換するように修正しました。

2020-03-12 10:36 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/client/store/DevtoolUiStore.ts
> +	@observable remainingTime: number;
`remainingTime`を削除し、 viewで計算するよう修正しました。

2020-03-12 10:36 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/client/store/DevtoolUiStore.ts
> +		this.totalTimeLimit = storage.data.totalTimeLimit ;
空白削除しました。

2020-03-12 10:37 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/client/store/ContentEntity.ts
> +	readonly defaultTotalTimeLimit = 85;
すいません、漏れていました。削除しました。

2020-03-12 10:37 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/client/store/DevtoolUiStore.ts
> +		storage.put({ totalTimeLimit: this.totalTimeLimit });
仰る通り、ここでの保存処理は不要でした。 inputの変更処理で保存しています。

2020-03-12 10:37 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/client/operator/DevtoolOperator.ts
> +	addTickHandler = (): void => {
重複チェックを追加し、`setupNiconicoDevtoolValueWatcher()` へ修正しました。

2020-03-13 01:56 UTC, xnv requested changes

2020-03-13 01:56 UTC, xnv commented on packages/akashic-cli-serve/src/client/store/ContentEntity.ts
> +		this.preferredSessionParameters.totalTimeLimit =
`niconicoConfig.preferredSessionParameters` が定義されていない場合に例外が飛びませんか。

2020-03-13 01:56 UTC, xnv commented on packages/akashic-cli-serve/src/client/view/molecule/NiconicoDevtool.tsx
> +		// if (isNaN(value)) value = DevtoolUiStore.DEFAULT_TOTAL_TIME_LIMIT;
作業中のコメントが残っているようです。意図したものなら残す背景がコメントとして欲しいです。

2020-03-13 03:51 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/client/store/ContentEntity.ts
> +		this.preferredSessionParameters.totalTimeLimit =
ありがとうございます。考慮漏れていました。
修正しました。

2020-03-13 03:51 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/client/view/molecule/NiconicoDevtool.tsx
> +		// if (isNaN(value)) value = DevtoolUiStore.DEFAULT_TOTAL_TIME_LIMIT;
すいません、削除しました。

2020-03-13 06:30 UTC, xnv approved these changes

2020-03-16 01:50 UTC, merged