fix akashicConfig.json to akashic.config.js
akashic-games/akashic-cli pull request #262
Opened 2020-03-09 10:54 UTC by kamakiri01

## このpull requestが解決する内容

### 概要
https://github.com/akashic-games/akashic-cli/pull/218 で実装した `akashicConfig.json` を `akashic.config.js` にリネームします。

## 破壊的な変更を含んでいるか?

- あり

****

2020-03-09 11:07 UTC, xnv requested changes

2020-03-09 11:07 UTC, xnv commented on packages/akashic-cli-commons/src/CliConfig/CliConfigurationFile.ts
> +			if (error) {
例外が飛ばなかった時、誰も callback を呼ばなくなっていませんか……。動作確認したいです。(`catch (error)` の中で `if (error)` する (nullish が throw されてくるのを考慮する) のも、まあまずなくていいんじゃないかと思います)

2020-03-09 11:10 UTC, xnv commented on packages/akashic-cli-commons/src/CliConfig/CliConfigurationFile.ts
> +			if (error) {
(実は非同期である必要もなくなってるんですが、そこは現状のままでもいいかなと思っています)

2020-03-10 02:54 UTC, kamakiri01 commented on packages/akashic-cli-commons/src/CliConfig/CliConfigurationFile.ts
> +			if (error) {
正常系でcallback呼んでいませんね直します…（nullishも）

余談：
近いことをしているsandbox.config.jsではcatchでthrowしていなかったりするんですが、実装的にはどちらが妥当でしょうか。
https://github.com/akashic-games/akashic-sandbox/blob/958e7a0b807a5f272010703505b34617e765e2d9/src/server/controller/sandboxConfig.ts#L21

2020-03-11 04:20 UTC, xnv requested changes

2020-03-11 04:20 UTC, xnv commented on packages/akashic-cli-commons/src/CliConfig/CliConfigurationFile.ts
> +			callback(cliConfig);
非同期っぽい I/F を同期で呼ぶのは避けたいです。(呼び出し元が想定しがちな処理順が狂うためです)　`callback` は `setImmediate()` の中で呼びませんか。

2020-03-11 04:34 UTC, xnv commented on packages/akashic-cli-commons/src/CliConfig/CliConfigurationFile.ts
> +			if (error) {
続行を断念すべきかは状況次第でしょうから、一概にどちらが正しいとも言えないかと思います。sandbox.config.js が読めない時に無視して続行しても実害は薄いような気はします (ゲームがうまく動かないかもしれませんが、開発中のゲームがうまく動かないのは普通の状況でしょう)(もちろん断念してダメなわけでもない)。一方で、 akashic.config.js は……読めなかった時に続行すると、例えば scan asset で game.json に書き込まれる内容が変わってしまい、復元するのが手間そうですから、続行断念は妥当に思えます。

というかこれ、よく考えると callback の第一引数が `Error | null` じゃない (エラーを返す口がない) のは問題ですね……？(元の実装から良くない)　callback のある (非同期処理する) メソッドは非同期の中では `throw` しちゃダメですよね。(例外が虚空に消える)　今たまたま中身は同期なので問題になりませんが……。

2020-03-11 06:08 UTC, kamakiri01 commented on packages/akashic-cli-commons/src/CliConfig/CliConfigurationFile.ts
> +			if (error) {
うっ確かに > callbackの第一引数
fs.exists() と同じI/F…

2020-03-11 06:11 UTC, kamakiri01 commented on packages/akashic-cli-commons/src/CliConfig/CliConfigurationFile.ts
> +			callback(cliConfig);
直します。

2020-03-13 05:36 UTC, xnv requested changes

2020-03-13 05:36 UTC, xnv commented on packages/akashic-cli-commons/src/CliConfig/CliConfigurationFile.ts
> +				callback(error, undefined);
ここだけ同期になっています。

2020-03-13 05:36 UTC, xnv commented on packages/akashic-cli-export-zip/src/cli.ts
> +		const conf = error ? {} : configuration.commandOptions.export ? (configuration.commandOptions.export.zip || {}) : {};
だんだん話が広がってますが、エラーを握り潰すのはやめませんか……。

というのも、よく考えると akashic.config.js の評価中にエラーになってもここに来そうだからです。その場合にエラーを握り潰されると、なんで無視されるのか把握するのは強烈に難しいと思います。「akashic.config.js にうっかり全角空白を入れた」とか。

またエラーを表示したいだけでなく、続行断念でいいと思います。 (どこか別のところでも書きましたが、 akashic.config.js が読めない ＝ game.json に書かれる内容が意図しないものになる、であり、かつその時 game.json を戻すのも難しいでしょう)

2020-03-13 06:03 UTC, kamakiri01 commented on packages/akashic-cli-export-zip/src/cli.ts
> +		const conf = error ? {} : configuration.commandOptions.export ? (configuration.commandOptions.export.zip || {}) : {};
> またエラーを表示したいだけでなく、続行断念でいいと思います

throwして停止させるようにします。

2020-03-16 11:18 UTC, kamakiri01 commented on packages/akashic-cli-commons/src/CliConfig/CliConfigurationFile.ts
> +				callback(error, undefined);
直します。

2020-03-30 04:01 UTC, xnv commented on packages/akashic-cli-scan/src/cli.ts
> +			if (error) throw error;
callback 内で  throw するのやめませんか……。現状はたまたま同期的に呼び出されるのでこれでも動きそうですが、非同期で呼び出されたら例外が虚空に消えるように思います。(この箇所なら終了にはなるかもしれませんが、少なくとも無言終了になると思います)

console.error() して process.exit(1) で明示的に終了したいです。

2020-03-30 04:01 UTC, xnv approved these changes
コメントつけましたが  approved.

2020-03-30 10:39 UTC, kamakiri01 commented on packages/akashic-cli-scan/src/cli.ts
> +			if (error) throw error;
明示的に終了させるようにします。

2020-03-31 12:40 UTC, merged