Add moduleMainScripts to template game.json
akashic-games/akashic-cli pull request #269
Opened 2020-03-16 06:01 UTC by ShinobuTakahashi

## 修正内容

akashic-init/templateのgame.jsonに ”moduleMainScripts” を追加

2020-03-16 07:27 UTC, xnv requested changes

2020-03-16 07:27 UTC, xnv commented on packages/akashic-cli-init/templates-src-v3/game-default/game.json
> +	"moduleMainScripts": [],
https://akashic-games.github.io/guide/game-json.html に書かれておらず恐縮なのですが、 moduleMainScripts って配列じゃなくてオブジェクトではないかと思います。動作確認をお願いしたいです。

具体的には
 - このブランチをビルドしたものを使って `akashic init` する
 - 確認(1): 生成された game.json に moduleMainScripts が反映されていること
 - そのゲームで akashic install @akashic-extension/akashic-timeline を実行する
 - 確認(2): game.json の moduleMainScripts に akashic-timeline に対応する値が追加されていること
 - 確認(3): ↑の akashic install 実行時 `Newly added the moduleMainScripts property to game.json.` で始まる [警告](https://github.com/akashic-games/akashic-cli-install/blob/master/src/Configuration.ts#L39-L41) が「出ない」こと
    - これが鬱陶しいので出ないようにしたいというのが目的です

2020-03-16 10:08 UTC, ShinobuTakahashi commented on packages/akashic-cli-init/templates-src-v3/game-default/game.json
> +	"moduleMainScripts": [],
仰る通り、配列ではなくオブジェクトでした。(thiefBusterで確認しました)
また修正したブランチを使い、上記手順でgame.jsonに`moduleMainScripts`が追加されていることとコンテンツの動作確認を行いました。

2020-03-17 02:38 UTC, xnv approved these changes

2020-03-17 03:35 UTC, merged