Fix installation of tgz file with akshic-cli-install
akashic-games/akashic-cli pull request #283
Opened 2020-04-09 07:39 UTC by ShinobuTakahashi

## 内容

akashic-cli-install で `npm pack`で生成されたtgzファイルをインストールするとエラーとなる問題の解決。
(e.g. `akashic install ./anyModule.tgz`)

原因が、指定されたtgzファイルのパスが browserifyへ渡り、browserifyでエラーとなっている。

対応として、`npm i` の前と後の `package.json` の dependencies の差分を取得し、その差分のモジュール名を後続の処理に渡すことにより解決する。

2020-04-09 11:40 UTC, dera- approved these changes

2020-04-10 03:43 UTC, xnv requested changes

2020-04-10 03:43 UTC, xnv commented on packages/akashic-cli-install/src/install.ts
> +	const beforePackageJson = JSON.parse(fs.readFileSync(path.join(param.cwd, "package.json"), "utf-8"));
before and after のイメージで  "before の package.json" という意図だろうと思いますが、こう書くと "package.json 以前" みたいになっていませんか。 packageJsonBeforeInstall, packageJsonAfterInstall というのが説明的だと思います。でもまあ長いので一長一短ですかね……。

2020-04-10 03:43 UTC, xnv commented on packages/akashic-cli-install/src/install.ts
> +	const beforeKeys = beforePackageJson.dependencies ? Object.keys(beforePackageJson.dependencies) : [];
- `keys` はこの値を「求めた方法」にすぎないと思います。一般に、変数名はこの値の「意味・内容」で命名する方が可読性が高いと思います。これだと `depsBeforeInstall`とかですよね。
- 使い方を考えると `Object.keys` で配列にするのはむしろ非効率では。key があるかどうか確かめたいだけなので。配列にすると `indexOf()` (O(N))が必要ですが、 object のままなら `hasOwnProperty()` (O(1)) で済みますよね。いえまあ要素数がしれてるので理論どおりの性能差とは思いませんが、しかしわざわざ新たに配列を生成するコストを払うのも本末転倒っぽいと思います。

2020-04-10 03:43 UTC, xnv commented on packages/akashic-cli-install/src/install.ts
> +					if (diffKeys.length > 0) param.moduleNames = diffKeys;
引数 `param` を破壊するのは抵抗があります。事前に `let installedModuleNames: string[] = []` とか変数つくっておいてそれに代入して取り回しませんか。

2020-04-10 03:43 UTC, xnv commented on packages/akashic-cli-install/src/install.ts
> +					// そのため、`npm i` 前後の package.json のモジュール名の差分を取得し、その差分のモジュール名を渡すようにする。
> tgzファイルのパスが指定された場合、akashic-cli-ommons の NodeModules#listScriptFiles() に tgzのパスが browserify へ渡りエラーとなる

これはこのコードが入る「前」の挙動を説明しているので、変更「後」のコードと一緒にコメントを見てもどこを指しているのか掴みにくいように思います。具体的な変数名に言及しませんか。 `param.moduleNames は npm pack された .tgz ファイルのパスを含む場合がある。しかし NodeModules#listScriptFiles() はこれを扱えない。そのため npm i 前後の〜` みたいに。

2020-04-10 03:43 UTC, xnv commented on packages/akashic-cli-install/spec/installSpec.js
> +					gameJson = JSON.parse(fs.readFileSync("./somedir/game.json", "utf-8").toString());
いや…… 「npm install をエミュレートするはずの処理で、なぜか変数 `gameJson` に代入が起きて、あまつさえ後続処理ではそれを参照せねばならない」というのはかなり厳しいと思います。(それはもはやエミュレートではないですし、責務分担としても非常に読み取りにくいので)　somedir だけ特別扱いというのも柔軟性に欠けますし、別でコメントしているとおり mockfs() しなおすという方針を見直したいです。

2020-04-10 03:43 UTC, xnv commented on packages/akashic-cli-install/spec/installSpec.js
> +				mockfs(mockFsContent);
よくよく考えるとこれ、そもそも `mockfs()` しなおさなくていい気がしてきました。(大昔の私が書いた処理のような気がするんですが、根本的に間違っている気がするという……)

というのもこれ、やりたいことは「mock された fs の中での game.json と package.json を編集する」ですよね。 mock されてるんだから `fs.writeFileSync()` などを実行すればもっと単純に書けたりしないでしょうか。すくなくとも「somedir の game.json がなぜか特別な変数に入ってそれを使わないといけない」というような仕様は避けたいです。

2020-05-12 03:58 UTC, ShinobuTakahashi commented
package.jsonの差分比較の場合、再度インストール実行時にgame.jsonが更新されないバグがある。
https://github.com/akashic-games/akashic-cli/pull/298/ で修正したため、クローズとする。

2020-05-12 03:58 UTC, closed without merging