Delete unnecessary lines from js template file
akashic-games/akashic-cli pull request #292
Opened 2020-04-15 04:49 UTC by ShinobuTakahashi

## 内容

akashic-cli-init の jsテンプレートにある下記2つの記述が初心者には理解しづらい箇所を jsファイルから取り除く。
- "use strict"
- Object.defineProperty()

2020-04-15 04:51 UTC, ShinobuTakahashi commented on packages/akashic-cli-init/templates-src-v3/typescript-base/tsconfig.json
> +    "noImplicitUseStrict": true
"use strict;" を出力に含めない。

2020-04-15 05:03 UTC, xnv requested changes

2020-04-15 05:03 UTC, xnv commented on packages/akashic-cli-init/templates-src/typescript-base/tsconfig.json
>      "module": "commonjs" ,
もしかしてこれを `"es6"` にしたら何もしなくても `Object.defineProperty()` がなくなったりしませんかね？
https://www.typescriptlang.org/v2/en/tsconfig#module

2020-04-15 05:03 UTC, xnv commented on packages/akashic-cli-init/build/generateTemplateSource.js
> +	const targetWord = "Object.defineProperty";
`Object.defineProperty()` がここにしか現れない保証はないので、消しすぎる恐れがあると思います。(テンプレートのゲーム処理の中に現れないとも限らない)　「ファイル先頭数行の」「`Object.defineProperty("__esModule", ...);` だけでできている行」だけ消す、ぐらいの処理が必要ではありませんか。

もちろん tsconfig.json でなんとかなったらそっちの方が嬉しいです。

2020-04-15 05:03 UTC, xnv commented on packages/akashic-cli-init/build/generateTemplateSource.js
> +		if (key === "shin-ichiba-ranking") {
対象を shin-ichiba-ranking に絞る理由はないのでは……？

2020-04-15 05:04 UTC, xnv commented on packages/akashic-cli-init/templates-src/typescript-base/tsconfig.json
>      "module": "commonjs" ,
これでいいならコメント残しておきたくはあります。(他でこの指定全然使ってないと思うので)

2020-04-15 07:04 UTC, ShinobuTakahashi commented on packages/akashic-cli-init/build/generateTemplateSource.js
> +		if (key === "shin-ichiba-ranking") {
仰る通りです。if分を削除しました。

2020-04-15 07:04 UTC, ShinobuTakahashi commented on packages/akashic-cli-init/build/generateTemplateSource.js
> +	const targetWord = "Object.defineProperty";
仰る通りです。`Object.defineProperty(exports, "__esModule", { value: true });` と対象行の空白を削除した物とが一致する場合は削除するように修正しました。

2020-04-15 07:04 UTC, ShinobuTakahashi commented on packages/akashic-cli-init/templates-src/typescript-base/tsconfig.json
>      "module": "commonjs" ,
ご指摘の通り、`"module": "es6"` にし export 部分を修正すると生成される js には、`Object.defineProperty()` は出力されませんでした。
ただ、実行環境である akashic-sandbox, serveが `export` を解決できずエラーとなるため、serve 等も `module: es6` に修正する必要があると思います。

2020-04-15 10:19 UTC, dera- approved these changes

2020-04-15 11:12 UTC, xnv commented on packages/akashic-cli-init/templates-src/typescript-base/tsconfig.json
>      "module": "commonjs" ,
ああそりゃそうですね……。 `export` 残したら Akashic Engine が扱えなかった。すいません、忘れてください。

2020-04-15 11:26 UTC, xnv requested changes

2020-04-15 11:26 UTC, xnv commented on packages/akashic-cli-init/build/generateTemplateSource.js
> +	const excludeWord = `Object.defineProperty(exports, "__esModule", { value: true });`.replace(/\s+/g, "");
「空白を無視してマッチさせたい」ということだと思いますが、ここで replace して文字列も各行いちいち replace して回るくらいなら、正規表現使って replace 一発で済ませたくなってきますね。試してませんが、こんな感じでどうでしょう。

```
const excludeRe = /^Object.defineProperty\(exports,\s*"__esModule",\s*{\s*value:\s*true\s*}\);\s*$/m;
const writeData = data.replace(excludeRe, "");
```

私の理解が合っていれば、 `/.../m` ですけど `/.../mg` ではないので、該当する `defineProperty()` が万一二度出てきても最初の一つしか潰さないはず。

2020-04-16 02:05 UTC, ShinobuTakahashi commented on packages/akashic-cli-init/build/generateTemplateSource.js
> +	const excludeWord = `Object.defineProperty(exports, "__esModule", { value: true });`.replace(/\s+/g, "");
ありがとうございます。
ご教授頂いた正規表現で実装し、`Object.defineProperty()` を削除でき動作確認できました。

2020-04-16 02:11 UTC, xnv approved these changes
実際出力されたファイルが問題ないかだけ確認お願いします。

2020-04-16 03:11 UTC, merged