fix tgz file installation
akashic-games/akashic-cli pull request #298
Opened 2020-05-11 01:57 UTC by ShinobuTakahashi

## 修正内容

akashic-cli-install で npm packで生成されたtgzファイルをインストールするとエラーとなる問題の解決。
(e.g. akashic install ./anyModule.tgz)

原因が、指定されたtgzファイルのパスが browserifyへ渡り、browserifyでエラーとなっている。

対応として、tgzファイルから package.json を取得&モジュール名を取得して後続処理に渡すように修正

動作確認として、モジュールAのtgzのファイルパス、モジュールBのモジュール名で実行し、game.json, package.jsonが更新されることを確認。
(e.g. akashic install ../anyModule.tgz @akashic/bmpfont-generator)

https://github.com/akashic-games/akashic-cli/pull/283 では、同モジュールを再度installした場合にgame.jsonの更新が行われないバグがあった。

2020-05-11 02:31 UTC, xnv requested changes

2020-05-11 02:31 UTC, xnv commented on packages/akashic-cli-install/src/install.ts
> +	const json = JSON.parse(data);
`data` が `any` なので通ってますが、配列を渡すのは望ましいコードとは言いにくいと思います。これで一見正しく動いているのは、

- `JSON.parse()` が最初に文字列を `toString()` する
- 配列を `toString()` すると「各要素を `toString()` したものを `,` で join したもの」になる
  - e.g. `["foo", "bar", "zoo"].toString === "foo,bar,zoo"` になる
- この配列は大抵の場合要 `length` が 1 で要素は文字列なので、たまたま多くの場合 `data.toString() === data[0]` である

といういくつかの挙動に依存しています。

そもそも配列の長さが 2 以上になることを想定せず、またその時点で動かないわけで、配列である必要はないはずです。

2020-05-11 02:31 UTC, xnv commented on packages/akashic-cli-install/src/install.ts
> +		if (entry.header.path.indexOf("package.json") !== -1) {
厳密にマッチしたいです。これだと `foo/bar/package.json` や `package.json.backup` などにも反応しそうに見えます。別コメントのとおり、複数ファイルマッチしてしまうと `JSON.parse()` の段階で例外が飛ぶと思います。

ルート直下の厳密に `package.json` というファイル名にだけ当たるようにすべきではないでしょうか。
また、最初から見たいファイルのパス (ルート直下の package.json) は決まっているので、直接パス名を指定してアクセスする API があればそちらを使う方が簡単ではないかと思います (なければ `onentry` に頼るこの形が必然だと思いますが)。

2020-05-11 02:31 UTC, xnv commented on packages/akashic-cli-install/src/install.ts
> +
不要な空行です。

2020-05-11 02:31 UTC, xnv commented on packages/akashic-cli-install/src/install.ts
> +						if (/\.tgz/.test(moduleName)) {
- 厳密にマッチしたいです。 `\.tgz$` にしませんか。 (foo.tgz.txt にも反応してしまうので )
- 念のため `.tar.gz` にもマッチしたいです。 `\.t\(ar\.\)?gz$` とかでいけないでしょうか。

2020-05-11 02:31 UTC, xnv commented on packages/akashic-cli-install/src/install.ts
> +							moduleName = _getPackageNameFromTgzFile(moduleName);
引数書き換えるのはまあ別に問題ではないんですが、ややびっくりします。

```
cons actualName = (...条件...) ? moduleName : _getPackageNameFromTgzFrile(moduleName);
installedModuleName..push(atcualName);
```

にしませんか。

2020-05-11 04:43 UTC, dera- commented on packages/akashic-cli-install/src/install.ts
> +						conf.addOperationPlugin(param.plugin, installedModuleNames[0]);
この時点でinstalledModuleNamesに必ず1つ以上のモジュールが記載されているという前提でよろしいでしょうか？もしそういう前提でなければ、`installedModuleNames.length > 0`といった条件を追加してほしいです。

2020-05-11 04:45 UTC, dera- commented
あと本題とは関係ないですが、このPRにLabelsの付与もお願いします

2020-05-12 02:12 UTC, ShinobuTakahashi commented on packages/akashic-cli-install/src/install.ts
> +	const json = JSON.parse(data);
ありがとうございます。`data` の型を `string`にし修正しました。

2020-05-12 02:12 UTC, ShinobuTakahashi commented on packages/akashic-cli-install/src/install.ts
> +		if (entry.header.path.indexOf("package.json") !== -1) {
直接パス指定のAPIが無かったので、`onentry` で処理しています。
`onentry` で取得できるパスが `解凍後のディレクトリ名/package.json` となるので、`/` でsplitして`package.json`を比較するよう修正しました。

2020-05-12 02:12 UTC, ShinobuTakahashi commented on packages/akashic-cli-install/src/install.ts
> +
削除しました。

2020-05-12 02:12 UTC, ShinobuTakahashi commented on packages/akashic-cli-install/src/install.ts
> +						if (/\.tgz/.test(moduleName)) {
判定を `/\.t(ar\.)?gz$/` へ修正しました。

2020-05-12 02:12 UTC, ShinobuTakahashi commented on packages/akashic-cli-install/src/install.ts
> +							moduleName = _getPackageNameFromTgzFile(moduleName);
修正しました。

2020-05-12 02:12 UTC, ShinobuTakahashi commented on packages/akashic-cli-install/src/install.ts
> +						conf.addOperationPlugin(param.plugin, installedModuleNames[0]);
`installedModuleNames` (param.moduleNames) が0の場合にはここのパスには入らず、`npm i` のみを実行し早期リターンしています。

2020-05-12 02:16 UTC, dera- approved these changes

2020-05-12 02:40 UTC, xnv approved these changes
コメントつけていますが  approved.

2020-05-12 02:40 UTC, xnv commented on packages/akashic-cli-install/src/install.ts
> +		if (splitPath[1] === "package.json") {
さすがに問題なさそうなので対応不要ですが、反射的に `(length === 2)` もチェックしたくなるコードですね。この処理だけ見ると、「package.json というディレクトリ」がある時の挙動が気になってしまうので。(現実的には npm pack していれば直下の package.json が JSON でないことは考えられませんが)

2020-05-12 02:40 UTC, xnv commented on packages/akashic-cli-install/src/install.ts
> +					param.moduleNames.forEach((moduleName) => {
今更ですが `map` で書くほうが簡潔そうですね。

```
installedModuleNames = param.moduleNames.map(name => {
  return /\.t(ar\.)?gz$/.test(name) ? _getPackageNameFromTgzFile(name) : name;
});
```

2020-05-12 03:16 UTC, ShinobuTakahashi commented on packages/akashic-cli-install/src/install.ts
> +					param.moduleNames.forEach((moduleName) => {
仰る通り、`map` の方が簡潔でしたので修正しました。

2020-05-12 03:58 UTC, merged