akashic-cli-serveでユーザー名表示許諾ダイアログを表示する対応
akashic-games/akashic-cli pull request #321
Opened 2020-05-31 19:49 UTC by dera-

### 概要
* akashic-cli-serveでコンテンツを動作させた時に、コンテンツ上でユーザー名を表示するかどうか尋ねてくるダイアログを表示する機能を追加しました。
  * ちなみに、この機能を利用するためにはコンテンツ中で`g.game.external.coeLimited`を有効にして、`g.game.external.coeLimited.startLocalSession()`と`g.game.external.coeLimited.exitLocalSession()`を実行する必要があります。

### やったこと
* ユーザー名表示ダイアログの表示条件をクリアしたコンテンツを実行した時に、ユーザー名表示許諾ダイアログをコンテンツの直下に表示
  * 許諾されればユーザー名を、許諾されなければ仮のユーザー名(ここでは`akashic-cli-serve-player`としている)がコンテンツ側に送られる。
  * 制限時間も付いていて、制限時間中に選択しなければ許諾されなかった時と同様の動作を行う。

### やっていないこと
* ユーザー名表示許諾ダイアログのUIデザイン部分

2020-05-31 19:50 UTC, dera- commented on packages/akashic-cli-serve/src/client/store/CoeLimitedPluginEntity.ts
> +	@action.bound
`@action` だと `this` をこのオブジェクトのコンテキストとして認識されないため、`@action.bound` を使用しました。`@action.bound` を使用しなくても済む方法についてもしご存知であれば教えていただきたいです。

2020-05-31 19:52 UTC, dera- commented on packages/akashic-cli-serve/src/client/store/CoeLimitedPluginEntity.ts
> +export class CoeLimitedPluginEntity {
`g.game.external.coeLimited` が直接参照するオブジェクトの関数・変数をビュー側から直接参照できる形にしてしまいましたが、ビューから参照される部分はuiStoreやuiOperator等に切り離した方がいいですかね？(そうなると、このentityがstoreに直接依存してしまって依存関係が複雑になるのではと思って今のような形にしていますが)

2020-06-01 04:17 UTC, yu-ogi commented on packages/akashic-cli-serve/src/client/view/molecule/ConfirmDialog.tsx
> +			<p>プレイヤー名をゲーム上で表示しますか？(残り時間：{ this.props.remainingSeconds })</p>
こちら文言は固定なのでしょうか。
固定であればもう少しコンポーネント名を具体化したほうが良いかと思います。

2020-06-01 04:17 UTC, yu-ogi commented on packages/akashic-cli-serve/src/client/view/organism/GameScreen.tsx
> +	onClickResolver?: (accepted: boolean) => void;
このあたりは単に `ConfirmDialogProps` を optional で持つだけで良さそうに思いましたがいかがでしょう。
このコンポーネントで二重にプロパティを抱え持つ必要はないかと思います。

2020-06-01 04:17 UTC, yu-ogi commented on packages/akashic-cli-serve/src/client/store/CoeLimitedPluginEntity.ts
> +	messageHandler: (message: any) => void;
ここの any は避けたいです。

2020-06-01 04:17 UTC, yu-ogi commented on packages/akashic-cli-serve/src/client/store/CoeLimitedPluginEntity.ts
> +export interface StartLocalSessionMessage {
`StartLocalSessionPameterObject` と紛らわしいですし、 `StartLocalSession` とは独立したインタフェースなので名前は再考したいです。

2020-06-01 06:13 UTC, dera- commented on packages/akashic-cli-serve/src/client/view/molecule/ConfirmDialog.tsx
> +			<p>プレイヤー名をゲーム上で表示しますか？(残り時間：{ this.props.remainingSeconds })</p>
そうですね。このコンポーネントは今のところ汎用的なものにするつもりはなく文言も固定にしようと考えています。ですので、仰る通り具体的なコンポーネント名にした方がよさそうですね。`UsernameDisplayAuthorizationDialog`とかですかね

2020-06-01 06:15 UTC, dera- commented on packages/akashic-cli-serve/src/client/view/organism/GameScreen.tsx
> +	onClickResolver?: (accepted: boolean) => void;
確かにそうですね。そのように修正してみます。

2020-06-01 06:16 UTC, dera- commented on packages/akashic-cli-serve/src/client/store/CoeLimitedPluginEntity.ts
> +	messageHandler: (message: any) => void;
了解しました、インターフェース定義しておきます

2020-06-01 07:31 UTC, dera- commented on packages/akashic-cli-serve/src/client/store/CoeLimitedPluginEntity.ts
> +export interface StartLocalSessionMessage {
なるほど。安直ですが、このserve内に限って言えばこのメッセージはユーザー名表示許諾ダイアログから送られるものなので`UsernameDisplayAuthorizationMessage`にしようかと思ってます。

2020-06-02 06:02 UTC, yu-ogi commented on packages/akashic-cli-serve/src/client/view/organism/GameScreen.tsx
>  				isDisplayingResolver ?
こちら `usernameDisplayAuthorizationDialogProps` の有無で表示/非表示を分けることはできないでしょうか。

2020-06-02 06:02 UTC, yu-ogi commented on packages/akashic-cli-serve/src/client/store/CoeLimitedPluginEntity.ts
> +		this.startLocalSession = (param: StartLocalSessionPameterObject) => {
コンストラクタでメソッドを定義している理由は何でしょう?
他の箇所と違うので気になりました。
https://github.com/akashic-games/akashic-cli/blob/77ce299c27eb40068e45975458490b50452bbad0/packages/akashic-cli-serve/src/client/store/CoePluginEntity.ts#L57

2020-06-02 06:02 UTC, yu-ogi commented on packages/akashic-cli-serve/src/client/view/molecule/UsernameDisplayAuthorizationDialog.tsx
> +			<p>プレイヤー名をゲーム上で表示しますか？(残り時間：{ this.props.remainingSeconds })</p>
制限時間を props 経由で渡すのはわかるのですが、残り時間も props で渡しているのに少々違和感があります。
内部状態 (この場合カウントダウンされていく残り時間) は state として `UsernameDisplayAuthorizationDialog` の中で管理し、残り時間が 0 になったら props 経由でコールバックで通知する (= そこで `messageHandler()` を呼ぶ ) という設計のほうが責務範囲として正しいように思いましたがいかがでしょう。

2020-06-02 06:02 UTC, yu-ogi commented on packages/akashic-cli-serve/src/client/store/CoeLimitedPluginEntity.ts
> +			// NOTE: この場合、F5実行時に表示上だけ制限時間がリセットされてしまう(実際はリセットされない)ので、現在時刻ではなくゲームの起動時刻を取得した方が良さそう？
`F5` -> `ページリロード` でしょうか。 (windows ユーザにしか伝わらなそう?)

2020-06-02 10:34 UTC, dera- commented on packages/akashic-cli-serve/src/client/view/organism/GameScreen.tsx
>  				isDisplayingResolver ?
了解しました。Container側でisDisplayingResolverの値によってGameScreenコンポーネント生成時にusernameDisplayAuthorizationDialogPropsを付与するかどうか分岐して、ここではその有無で表示/非表示を分けるようにしました(やっていることは本質的には同じですが、その方法の方がGameScreenのpropsも減ってよりスマートかと思います)。

2020-06-02 10:35 UTC, dera- commented on packages/akashic-cli-serve/src/client/store/CoeLimitedPluginEntity.ts
> +		this.startLocalSession = (param: StartLocalSessionPameterObject) => {
あ、すみません。コンストラクタで定義しなければいけない理由は特にないので、他箇所と併せて最初から定義するように修正します。

2020-06-02 10:35 UTC, dera- commented on packages/akashic-cli-serve/src/client/store/CoeLimitedPluginEntity.ts
> +			// NOTE: この場合、F5実行時に表示上だけ制限時間がリセットされてしまう(実際はリセットされない)ので、現在時刻ではなくゲームの起動時刻を取得した方が良さそう？
あ、、確かにそうですね。。こちら修正します。

2020-06-02 10:53 UTC, dera- commented on packages/akashic-cli-serve/src/client/view/molecule/UsernameDisplayAuthorizationDialog.tsx
> +			<p>プレイヤー名をゲーム上で表示しますか？(残り時間：{ this.props.remainingSeconds })</p>
確かに責務範囲としてはその方が正しいかと思いますが、serveのコンポーネントのほとんどはstateを持たない作りになっていてこのコンポーネントもそれに合わせるべきかと思ってます。
ですので、やるのであればこのコンポーネントでしか使わないstateをCoeLimitedEntityではなくuiStore等に置くべきだと考えているのですが、https://github.com/akashic-games/akashic-cli/pull/321#discussion_r432978478 に記載している理由のためCoeLimitedEntityに定義してたんですよね。。

この個所についてはどうすべきか一旦考えさせてください

2020-06-03 04:00 UTC, yu-ogi commented on packages/akashic-cli-serve/src/client/store/CoeLimitedPluginEntity.ts
> +	@action.bound
↑の箇所と同様に `=` で定義すれば問題ないように思います。
```javascript
sendName = (accepted: boolean): void => {
    ...
}
```

2020-06-03 06:04 UTC, dera- commented on packages/akashic-cli-serve/src/client/store/CoeLimitedPluginEntity.ts
> +	@action.bound
なるほど、ありがとうございます。そのように修正してみようと思います。

2020-06-03 12:27 UTC, xnv requested changes

2020-06-03 12:27 UTC, xnv commented on packages/akashic-cli-serve/src/client/store/CoeLimitedPluginEntity.ts
> +	sendName = (accepted: boolean): void => {
this を bind する形式で書かれていますが、だいたい UI からはこれを直接呼ばず、Operator を経由して呼ばせてるので、 store のメソッドを action.bound なりこの形式で書く必要はない認識です。(ただ Operator で一段かます意味ないかもしれないという気もしており、この形でもいいかも……と思いつつあります)

2020-06-03 12:27 UTC, xnv commented on packages/akashic-cli-serve/src/client/store/CoeLimitedPluginEntity.ts
> +	startLocalSession = (param: StartLocalSessionPameterObject): void => {
想定しないアプリケーション名がきたら弾く処理ぐらいは入れておきたいです。

2020-06-03 12:27 UTC, xnv commented on packages/akashic-cli-serve/src/client/store/CoeLimitedPluginEntity.ts
> +export class CoeLimitedPluginEntity {
そもそもこれ (plugin) が store の entity であるという設計がいまいち腑に落ちておらず (他プラグインもそうなってる気がしますが)、個人的には一旦このままでいい気がします。

2020-06-04 00:50 UTC, yu-ogi approved these changes

2020-06-04 09:35 UTC, dera- commented on packages/akashic-cli-serve/src/client/store/CoeLimitedPluginEntity.ts
> +	startLocalSession = (param: StartLocalSessionPameterObject): void => {
了解しました。こちら対応します。

2020-06-04 10:48 UTC, xnv commented on packages/akashic-cli-serve/src/client/view/molecule/UsernameDisplayAuthorizationDialog.tsx
> +			<p>プレイヤー名をゲーム上で表示しますか？(残り時間：{ this.props.remainingSeconds })</p>
ここで提案されている変更は「state の初期値として props を使う」ということに思えます。そしてそれは (Hook の導入とかで背景が変わっていなければ) anti-pattern とされているもののような気がします: https://ja.reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html#anti-pattern-unconditionally-copying-props-to-state

このページでは Recommendation として「そもそも state やめる」が真っ先に提案されており、その意味でも現行この形は穏当ではないかと思います。(コンポーネントの内部状態っぽいという感覚は理解するのですが、初期値が props に依存する時点で、これは純粋な内部状態ではない、ということなのではないかと思っています。)

2020-06-05 07:17 UTC, dera- commented on packages/akashic-cli-serve/src/client/store/CoeLimitedPluginEntity.ts
> +export class CoeLimitedPluginEntity {
このエンティティは本来はakashicディレクトリに置くべき気がしていますが、一旦はその旨のTODOコメントだけ残しておく対応をしようと思います。

2020-06-05 07:19 UTC, dera- commented on packages/akashic-cli-serve/src/client/store/CoeLimitedPluginEntity.ts
> +	sendName = (accepted: boolean): void => {
こちら仰る通りですが、この対応( https://github.com/akashic-games/akashic-cli/pull/321#discussion_r435733113 )と同様にこちらもTODOコメントだけ残して一旦はこれで行きたいと思ってます。

2020-06-12 13:17 UTC, xnv approved these changes

2020-06-15 06:37 UTC, merged