akashic-cli-serveに起動画面表示オプションと起動画面を追加
akashic-games/akashic-cli pull request #33
Opened 2019-02-27 09:31 UTC by dera-

### 概要
* akashic-cli-serveからコンテンツに対して引数を渡す機能が無かったので今回追加しました。
  * 引数を渡す場合は、-wオプションを付けてakashic-cli-serveを起動して、コンテンツを開くと表示される起動画面上のUIから送ることになります

### やったこと
* 起動画面を表示するかどうかのコマンドオプション(-w, --wait)を追加
* クライアント側で以下のことができる起動画面を表示できるようにした
  * コンテンツにjoinするかどうかの選択
  * コンテンツに送る引数の編集
* 対象コンテンツのディレクトリ上に「startup_argument.json」を置いておくと、底に記載されている引数候補がリストの形で起動画面上に表示されるようになった
* 以下の内部APIを追加
  * /config/options: サーバー起動時の各種オプションの値を取得
  * /api/atartup-argument: 対象コンテンツのディレクトリ上にあるstartup_argument.jsonの内容を取得

2019-02-27 09:44 UTC, dera- commented on packages/akashic-cli-serve/src/client/operator/Operator.ts
> +	startContent = async (params?: StartContentParameterObject): Promise<void> => {
起動画面の追加に伴って、playの生成とLocalInstanceの生成を分けることにしました

2019-02-27 09:45 UTC, dera- commented on packages/akashic-cli-serve/src/client/store/StartupScreenUiStore.ts
> +	constructor() {
起動画面のUIの各種値は引き回すことはないと思われますので、storageは利用しない感じにしました

2019-02-27 09:47 UTC, dera- commented on packages/akashic-cli-serve/src/client/store/StartupScreenUiStore.ts
> +		this.startupArgumentListWidth = 150;
手抜きでマジックナンバーにしてしまいました。。どこかにUI用の定数を定義できるところがあればいいのですが。。

2019-02-27 09:47 UTC, dera- commented on packages/akashic-cli-serve/src/client/view/atom/RightResizable.tsx
> -		console.log({ py: ev.pageX, sy: this.lastPageX, diff: (ev.pageX - this.lastPageX) });
これらのconsoleは不要かと思ったので削除しました。削除していけないものであれば教えていただきたいです

2019-02-27 09:50 UTC, dera- commented on packages/akashic-cli-serve/src/client/view/organism/StartupScreen.css
> +.devtool {
このcssの内容は、後から修正していただく前提で用意したので、現状はほとんどEventsDevtool.cssとDevtool.cssの内容のコピーとなっています。

2019-02-27 09:53 UTC, dera- commented on packages/akashic-cli-serve/src/client/view/organism/StartupScreen.tsx
> +import * as React from "react";
起動画面コンポーネントを暫定的にこのファイル1つでまとめました。
コンポーネントを切り出す余地はありそうですが、その対応はやるとしたら別PRになるかと思います

2019-02-27 10:26 UTC, xnv requested changes

2019-02-27 10:26 UTC, xnv commented on packages/akashic-cli-serve/src/client/view/organism/StartupScreen.tsx
> +	startContent: (params?: StartContentParameterObject) => Promise<void>;
他と名前を合わせて欲しいです。 onClickStartContent とかでしょうか。

2019-02-27 10:26 UTC, xnv commented on packages/akashic-cli-serve/src/client/view/organism/StartupScreen.tsx
> +	joinFlag: boolean;
これも。 `showsEventList` い倣うなら `joinsToPlay` とかでしょうか。

2019-02-27 10:26 UTC, xnv commented on packages/akashic-cli-serve/src/client/view/atom/RightResizable.tsx
> -		console.log({ py: ev.pageX, sy: this.lastPageX, diff: (ev.pageX - this.lastPageX) });
消す忘れですね……ありがとうございます。

2019-02-27 10:26 UTC, xnv commented on packages/akashic-cli-serve/src/client/api/ApiClient.ts
> +	SandboxConfigApiResponse, OptionsApiResponse, StartupArgumentApiResponse
周辺と合わせて改行をお願いしたいですね……。

2019-02-27 10:26 UTC, xnv commented on packages/akashic-cli-serve/src/client/bootstrap.tsx
> +		console.error(e);
これはどういうケースの想定なのでしょうか。 bootstrap() できない状況で render() する……？

2019-02-27 10:26 UTC, xnv commented on packages/akashic-cli-serve/src/client/view/organism/StartupScreen.tsx
> +						title={"イベントリストの表示・非表示を切り替え"}
起動引数リストの〜にしたいです。 (後からいじるとはいえ tooltip に事実と異なる表示が出ちゃうので)

2019-02-27 10:26 UTC, xnv commented on packages/akashic-cli-serve/src/client/view/organism/StartupScreen.tsx
> +					placeholder={"an array of playlog events (JSON) to send"}
ここもイベントのままになっています。

2019-02-27 10:26 UTC, xnv commented on packages/akashic-cli-serve/src/server/controller/StartupArgumentController.ts
> +				data.args = require(path.resolve(dirpath, "startup_argument.json"));
イベントリスト同様に sandbox.config.js の1フィールドでいいかと思います。 "events" に倣って "arguments" でどうでしょうか。

2019-02-27 12:03 UTC, dera- commented on packages/akashic-cli-serve/src/client/view/organism/StartupScreen.tsx
> +	startContent: (params?: StartContentParameterObject) => Promise<void>;
onClickStartContent に修正しました

2019-02-27 12:03 UTC, dera- commented on packages/akashic-cli-serve/src/client/view/organism/StartupScreen.tsx
> +	joinFlag: boolean;
了解しました、joinFlag使っている箇所をjoinsToPlayに変更しました

2019-02-27 12:04 UTC, dera- commented on packages/akashic-cli-serve/src/client/api/ApiClient.ts
> +	SandboxConfigApiResponse, OptionsApiResponse, StartupArgumentApiResponse
こちら修正しました

2019-02-27 12:05 UTC, dera- commented on packages/akashic-cli-serve/src/client/bootstrap.tsx
> +		console.error(e);
こちらは以前に書かれていたものを踏襲した感じですね。ちなみにこの変更はload時のみbootstrapが実行されるようにしたかったので行いました。

2019-02-27 12:05 UTC, dera- commented on packages/akashic-cli-serve/src/client/view/organism/StartupScreen.tsx
> +						title={"イベントリストの表示・非表示を切り替え"}
修正しました

2019-02-27 12:06 UTC, dera- commented on packages/akashic-cli-serve/src/client/view/organism/StartupScreen.tsx
> +					placeholder={"an array of playlog events (JSON) to send"}
こちらも修正しました

2019-02-27 12:06 UTC, dera- commented on packages/akashic-cli-serve/src/server/controller/StartupArgumentController.ts
> +				data.args = require(path.resolve(dirpath, "startup_argument.json"));
sandbox.config.jsを使うように修正しました。同時にSandboxConfig型にもarguments要素を追加しました

2019-02-28 01:02 UTC, yu-ogi commented on packages/akashic-cli-serve/src/client/view/organism/StartupScreen.css
> +.devtool {
将来的には scss あたりで共通化したいですね。

2019-02-28 01:45 UTC, yu-ogi commented on packages/akashic-cli-serve/src/server/route/ConfigRoute.ts
> +	configRouter.get("/options", handleToGetStartupOptions);
`create...` と `handle...` の命名の違いの意図って何でしょう?
理由がなければ揃えたほうが良さそうに思いました。

2019-02-28 01:45 UTC, yu-ogi commented on packages/akashic-cli-serve/src/server/index.ts
> +		.option("-w, --wait", `Stop automatic startup of contents. default: false`)
- 説明が `Stop ...` で始まるなら `--stop` のほうが適切に思えました。
   - `--wait` であるなら `Wait ..` で説明を始めたほうが良さそうに思えます。
- `-w` って必要ですかね?

2019-02-28 01:45 UTC, yu-ogi commented on packages/akashic-cli-serve/src/client/store/LocalInstanceEntity.ts
> +	startupArgument?: any;
(imo) `LocalInstanceEntity` からみたら `startup` なのは自明なので `argument` で良いと思います。

2019-02-28 01:45 UTC, yu-ogi commented on packages/akashic-cli-serve/src/client/store/StartupScreenUiStore.ts
> +	constructor() {
個人的には保存されてほしいなと思っています。

2019-02-28 01:47 UTC, yu-ogi commented
PullRequst の説明にある

> * /api/atartup-argument: 対象コンテンツのディレクトリ上にあるstartup_argument.jsonの内容を取
得

はどこに処理があるのでしょう?

2019-02-28 05:21 UTC, dera- commented on packages/akashic-cli-serve/src/server/route/ConfigRoute.ts
> +	configRouter.get("/options", handleToGetStartupOptions);
create~~ はハンドラ関数を生成しているもので、handle~~はハンドラ関数自体という区別がありますね。
そもそもhandle~~を定義するのではなくハンドラ関数を生成するcreate~~で定義するに揃えたらいいのではとも思われそうですが、外部から渡されるものもなく常に作られるハンドラは同じになるものについてはパフォーマンス的なことも考慮して(それほど影響はなさそうですが)ハンドラ関数の定義だけでいいのではと思ってこのようにしてます

2019-02-28 05:29 UTC, dera- commented on packages/akashic-cli-serve/src/server/index.ts
> +		.option("-w, --wait", `Stop automatic startup of contents. default: false`)
> `--wait` であるなら `Wait ..` で説明を始めたほうが良さそうに思えます。

確かにそうですね。`Wait ..` で説明を書いてみます。

> `-w` って必要ですかね?

すみません、よく分かっていないのですが、これは `wait` オプション自体必要ないのではということでしょうか？であれば、起動画面の表示を省略したい場合もあると思うので僕は必要だと思ってますが。。

2019-02-28 05:29 UTC, dera- commented on packages/akashic-cli-serve/src/client/store/LocalInstanceEntity.ts
> +	startupArgument?: any;
修正しておきます

2019-02-28 05:31 UTC, dera- commented on packages/akashic-cli-serve/src/client/store/StartupScreenUiStore.ts
> +	constructor() {
なるほど。。ちょっと検討してみます

2019-02-28 05:47 UTC, dera- commented
> * /api/atartup-argument: 対象コンテンツのディレクトリ上にあるstartup_argument.jsonの内容を取
  得

このAPIですが使わないことにして削除したので、上記説明を修正しておきます。
ちなみに、代わりに起動引数候補リストは/api/sandbox-configから取得できるようにしています

2019-02-28 05:55 UTC, yu-ogi commented on packages/akashic-cli-serve/src/server/index.ts
> +		.option("-w, --wait", `Stop automatic startup of contents. default: false`)
> すみません、よく分かっていないのですが、これは `wait` オプション自体必要ないのではということでしょうか？

いえ、省略した引数 `-w` のことです。

2019-02-28 05:57 UTC, yu-ogi commented on packages/akashic-cli-serve/src/server/route/ConfigRoute.ts
> +	configRouter.get("/options", handleToGetStartupOptions);
なるほど、見落としていました。

2019-02-28 06:48 UTC, dera- commented on packages/akashic-cli-serve/src/server/index.ts
> +		.option("-w, --wait", `Stop automatic startup of contents. default: false`)
うーん、省略形はあってもいいと思うんですよね。。個人的な話ですみませんが、僕としては省略系の方を多用しますし。
逆にあるとまずかったりしますでしょうか？

2019-02-28 07:21 UTC, yu-ogi commented on packages/akashic-cli-serve/src/server/index.ts
> +		.option("-w, --wait", `Stop automatic startup of contents. default: false`)
> 逆にあるとまずかったりしますでしょうか？

別にまずくないと思います。

- 今後 `--w...` で始まる引数が追加された場合に `-w` が使えなくなる
- そもそも自動で開始される動作こそ引数が必要 ( `--auto-start` など) なのではないか

など考えられる中で `-w` を今すぐ使ってしまう必要性があるのか?という意味で質問いたしました。

2019-02-28 09:32 UTC, dera- commented on packages/akashic-cli-serve/src/server/index.ts
> +		.option("-w, --wait", `Stop automatic startup of contents. default: false`)
なるほど。ちょっとその件については後日相談させてください。
現状プレリリースバージョンで `-w` が使える状態になってしまっているため、いきなり無くすことを即決できない状況ですので。。

2019-02-28 09:51 UTC, dera- commented on packages/akashic-cli-serve/src/server/index.ts
> +		.option("-w, --wait", `Stop automatic startup of contents. default: false`)
別で相談したところ、`--wait`オプション自体暫定的なものなので一旦`--wait`だけにするという結論になりました。
また`--wait`オプションの名前をどうするかやそもそも自動開始の方をオプションにすべきだとかそういった議論は別途相談ということになりました

2019-03-04 02:47 UTC, yu-ogi commented on packages/akashic-cli-serve/src/client/view/organism/StartupScreen.tsx
> +export class StartupScreen extends React.Component<StartupScreenProps, {}> {
`Screen` というものが初めて使われていますが `Screen` とはどのようなものでしょう?

2019-03-04 02:47 UTC, yu-ogi commented on packages/akashic-cli-serve/src/client/view/organism/StartupScreen.tsx
> +	private _generateStartArgumentDom = (): React.ReactNode => {
場所によって `startupArgument` だったり `startArgument` だったりと異なる名前になってしまっているので、できれば統一したいです。

2019-03-04 02:47 UTC, yu-ogi commented on packages/akashic-cli-serve/src/client/store/storage.ts
> +	joinsToPlay: boolean;
自動的に `join` する、という意なら `joinsAuto(matically)` などの方が適切かなと思いました。

2019-03-04 07:21 UTC, dera- commented on packages/akashic-cli-serve/src/client/view/organism/StartupScreen.tsx
> +export class StartupScreen extends React.Component<StartupScreenProps, {}> {
「起動画面」の「画面」という意味で使いたかった(新しい概念を追加したかったわけでなく単なる名詞として入れたいという意図)のですが、screenはあまり一般的なものではない感じでしょうか？

2019-03-04 07:23 UTC, dera- commented on packages/akashic-cli-serve/src/client/view/organism/StartupScreen.tsx
> +	private _generateStartArgumentDom = (): React.ReactNode => {
お、それはケアレスミスな気がしますね。。僕としては`startupArgument`で統一したい気持ちなので`startArgument`となっているところを直そうと思います。

2019-03-04 07:38 UTC, dera- commented on packages/akashic-cli-serve/src/client/store/storage.ts
> +	joinsToPlay: boolean;
なるほど。確かに意味としては「ゲーム開始時に自動でjoinする」なのでそちらの方が適切に思えます。修正しておきます。

2019-03-04 08:13 UTC, dera- commented on packages/akashic-cli-serve/src/client/store/StartupScreenUiStore.ts
> +	constructor() {
こちらstorageを利用するように変更してみました

2019-03-04 08:50 UTC, yu-ogi commented on packages/akashic-cli-serve/src/client/view/organism/StartupScreen.tsx
> +export class StartupScreen extends React.Component<StartupScreenProps, {}> {
処理を見れば確かに「画面」を示していることは読み取れるのですが、 `ToolBarContainer` や `DevtoolContainer` の兄弟関係に近いものが `organism` として存在しているという状況がよくわからず...
( `StartupContainer` や `StartupScreenContainer` として `container` に追加されるなら理解できるのですが)

2019-03-04 10:31 UTC, dera- commented on packages/akashic-cli-serve/src/server/index.ts
> +		.option("-w, --wait", `Stop automatic startup of contents. default: false`)
auto-startの方がデフォルトということなので、デフォルトとは違う挙動をするというのを直感的にするために--no-auto-start というオプション名に変えてみました

2019-03-05 01:00 UTC, yu-ogi approved these changes

2019-03-05 01:00 UTC, yu-ogi commented on packages/akashic-cli-serve/src/server/index.ts
> +		serverGlobalConfig.waitStarting = !commander.autoStart;
特に理由がなければ他と合わせて `serverGlobalConfig` 側も `autoStart` にしたいです。

2019-03-05 13:03 UTC, dera- commented on packages/akashic-cli-serve/src/server/index.ts
> +		serverGlobalConfig.waitStarting = !commander.autoStart;
修正します

2019-03-06 11:02 UTC, xnv approved these changes
起動引数/startup argument なのだと思いますが、どちらかというと「ゲームコンテンツの引数」であることの方が強調したい気もし、 game argument とか content argument とかはどうでしょうか。

……というコメントはありますが approved です。

2019-03-11 10:44 UTC, merged