Add specification of assets directory in scan
akashic-games/akashic-cli pull request #334
Opened 2020-06-15 07:04 UTC by ShinobuTakahashi

## 概要

- `akashic-cli-scan` で  `assets/` ディレクトリを特別扱いとする
 - `assets/` ディレクトリ配下にある image, audio, scripts, text の全てのファイルをscanする。
 -  アセットID は assets_golup5vr のような `assets_xxxxx` 形式として自動生成され保証されないものとする。

2020-06-15 10:14 UTC, xnv requested changes

2020-06-15 10:14 UTC, xnv commented on packages/akashic-cli-scan/src/Configuration.ts
> +		return "assets_" + Math.floor(Date.now() * Math.random()).toString(32);
- `assets_xxxxxxx` を  `asset:xxxxxxx` にしたいです。 `_` だと `/image/assets_xxxxx.png` とかが万一あると被るので……。
- さすがに乱数だと挙動が非決定的になってテストなども難しくなりそうです。ファイルパスからハッシュ値を求めるコードが commons にあったと思うので、それを使いませんか。

2020-06-15 10:14 UTC, xnv commented on packages/akashic-cli-scan/src/Configuration.ts
> +								} else if (this._isAssetsDir(durationMap[current].path)) {
この判断ロジックが `_scanAssetsAudio()` などの中に入り込むのはちょっと、他から浮いていて気になります。↑の `_resolveAssetIdsFromPath` を `_assetIdResolveMode: "basename" | "path" | "hash"` に変えて、 それで分岐するようにしませんか。

2020-06-15 10:14 UTC, xnv commented on packages/akashic-cli-scan/src/Configuration.ts
> +	scanAssetsDir(info: ScanAssetsInformation): void {
scan はしてないのでは……？　この処理内容だと、scan 対象のディレクトリを決定しているのであって、 scan そのものではないですよね。また現状だと次のようなディレクトリ構造があった時、

```
- `assets/chara0/faces/laugh.png`
- `assets/chara0/faces/cry.png`
- `assets/chara0/charachip.png`
```

`assets/chara0/` と `assets/chara0/faces/` が両方 scanDirectoryTable に積まれそうに見えます。恐らく前者を scan する後者のディレクトリもリストアップされてしまうのではないでしょうか。動作上問題はなさそうですが、無駄っぽいのが気になります。

どちらかというと、 `_scanAssetsAudio()` などから「ファイルひとつ分の処理」を関数として切り出して、ここで  `_isImageFilePath()` を満たすならそのまま image asset としての登録処理を行う方が straightforward ではありませんか。

2020-06-16 06:31 UTC, ShinobuTakahashi commented on packages/akashic-cli-scan/src/Configuration.ts
> +		return "assets_" + Math.floor(Date.now() * Math.random()).toString(32);
`asset:xxxxxxx` の形式に修正しました。

2020-06-16 06:32 UTC, ShinobuTakahashi commented on packages/akashic-cli-scan/src/Configuration.ts
> +								} else if (this._isAssetsDir(durationMap[current].path)) {
`_assetIdResolveMode` で条件分岐するよう修正しました。

2020-06-16 06:32 UTC, ShinobuTakahashi commented on packages/akashic-cli-scan/src/Configuration.ts
> +	scanAssetsDir(info: ScanAssetsInformation): void {
仰る通り scan してませんでした... 
各 `scanAssetxxx()` から1ファイル 処理する部分を関数化し、この `scanAssetsDir()` で処理するよう修正しました。

2020-06-16 06:33 UTC, ShinobuTakahashi commented on packages/akashic-cli-scan/src/Configuration.ts
> +	if (!/^[a-zA-Z_$:]{1}[0-9a-zA-Z_$:]*$/.test(name))
assets ディレクトリの idが `asset:xxxxxx` 形式のため `:` を追加

2020-06-17 05:12 UTC, xnv requested changes

2020-06-17 05:12 UTC, xnv commented on packages/akashic-cli-scan/src/Configuration.ts
> +			!this._resolveAssetIdsFromPath && this._isAssetsDir(durationInfo.path) ? "hash" : this._assetIdResolveMode;
> _resolveAssetIdsFromPath を _assetIdResolveMode: "basename" | "path" | "hash" に変えて、

と書いたのは、  `this._resolveAssetIdsFromPath` を廃止して `this._assetIdResolveMode` を追加しませんか、っていう話のつもりだったのですが、なんかそれだと難しいところがあったりしますか……？

なぜそんな話をしているかというと、これは「アセット ID をどう決定するか」という一つの問題だからです。一つの問題に対応する一つの変数があるのは自然に思えますし、それはできるだけ、一箇所で定まってほしいです。(現状だと、 `_resolveAssetIdFromPath` はコンストラクタ時点で定まるのに、本当の「アセット ID の決め方」はここまで来ないと決まらなくなっている)

2020-06-17 05:12 UTC, xnv commented on packages/akashic-cli-scan/src/Configuration.ts
> +	if (!/^[a-zA-Z_$:]{1}[0-9a-zA-Z_$:]*$/.test(name))
この変更は不要なはずです。

この関数は「アセットのファイル名が (アセット ID として) valid かどうか」を判定していて、「妥当なアセット ID かどうか判定する」ではありません。いや関数名に反映しにくくて非常に紛らわしいのですが、二つは別物です。その証拠に mode `"path"` で入り込む `/` はここの判定ではエラーになります。

mode `"hash"` で生成したアセット ID も、 mode `"path"` と同様に (というかむしろ敢えて) ここではエラーになるものにしたいと考えています。そうすることで、他のアセット ID と衝突しないことを保証できるからです。

2020-06-17 05:12 UTC, xnv commented on packages/akashic-cli-scan/src/Configuration.ts
> +			!this._resolveAssetIdsFromPath && this._isAssetsDir(durationInfo.path) ? "hash" : this._assetIdResolveMode;
というか、 `this._assetIdResolveMode` があるのに、それと別に  `assetIdResolveMode` があるのは難解すぎるように思います。

2020-06-17 05:12 UTC, xnv commented on packages/akashic-cli-scan/src/Configuration.ts
> +	 * `assets:xxxxxx` の形式とする。
`assets` (複数形) になっています (細かいですがコードと違うとどっちが意図なのかわからなくなります)

2020-06-17 05:12 UTC, xnv commented on packages/akashic-cli-scan/src/Configuration.ts
> +				if (!this._resolveAssetIdsFromPath) {
`_assertAssetFilenameValid()` に変更が必要になったのはここの分岐のせいだと思いますが、 根本的に `_resolveAssetIdsFromPath` を廃止したいです。ここの分岐は `assetIdResolveMode === "basename"` となると思いますし、そうすれば `_assert〜()` の方に修正は不要かと思います。

2020-06-17 05:12 UTC, xnv commented on packages/akashic-cli-scan/src/Configuration.ts
> +	_scanImageFile(f: string, imageAssetDir: string, assets: cmn.Assets, revmap: { [key: string]: string[] }): void {
- image file を scan する関数ではないので名前は変えたいです。 `_registerImageAssetIfNeeded()` とかですかね。
- `assets` は登録先でしょうし、それは `this` から常に求まるので、引数としては不要ではありませんか。このインスタンスに register するという処理なら、register 先を引数にとるのは不自然です。
  - 似たようなことは `revmap` にも言えるんですが、まあこちらは効率のためにいったん妥協するとしても (本当は `this._assetsRevMap` として `this` に抱えるべきかもしれないですが、改造がおおごとになりそうなので)
- 引数 `imageAssetDir` が 「image asset の」ディレクトリなのは自明ですし、逆に `f` は何をさしているのか不明確で気になります。この関数の I/F としては `imageAssetDir` と `f` をくっつけた `filePath: string` を受け取る方が自然ではありませんか。
  - `_assertAssetTypeNoConflict()` あたりで `f` 単体を使っていますが、これはエラーメッセージに含める用なので、ベースディレクトリまでくっついた `filePath` を渡しても実害ないと思います。

2020-06-17 07:46 UTC, ShinobuTakahashi commented on packages/akashic-cli-scan/src/Configuration.ts
> +	if (!/^[a-zA-Z_$:]{1}[0-9a-zA-Z_$:]*$/.test(name))
なるほど。ご指摘頂いた後者の"妥当なアセットID" と認識していました。修正しました。

2020-06-17 07:46 UTC, ShinobuTakahashi commented on packages/akashic-cli-scan/src/Configuration.ts
> +	_scanImageFile(f: string, imageAssetDir: string, assets: cmn.Assets, revmap: { [key: string]: string[] }): void {
`_registerXxxAsset()` へ関数名を修正、引数を修正しました。

2020-06-17 07:47 UTC, ShinobuTakahashi commented on packages/akashic-cli-scan/src/Configuration.ts
> +			!this._resolveAssetIdsFromPath && this._isAssetsDir(durationInfo.path) ? "hash" : this._assetIdResolveMode;
頂いたコメントの `↑の _resolveAssetIdsFromPath を~` を周辺の if 文の判定部分と認識してしまいました。
`_resolveAssetIdsFromPath` を廃止するよう修正しました。
ただ、`hash` だけは  assetsディレクトリのみ対象のため、コンストラクタ引数の `resolveAssetIdsFromPath` が false かつ対象が assets ディレクトリの場合となるため、scan処理の最後に実行される `scanAssetsDir()` の中で `hash` かを判定し設定しています。

2020-06-17 07:47 UTC, ShinobuTakahashi commented on packages/akashic-cli-scan/src/Configuration.ts
> +				if (!this._resolveAssetIdsFromPath) {
ありがとうございます。修正しました。

2020-06-17 07:47 UTC, ShinobuTakahashi commented on packages/akashic-cli-scan/src/Configuration.ts
> +	 * `assets:xxxxxx` の形式とする。
ありがとうございます。修正漏れていました...修正しました。

2020-06-18 02:41 UTC, xnv requested changes

2020-06-18 02:41 UTC, xnv commented on packages/akashic-cli-scan/src/Configuration.ts
> +				const revmap = cmn.Util.invertMap(this._content.assets, "path");
`revmap` を逐一作り直す必要はありますか？

2020-06-18 02:41 UTC, xnv commented on packages/akashic-cli-scan/src/Configuration.ts
> +			const revmap = cmn.Util.invertMap(this._content.assets, "path");
ここも。上のを流用できないのでしょうか。

2020-06-18 02:41 UTC, xnv commented on packages/akashic-cli-scan/src/Configuration.ts
> +			this._registerXXXAsset( path.join(dir, f), revmap, type);
不要な空白があります。

2020-06-18 02:41 UTC, xnv commented on packages/akashic-cli-scan/src/Configuration.ts
> +					this._registerXXXAsset( targetDir + "/" + path.basename(file), revmap, "script");
不要な空白があります。

2020-06-18 02:41 UTC, xnv commented on packages/akashic-cli-scan/src/Configuration.ts
> +			// scanAssets() で最後に実行されるため、assets ディレクトリでは mode が path でなければ mode を `hash` とする
そうか、こうなるんですね……。いったんこれでいいので、TODO として「 `_assetIdResolveMode` は引数として指定できるようにする」って書いておいてもらえませんか。

2020-06-18 03:19 UTC, ShinobuTakahashi commented on packages/akashic-cli-scan/src/Configuration.ts
> +				const revmap = cmn.Util.invertMap(this._content.assets, "path");
必要なかったです。ループの外へ出し修正しました。

2020-06-18 03:19 UTC, ShinobuTakahashi commented on packages/akashic-cli-scan/src/Configuration.ts
> +			const revmap = cmn.Util.invertMap(this._content.assets, "path");
修正しました。

2020-06-18 03:19 UTC, ShinobuTakahashi commented on packages/akashic-cli-scan/src/Configuration.ts
> +			this._registerXXXAsset( path.join(dir, f), revmap, type);
修正しました。

2020-06-18 03:19 UTC, ShinobuTakahashi commented on packages/akashic-cli-scan/src/Configuration.ts
> +					this._registerXXXAsset( targetDir + "/" + path.basename(file), revmap, "script");
修正しました。

2020-06-18 03:19 UTC, ShinobuTakahashi commented on packages/akashic-cli-scan/src/Configuration.ts
> +			// scanAssets() で最後に実行されるため、assets ディレクトリでは mode が path でなければ mode を `hash` とする
TODOコメント追加しました。

2020-06-19 02:51 UTC, xnv commented on packages/akashic-cli-scan/src/Configuration.ts
> +		return "asset:" + path.basename(hashPath, path.extname(filePath));
よく考えたらこれ既知の ID とかぶった時に避けるコードが欲しいですね……。
(revmap があるので、同じファイル名から一意な ID が出なくても大丈夫)

2020-06-19 03:54 UTC, ShinobuTakahashi commented on packages/akashic-cli-scan/src/Configuration.ts
> +		return "asset:" + path.basename(hashPath, path.extname(filePath));
生成する ID が既知の ID となる場合、生成を行わず既知の ID を返すよう修正しました。

2020-06-22 02:56 UTC, xnv commented on packages/akashic-cli-scan/src/Configuration.ts
> +		return "asset:" + path.basename(hashPath, path.extname(filePath));
あー、これはこれで必要かもしれないんですが、私が気にしたのは 「別のファイルパス (e.g. /assets/a.png と /assets/b.txt) でハッシュ値が一致する時」の対応です。普通のハッシュ値でそんな低確率な衝突は気にされませんが、ここだと頭 6 文字しか使ってないので、それよりはずっと衝突しやすいはずですよね。(現実的には頭 7 文字でも衝突を見たことはありませんが、これだとそれよりもさらに短いですし)

解法の一つは「6 文字と言わずハッシュ値全部アセット ID に含める」なんですけど、game.json の見た目がアレになりますし、そもそもここでは普通に衝突検査できるので「衝突したら末尾に1文字足して再チェック」みたいな処理を加えたいです。

2020-06-22 05:21 UTC, ShinobuTakahashi commented on packages/akashic-cli-scan/src/Configuration.ts
> +		return "asset:" + path.basename(hashPath, path.extname(filePath));
すいません、意図を読み違えていました。
別ファイルと生成するIDが衝突する場合、ファイルパスの末尾にランダムな1文字を追加しハッシュIDを生成するように修正しました。

2020-06-23 03:03 UTC, xnv commented on packages/akashic-cli-scan/src/Configuration.ts
> +	private isDuplicateHashId(filePath: string, hashId: string, revmap: { [key: string]: string[] }): boolean {
これ `revmap` じゃなくて game.json の `assets` 使えば `!!assets[hashId]` で一発で求まりませんか。

2020-06-24 02:10 UTC, ShinobuTakahashi commented on packages/akashic-cli-scan/src/Configuration.ts
> +	private isDuplicateHashId(filePath: string, hashId: string, revmap: { [key: string]: string[] }): boolean {
ありがとうございます。`!!assets[hashId] && assets[hashId].path !== filePath` とういう条件だけで問題ありませんでしたので、修正しました。

2020-06-25 02:56 UTC, xnv commented on packages/akashic-cli-scan/src/Configuration.ts
> +import { file } from "mock-fs";
使っていなさそう＋不要そうです。テストコードの残骸でしょうか。

2020-06-25 02:57 UTC, xnv approved these changes
コメント追加していますが approved.

2020-06-25 03:12 UTC, ShinobuTakahashi commented on packages/akashic-cli-scan/src/Configuration.ts
> +import { file } from "mock-fs";
すいません、削除しました。

2020-06-26 02:47 UTC, kamakiri01 approved these changes

2020-06-26 03:16 UTC, merged