Add preserveUnbundleScript parameter of export
akashic-games/akashic-cli pull request #341
Opened 2020-06-25 02:34 UTC by ShinobuTakahashi

## 概要

export-html, export-zip に `preserveUnbundleScript` の追加。

`preserveUnbundleScript` は export-html の `--atsumaru`, export-zipの `--bundle`  オプションが指定された場合、デフォルトではバンドルされない js ファイルは出力されず game.json からも削除されるが、`preserveUnbundleScript` が真の時にはバンドルされない js ファイルは出力され game.json にも残る動作となる。

2020-06-25 09:03 UTC, dera- approved these changes

2020-06-29 02:57 UTC, xnv requested changes

2020-06-29 02:57 UTC, xnv commented on packages/akashic-cli-commons/src/CliConfig/CliConfigExportHtml.ts
> +	preserveUnbundleScript?: boolean;
`Unbundled` にしたいです。(英語的にはそっちのが妥当だと思うので)

2020-06-29 03:40 UTC, ShinobuTakahashi commented on packages/akashic-cli-commons/src/CliConfig/CliConfigExportHtml.ts
> +	preserveUnbundleScript?: boolean;
`unbundled` へ修正しました。

2020-06-29 11:41 UTC, xnv commented on packages/akashic-cli-commons/src/CliConfig/CliConfigExportHtml.ts
> +	preserveUnbundleScript?: boolean;
ゔぇっごめんなさい、 `preserveUnbundledScript` にしたいのつもりでした……！ (別に unbundle/バンドルしない というオプションではないので)

2020-06-30 02:01 UTC, ShinobuTakahashi commented on packages/akashic-cli-commons/src/CliConfig/CliConfigExportHtml.ts
> +	preserveUnbundleScript?: boolean;
なるほどです。`preserveUnbundledScript` へ秀英しました。

2020-06-30 02:49 UTC, xnv approved these changes

2020-06-30 07:29 UTC, ShinobuTakahashi commented
https://github.com/akashic-games/akashic-cli/pull/342#discussion_r447379425 により `preserveUnbundledScript` から `omitUnbundledJs` へ変更

2020-06-30 09:09 UTC, merged