Support tree-shaking of export-zip
akashic-games/akashic-cli pull request #342
Opened 2020-06-25 02:50 UTC by ShinobuTakahashi

## 概要

export-zip の実行で `--bundle` オプションが指定された時、バンドルされなかったファイルの削除、game.json からの削除をデフォルト挙動とする。
`--bundle` に加え `--preserve-unbundle-script` オプションを指定する事により、バンドルされなかったファイルも出力・game.jsonに残る挙動となる。

2020-06-25 02:51 UTC, ShinobuTakahashi commented on packages/akashic-cli-export-zip/package.json
> +    "@akashic/akashic-cli-commons": "../akashic-cli-commons",
`akashic-cli-commons` を publish 後に修正し確認します。

2020-06-25 02:52 UTC, ShinobuTakahashi commented on packages/akashic-cli-export-zip/src/GameConfigurationUtil.ts
> +	return /^(script|assets)\/.+(\.js$)/.test(filePath);
`assets` ディレクトリにもjsファイルを置く事ができるようになるので対象とします

2020-06-25 09:03 UTC, dera- approved these changes
コメントしましたがapproveします

2020-06-25 09:03 UTC, dera- commented on packages/akashic-cli-export-zip/src/cli.ts
> +			preserveUnbundleScript: param.bundle ? param.preserveUnbundleScript : false,
意味は同じですが、`preserveUnbundleScript: param.bundle && param.preserveUnbundleScript` の方がシンプルかと思いました。

2020-06-25 10:27 UTC, ShinobuTakahashi commented on packages/akashic-cli-export-zip/src/cli.ts
> +			preserveUnbundleScript: param.bundle ? param.preserveUnbundleScript : false,
ありがとうございます。修正しました。

2020-06-30 03:01 UTC, xnv requested changes

2020-06-30 03:01 UTC, xnv commented on packages/akashic-cli-export-zip/src/convert.ts
> +							const regex = new RegExp(p);
動的に `new RegExp()` で組み立てる時はエスケープを考慮する必要があります。("shell.js" に  "shellyjs" や "shell2js" なんかがマッチしてしまう)　今回は moduleMainScripts は触らずそのまま残すでいいと思います。(あっても実害ないので)

2020-06-30 03:01 UTC, xnv commented on packages/akashic-cli-export-zip/src/convert.ts
> +							}
↓のコードに合わせて `return false` しませんか。

2020-06-30 03:01 UTC, xnv commented on packages/akashic-cli-export-zip/src/convert.ts
> +						return;
if のこっちのパスだと return するものの  else 側では  return せずに続行する、というの、フローが追いにくい感じがするので、これ独立した if にしませんか。 else if でなくても return してしまうので影響はないと思います。

2020-06-30 03:01 UTC, xnv commented on packages/akashic-cli-export-zip/src/cli.ts
> +			preserveUnbundledScript: commander["preserveUnbundledScript"] ?? conf.preserveUnbundledScript
別でオプション名色々書いたあとでめっちゃ申し訳ないんですけど、この並びで見たら `--no-omit-unbundled-js` とかのがいいですかね……？

2020-06-30 04:33 UTC, ShinobuTakahashi commented on packages/akashic-cli-export-zip/src/cli.ts
> +			preserveUnbundledScript: commander["preserveUnbundledScript"] ?? conf.preserveUnbundledScript
仰る通り、export-zip だと`--no-omit-unbundled-js` のほうが正しいと思います。
export-html も `--no-omit-unbundled-js` に合わせて修正し、commons 等の　`preserveUnbundledScript`を `omitUnbundleJs` へ修正します。

2020-06-30 04:33 UTC, ShinobuTakahashi commented on packages/akashic-cli-export-zip/src/convert.ts
> +						return;
独立いた if 文に修正しました。

2020-06-30 04:33 UTC, ShinobuTakahashi commented on packages/akashic-cli-export-zip/src/convert.ts
> +							}
`return false` へ修正しました。

2020-06-30 04:33 UTC, ShinobuTakahashi commented on packages/akashic-cli-export-zip/src/convert.ts
> +							const regex = new RegExp(p);
なるほど。 `moduleMainScripts` の箇所削除し修正しました。

2020-06-30 05:41 UTC, xnv commented on packages/akashic-cli-export-zip/src/cli.ts
> +			preserveUnbundledScript: commander["preserveUnbundledScript"] ?? conf.preserveUnbundledScript
すいません、二転三転で申し訳ないんですがではそれでお願いします。

2020-06-30 07:32 UTC, ShinobuTakahashi commented on packages/akashic-cli-export-zip/src/cli.ts
> +			preserveUnbundledScript: commander["preserveUnbundledScript"] ?? conf.preserveUnbundledScript
command option を `--no-omit-unbundled-js` へ、変数を `omitUnbundleJs`  へ export-html, commons と合わせて修正しました。

2020-06-30 08:01 UTC, xnv approved these changes

2020-07-01 02:42 UTC, merged