can download latest engine-files in akashic-serve
akashic-games/akashic-cli pull request #38
Opened 2019-03-03 07:37 UTC by dera-

### 概要
* akashi-cli-serveではakashic engine v2系にしか対応していないengineFilesを利用していました。そのため、akashic engine v1系のコンテンツがakashic serveで動かない状態でした。
* 本対応では、v1用とv2用のengineFilesを予め入れておいて、コンテンツによって使用するengineFilesを使い分けられるようにしました。
* v1用とv2用のそれぞれ最新のengineFilesをダウンロードしてくるスクリプトの作成

### やったこと
* engineFilesのバージョンを管理するファイルであるengineFilesVersion.jsonを新規作成
* engineFilesVersion.jsonの更新とビルド済みの最新のengineFilesを取得してくるスクリプトFilesAboutEngineFilesGenerator.jsを新規作成
  * これはnpm run copy:engine-files実行時に実行されるようにした
* getEngineConfigメソッドでコンテンツのgame.jsonを読み込んでv1系とv2系のどちらなのか 判定し、利用するengineFilesを決定するようにした

2019-03-03 07:39 UTC, dera- commented on packages/akashic-cli-serve/package.json
> +    "node-fetch": "~2.3.0",
プロダクトコードでnode-fetchを使うことにしたので、dependencies側に移しました

2019-03-03 07:40 UTC, dera- commented on packages/akashic-cli-serve/src/server/domain/EngineConfig.ts
> +				external: ["coe"], // TODO: game.json から取得するように
game.jsonから情報を取得するようにしたので、こちらも対応できそうなのですが、game.jsonのどの要素を見ればよろしいでしょうか？

2019-03-03 07:41 UTC, dera- commented on packages/akashic-cli-serve/src/server/domain/EngineConfig.ts
> +	const gameJsonUrl = `${baseUrl}/${gameContentDir}/game.json`;
v1系かv2系かを判断するためにコンテンツのgame.jsonを読み込むようにしましたが、もっと手軽にengineのバージョンを取得できる方法があれば教えていただきたいです

2019-03-03 07:43 UTC, dera- commented on packages/akashic-cli-serve/src/server/domain/EngineConfig.ts
> -	engine_configuration_version: string;
この要素は現状固定値だけ与えていて、利用していないので一旦削除することにしました。
ちなみに、この値は将来的に必要になりますでしょうか？もしそうであれば、消さずにTODOコメントを付けて残しておこうと思います

2019-03-04 08:23 UTC, yu-ogi requested changes

2019-03-04 08:23 UTC, yu-ogi commented on packages/akashic-cli-serve/build/FilesAboutEngineFilesGenerator.js
> +return Promise.resolve().then(() => {
こちらインデントがずれているようです。

2019-03-04 08:23 UTC, yu-ogi commented on packages/akashic-cli-serve/src/server/domain/EngineConfig.ts
> +			const version = json["environment"]["sandbox-runtime"] || "1";
古いコンテンツの場合 environment が存在しない場合もあるので、そのケアはしたいです。

2019-03-04 08:23 UTC, yu-ogi commented on packages/akashic-cli-serve/src/server/domain/EngineConfig.ts
> +	return fetch(gameJsonUrl, { method: "GET" })
リクエストのたびに `fetch` を介すのは少し気が引けますね。
キャッシュに保持したりはできないでしょうか。

2019-03-04 08:23 UTC, yu-ogi commented on packages/akashic-cli-serve/src/server/domain/EngineConfig.ts
> +			const engineFilesName = `engineFilesV${versionsJson[`v${version}`].replace(/\./g, "_")}.js`
素直に以下のような table を保持しておいたほうがわかりやすいように思えますがいかがでしょう。

```json
{
  "v1": "engineFilesV1_1_7.js",
  "v2": "engineFilesV2_1_10.js"
} 
```

2019-03-04 08:23 UTC, yu-ogi commented on packages/akashic-cli-serve/package.json
> +    "build": "npm run build:client && npm run build:server && shx cp ./src/server/engineFilesVersion.json ./lib/server",
`./src` 以下の静的なファイルを `./lib` ディレクトリにコピー、というのは直感に反しているように思えました。
以下のどちらかの方が望ましいと思いますがいかがでしょう。

- `/config/` あたりに `.json` ファイルとして格納しておく
- `.ts` ファイルとして TypeScript でコンパイルされることを前提とする

2019-03-04 11:54 UTC, dera- commented on packages/akashic-cli-serve/build/FilesAboutEngineFilesGenerator.js
> +return Promise.resolve().then(() => {
修正します

2019-03-04 11:55 UTC, dera- commented on packages/akashic-cli-serve/src/server/domain/EngineConfig.ts
> +			const version = json["environment"]["sandbox-runtime"] || "1";
あ、すっかり忘れてました。。こちらも対応します

2019-03-04 11:56 UTC, dera- commented on packages/akashic-cli-serve/src/server/domain/EngineConfig.ts
> +	return fetch(gameJsonUrl, { method: "GET" })
了解しました、キャッシュするよう修正してみます

2019-03-05 09:30 UTC, dera- commented on packages/akashic-cli-serve/package.json
> +    "build": "npm run build:client && npm run build:server && shx cp ./src/server/engineFilesVersion.json ./lib/server",
前者の方を試してみようかと思います。後者の方がtypescriptの世界で見れば健全な感じはしますがコンパイル前提のファイルを生成するのも微妙かと思いましたので。

2019-03-05 12:27 UTC, dera- commented on packages/akashic-cli-serve/src/server/domain/EngineConfig.ts
> +			const engineFilesName = `engineFilesV${versionsJson[`v${version}`].replace(/\./g, "_")}.js`
engineFilesVersion.jsonはここだけでなく、ビルドファイルの中で最新バージョンかどうかの比較(最新バージョンならダウンロードを省略)をするためにも使おうと思っていて、その比較をする時に今の形の方が比較しやすいのでできれば今の形で行きたいですね。いちいちファイル名に変換するのは少々手間ではありますが。。

2019-03-07 03:41 UTC, xnv requested changes

2019-03-07 03:41 UTC, xnv commented on packages/akashic-cli-serve/src/server/domain/EngineConfig.ts
> +	return fetch(gameJsonUrl, { method: "GET" })
どっちかというと `ScriptAssetController` と同じことだと思うので readFileSync して JSON.parse() する方が統一的なのではありませんか。(そちらではキャッシュはTODOになっていますが)

2019-03-07 03:41 UTC, xnv commented on packages/akashic-cli-serve/build/FilesAboutEngineFilesGenerator.js
> +			fileStream.on("finish", function() {
同じクロージャの文脈で function と => が混在しているのが気になります。どっちかにしませんか。

2019-03-07 03:41 UTC, xnv commented on packages/akashic-cli-serve/build/FilesAboutEngineFilesGenerator.js
> +	}).then(() => {console.log(`end to download engineFiles (v${version})`);});
ここで波括弧に空白開けないポリシー他であんまり使ってないと思いますし、そもそも式一つでいいので波括弧不要そうです。

2019-03-07 03:41 UTC, xnv commented on packages/akashic-cli-serve/package.json
> +    "node-fetch": "~2.3.0",
readFileSync するならこれは devDependencies で済むと思います。

2019-03-07 03:41 UTC, xnv commented on packages/akashic-cli-serve/package.json
> +    "@types/node-fetch": "~2.1.6",
これも。

2019-03-07 03:41 UTC, xnv commented on packages/akashic-cli-serve/src/server/domain/EngineConfig.ts
> +	const gameJsonUrl = `${baseUrl}/${gameContentDir}/game.json`;
これは不可避かと思います。(起動時に与えれば別ですけど、 game.json に書いてあるものを起動時にいちいち指定したくないですし)

2019-03-07 07:14 UTC, yu-ogi commented on packages/akashic-cli-serve/build/FilesAboutEngineFilesGenerator.js
> +var promises = updatedVersions.map(version => {
ここの `map()` は 上の `map()` と共通化できないでしょうか。

2019-03-07 07:14 UTC, yu-ogi commented on packages/akashic-cli-serve/src/server/domain/EngineConfig.ts
> +			cachedEngineFilesName = `engineFilesV${versionsJson[`v${version}`].replace(/\./g, "_")}.js`;
うーん、やはりこの `replace()` 処理が複数あるのが気になります。
現状はまだ2箇所だけですが、prerelease の動作確認などを考えると version と engineFiles の名前は独立していたほうが良さそうに思います。
例えばですが、engineFilesVersion.json の型を以下のような形式にするというのはいかがでしょう。

```json
{
  "v1": {
    "version": "1.1.7",
    "engineFileName": "engineFilesV1_1_7.js"
  },
  "v2": {
    "version": "2.1.11",
    "engineFileName": "engineFilesV2_1_11.js"
}
```

2019-03-10 08:22 UTC, dera- commented on packages/akashic-cli-serve/src/server/domain/EngineConfig.ts
> +			cachedEngineFilesName = `engineFilesV${versionsJson[`v${version}`].replace(/\./g, "_")}.js`;
了解しました。engineFilesVersion.jsonを以下のような形式に修正しました。
```
{
  "v1": {
    "version": "1.1.7",
    "fileName": "engineFilesV1_1_7.js"
  },
  "v2": {
    "version": "2.1.11",
    "fileName": "engineFilesV2_1_11.js"
}
```

2019-03-10 08:23 UTC, dera- commented on packages/akashic-cli-serve/build/FilesAboutEngineFilesGenerator.js
> +var promises = updatedVersions.map(version => {
共通化する方向に修正しました

2019-03-10 08:24 UTC, dera- commented on packages/akashic-cli-serve/package.json
> +    "node-fetch": "~2.3.0",
戻しました

2019-03-10 08:24 UTC, dera- commented on packages/akashic-cli-serve/src/server/domain/EngineConfig.ts
> +	const gameJsonUrl = `${baseUrl}/${gameContentDir}/game.json`;
なるほど、了解しました

2019-03-10 08:25 UTC, dera- commented on packages/akashic-cli-serve/src/server/domain/EngineConfig.ts
> +	return fetch(gameJsonUrl, { method: "GET" })
readFileSync 使う方に修正しました。また、キャッシュについては今回はTODOとさせていただきたいです

2019-03-10 08:26 UTC, dera- commented on packages/akashic-cli-serve/build/FilesAboutEngineFilesGenerator.js
> +			fileStream.on("finish", function() {
アローファンクションで統一しました

2019-03-10 08:28 UTC, dera- commented on packages/akashic-cli-serve/package.json
> +    "@types/node-fetch": "~2.1.6",
こちらは削除しました

2019-03-10 08:33 UTC, dera- commented on packages/akashic-cli-serve/build/FilesAboutEngineFilesGenerator.js
> +	}).then(() => {console.log(`end to download engineFiles (v${version})`);});
修正します

2019-03-11 01:55 UTC, yu-ogi approved these changes

2019-03-11 01:55 UTC, yu-ogi commented on packages/akashic-cli-serve/build/FilesAboutEngineFilesGenerator.js
> +	return Promise.resolve().then(() => {
`fetch(...).then()..` で次の promise につないでしまっても良いのではないでしょうか。

2019-03-11 12:15 UTC, dera- commented on packages/akashic-cli-serve/build/FilesAboutEngineFilesGenerator.js
> +	return Promise.resolve().then(() => {
確かにその方がシンプルですね。修正します

2019-03-15 05:01 UTC, xnv commented on packages/akashic-cli-serve/build/FilesAboutEngineFilesGenerator.js
> +		console.log("end to generate engineFilesVersion.json");})
ここ末尾さすがに改行しませんか。(Lisp ならこれスタンダードだと思いますけど、我々のリポジトリでこのスタイルの改行は他にないと思います。)

2019-03-15 05:02 UTC, xnv commented on packages/akashic-cli-serve/spec/server/SubscriberSpec.js
> +		xit("is sent from server, when access to create-play api", function(done) {
全体まとめて xdescribe でいいと思います。(というか他PRでやってるのでそれにしておく方が二重に x をつけなくて済むと思います。

2019-03-15 05:47 UTC, xnv approved these changes
コメントつけましたが approved.

2019-03-15 10:44 UTC, dera- commented on packages/akashic-cli-serve/build/FilesAboutEngineFilesGenerator.js
> +		console.log("end to generate engineFilesVersion.json");})
了解しました。こちら修正しました。

2019-03-15 10:44 UTC, dera- commented on packages/akashic-cli-serve/spec/server/SubscriberSpec.js
> +		xit("is sent from server, when access to create-play api", function(done) {
こちらも修正しました

2019-03-15 10:45 UTC, merged