investigation for TravisCi
akashic-games/akashic-cli pull request #386
Opened 2020-07-17 03:56 UTC by ShinobuTakahashi

ciの調査用

2020-07-21 02:08 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/spec/server/SocketIOAMFlowManagerSpec.js
> +				amflow1a.sendTick([2, [[0, 0x20, 1, "foo", {}]]]);
Tick の配列2番目は `Event[]` なので修正

2020-07-21 02:08 UTC, ShinobuTakahashi commented on .travis.yml
> +dist: bionic
`Ubuntu Bionic 18.04` に変更で、travisの実行時間が10分未満となったため `bionic` に変更

2020-07-21 02:08 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/package.json
> +    "@akashic/akashic-cli-commons": "0.5.17",
親のブランチ でコンフリクトしているので最新に修正

2020-07-21 07:00 UTC, xnv requested changes

2020-07-21 07:00 UTC, xnv commented on packages/akashic-cli-serve/spec/server/SocketIOAMFlowManagerSpec.js
> +				amflow1a.sendTick([2, [[0, 0x20, 1, "foo", {}]]]);
元コードも型があってないのでアレですが、 `Event` の中身にも型があって、突然先頭に 0 を追加しても型があいません (例えば第 0 要素はイベント種別 (0x20 は `MessageEvent`) だとか)。単に 0 を削りたいです。

2020-07-21 07:38 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/spec/server/SocketIOAMFlowManagerSpec.js
> +				amflow1a.sendTick([2, [[0, 0x20, 1, "foo", {}]]]);
修正しました。

2020-07-28 01:53 UTC, xnv approved these changes

2020-07-28 02:58 UTC, merged