feat:  npm script of zip in Akashic-cli-init
akashic-games/akashic-cli pull request #39
Opened 2019-03-05 04:39 UTC by ShinobuTakahashi

# このPullRequestが解決する内容
`Akashic-cli-init` の npm script の `zip:js`, `zip:ts` で作成する zipファイルのトップレベルに  `javascript` / `typescript` のディレクトリを含まないようコマンドを変更。
(解凍時、game.json等のファイルがトップレベルになる)

2019-03-06 10:56 UTC, xnv requested changes

2019-03-06 10:56 UTC, xnv commented on packages/akashic-cli-init/spec/downloadTemplateSpec.js
> +							"javascript",
この差分は何由来なのでしょうか……？　ここを直すなら他のテストも合わせて変わらないとまずいように思えます。

2019-03-06 10:56 UTC, xnv commented
一応: この変更は `feat` というよりは `fix` だと思います。

2019-03-08 02:44 UTC, ShinobuTakahashi commented on packages/akashic-cli-init/spec/downloadTemplateSpec.js
> +							"javascript",
すいません、ローカルにファイルが残っていたためにテストが通ってました。 
他部分も `javascript` のパスが正しいです。
tempディレクトリを作成し、そのディレクトリでテストを実施するよう修正しました。

2019-03-13 04:36 UTC, xnv approved these changes

2019-03-13 10:32 UTC, merged