add id to html dom in akashic-cli-serve
akashic-games/akashic-cli pull request #397
Opened 2020-07-22 05:54 UTC by dera-

### やったこと
* akashic-cli-serveのDOMにidを付与する対応を行いました。本対応で対象としたDOMは以下の通りです。
  * クリック時にイベントが発火するbuttonやinput等のDOM
  * GameScreenコンポーネントの各divタグ

2020-07-22 09:28 UTC, ShinobuTakahashi approved these changes

2020-07-27 04:39 UTC, xnv requested changes

2020-07-27 04:39 UTC, xnv commented on packages/akashic-cli-serve/src/client/view/molecule/EntityTreeOptionBar.tsx
> +				id="selectingEntity"
- よく考えるとこれ、 id つけちゃうと、このコンポーネントは複数存在できなくなりますね。(id は重複してはならないので。現実的にはブラウザは普通に表示しますが)
- この名前は CSS の style づけには使っていないこと、グローバルな名前にならざるをえない (他コンポーネントと衝突しうる) こと、そして何より事実上対外 API になってしまうことを考えると、もう少しロバスト (冗長でも衝突しにくい) な名前にしたいです。共通の接頭辞をつけるとか。
- class 名にあわせて `kebab-case` にしたいです。

……あたりの考えを総合して、class 名にして、 `external-ref_button_select-entity-from-screen` とかにするのはどうでしょう。 `external-ref` が「外部から参照する」目的のものに共通の接頭辞で。

2020-07-27 18:03 UTC, dera- commented on packages/akashic-cli-serve/src/client/view/molecule/EntityTreeOptionBar.tsx
> +				id="selectingEntity"
了解しました。複数存在しない想定のボタン等のDOMなのでidでも良いかと考えていたのですが、今後全く同じDOMを生成したくなる場面が出ないとも言い切れないですよね。そのように修正しておきます。

2020-07-28 01:07 UTC, dera- commented on packages/akashic-cli-serve/src/client/view/molecule/EntityTreeOptionBar.tsx
> +				id="selectingEntity"
すみません。。と思ったのですが、ToolIconButtonやToolLabelButtonには既にclass名が設定されていますね。。となると代わりに[dataset](https://developer.mozilla.org/ja/docs/Web/API/HTMLOrForeignElement/dataset)を利用するとかですかね？

2020-07-28 02:53 UTC, xnv commented on packages/akashic-cli-serve/src/client/view/molecule/EntityTreeOptionBar.tsx
> +				id="selectingEntity"
- CSS の仕様上、 class は空白区切りで複数指定できます。(それが class と id の最大の違いです)
- dataset が使えるならそれでいいんですが、 dataset の指定に応じて検索ってできるんですっけ……？　今回のケースは「要素に紐づけておいた値を取り出す」ではなく「紐づけた値に応じて要素を検索する」だと思いますが。

2020-07-28 05:30 UTC, dera- commented on packages/akashic-cli-serve/src/client/view/molecule/EntityTreeOptionBar.tsx
> +				id="selectingEntity"
なるほど、、ありがとうございます。では、ToolIconButtonやToolLabelButtonのpropsではidではなく追加のclass名(プロパティ名は`addtionalClassName`とかですかね)を受け取ってそのままclass名として利用しようと思います。
あー、datasetだと要素自体の検索は難しい気がしますね。。classを利用する方向で進めます

2020-07-29 05:47 UTC, xnv commented
よく考えると  README に書いておきたいですね。「利用方法」と「開発」の間あたりで、この className について言及しておきませんか。 `## 外部参照できる DOM 要素` というようなセクションを作り、自動テストのための仕様であることを断りつつ、テーブルで「`class` 名」と「要素 (e.g. 「"新規プレイ" ボタン」)」の対応関係を書いておくとか。

2020-07-29 05:47 UTC, xnv approved these changes
コメントつけていますが approved.

2020-07-30 11:34 UTC, merged