Add targetService Option
akashic-games/akashic-cli pull request #404
Opened 2020-07-29 01:54 UTC by ShinobuTakahashi

## 概要

オプションに `targetService` を追加します。
`targetService` の引数に `nicolive` が指定された場合、game.json の image アセットの hint に `{ untainted: true }`  を付与します。

2020-07-29 01:55 UTC, ShinobuTakahashi commented on packages/akashic-cli-export-zip/package.json
> +    "@akashic/akashic-cli-commons": "../akashic-cli-commons",
ローカルで確認しています。 `akashic/akashic-cli-commons` のpublish 後にバージョン指定して確認します。

2020-07-29 02:11 UTC, ShinobuTakahashi commented on packages/akashic-cli-export-zip/src/cli.ts
> +		`Simulate the specified service. arguments: ${Object.values(ServiceType)}`);
akashic-cli-serve では短縮オプションは `-s`  ですが、`--no-strip` で `-s` が使われているため、 `-t` にしています。
serve と合わないので、むしろ短縮オプションは無い方が良いでしょうか？

2020-07-29 04:22 UTC, dera- commented on packages/akashic-cli-export-zip/src/convert.ts
> +	targetService?: string;
ここでServiceType は利用できない感じでしょうか？

2020-07-29 04:24 UTC, dera- commented on packages/akashic-cli-export-zip/src/cli.ts
> +		if (commander["targetService"] && !Object.values(ServiceType).includes(commander["targetService"] as ServiceType)) {
キャストは利用しない方向で対応はできないでしょうか？それが難しければキャストが必要になる旨のコメントが欲しいです。

2020-07-29 05:22 UTC, ShinobuTakahashi commented on packages/akashic-cli-export-zip/src/cli.ts
> +		if (commander["targetService"] && !Object.values(ServiceType).includes(commander["targetService"] as ServiceType)) {
ここキャスト必要ありませんでしたので削除し修正しました。

2020-07-29 05:22 UTC, ShinobuTakahashi commented on packages/akashic-cli-export-zip/src/convert.ts
> +	targetService?: string;
`ServiceType` へ修正しました。 commander から受け取った時は string なので、`promiseExportZip()` に渡す時に `ServiceType` へキャストするようにしました。

2020-07-29 06:31 UTC, xnv requested changes

2020-07-29 06:31 UTC, xnv commented on packages/akashic-cli-export-zip/src/exportZip.ts
>  function _createExportInfo(param: ExportZipParameterObject): cmn.ExportZipInfo {
ここの戻り値に targetService の情報を反映したいです。

2020-07-29 06:31 UTC, xnv commented on packages/akashic-cli-export-zip/src/cli.ts
> +		`Simulate the specified service. arguments: ${Object.values(ServiceType)}`);
`--no-strip` は大文字 `S` ではありませんか？　とはいえ serve のように多用するわけでもないでしょうし、一旦短縮オプションなしでいいかなと思います。(増やすのはいつでもできますが変えると仕様変更なので)

2020-07-29 06:31 UTC, xnv commented on packages/akashic-cli-export-zip/src/ServiceType.ts
> +
不要な空行です。

2020-07-29 06:31 UTC, xnv commented on packages/akashic-cli-export-zip/src/ServiceType.ts
> + * nicolive: ニコ生互換のコンテンツとし、`{ untainted: true }` の hint を `image asset` につける
ServiceType はまず「対象の (コンテンツを実行する) サービス」ではないでしょうか。
そしてその `"nicolive"` の項の説明は「ニコニコ生放送」になると思います。(その上で、補足として hint の話があるのはいいと思うのですが)

2020-07-29 06:31 UTC, xnv commented on packages/akashic-cli-export-zip/src/cli.ts
> +		`Simulate the specified service. arguments: ${Object.values(ServiceType)}`);
simulate するというのは serve の説明だと思います。 ここでは `Specify the target service of the exported content` とかではありませんか。(具体的な動作を説明しにくくて悩ましいですが)

2020-07-29 07:20 UTC, ShinobuTakahashi commented on packages/akashic-cli-export-zip/src/cli.ts
> +		`Simulate the specified service. arguments: ${Object.values(ServiceType)}`);
承知しました。短縮オプション削除しました。

2020-07-29 07:21 UTC, ShinobuTakahashi commented on packages/akashic-cli-export-zip/src/ServiceType.ts
> +
削除しました。

2020-07-29 07:22 UTC, ShinobuTakahashi commented on packages/akashic-cli-export-zip/src/ServiceType.ts
> + * nicolive: ニコ生互換のコンテンツとし、`{ untainted: true }` の hint を `image asset` につける
コメント修正しました。

2020-07-29 07:22 UTC, ShinobuTakahashi commented on packages/akashic-cli-export-zip/src/cli.ts
> +		`Simulate the specified service. arguments: ${Object.values(ServiceType)}`);
ありがとうございます。修正漏れていました。

2020-07-29 07:22 UTC, ShinobuTakahashi commented on packages/akashic-cli-export-zip/src/exportZip.ts
>  function _createExportInfo(param: ExportZipParameterObject): cmn.ExportZipInfo {
`exportInfo` に `targetService` の情報を追加しました。この修正に伴い、akashic-cli-commons の `ExportZipInfo` に `targetService` を追加しました。 
https://github.com/akashic-games/akashic-cli/pull/403/commits/ec4e0b9412e3f6ec6a8a386d4a082d3037580b2f

2020-07-31 02:54 UTC, dera- approved these changes

2020-07-31 02:59 UTC, xnv approved these changes

2020-07-31 05:41 UTC, merged