check game.json update
akashic-games/akashic-cli pull request #43
Opened 2019-03-12 08:55 UTC by kamakiri01

## このpull requestが解決する内容

serveコマンドにおいて、実行中のgame.jsonのファイル更新を監視することで、
ランタイムなファイルアクセス数を削減します。

### 概要

## 破壊的な変更を含んでいるか?

- なし

2019-03-12 12:31 UTC, kamakiri01 commented on packages/.remarkrc
> +      "maximum-line-length": 1000,
自動更新される CHANGELOG.md が140文字に収まらないケースに対応するため、通常到達しない値まで上げます（デフォルトで80) https://github.com/remarkjs/remark-lint/tree/master/packages/remark-lint-maximum-line-length

2019-03-13 04:52 UTC, yu-ogi commented on packages/akashic-cli-serve/src/server/controller/ScriptAssetController.ts
> +		gameJson = JSON.parse(fs.readFileSync(gameJsonPath).toString());
不正な game.json の場合 `gameJson === undefined` になってしまい、L17 あたりでサーバ側が落ちてしまいそうな気がしました。
(監視をチェックするとなると入力途中の game.json が読み込まれる可能性も高まるため)

https://github.com/akashic-games/akashic-cli/blob/863e04e52ded819c60ec531be6348badbc877bbb/packages/akashic-cli-serve/src/server/controller/ScriptAssetController.ts#L17-L18

L17 の直前で `gameJson == null` であれば `next(e)` で例外を express に通知したほうが良いかなと思いましたがいかがでしょう。

2019-03-13 05:25 UTC, xnv requested changes

2019-03-13 05:25 UTC, xnv commented on packages/akashic-cli-serve/src/server/controller/ScriptAssetController.ts
> +		gameJson = JSON.parse(fs.readFileSync(gameJsonPath).toString());
ここで `JSON.parse()` 失敗したら `gameJson` は更新せず、 `console.warn()` あたりで「game.json の更新を検出したけど、パースできなかったからリロードしなかったよ」っていうメッセージを出しておくのが一番利便性が高そうですね。

2019-03-14 09:22 UTC, kamakiri01 commented on packages/akashic-cli-serve/src/server/controller/ScriptAssetController.ts
> +		gameJson = JSON.parse(fs.readFileSync(gameJsonPath).toString());
確かに、不正なgame.jsonのケースを考慮していませんでした。
提案頂いた方針で修正します。

2019-03-15 01:03 UTC, yu-ogi requested changes

2019-03-15 01:03 UTC, yu-ogi commented on packages/akashic-cli-serve/src/server/controller/ScriptAssetController.ts
> +        try {
インデントがずれています。

2019-03-15 01:03 UTC, yu-ogi commented on packages/akashic-cli-serve/src/server/controller/ScriptAssetController.ts
> +            console.warn("detected game.json updated but dit not reflect because parsing failed.");
ログ出力は他の箇所と合わせたいです。

https://github.com/akashic-games/akashic-cli/blob/6c993de4a30baa2bbb9b9ab03e61c7bf41456b6e/packages/akashic-cli-serve/src/server/controller/SandboxConfigController.ts#L17-L19

2019-03-15 03:15 UTC, yu-ogi approved these changes

2019-03-15 04:16 UTC, kamakiri01 commented on packages/akashic-cli-serve/src/server/controller/ScriptAssetController.ts
> +        try {
ありがとうございます、直します。

2019-03-15 04:16 UTC, kamakiri01 commented on packages/akashic-cli-serve/src/server/controller/ScriptAssetController.ts
> +            console.warn("detected game.json updated but dit not reflect because parsing failed.");
他の箇所のログ出力に揃えます。

2019-03-15 08:43 UTC, xnv approved these changes

2019-03-15 09:53 UTC, merged