Export html use SendEventName
akashic-games/akashic-cli pull request #458
Opened 2020-08-12 10:06 UTC by kamakiri01

## このpull requestが解決する内容

### 概要

https://github.com/akashic-games/akashic-cli/pull/146 を autoSendEventName に対応させます。
コマンドライン引数においては `--autoSendEventName` を `--autoSendEvents` に優先して扱い、sandbox.config.jsにおいてはautoSendEventNameのフォールバックとしてautoSendEventsを参照するようにします。

## 破壊的な変更を含んでいるか?

- なし

2020-08-12 10:14 UTC, kamakiri01 commented on packages/akashic-cli-export-html/src/app/cli.ts
> -		exclude: param.exclude,
PRの主旨ではありませんが、利用していないため削除します。

2020-08-19 06:13 UTC, xnv requested changes

2020-08-19 06:13 UTC, xnv commented on packages/akashic-cli-export-html/src/app/cli.ts
> +	.option("--auto-send-event-name [eventName]", "event name that send automatically when game start")
`-A` はこれにしてしまっていいのではないでしょうか。

2020-08-19 06:13 UTC, xnv commented on packages/akashic-cli-export-html/templates/template-export-html-v3/js/sandbox.js
> +			if (!autoSendEventName) autoSendEventName = (window.__akashic__.autoSendEventName === true) ? sandboxConfig.autoSendEvents : window.__akashic__.autoSendEvents;
これ必要でしょうか？　`autoSendEventName` への読み替えは HTML に出力する時点で 行われているので、二重な気がしています。(この sandbox.js が古いバージョンの akashic export html の出力と組み合わせられるのなら別ですが……)

2020-08-19 06:39 UTC, dera- commented on packages/akashic-cli-commons/src/CliConfig/CliConfigExportHtml.ts
>  	autoSendEvents?: string | boolean;
間違えていたらすみませんが、全体的に`autoSendEvents`は`autoSendEventName`に置き換えられているように見えるので、`autoSendEvents`も今回の変更で不要になるのではと思えました。

2020-08-19 07:35 UTC, kamakiri01 commented on packages/akashic-cli-commons/src/CliConfig/CliConfigExportHtml.ts
>  	autoSendEvents?: string | boolean;
ここの `autoSendEvents` はcli引数の定義なので、deprecatedでもまだ残っている `autoSendEvents` は残しておきたいです。

2020-08-19 07:35 UTC, kamakiri01 commented on packages/akashic-cli-export-html/templates/template-export-html-v3/js/sandbox.js
> +			if (!autoSendEventName) autoSendEventName = (window.__akashic__.autoSendEventName === true) ? sandboxConfig.autoSendEvents : window.__akashic__.autoSendEvents;
うっ確かに、出力html側の内部ではautoSendEventsは消すつもりでいるので、これは不要ですね。削除します。

2020-08-19 07:35 UTC, kamakiri01 commented on packages/akashic-cli-export-html/src/app/cli.ts
> +	.option("--auto-send-event-name [eventName]", "event name that send automatically when game start")
確かに。 `-A` も移します。

2020-08-19 08:09 UTC, kamakiri01 commented on packages/akashic-cli-export-html/templates/template-export-html-v3/js/sandbox.js
> +			if (!autoSendEventName) autoSendEventName = (window.__akashic__.autoSendEventName === true) ? sandboxConfig.autoSendEvents : window.__akashic__.autoSendEvents;
…と思ったのですが、「最新のexport htmlを使用している」「sandbox.config.jsはautoSendEvents記述を使っている」ケースでは `sandboxConfig.autoSendEvents` からイベント名を拾うことがあるように思います。

2020-08-20 04:48 UTC, xnv commented on packages/akashic-cli-export-html/templates/template-export-html-v3/js/sandbox.js
> +			if (!autoSendEventName) autoSendEventName = (window.__akashic__.autoSendEventName === true) ? sandboxConfig.autoSendEvents : window.__akashic__.autoSendEvents;
ああなるほど、 `autoSendEventName` が true だと、export 時点で名前を解決できないんですね……。
しかしであれば、 `window.__akashic__.autoSendEvents` はどこで設定されるんでしょうか？ (今回の差分で消えちゃっているような？)

2020-08-20 05:05 UTC, kamakiri01 commented on packages/akashic-cli-export-html/templates/template-export-html-v3/js/sandbox.js
> +			if (!autoSendEventName) autoSendEventName = (window.__akashic__.autoSendEventName === true) ? sandboxConfig.autoSendEvents : window.__akashic__.autoSendEvents;
確かに、 `window.__akashic__.autoSendEvents ` はバンドルされなくなるので拾いにいく必要はないですね。このケースは削除して、 `sandboxConfig.autoSendEvents` があればフォールバックにするようにしようと思います。

2020-08-24 03:37 UTC, dera- approved these changes

2020-08-24 08:13 UTC, xnv commented on packages/akashic-cli-export-html/templates/template-export-html-v3/js/sandbox.js
> +			if (!autoSendEventName && window.__akashic__.autoSendEventName === true) autoSendEventName = sandboxConfig.autoSendEvents;
よさそうな気がしますが、前の行と部分的に条件が重複していて難解なので、次のように整理するのはどうでしょう？

```
var autoSendEventName = window.__akashic__.autoSendEventName;
if (autoSendEventName === true) {
  autoSendEventName = sandboxConfig.autoSendEventName || sandboxConfig.autoSendEvents;
}
```

2020-08-24 08:14 UTC, xnv approved these changes

2020-08-24 08:14 UTC, xnv commented
コメント加えましたが approed.

2020-08-24 11:02 UTC, merged