feat: Support coe plugin (non local session) experimentally
akashic-games/akashic-cli pull request #46
Opened 2019-03-15 02:42 UTC by yu-ogi

## このPullRequestが解決する内容
- 非ローカルの coe-plugin の実装
- プレー親子関係APIの新設
- サーバ上で動作している Runner の取得APIの新設

2019-03-15 04:32 UTC, yu-ogi commented on packages/akashic-cli-serve/src/client/operator/Operator.ts
> +		const pooling = () => {
headless-driver 側の改修予定です。

2019-03-15 04:32 UTC, yu-ogi commented on packages/akashic-cli-serve/src/client/akashic/GameViewManager.ts
> +			// customGameConfig.gameLoaderCustomizer.platformCustomizer = this.customizePlatform;
現状複数コンテンツのホスティングに対応していないため、コメントアウトしています。

2019-03-15 04:32 UTC, yu-ogi commented on packages/akashic-cli-serve/src/server/domain/SocketIOAMFlowManager.ts
> +					if (this.playStore.getPlay(conn.playId) != null) {
headless-driver 側で、すでに終了しているプレーに紐付いている `AMFLow#close()` を呼んでしまうとエラーが発生するという問題が発覚しました。

2019-03-15 04:32 UTC, yu-ogi commented on packages/akashic-cli-serve/src/server/route/ApiRoute.ts
> +	apiRouter.get("/play/child", createHandlerToGetPlayTree(params.playTreeStore));
`child` -> `children` のほうが適切に思えますが、全体的に単数形なのでそれに合わせています。

2019-03-15 08:57 UTC, xnv commented on packages/akashic-cli-serve/src/server/route/ApiRoute.ts
> +	apiRouter.get("/play/child", createHandlerToGetPlayTree(params.playTreeStore));
これ全体的に複数形に直すつもりなので、合わせずに複数形にしちゃってほしいです。

 (REST API のデザインとしては全部複数形にするのがベストプラクティスとされていたりするようなので、単数と複数が入り混じってる現状は割と異端だと思います。 参考: 「REST API best practices」でぐぐったトップヒット: https://blog.florimondmanca.com/restful-api-design-13-best-practices-to-make-your-users-happy )

2019-03-18 04:23 UTC, xnv requested changes

2019-03-18 04:23 UTC, xnv commented on packages/akashic-cli-serve/src/server/domain/SocketIOAMFlowManager.ts
> +					if (this.playStore.getPlay(conn.playId) != null) {
別で議論しましたが、これは AMFlow 実装の側が吸収すべきことに思えます。(play が終了すると実体が完全に消えて操作できなくなるのは headless-driver の内側の話なので、ここでは終了していようが close() できるべき)

headless-driver 側の対応までの暫定処理なら、その旨 TODO コメントがほしいです。

2019-03-18 04:23 UTC, xnv commented on packages/akashic-cli-serve/src/server/domain/PlayTreeStore.ts
> +	hasChildren(childId: string): boolean {
- 呼び出し箇所がなさそうですが、必要でしょうか。
- 必要だとして、実装を見る限りではこのメソッドは `hasGrandChild()` に思えます。

2019-03-18 04:23 UTC, xnv commented on packages/akashic-cli-serve/src/server/domain/PlayTreeStore.ts
> +	searchChild(childId: string): PlayTree | null {
子/child と 子孫/descendant を区別したいです。 `hasChild()` に倣えばこれは `hasDescendant()` ではありませんか。  (もっと言うと自身も検索対象に含めているので `isSelfOrDescendant()` とでも呼ぶ方が厳格な気もしますが、そこまでやるかはともかくとしても)

2019-03-18 04:23 UTC, xnv commented on packages/akashic-cli-serve/src/server/domain/PlayTreeStore.ts
> +	hasChild(childId: string): boolean {
`hasChildren()` (呼び出し箇所が見当たらない) からしか呼ばれていなそうです。必要でしょうか。

2019-03-18 04:23 UTC, xnv commented on packages/akashic-cli-serve/src/server/domain/PlayTreeStore.ts
> +	toString(): string {
デバッグ用でしょうか。この処理だとほとんど意味のある情報になりそうにない (ツリー構造に依存して 0 個以上の `,` が連続した文字列が出そうに見えます) ので、master に入れるなら情報量をもたせたいですし、でなければ単に削除したいです。

2019-03-18 04:23 UTC, xnv commented on packages/akashic-cli-serve/src/server/domain/PlayTreeStore.ts
> +			this.playTree[i].removeChild(playId);
ルート play 群の直下の子しか削除できそうにありませんが、根本的にそうあるべきものなのでなければ最低限「簡易実装である」旨のコメントがほしいです。

2019-03-18 04:23 UTC, xnv commented on packages/akashic-cli-serve/src/server/domain/PlayTreeStore.ts
> +			parent = this.playTree[i].searchChild(playId);
あらゆる処理でループ回して `searchChild()` をしていますが、そもそも直接ツリー構造で持つよりも、二次元のテーブルチックに `PlayTreeStore#childrenList: { [playId: string]: string[] }` で持った方が手っ取り早くありませんか。

まあ正味なところこの箇所は10000のプレイを管理するわけでも20段の親子関係を扱うわけでもないので、別にこのブルートフォースな実装でも実害は薄いんですが、簡易実装なら簡易実装としてコメントがほしいです。

2019-03-18 09:08 UTC, yu-ogi commented on packages/akashic-cli-serve/src/server/domain/PlayTreeStore.ts
> +			parent = this.playTree[i].searchChild(playId);
API の仕様的に高々親子関係までしか利用されないはずなので、このPullRequestはこの実装のまま進めてしまおうと思います。
ただどちらにせよ `PlayTreeStore` 単体で見たら簡易実装なのは変わりないので、その旨をコメントしておきます。

2019-03-18 09:10 UTC, yu-ogi commented on packages/akashic-cli-serve/src/server/domain/PlayTreeStore.ts
> +			this.playTree[i].removeChild(playId);
API の仕様的に高々親子関係までしか利用されないはずなので、このPullRequestはこの実装のまま進めてしまおうと思います。
ただどちらにせよ `PlayTreeStore` 単体で見たら簡易実装なのは変わりないので、その旨をコメントしておきます。

2019-03-18 09:17 UTC, yu-ogi commented on packages/akashic-cli-serve/src/server/domain/PlayTreeStore.ts
> +			parent = this.playTree[i].searchChild(playId);
1. 子プレーを追加/削除
2. プレーツリーを取得

のどちらかでプレーツリーの再構築をする必要があり、2. より 1. のほうが呼び出し回数が少ないだろうという推測からツリー構造を直接いじるようにしています。
簡易実装であることには変わりないのでコメントしておきます。

2019-03-18 09:45 UTC, yu-ogi commented on packages/akashic-cli-serve/src/server/domain/SocketIOAMFlowManager.ts
> +					if (this.playStore.getPlay(conn.playId) != null) {
https://github.com/akashic-games/akashic-cli/pull/46/commits/724125f7426dd36be66437a3f97e3d3bb69937e2 こちらコメント追加しました。

2019-03-18 09:46 UTC, yu-ogi commented on packages/akashic-cli-serve/src/server/route/ApiRoute.ts
> +	apiRouter.get("/play/child", createHandlerToGetPlayTree(params.playTreeStore));
https://github.com/akashic-games/akashic-cli/pull/46/commits/392298f25f5d8003e31acc4fdf3fe74860c411bb 対応しました。

2019-03-18 09:46 UTC, yu-ogi commented on packages/akashic-cli-serve/src/server/domain/PlayTreeStore.ts
> +	hasChildren(childId: string): boolean {
こちら削除しました。

2019-03-18 09:46 UTC, yu-ogi commented on packages/akashic-cli-serve/src/server/domain/PlayTreeStore.ts
> +	searchChild(childId: string): PlayTree | null {
こちらは `hasDescendant()` にリネームいたしました。

2019-03-18 09:47 UTC, yu-ogi commented on packages/akashic-cli-serve/src/server/domain/PlayTreeStore.ts
> +	toString(): string {
こちらも削除しました。

2019-03-18 09:47 UTC, yu-ogi commented on packages/akashic-cli-serve/src/server/domain/PlayTreeStore.ts
> +	hasChild(childId: string): boolean {
こちらも削除しました。

2019-04-19 06:59 UTC, xnv commented
#69 でまとめて coe-ui ブランチに取り込んだのでこの PR はクローズします。

2019-04-19 06:59 UTC, closed without merging