write environtment when install from akashic-lib.json
akashic-games/akashic-cli pull request #469
Opened 2020-08-19 11:23 UTC by kamakiri01

## このpull requestが解決する内容

### 概要

`akashic install` コマンドでパッケージをインストールしたとき、そのパッケージに `akashic-lib.json` が含まれていた場合、その内容を `game.json` の `environment` に転写します。

## 破壊的な変更を含んでいるか?

- なし

2020-08-21 03:00 UTC, kamakiri01 commented on packages/akashic-cli-install/package.json
> +    "deepmerge": "^4.2.2",
environmentの `{}` ネストの深さが不定なので、 deep merge用に外部ライブラリを使います。

2020-08-24 04:31 UTC, kamakiri01 commented on packages/akashic-cli-install/src/install.ts
> +								content.environment = deepmerge(content.environment || {}, libJsonData.gameJson.environment);
uninstall時に消すべき要素を特定する方法が無いので、追加するだけの挙動にしています。

2020-08-24 05:29 UTC, yu-ogi reviewed
背景を読み取れきれていなくて恐縮ですが、気になった点をコメントしました。

2020-08-24 05:29 UTC, yu-ogi commented on packages/akashic-cli-install/src/install.ts
> +								content.environment = deepmerge(content.environment || {}, libJsonData.gameJson.environment);
* うーん、その仕様は流石に許容できないように思います。あくまで一案ですが「インストール/アンインストール後に全てのモジュールの "akashic-lib.json" を走査して environment を更新する」という対応が必要そうに思います。
  * ただその場合「コンテンツ自体のベースとなる environment 値」と、それをベースとした merge 後の値を明確に区別する必要がありそうです。
* こちら `environment` 全体を merge してしまっても大丈夫なのでしょうか。例えば、v2 のコンテンツに間違って v3 のライブラリをインストールしてしまったら game.json の environment["sandbox-runtime"] の値が "3" に上書きされてしまいそうです。
  * environment の中から許可リスト的な形で「マージする必要のあるプロパティ」と「マージする必要のないプロパティ」をロジックで区別する必要があるように思いました。

2020-08-27 03:01 UTC, xnv commented on packages/akashic-cli-install/package.json
> +    "deepmerge": "^4.2.2",
(environment.external を扱うことに関しては、深さは 1 なので不要かと思います。)

2020-08-28 01:08 UTC, yu-ogi commented on packages/akashic-cli-install/src/install.ts
> +							const libJsonData = JSON.parse(fs.readFileSync(libPath, "utf8"));
こちら型を付けておきたいです。

2020-08-28 01:08 UTC, yu-ogi commented on packages/akashic-cli-install/src/install.ts
> +							if (error.code === "ENOENT") return; // akashic-lib.jsonを持っていないケース
(imo) こちら `accessSync()` を利用している理由って何でしょう?
個人的には単に boolean を返す `existsSync()` の方が簡潔かなと思いました。

```javascript
if (!fs.existsSync(...)) {
  return; // akashic-lib.json が存在しない
}
```

2020-08-28 01:08 UTC, yu-ogi commented on packages/akashic-cli-install/src/install.ts
> +								content.environment.external[libJsonData.gameJson.environment.external.name] = libJsonData.gameJson.environment.external.version;
`content` のプロパティを直接いじるのは正攻法なのでしょうか。他の箇所は `conf` のメソッドまたは `conf._content` を利用しているようです。

2020-08-28 01:08 UTC, yu-ogi commented on packages/akashic-cli-uninstall/src/uninstall.ts
> +								content.environment.external[libJsonData.gameJson.environment.external.name] = undefined;
* L87 で conf を書き込んだ後に更に conf の書き換え処理を行っているのに違和感があります。この処理は L87 より前に行ったほうが自然なように思いました。
* `undefined` を代入するよりも `delete` でプロパティを消してしまったほうがわかりやすいかと思いました。(JSON に `undefined` は定義されていないはずなので)
* ここでアンインストールしたライブラリのと同様の environment.external をインストール元のコンテンツが持っていた場合、この箇所で消えてしまうように思いますが、それは仕様という形になるのでしょうか。
   * 根本解決が難しそうですが、自分自身の `"akashic-lib.json"` を参照するなどの対応が必要そう?

2020-09-01 03:01 UTC, kamakiri01 commented on packages/akashic-cli-install/src/install.ts
> +							const libJsonData = JSON.parse(fs.readFileSync(libPath, "utf8"));
追加します。

2020-09-01 03:01 UTC, kamakiri01 commented on packages/akashic-cli-install/src/install.ts
> +								content.environment.external[libJsonData.gameJson.environment.external.name] = libJsonData.gameJson.environment.external.version;
確かに… `Configuration#addExternal()` を経由させます。

2020-09-01 03:02 UTC, kamakiri01 commented on packages/akashic-cli-install/src/install.ts
> +							if (error.code === "ENOENT") return; // akashic-lib.jsonを持っていないケース
akashic-cli では `accessSync()` と `exitsSync()` が混在していそうです。
cli-commonsでtry-catchとaccessSyncを使っているので、これに倣っています。

どちらを使いたいという強いモチベ―ションはないですが、ENOENT以外をthrowで拾えるケースはあるかな、ぐらいです。

2020-09-01 03:02 UTC, kamakiri01 commented on packages/akashic-cli-uninstall/src/uninstall.ts
> +								content.environment.external[libJsonData.gameJson.environment.external.name] = undefined;
- そもそもwrite後にcontent書き換えしてもjsonファイルに反映されないですね…writeは次のthenで処理するようにします。
- uninstall時に正しい状態を推定するのは難しいところですが…仕様化されていないもののユースケース実態としてexternalに追加される要素名はライブラリと1:1対応をしているので、externalのみを操作する場合は単純な追記/削除でカバーできそうです。environment全体をカバーするには、node_modules以下の `akashic-lib.json` すべてを参照するなどの処理が必要だと思います。

2020-09-01 05:48 UTC, yu-ogi commented on packages/akashic-cli-install/src/install.ts
> +							if (error.code === "ENOENT") return; // akashic-lib.jsonを持っていないケース
いえ、try catch 自体を消してしまうというような意味ではありませんでした。 `JSON.parse()` があるのでむしろ try catch は必須かと思います。
単に「エラーを発生させる→try catch で特定のエラーを判断する」という流れがわかりづらく見えたので上記のようにすれば意図がわかりやすいかなと思っただけです。

2020-09-01 05:53 UTC, yu-ogi commented on packages/akashic-cli-uninstall/src/uninstall.ts
> +								content.environment.external[libJsonData.gameJson.environment.external.name] = undefined;
なるほど、ありがとうございます。

> 仕様化されていないもののユースケース実態としてexternalに追加される要素名はライブラリと1:1対応をしているので、externalのみを操作する場合は単純な追記/削除でカバーできそう

この部分はソース内でコメントしておきたい気がします。

2020-09-01 05:56 UTC, yu-ogi commented on packages/akashic-cli-install/src/install.ts
> +							if (error.code === "ENOENT") return; // akashic-lib.jsonを持っていないケース
とはいえ他の箇所と合わせている&個人的な意見ということで理解しました。

2020-09-01 05:59 UTC, yu-ogi approved these changes
https://github.com/akashic-games/akashic-cli/pull/469#discussion_r480847732 だけ気になりましたが approved です。

2020-09-02 07:50 UTC, xnv requested changes

2020-09-02 07:50 UTC, xnv commented on packages/akashic-cli-install/src/install.ts
> +						const libPath = path.resolve(".", name, "akashic-lib.json");
- これってどこにある想定なんですかね……？　 `.` はゲームのあるディレクトリではないかと思いますが、そこにこのファイルがありそうな気はしないような。
- それはそれとして `param.moduleName` には「(npm pack された) ローカルの tgz ファイルのパス」がくることがあり、現状では動かないと思います。対応は TODO としてもいいんですが、 当該ケースで警告メッセージを出すぐらいの対応はしておきたいです。
  - 参考: https://github.com/akashic-games/akashic-cli/pull/469/files#diff-79cf7efad1109f2e5a71e0359445c6baR95-R99

2020-09-02 07:50 UTC, xnv commented on packages/akashic-cli-commons/src/LibConfiguration.ts
> +	gameJson: LibGameJson;
あまりイメージ共有できてなかったのですが、 `gameJson` プロパティはなしでこの直下に `environment` が来るようにしませんか。game.json と共通に扱える部分は対称にしておく方が扱いやすい気がします。

2020-09-02 07:50 UTC, xnv commented on packages/akashic-cli-install/src/install.ts
> +							if (error.code === "ENOENT") return; // akashic-lib.jsonを持っていないケース
どのみちなければ `readFileSync()` で失敗するので、 `accessSync()` でも `existsSync()` でも不要だったりしませんか。

2020-09-08 08:53 UTC, kamakiri01 commented on packages/akashic-cli-commons/src/LibConfiguration.ts
> +	gameJson: LibGameJson;
gameJsonの構造にそのまま載せられない情報が将来追加される場合がありそうな気がしたので1階層分けましたが、必要ないでしょうか。

2020-09-08 08:53 UTC, kamakiri01 commented on packages/akashic-cli-install/src/install.ts
> +						const libPath = path.resolve(".", name, "akashic-lib.json");
- `./node_modules/${xxx}/akashic-lib.json` から取得を試みるようにします。
- tgzを与えられた際のメッセージを追加します。

2020-09-08 08:53 UTC, kamakiri01 commented on packages/akashic-cli-install/src/install.ts
> +							if (error.code === "ENOENT") return; // akashic-lib.jsonを持っていないケース
確かに…accessチェック後に何か処理するわけでもないので、そのままreadFileSyncで良さそうです。

2020-09-08 08:53 UTC, kamakiri01 commented on packages/akashic-cli-install/package.json
> +    "deepmerge": "^4.2.2",
不要になったので削除しました。

2020-09-10 00:34 UTC, xnv commented on packages/akashic-cli-commons/src/LibConfiguration.ts
> +	gameJson: LibGameJson;
その時は game.json の型と akashic-lib.json の型に違いが出ればよいのでは。

まず、 akashic-lib.json が game.json を一式抱えるようなことはないと思っています。たとえば akashic-lib.json の中に `width: number` や `fps: number` のフィールドを持つことはなさそうです。その意味で、まるで game.json 全体を抱えられるに見える `gameJson` というプロパティ名にはちょっと違和感があります。

またこれはさほど決定的な要因ではありませんが、 game.json と同型にできる部分はしておいた方が、たとえば `akashic scan assets` の実装がほぼそのままライブラリ開発でも流用できるのではないか、という目論見もあります。

`gameJson` プロパティを独立させておくメリットがあるとしたら、「game.json のプロパティと同名でありながら違う型違う用途を持つプロパティを akashic-lib.json に持たせたくなった時」だと思いますが、あまり差し迫った話にも思えず、それはその時考えればよいのでは、という気分でいます。

2020-09-10 01:14 UTC, xnv requested changes

2020-09-10 01:14 UTC, xnv commented on packages/akashic-cli-install/src/install.ts
> +						if (path.extname(name) === ".tgz") {
`installedModuleNames` を使えばこのケースはないのではありませんか。

2020-09-10 01:14 UTC, xnv commented on packages/akashic-cli-commons/src/LibConfiguration.ts
> +	external?: { name: string, version: string };
型は `{ [name: string]: string }` でお願いしたいです。 game.json がそうなっています。(これはやめたいというコメントを別で書いていますが、 `gameJson` というプロパティで中身がそれと違う型なのは流石に苦しい気がします。)

(もしかして私の別の場所での発言が誤解を招いたかもしれませんが、私が述べたのは「特定の name を挙げるライブラリは現状 name ごとに一つしかないと想定できる」であって、「特定のライブラリが挙げる name は一つしかない」ではないです)

2020-09-10 01:14 UTC, xnv commented on packages/akashic-cli-install/src/install.ts
> +								conf.addExternal(libJsonData.gameJson.environment.external.name, libJsonData.gameJson.environment.external.version);
(imo) この箇所のコードはまだ変わると思いますが、現状に関して言うと `libJsonData.gameJson.environment` が多すぎるので、一度変数に入れておく方が可読性が高い気がします。

2020-09-15 10:34 UTC, kamakiri01 commented on packages/akashic-cli-commons/src/LibConfiguration.ts
> +	external?: { name: string, version: string };
`{ [name: string]: string }` に直します。

2020-09-15 10:34 UTC, kamakiri01 commented on packages/akashic-cli-install/src/install.ts
> +								conf.addExternal(libJsonData.gameJson.environment.external.name, libJsonData.gameJson.environment.external.version);
整理します。

2020-09-15 10:34 UTC, kamakiri01 commented on packages/akashic-cli-install/src/install.ts
> +						if (path.extname(name) === ".tgz") {
うっ確かに。直します。

2020-09-15 10:34 UTC, kamakiri01 commented on packages/akashic-cli-commons/src/LibConfiguration.ts
> +	gameJson: LibGameJson;
> akashic-lib.json が game.json を一式抱えるようなことはないと思っています。
はい、これはそうで、 `LibGameJson` 型は `GameConfiguration` 型（game.jsonの定義）とは独立して定義しています。 `LibGameJson` 型は game.json のプロパティのうち、 akashic-lib.json で必要になるプロパティだけを定義すれば良いと思います。

個人的には、 akashic-lib.json は「そのライブラリをakashicコンテンツに取り込む際、 game.json のenvironment追記に留まらない処理が必要なとき、それを記述する場所」としても使うと考えています（将来の話になりますが…）
それらの記述は、 akashic-lib.json の中では game.json 由来のプロパティとは階層を分けておく方が良いのではないか、と思っています。

`LibGameJson` のプロパティ名が gameJson であることには強いこだわりはないです。 akashic-lib.json の中で game.json （由来）のプロパティを1つのオブジェクトにまとめておけば、後から上記の使い方をする際に追加が容易ですが、同型にした構造を後から変えるのは破壊的変更になるので、予め分けておきたい、という気持ちがあります。

2020-09-16 10:23 UTC, xnv commented on packages/akashic-cli-commons/src/LibConfiguration.ts
> +	gameJson: LibGameJson;
別で議論させていただき、イメージ図こんな感じで `gameConfigurationData` と呼ぶのはどうかという話になりました。

```json
{
   "gameConfigurationData": {
     "environment": {
       "external": { "foobar": "1" }
     },
     "assets": {
       "ok_se": { type: "audio", ... }
     }
   },
   "requiredRuntime": "3.2.0",
   "scripts": {
     "postinstall": "./scripts/postinstall.js"
   }
}
```

2020-09-16 13:03 UTC, kamakiri01 commented on packages/akashic-cli-commons/src/LibConfiguration.ts
> +	gameJson: LibGameJson;
反映します。

2020-09-23 08:15 UTC, xnv approved these changes

2020-09-25 03:11 UTC, merged