unify player id in akashic-cli-serve
akashic-games/akashic-cli pull request #489
Opened 2020-09-09 15:33 UTC by dera-

### 概要
今までplayerIdが`Data.now()`の値になっていて一意に定まらなかったので一意に定まるように修正

### やったこと
* サーバー側にプレイヤーを登録するAPIの追加
* クライアント側でプレイヤーIDの登録時に新規追加のAPIを叩くように修正

### 疑問点
* プレイヤーID重複時の仕様について
  * 今はその場合重複したままサーバー側に登録する仕様にしている(今は無いがサーバー側にプレイヤー登録解除処理が必要になった場合こちらの仕様の方がクライアント側の実装コスト的に楽なので)が、重複を許さない仕様に変えるべきか？
* プレイIDが生成されてからプレイヤーIDの登録という手順にしているが、それでよいか？
  * プレイヤーIDはプレイID毎に用意するものという考えからそのようにしました。

2020-09-09 15:35 UTC, dera- commented on packages/akashic-cli-serve/src/client/store/Store.ts
> +		this.player = null;
プレイヤーID等はサーバーに問い合わせないと分からない仕様に変わったので、初期値はnullに変更しました

2020-09-09 15:37 UTC, dera- commented on packages/akashic-cli-serve/src/client/store/storage.ts
> +	// メソッド名これでよいのか不明
本来コメントでアウトではなく、ここに書くべきものでした。後で消しておきます。
ただ、ここにも書いたようにメソッド名がこれでよいのか疑問(実態に即した名前になっていない気がしました)なので、他に良いメソッド名があれば教えていただけると助かります。:bow:

2020-09-09 15:39 UTC, dera- commented on packages/akashic-cli-serve/src/common/types/Player.ts
> +	isJoined?: boolean;
PlayStoreのところでも説明していますが、PlayStoreにすでに`joinedPlayer`というものがあったのでまとめるためにこのプロパティを追加しました。プレイヤーの状態を表すものとしてここに置いても不自然は無いのではと思ってます

2020-09-09 15:42 UTC, dera- commented on packages/akashic-cli-serve/src/server/domain/PlayStore.ts
> +			players: [],
当初は`joinedPlayers`とは別にプレイヤーIDを管理しようと思ったのですが、よく考えたらどちらも同じものなので`players`にまとめられると判断してこのように修正しました

2020-09-09 15:46 UTC, dera- commented on packages/akashic-cli-serve/src/server/domain/PlayStore.ts
> +	// unregisterも用意すべきか？
こちらもコメントアウトではなくここに書くべきものなので、あとで消しておきます。
特にクライアント側にプレイヤーの登録解除に相当する処理がないので、登録解除的処理は用意しなかったのですが必要であれば追加します。

2020-09-09 15:50 UTC, dera- commented on packages/akashic-cli-serve/src/client/store/storage.ts
> +	getSessionData(): any {
anyを返すのが若干微妙ですが、既存の処理をそのままメソッドに切り出した結果このようになった感じです。問題があればセッションに保存するデータ用のインターフェースを用意しようと思いますが、変更頻度が高そうなインターフェースになりそうなので個人的にはあまり気乗りはしていないです。

2020-09-10 13:50 UTC, dera- commented on packages/akashic-cli-serve/src/client/bootstrap.tsx
> -import { ClientContentLocator } from "./common/ClientContentLocator";
使用されて無いようでしたので削除しました

2020-09-10 14:10 UTC, dera- commented on packages/akashic-cli-serve/src/server/domain/PlayerStore.ts
> +		const playerName: string = player.name || "player" + playerId;
"player~~"というユーザー名は今までクライアント側で付けていたもので、サーバー側にそのまま移植してきました

2020-09-10 14:12 UTC, dera- commented on packages/akashic-cli-serve/src/server/domain/PlayerStore.ts
> +export class PlayerStore {
PlayerのデータはPlayと紐づけるべきものかと思いましたが、その場合同じプレイヤーで別のPlayを実行するということができなくなるのでPlayStoreとは独立して新たにこのStoreを作成しました

2020-09-10 14:33 UTC, dera- commented on packages/akashic-cli-serve/src/server/controller/PlayerController.ts
> +				player = { id: player.id, name: playerName || player.name };
プレイヤーID重複時に同じデータを使うのであればリクエストされたプレイヤー名は無視すべきかとも思いましたが、その場合の挙動がユーザーから見て不具合に見えそうだったので、リクエストされたプレイヤー名は保存はせずともそのまま利用する方向でいくことにしました(この仕様で問題等あれば教えていただけると助かります)。

2020-09-11 05:03 UTC, yu-ogi commented on packages/akashic-cli-serve/src/client/api/ApiClient.ts
> +export const registerPlayer = async(
unregister は不要でしょうか。
大部分のケースでは問題にならなそうですが、API として対称性が取れていないのが気になります。

2020-09-11 05:03 UTC, yu-ogi commented on packages/akashic-cli-serve/src/client/api/ApiClient.ts
> +		{ playerId, playerName }
現状の実装だと クライアントが生成したプレイヤーIDをサーバ側に登録しているようですが、筋論としては「プレイヤーIDは常にサーバ側から提供される」というのが正しいような気がしています。
そのためには [エントリポイント](https://github.com/akashic-games/akashic-cli/blob/master/packages/akashic-cli-serve/www/public/index.html) を ejs などのサーバサイドレンダリングでプレイヤーIDを渡して出力するのが正攻法のように思います。
とはいえ結構な改修になりそうなので、少なくとも今の実装であれば「クライアント側からは一切のパラメータを送らず、サーバは常にユニークなプレイヤーIDを返す」とした方がわかりやすいのかなと思いました。

その上でクライアント側では「リロード等で既にサーバ側からプレイヤーIDを受け取っていれば localStorage や sessionStorage に格納した値を利用する」という挙動にもできるのではないかと思います。

2020-09-11 12:04 UTC, dera- commented on packages/akashic-cli-serve/src/client/api/ApiClient.ts
> +export const registerPlayer = async(
こちら僕も悩んだのですが、クライアント側に登録解除に相当する機能がない(ウィンドウを閉じたら消すというものでもないですし)ので用意しない方向で考えています。

2020-09-11 12:29 UTC, dera- commented on packages/akashic-cli-serve/src/client/api/ApiClient.ts
> +		{ playerId, playerName }
すみません、このパラメーターからは分かりづらいのですが、playerIdが空文字の場合はサーバ側でプレイヤーIDを生成して、playerIdが空文字でない場合はその値をサーバーに登録する仕様になってます。ちなみに、playerIdがクライアントで生成されることは無く、空文字でない場合はクエリパラメータでプレイヤーIDが指定された時もしくはセッションに保存されている時のみです。

インターフェースが分かりづらいということであれば、サーバー側で生成するAPIと渡したものを登録するAPIで分けようと思いますが、クエリパラメータでプレイヤーIDを指定するという現状の仕様はなくすことはできなさそうです(わざと同じプレイヤーIDを指定して複数画面で同じプレイヤーとしてプレイするというケースがあり得るため)。

2020-09-14 06:31 UTC, xnv requested changes

2020-09-14 06:31 UTC, xnv commented on packages/akashic-cli-serve/src/client/store/Store.ts
> +	setPlayer(player: Player): void {
`Store#assertInitialized()` で `storage` の initialize も待って、完了次第 `storage` の情報から `this.player` をセットすることはできないでしょうか。その方がもともとのコードに近いと思います。

汎用の setter の公開は避けられるなら避けたいです。実際には一度しか呼び出さない (途中で変えるつもりがない) 値なのに、どこから誰が呼び出す想定なのか、何をすればこのクラスは使用可能な状態になるのか、このクラス自体から読み取るのが難しくなるからです。

2020-09-14 06:31 UTC, xnv commented on packages/akashic-cli-serve/src/client/api/ApiClient.ts
> +		{ playerId, playerName }
> その上でクライアント側では「リロード等で既にサーバ側からプレイヤーIDを受け取っていれば localStorage や sessionStorage に格納した値を利用する」という挙動にもできるのではないかと思います。 

これをやるとサーバがユニークな値を生成できなくなりませんか。(クライアントが何の playerId を使ってるのか把握できなくなるので。特にクエリパラメータで  playerId を受けてる場合は絶対に把握できなくなります)


> このインターフェースではAPIの仕様が分かりづらいということであれば、サーバー側で生成するAPIと渡したものを登録するAPIで分けようと思いますが、

こうしてもいいと思いますが、そうでなければ `playerId?: string` にして「(空文字列ではなく) 省略を特別扱い」し、さらにコメントをつけたいですね。そもそも空文字列を特別扱いしていい理由もないと思いますが、特別扱いしているのが読み取れないのが一番の問題でしょう。

2020-09-14 06:31 UTC, xnv commented on packages/akashic-cli-serve/src/server/domain/PlayerStore.ts
> +		this.nextPlayerId++;
- これこんな単純でいいんですっけ。 クエリパラメータで `1` とか指定されたらいきなり次の生成で重複するのでは。
- `player.id` があって実際には `nextPlayerId` を使ってないケースにまでインクリメントする理由もないと思います。
- クライアントから勝手に (連番とも限らない値を) 名乗ってくることを考えたら、 "next" の値を一意に決めるのは難しいと思います。一番手抜きした簡単な実装は `knownMaxPlayerId` を管理することでは。(生成時の処理はほとんど変わりませんが、 `player.id` がある時は値をチェックして `known〜` の値を更新する)

2020-09-14 06:31 UTC, xnv commented on packages/akashic-cli-serve/src/server/controller/PlayerController.ts
> +				player = { id: player.id, name: playerName || player.name };
そもそも `playerName` までサーバで管理する必要あるんですっけ。最初から `playerId` だけ管理すればこんな大変な仕様にしなくてもいいような？

2020-09-14 07:40 UTC, yu-ogi commented on packages/akashic-cli-serve/src/client/api/ApiClient.ts
> +		{ playerId, playerName }
> これをやるとサーバがユニークな値を生成できなくなりませんか。

> プレイヤーIDは常にサーバ側から提供される

という前提であれば Date.now() 等でユニークな値を生成できるかと思います。
(クライアントが独自にプレイヤーIDを生成してしまえばその限りでは無いですが)

2020-09-14 12:12 UTC, dera- commented on packages/akashic-cli-serve/src/client/store/Store.ts
> +	setPlayer(player: Player): void {
了解しました、そのように対応してみようと思います

2020-09-14 12:16 UTC, dera- commented on packages/akashic-cli-serve/src/server/domain/PlayerStore.ts
> +		this.nextPlayerId++;
なるほど、、この実装であればサーバー側でID生成に重複してしまうということは避けられそうですね。。この実装で対応してみようかと思います。

2020-09-14 12:24 UTC, dera- commented on packages/akashic-cli-serve/src/server/controller/PlayerController.ts
> +				player = { id: player.id, name: playerName || player.name };
あーー、、、これは今までplayerIdが決まってからでないとplayerNameが生成できない仕様(`player${playerId}`的な名前になる)なのでplayerNameもサーバー側で管理すべきかと思ったのですが、今までの仕様通りであればサーバーから送られてくるもしくは登録されるIDを待ってからクライアント側で生成すればいいだけの話だったので管理する必要はなかったですね。。playerIdだけ管理するように修正しておきます。

2020-09-15 13:33 UTC, dera- commented on packages/akashic-cli-serve/src/client/store/storage.ts
> +			const playerName: string = choose(getQueryValue(qp.playerName), s.playerName, `player${registered}`);
プレイヤー名は特にサーバー側で管理する必要は無いので、サーバー側にはプレイヤーIDのみ登録してプレイヤー名はクライアント側で生成するように変更しました

2020-09-16 00:42 UTC, yu-ogi approved these changes

2020-09-23 08:14 UTC, xnv approved these changes
コメントつけていますが approved.

2020-09-23 08:14 UTC, xnv commented on packages/akashic-cli-serve/src/client/store/Store.ts
> +import { storage } from "./storage";
(個人的にはこっち派ですが) なんかわざわざ周辺と違うフォーマットにするだけの差分になってませんか。

2020-09-23 08:14 UTC, xnv commented on packages/akashic-cli-serve/src/server/domain/PlayerIdStore.ts
> +		if (this.knownMaxPlayerId < parseInt(playerId, 10)) {
- `playerId` が数値を表す文字列じゃない時の動作が一見不安になるのでコメントを残しておきたいですね (`x` が  `number` なら `x < NaN === false` なのでぎりぎり動きそう)
- すごい細かいですしこれも実害なさそうですが、 `parseInt()` 二回呼ぶの避けたいですね。(文字列長に依存するループを無駄に二度実行することになるので)

2020-09-23 09:25 UTC, dera- commented on packages/akashic-cli-serve/src/client/store/Store.ts
> +import { storage } from "./storage";
あー、、このファイルのフォーマットに合わせるべきでしたね。。こちら修正しておきます。

2020-09-23 09:27 UTC, dera- commented on packages/akashic-cli-serve/src/server/domain/PlayerIdStore.ts
> +		if (this.knownMaxPlayerId < parseInt(playerId, 10)) {
了解しました、`playerId`が数字じゃない時でも問題なく動作する旨をコメントしてparseIntした値を`playerIdInt`という変数に代入するように修正しておきます。

2020-09-24 03:11 UTC, merged