remarkのバージョンを最新のものにした
akashic-games/akashic-cli pull request #49
Opened 2019-03-18 07:30 UTC by dera-

### 概要
* npm auditで警告が出ないようにするためにremark-cliのバージョンを最新にする必要があったが、その場合以下の対応も必要になるためこのPRで対応した。
* remarkモジュールの導入とremark-lintのアップデート
* .remarkrcをremark-cli@6でサポートされている書き方に修正する

### やったこと
* remark-cli, remark-lintのアップデート
* remarkモジュールの導入
* .remarkrcをremark-cli@6でサポートされている書き方に修正
  * そのため、remark-lintルールプリセットやremarkルールモジュールも導入
* remark-lintはトップディレクトリにだけ置いて、各akashic-cli-xxxのmd lint時はそこのremark-lintを利用するようにした。
* トップディレクトリに最新のremarkを入れた影響で各モジュールのビルド時にコンパイルエラーが発生してしまうようになってしまったので、tsconfigに`"skipLibCheck": true`のルールを追加した。

2019-03-18 07:35 UTC, dera- commented on package.json
> +    "remark-preset-lint-markdown-style-guide": "~2.1.2"
remarkのルールは基本的にpreset-lint-markdown-style-guideを利用して、今までの.remarkrcでは定義されていたがプリセットに無いものに関しては個別でルールモジュールをインストールするようにしました。`remark-lint-~~`となっているのがルールモジュールです。

2019-03-18 07:39 UTC, dera- commented on .remarkrc
> +    ["lint-no-tabs", true]
remarkのルールとしてpreset-lint-markdown-style-guideを利用していますが、今までの.remarkのルールを保つようにしています。
ですので、プリセットで異なるルールになっているものはこのファイル上でルールの上書きを行っています。
また、どういうルールを使っているか明示したかったので、異なるルールでないものについてもわざわざこちらに記述しています。

2019-03-18 07:43 UTC, dera- commented on packages/akashic-cli-commons/tsconfig.json
> +    "skipLibCheck": true
こちらは`*.d.ts`の定義を無視するという内容のオプションになります。コンパイル時に本来読む必要のないトップディレクトリのnode_modulesを読みに行ってコンパイルエラーになってしまうため、一時的にこのようなオプションを付けさせていただきましたが、本来必要な型定義ファイルを無視してしまう時点であまりよろしくない対応だと思われるので別の対応を考えたいです

2019-03-18 08:38 UTC, dera- commented on packages/akashic-cli-commons/tsconfig.json
> +    "skipLibCheck": true
skipLibCheckの代わりにtypesを指定する対応に変更します

2019-03-19 01:10 UTC, yu-ogi commented on packages/akashic-cli-commons/package.json
> +    "lint:md": "../../node_modules/.bin/remark ./*.md --frail --no-stdout --quiet --rc-path ../../.remarkrc",
https://github.com/lerna/lerna/tree/master/commands/bootstrap#--hoist-glob
root package のモジュールを使いたいなら `--hoist` を使ったほうが良さそうに思います。
(ただしすべての packages のすべての依存モジュールのバージョンが固定されてしまいます)

2019-03-19 07:19 UTC, dera- commented on packages/akashic-cli-commons/package.json
> +    "lint:md": "../../node_modules/.bin/remark ./*.md --frail --no-stdout --quiet --rc-path ../../.remarkrc",
ありがとうございます。依存モジュールのバージョンが固定されても特に困ることはないので、そのオプションを使ってみようかと思います。

2019-03-19 08:19 UTC, dera- commented on packages/akashic-cli-commons/package.json
> +    "lint:md": "../../node_modules/.bin/remark ./*.md --frail --no-stdout --quiet --rc-path ../../.remarkrc",
と思いましたが、`lerna bootstrap --hoist` をやってみたところ消えてしまう依存モジュールもあったりしたので(akashic-cli-serveのmaterial-design-iconsがakashic-cli-serveのnode_modules下から消えました)、使うかどうかは一旦保留とさせていただきたいです。。

2019-03-20 04:33 UTC, xnv requested changes

2019-03-20 04:33 UTC, xnv commented on packages/akashic-cli-export-html/src/export/tsconfig.json
> +    "skipLibCheck": true
ここ skipLibCheck が残ってるのは意図通りでしょうか。

2019-03-20 06:24 UTC, dera- commented on packages/akashic-cli-export-html/src/export/tsconfig.json
> +    "skipLibCheck": true
修正忘れてました。。こちら直しておきます

2019-03-28 11:53 UTC, dera- commented on package.json
> -    "remark": "~10.0.1",
このモジュールが無くてもremarkは動作するようでしたので、uninstallしました。
そのため今回は各パッケージのtsconfigにtypesを追加する対応も必要ではなくなりますが、istanbulをjestに変更する対応の時に必要になるので、typesについてはその時のために予め入れておこうかと思います

2019-03-29 03:40 UTC, yu-ogi commented on packages/akashic-cli-commons/package.json
> +    "lint:md": "../../node_modules/.bin/remark ./*.md --frail --no-stdout --quiet --rc-path ../../.remarkrc",
なるほど、それであれば `remark-cli` は各 packages 以下にインストールする形のほうが適切かと思いました。
(本来 `typescript` や `tslint` あたりも root package で共通化できるはずなので、現段階で `remark-cli` のみを例外扱いするのは違和感があります。)

2019-03-29 14:48 UTC, dera- commented on packages/akashic-cli-commons/package.json
> +    "lint:md": "../../node_modules/.bin/remark ./*.md --frail --no-stdout --quiet --rc-path ../../.remarkrc",
了解しました。では、各パッケージで`remark-cli`をインストールするように修正してみます

2019-04-01 01:23 UTC, yu-ogi approved these changes

2019-04-03 03:12 UTC, xnv approved these changes

2019-04-03 09:50 UTC, merged