CHANGELOGの生成方法の変更
akashic-games/akashic-cli pull request #52
Opened 2019-03-26 10:54 UTC by dera-

### 概要
* 今までCHANGELOGをcommitベースで各モジュール内で生成するようにしていましたが、この変更でPRベースで且つトップディレクトリにCHANGELOGを生成する方法に変更します。
* この変更によってakashic-cliのPRに内容に沿うように以下のラベルを付けることが新たに必要になります
  * breaking: 互換性の破壊
  * enhancement: 機能追加
  * bug: バグ修正
  * documentation: ドキュメントの追加・修正
  * internal: 内部モジュールの変更など

### やったこと
* lerna-changelogとsemverモジュール導入
  * lerna-changelogの設定はpackage.jsonに記載
* publishスクリプトの修正
* npm auditで警告されたのでlernaのバージョンを上げた

2019-04-01 04:37 UTC, xnv requested changes

2019-04-01 04:37 UTC, xnv commented on package.json
> +      "other": "Other Change"
この辺開発者が PR を作る時にきにする必要があることですよね。 README に開発者向けのセクションを作って記述しておいてほしいです。

2019-04-02 03:50 UTC, dera- commented on package.json
> +      "other": "Other Change"
そうですね、PRにラベルを付ける作業は必要になりますので、その辺りはPRに記載しておこうと思います。

2019-04-03 09:15 UTC, xnv approved these changes
コメント加えましたが approved.

2019-04-03 09:15 UTC, xnv commented on build/updateChangelog.js
> +// lerna-changelogコマンドを実行するために環境変数GITHUB_AUTHにgithubへのアクセストークンを与える必要があるが、与えられていなくてもコマンド実行時にエラーは発生しないのでここで事前にチェックする
1行非常に長いですが lint に引っかかっていませんか。(これが対象になっていなくても改行したいです)

2019-04-03 12:31 UTC, dera- commented on build/updateChangelog.js
> +// lerna-changelogコマンドを実行するために環境変数GITHUB_AUTHにgithubへのアクセストークンを与える必要があるが、与えられていなくてもコマンド実行時にエラーは発生しないのでここで事前にチェックする
了解しました。改行しておきます。

2019-04-05 06:40 UTC, kamakiri01 approved these changes

2019-04-08 06:28 UTC, merged