add step button for serve
akashic-games/akashic-cli pull request #529
Opened 2020-10-06 11:58 UTC by kamakiri01

## このpull requestが解決する内容

### 概要

serveコマンドのGUIに、一時停止中に利用できる「ステップ実行」ボタンを追加します。
この利用のために、 https://github.com/akashic-games/headless-driver/pull/187 の更新が必要です。

## 破壊的な変更を含んでいるか?

- なし

2020-10-07 03:44 UTC, kamakiri01 commented on packages/akashic-cli-serve/src/server/domain/RunnerStore.ts
> +			this.onRunnerPause.fire({ playId: runner.playId, runnerId: runnerId })
既存のpauseはstopGameを利用してコンテンツを停止していましたが、今後はheadress-driverが提供するpause/resume機能で停止するように変更されます。

2020-10-08 03:41 UTC, xnv requested changes

2020-10-08 03:41 UTC, xnv commented on packages/akashic-cli-serve/src/server/domain/RunnerStore.ts
> +			this.onRunnerPause.fire({ playId: runner.playId, runnerId: runnerId })
`this.onRunnerPause` の発火が if の内側に入ってますが意図されたものでしょうか。(利用箇所から「"実際に" runner を pause した」とき "だけ" に発火するべき……ということでしょうか？)

2020-10-08 03:41 UTC, xnv commented on packages/akashic-cli-serve/src/server/domain/RunnerStore.ts
> +			await this.runnerManager.stepRunner(runner.runnerId);
pause してなかったらエラーになる、みたいな対応は不要でしょうか？(UI上はありえないかもしれませんが)

2020-10-08 03:41 UTC, xnv commented on packages/akashic-cli-serve/src/server/controller/RunnerController.ts
> +			} else if (status === "resumed") {
"running" とかぶっていませんか＋ "running" が動作しなくなっていませんか。  `"resumed"` の追加は不要そうに見えます。

2020-10-08 03:41 UTC, xnv commented on packages/akashic-cli-serve/src/client/view/molecule/PlayControl.tsx
> +				title={`アクティブインスタンスのポーズ中、プレイを1フレーム進めます。`}
`isActivePausing` 出ないときは  disable するか非表示にしたいです。(どっちがいいかは微妙なところですが、disable だと web サイトの画像とかに更新が必要になりますね)

2020-10-08 03:41 UTC, xnv commented on packages/akashic-cli-serve/src/client/store/ServerInstanceEntity.ts
> +	async tep(): Promise<void> {
削除漏れですかね……？

2020-10-08 03:41 UTC, xnv commented on packages/akashic-cli-serve/src/client/api/ApiClient.ts
> +export const stepPlayDuration = async(playId: string): Promise<PlayPatchApiResponse> => {
必要そうですが呼び出し箇所がないような？

2020-10-08 03:41 UTC, xnv commented on packages/akashic-cli-serve/src/server/controller/RunnerController.ts
> +			} else if (status === "step") {
step は status/状態 ではないので、ここにあるのは概念的に抵抗があります。step するとき status は  paused でなければならず、また  step した後も status は paused のまま、というのが直観に沿う挙動ではないでしょうか。

どう実装するかは悩ましいものの、 runner に対する  patch であることは間違いなさそうに思えます。 `req.body` に `step?: boolean` を持たせてそれを扱うのはどうでしょうか。(この箇所の  status の操作に加えて、 step フラグに対する処理もここで行う)

2020-10-13 05:46 UTC, dera- commented on packages/akashic-cli-serve/src/server/domain/RunnerStore.ts
> +	async pauseRunner(runnerId: string): Promise<void> {
asyncを利用するように変更するのであれば、このメソッドの利用側でもawaitを付与する必要があるのではという気がしています

2020-10-13 11:02 UTC, kamakiri01 commented on packages/akashic-cli-serve/src/server/domain/RunnerStore.ts
> +	async pauseRunner(runnerId: string): Promise<void> {
うっ確かに、直します。

2020-10-13 11:02 UTC, kamakiri01 commented on packages/akashic-cli-serve/src/server/controller/RunnerController.ts
> +			} else if (status === "step") {
patchの `status: paused` に stepフラグを持たせるようにします。

2020-10-13 11:02 UTC, kamakiri01 commented on packages/akashic-cli-serve/src/client/api/ApiClient.ts
> +export const stepPlayDuration = async(playId: string): Promise<PlayPatchApiResponse> => {
stepは RunnerPatchApiResponse 経由で送るのでこれは使用していないですね…削除します。

2020-10-13 11:02 UTC, kamakiri01 commented on packages/akashic-cli-serve/src/client/store/ServerInstanceEntity.ts
> +	async tep(): Promise<void> {
削除します。

2020-10-13 11:03 UTC, kamakiri01 commented on packages/akashic-cli-serve/src/server/controller/RunnerController.ts
> +			} else if (status === "resumed") {
runningのみにまとめます。

2020-10-13 11:03 UTC, kamakiri01 commented on packages/akashic-cli-serve/src/server/domain/RunnerStore.ts
> +			await this.runnerManager.stepRunner(runner.runnerId);
`RunnerStore#isPaused` などを追加して判定するのが良さそうでしょうか…？

2020-10-13 11:03 UTC, kamakiri01 commented on packages/akashic-cli-serve/src/server/domain/RunnerStore.ts
> +			this.onRunnerPause.fire({ playId: runner.playId, runnerId: runnerId })
runner の pause に成功したとき発火する、で実態に伴うものだと思いましたが、気付いた点があれば伺いたいです。

2020-10-13 11:20 UTC, kamakiri01 commented on packages/akashic-cli-serve/src/client/view/molecule/PlayControl.tsx
> +				title={`アクティブインスタンスのポーズ中、プレイを1フレーム進めます。`}
個人的にはレイアウトの維持されるdisableを使いたいです。
マージ後にwebサイトの画像を追従します。

2020-10-16 02:44 UTC, xnv requested changes

2020-10-16 02:44 UTC, xnv commented on packages/akashic-cli-serve/src/server/domain/RunnerStore.ts
> +			await this.runnerManager.stepRunner(runner.runnerId);
はい。下手に呼べると「普通にゲーム進んでるのになぜか割り込みで 1  フレ追加で進められる」みたいな謎機能になりそうですよね。

実装的には、もっと単純に `Looper` 実装の側で「 `debugStop()` してない状態で `debugStep()` されたら例外」とかでもいいかもしれません。 (例外はこれの呼び出し元が catch してるでしょうし)

2020-10-16 02:44 UTC, xnv commented on packages/akashic-cli-serve/src/server/controller/RunnerController.ts
> +			if (status !== "running" && status !== "paused" && status !== "step") {
この差分は不要になっていませんか。

2020-10-16 02:44 UTC, xnv commented on packages/akashic-cli-serve/src/server/controller/RunnerController.ts
> +				if (req.body.step) {
うーん…… `status` に値を指定したのに `status` が設定されないパスがあるんでしょうか。

`step` と `status` は完全に独立しているものではないので微妙なところではありますが、モデルとしては単純に、「 request の `status` は `Runner` の状態/status を操作する、 `step` はステップ実行だけをやる」という形で単純化しておきたい気がします。言い換えると、 `step` は `status` を扱うこの if 文の外側で扱いませんか。

2020-10-16 02:44 UTC, xnv commented on packages/akashic-cli-serve/src/server/domain/RunnerStore.ts
> +			this.onRunnerPause.fire({ playId: runner.playId, runnerId: runnerId })
「概念的にそうであるべき」という考えと、「現に今 `onRunnerPause` が何につながっていてこの変更がどこに影響するのか」は別なので確認したかったです。

……で、自分で確認しましたが、クライアント側に通知して状態を変更しているだけなので動作上の影響はなさそうですね。

2020-10-16 02:44 UTC, xnv commented on packages/akashic-cli-serve/src/client/store/PlayEntity.ts
> +		ApiClient.stepRunner(this.playId);
……今更ですが、何か対称性がおかしいような。これはすぐ上の `pauseActive()` や `resumeActive()` とほとんど同じ形のメソッドになるべきではありませんか？

- 名前と役割からすれば、 `stepRunner()` はここから呼ぶのではなく、 `ServerInstanceEntity#step()` を作ってそこから呼び出すべきに思えます。
- `stepRunner()` の引数は `runnerId` だと思いますが `playId` を渡して動作するでしょうか
- `pauseActive()` などと同様、プレイ時間/playDuration を進める必要があると思います。追加したはずの `stepPlayDuration()` を呼び出すのがここではありませんか。
   - 「サーバインスタンスが実行されているか」と「プレイ時間が進んでいるか」は別なので、 `stepPlayDuration()` は `stepRunner()` とは別に必要に思えます。(後者は確かクライアント側の時間進行を管理するためにあります)

2020-10-20 11:09 UTC, kamakiri01 commented on packages/akashic-cli-serve/src/server/domain/RunnerStore.ts
> +			await this.runnerManager.stepRunner(runner.runnerId);
LooperのdebugStep側に判定を入れます。

2020-10-20 11:28 UTC, kamakiri01 commented on packages/akashic-cli-serve/src/server/controller/RunnerController.ts
> +			if (status !== "running" && status !== "paused" && status !== "step") {
削除します。

2020-10-20 11:28 UTC, kamakiri01 commented on packages/akashic-cli-serve/src/server/controller/RunnerController.ts
> +				if (req.body.step) {
statusは「ポーズ状態」であり、操作としてstepが指定されるという意図でしたが、それであればpauseRunnerも同時に呼ばれないと不自然でしたね…。stepの扱いはif文の外に出します。

2020-10-21 11:36 UTC, kamakiri01 commented on packages/akashic-cli-serve/src/client/store/PlayEntity.ts
> +		ApiClient.stepRunner(this.playId);
- `ServerInstanceEntity#step()` 経由で呼び出すよう修正します。
- duration 管理のため、 `PlayStore#stepPlayDuration()` を追加します。

2020-10-23 05:16 UTC, xnv commented on packages/akashic-cli-serve/src/client/view/molecule/PlayControl.tsx
> +				className="external-ref_button_active-pause"
これ名前のとおり外部から DOM 要素を引くためのやつなので、 `-pause` でなく `-step` にしておきたいです。

2020-11-04 09:02 UTC, kamakiri01 commented on packages/akashic-cli-serve/src/client/view/molecule/PlayControl.tsx
> +				className="external-ref_button_active-pause"
直します。

2020-11-06 05:27 UTC, dera- approved these changes

2020-11-09 04:09 UTC, xnv approved these changes

2020-11-10 08:38 UTC, merged