Fix highlight in entityTree
akashic-games/akashic-cli pull request #551
Opened 2020-10-21 06:57 UTC by ShinobuTakahashi

## 概要

v3 コンテンツのエンティティ検索のハイライトが 2回目以降は黒の fillRect となる問題の修正。

**原因**
AEv3 の場合、`game._modified` が false の場合、`Game#render()` は画面更新せず早期 return となる。
そのため、1回目にハイライトした fillRect を描画した後に2回目以降のハイライトを描画しようとすると、
1回目のハイライト描画の終わりの処理で CanvasRenderingContext2D#restore にて復元されているため fillStyle にデフォルトの黒が設定されてしまうためでした。
(pdi-browser 側で restore() で currentStyle が context と合っていない問題は別タスクで修正します。)

**修正**
AEv3の場合は、ハイライト前に `game._modified` を true に設定してから `game.render()` を呼ぶように修正。

2020-10-21 10:12 UTC, xnv requested changes

2020-10-21 10:12 UTC, xnv commented on packages/akashic-cli-serve/src/client/akashic/ServeGameContent.ts
> +			// AEv3では _modified が false の場合は game#render() で画面更新しないため、2回目以降のハイライトが `CanvasRenderingContext2D#restore` により黒くなる。
黒くなるのは  pdi-browser の別件のバグのように思えますし、ここに書くのはやめておきませんか。
「AEv3 では _modified フラグが false の場合 render() が画面更新をスキップするため、 true を設定して必ず描画させる」でいいと思います。

2020-10-21 10:12 UTC, xnv commented on packages/akashic-cli-serve/src/client/akashic/ServeGameContent.ts
> +			if ("_modified" in game && !game._modified) return; // AEv3 は画面更新が不要ならなにもしない。
現状これでいいはずではあるんですが、元の `render()` の呼び出しを潰してしまうのは避けておきませんか。(元の `render()` に「_modified が落ちていてもこれだけはやる」みたいな処理を後からつけない保証はないので。その時に serve でだけ呼ばれない形になると、ほぼ確実に一回ハマることになると思います)

若干迂遠ですが、 `renderOriginal` の呼び出し前に `_modified` の値を取得しておき、 `=== false` ならハイライト描画をスキップする形にしたいです。

2020-10-21 10:12 UTC, xnv commented on packages/akashic-cli-serve/src/client/akashic/AkashicGameViewWeb.d.ts
> +		_modified: boolean;
- `_modified?` にして、 v3 でのみ存在する旨コメントしておきたいです。

2020-10-21 10:32 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/client/akashic/ServeGameContent.ts
> +			// AEv3では _modified が false の場合は game#render() で画面更新しないため、2回目以降のハイライトが `CanvasRenderingContext2D#restore` により黒くなる。
ありがとうございます。コメント修正しました。

2020-10-21 10:32 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/client/akashic/ServeGameContent.ts
> +			if ("_modified" in game && !game._modified) return; // AEv3 は画面更新が不要ならなにもしない。
仰るとおりです。`renderOriginal` の処理後にハイライト描画をスキップするよう修正しました。

2020-10-21 10:32 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/client/akashic/AkashicGameViewWeb.d.ts
> +		_modified: boolean;
コメントを追加し、修正しました。

2020-10-21 12:17 UTC, dera- approved these changes

2020-10-22 02:45 UTC, xnv approved these changes

2020-10-22 03:07 UTC, merged