add watch option in akashic-cli-scan
akashic-games/akashic-cli pull request #552
Opened 2020-10-21 12:02 UTC by dera-

### 概要
* akashicコンテンツ作成時にアセットのホットリロード的なことを可能にするために、akashic-cli-scanにwatchオプションを追加しました。

2020-10-29 03:07 UTC, xnv commented on packages/akashic-cli-scan/src/scan.ts
> +			param.assetScanDirectoryTable.image.some(dir => filePath.indexOf(path.join(param.cwd, dir)) !== -1)
これ `assets/` ディレクトリのサポートできてますかね？

2020-10-29 06:54 UTC, dera- commented on packages/akashic-cli-scan/src/scan.ts
> +			param.assetScanDirectoryTable.image.some(dir => filePath.indexOf(path.join(param.cwd, dir)) !== -1)
あ、、すみません`assets/`が完全に考慮から抜けてました。。assetsディレクトリの判定も追加しておきます。ちなみに、`assets`の他にこういった特別な扱いをしているディレクトリってあったりしますか？

2020-11-05 01:30 UTC, xnv requested changes

2020-11-05 01:30 UTC, xnv commented on packages/akashic-cli-scan/src/scan.ts
> +	watcher.on("unlink", handler);
- 一番重要そうなファイルの「追加時」に反応してないような？ (assets/ ディレクトリだけなぜか追加も反応してそうですが)
- change に反応するのは image, audio だけにしたいです  (width, height, duration しか内容の変化の影響は受けないと思うので)
   - 現状だと JS 保存するたびに無駄に scan が走るような気がします

2020-11-05 04:02 UTC, dera- commented on packages/akashic-cli-scan/src/scan.ts
> +	watcher.on("unlink", handler);
changeでも「追加時」に反応するようでしたのでchangeをaddと兼用のつもりで使ってましたが、changeとaddで対象のディレクトリが変わるのであればaddへのハンドラ登録も用意した方がよさそうですね。

2020-11-05 05:03 UTC, dera- commented on packages/akashic-cli-scan/src/scan.ts
> +	watcher.on("unlink", handler);
ちなみに、assetsディレクトリもchnageに反応させないということで大丈夫でしょうか？

2020-11-06 03:06 UTC, xnv commented on packages/akashic-cli-scan/src/scan.ts
> +			param.assetScanDirectoryTable.image.some(dir => filePath.indexOf(path.join(param.cwd, dir)) !== -1)
ないはずです！

2020-11-06 04:55 UTC, xnv commented on packages/akashic-cli-scan/src/scan.ts
> +			|| param.assetScanDirectoryTable.audio.some(dir => filePath.indexOf(path.join(param.cwd, dir)) !== -1)
assets/ 内の拡張子が画像・音声であるものも対象にしたいです。

2020-11-06 05:08 UTC, xnv commented on packages/akashic-cli-scan/src/scan.ts
> +	watcher.on("unlink", handler);
いや失礼、 「change に反応するのは image asset と audio asset にしたい」ですね。 assets/ ディレクトリ下の拡張子が png, jpg, jpeg, ogg, aac あたりのファイルも反応する必要があります。

2020-11-09 10:30 UTC, ShinobuTakahashi commented on packages/akashic-cli-scan/src/scan.ts
> +import { Configuration, _isAudioFilePath, _isImageFilePath } from "./Configuration";
`_isAudioFilePath`, `_isImageFilePath`  接頭に `_` 付いているのでプライベート変数/関数の認識があり、他から参照されるので違和感があります。
export するのであれば、接頭の `_` を削除するのはいかがでしょうか？

2020-11-09 10:30 UTC, ShinobuTakahashi approved these changes
コメントしましたがapprovedです

2020-11-09 11:53 UTC, dera- commented on packages/akashic-cli-scan/src/scan.ts
> +			param.assetScanDirectoryTable.image.some(dir => filePath.indexOf(path.join(param.cwd, dir)) !== -1)
了解しました、ありがとうございます

2020-11-09 12:25 UTC, dera- commented on packages/akashic-cli-scan/src/scan.ts
> +	watcher.on("unlink", handler);
了解しました。assetsディレクトリ下であれば拡張子も確認してimage assetかaudio assetならscanを実行するように修正します

2020-11-09 12:40 UTC, dera- commented on packages/akashic-cli-scan/src/scan.ts
> +import { Configuration, _isAudioFilePath, _isImageFilePath } from "./Configuration";
うーーん、確かに`_`が付いている関数を外部から呼び出すのは本来の使い方から外れたものなので仰る通り避けるべきなきはしますが、この2つの関数以外にも`_isScriptAssetPath()`など～アセットかどうかを判定する関数があるので、もしリネームするのであれば一貫性を保つためにこれらの関数もまとめてリネームすべき気がするんですよね。。

流石にそこまで大きく変更するほどの処理ではないと考えているので、対応するのであれば「本来外部利用すべきでないがimageアセットかどうかの判定をするための関数がこれだけなので利用する」といった旨のコメントを追記するだけに留めたいです

2020-11-10 03:06 UTC, xnv commented on packages/akashic-cli-scan/src/scan.ts
> +import { Configuration, _isAudioFilePath, _isImageFilePath } from "./Configuration";
いや普通に rename しちゃえばいいのでは。(モジュール外から触ってるとかなら一段めんどくさくなりますけど)

2020-11-10 07:34 UTC, dera- commented on packages/akashic-cli-scan/src/scan.ts
> +import { Configuration, _isAudioFilePath, _isImageFilePath } from "./Configuration";
すみません、軽くakashic-cli内で`_is~Path()`の利用箇所を検索してみたところ今回参照した箇所以外で外部参照されているものは無かったのでリネームしました

2020-11-11 03:29 UTC, xnv approved these changes

2020-11-11 08:12 UTC, merged