Add serve startup options
akashic-games/akashic-cli pull request #606
Opened 2020-11-26 04:53 UTC by ShinobuTakahashi

## 概要

serve 起動時、ネットワーク切断時の挙動を修正
- serve 起動時にブラウザを自動で開くよう(デフォルト挙動)に修正。
   - 自動でブラウザを開かないようにする `--no-open-browser` オプションを追加。

- サーバとの切断時に開いている子ウィンドウを自動で閉じるよう修正。
  - 子ウィンドウを閉じない `--preserve-disconnected` オプションを追加。

また、#598 で対応したサーバ再起動時に再接続する機能と、自動でブラウザを開く機能が共存すると、同じ playId を持つタブが出来てしまう等の問題があるため、再接続機能を元に戻しています。

2020-11-26 04:54 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/package.json
> +    "@akashic/akashic-cli-commons": "../akashic-cli-commons",
commons の publish 後に取り込んで確認します。

2020-11-26 04:55 UTC, ShinobuTakahashi commented
commons を取り込んでいないため CI が落ちています。
commons の publish 後に最新にし CI が通る事を確認します。

2020-11-26 04:58 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/client/operator/PlayOperator.ts
> +			`width=${window.innerWidth},height=${window.innerHeight}`
`noopener` オプションで自分が親ウィンドウなのか子ウィンドウが判別できなくなるため削除しています。

2020-11-26 05:04 UTC, ShinobuTakahashi commented
commons の定義を取り込んでいないため CI が落ちています。 commons の publish 後に最新にし CI が通る事を確認します。

2020-11-27 03:02 UTC, xnv requested changes

2020-11-27 03:02 UTC, xnv commented on packages/akashic-cli-serve/src/server/index.ts
> +		.option("--preserve-disconnected", "Preserve the state of window disconnected from the network")
network ……といっても localhost ですし、 state of window というのも色々解釈できちゃいそうですし、 "Disable auto closing for disconnected windows." ぐらいにしておきませんか。

2020-11-27 03:02 UTC, xnv commented on packages/akashic-cli-serve/src/server/index.ts
> +		.option("--no-open-browser", "No open browser at startup")
no open って英語的に見慣れない気がするので、 "Disable to open a browser window at startup" とかでどうでしょうか。

2020-11-27 03:02 UTC, xnv commented on packages/akashic-cli-serve/src/client/operator/PlayOperator.ts
> +		console.log(`OPENWINDOW: width=${window.innerWidth},height=${window.innerHeight}`);
これデバッグ用出力を残してしまっただけだと思うので、この際削除しちゃいたいです。

2020-11-27 03:02 UTC, xnv commented on packages/akashic-cli-serve/src/client/operator/PlayOperator.ts
> +			`width=${window.innerWidth},height=${window.innerHeight}`
ここで noopener 外しても実は (noopener の不具合対策で入れた) `ignoreSession` があるので正常動作するんですが、こうなるともはや [↑のコメント](https://github.com/akashic-games/akashic-cli/pull/606/files#diff-fea754147532d42c6fabaf3d69c780bb15ac1741bf457087175e08482806a15dR34) が正しくなくなってると思います。コメントの方を修正して「Mac Chrome で正しく動作しないのと、親ウィンドウかどうか判別したいことがあるので noopener はつけない。代わりに ignoreSession を指定して自前でセッションストレージをウィンドウごとに使い分ける (ref. ../store/storage.ts)」みたいにしたいです。

2020-11-27 03:02 UTC, xnv commented on packages/akashic-cli-serve/src/client/operator/PlayOperator.ts
> +	closeSubWindows = (): void => {
close しないこともあるので 〜IfNeeded としておきませんか。

2020-11-27 03:02 UTC, xnv commented on packages/akashic-cli-serve/src/server/index.ts
> +		if (cliConfigParam.openBrowser ) {
不要な空白があります。

2020-11-27 03:21 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/server/index.ts
> +		.option("--preserve-disconnected", "Preserve the state of window disconnected from the network")
ありがとうございます。修正しました。

2020-11-27 03:21 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/server/index.ts
> +		.option("--no-open-browser", "No open browser at startup")
ありがとうございます。修正しました。

2020-11-27 03:22 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/client/operator/PlayOperator.ts
> +		console.log(`OPENWINDOW: width=${window.innerWidth},height=${window.innerHeight}`);
console 削除しまし、コメントも修正しました。

2020-11-27 03:22 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/client/operator/PlayOperator.ts
> +	closeSubWindows = (): void => {
`closeSubWindowsIfNeeded()` へ修正しました。

2020-11-27 03:22 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/server/index.ts
> +		if (cliConfigParam.openBrowser ) {
空白削除しました。

2020-11-27 03:23 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/client/operator/PlayOperator.ts
> +			`width=${window.innerWidth},height=${window.innerHeight}`
コメント修正しました。

2020-12-01 02:22 UTC, xnv commented on packages/akashic-cli-serve/src/client/operator/PlayOperator.ts
> +	closeSubWindowsIfNeeded = (): void => {
すいませんこれ「必要なら (自分の) サブウィンドウたちをクローズ」ではなく「必要なら自分をクローズ」してるので、 `closeThisWindowIfNeeded` の方が適当ですね。

2020-12-01 02:22 UTC, xnv approved these changes
コメントつけてますが  approved.

2020-12-01 02:31 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/client/operator/PlayOperator.ts
> +	closeSubWindowsIfNeeded = (): void => {
確かに仰る通りです。`closeThisWindowIfNeeded()` へ修正しました。

2020-12-01 05:26 UTC, dera- approved these changes

2020-12-01 06:42 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/package.json
> +    "@akashic/akashic-cli-commons": "../akashic-cli-commons",
最新の commons を取り込み CI が通る事を確認済み

2020-12-01 06:43 UTC, merged