add watch option in akashic-cli-serve
akashic-games/akashic-cli pull request #640
Opened 2020-12-25 12:05 UTC by dera-

### やったこと
* akashic-cli-scanにあったwatchオプションをakashic-cli-serveに移す対応

2021-01-04 07:27 UTC, ShinobuTakahashi approved these changes

2021-01-05 02:56 UTC, xnv requested changes

2021-01-05 02:56 UTC, xnv commented on packages/akashic-cli-serve/src/server/index.ts
> +				scan.watchAsset({
えっと、「scan の watch 機能をここから呼び出す」ではなく、「scan の watch 機能をそもそも serve に移す」をお願いしたいです。なぜなら、

- このままではアセットを自動で scan して game.json が変化したことに serve が反応できない (たとえば新規プレイに移行する・リロードするなど)
- アセット登録内容の変化以外のものも watch する時に、 chokidar を扱う場所が二箇所に増える

ためです。

2021-01-05 10:35 UTC, dera- commented on packages/akashic-cli-serve/src/server/index.ts
> +				scan.watchAsset({
アセットのscan自体はakashic-cli-scanの責務なので移す必要はないかと思っていましたが、アセットの登録内容変更以外にも監視するケース(コードの変更等)は出てくるので仰る通りでした。あと、akashic-cli-scan側で使わないものを置いていてもしょうがないですよね。。こちらserveに移してserveに合った形に修正しようと思います。

2021-01-05 13:43 UTC, dera- commented on packages/akashic-cli-serve/src/server/index.ts
> +			watchContent(cliConfigParam.targetDirs[i], (err: any) => {
コンテンツ毎にコールバック関数を設定したい(今はエラーメッセージの表示しかしてませんが、この後のPRでコンテンツ再起動などの処理も入れる予定です)ので、watchContent関数はディレクトリを1つだけ受け取るようにしました。

2021-03-19 05:57 UTC, xnv commented on packages/akashic-cli-scan/src/cli.ts
> +				console.warn("--watch option is deprecated");
末尾に "DO NOT USE." と付け加えたいです。

2021-03-19 05:57 UTC, xnv commented on packages/akashic-cli-scan/src/cli.ts
> +	.option("-w, --watch", "Watch Directories of asset")
こっちも `(deprecated)` とつけておきたいです。

2021-03-19 05:57 UTC, xnv approved these changes
コメントつけましたが approved.

2021-03-19 08:39 UTC, dera- commented on packages/akashic-cli-scan/src/cli.ts
> +				console.warn("--watch option is deprecated");
了解しました、追記しておきます

2021-03-19 08:39 UTC, dera- commented on packages/akashic-cli-scan/src/cli.ts
> +	.option("-w, --watch", "Watch Directories of asset")
こちらも追記しておきます

2021-03-19 09:25 UTC, merged