create new play by watch option in akashic-cli-serve
akashic-games/akashic-cli pull request #641
Opened 2021-01-04 10:10 UTC by dera-

### やったこと
* akashic-cli-serveでwatchオプション使用時にコンテンツに変化があった時、新しくplayを作り直す処理を行うようにした

2021-01-04 10:11 UTC, dera- commented on packages/akashic-cli-serve/src/server/index.ts
> +	if (cliConfigParam.watch) {
scoket.ioでの通信を利用したかったので、watchオプション処理の記載場所を変更しました。この変更による他箇所への影響はない想定です。

2021-01-04 10:15 UTC, dera- commented
今のままだとakashic-cli-scanのwatchAssetメソッドの仕様上scriptやtextの内容が更新されても反応しないようになってしまっているのですが、こちらscriptやtextの内容の更新にも対応できるようにしておいた方が良いでしょうか？(そもそもそれらの変更を反映していなかったのはgame.jsonの内容に影響がないからなのですが)
https://github.com/akashic-games/akashic-cli/blob/83e6fbf4285882164ffe00cae813d29555d619b7/packages/akashic-cli-scan/src/scan.ts#L184

2021-01-05 04:40 UTC, xnv requested changes

2021-01-05 04:40 UTC, xnv commented on packages/akashic-cli-serve/src/client/operator/Operator.ts
> +			this.restartWithNewPlay();
サーバからの broadcast を受けてこれ全員が実行するということは、接続している全員が全員「新しいプレイを作り、サーバインスタンスを作り、全員に新しいプレイへの移行を要求する」という動作を行いませんか。
 
 `restartWithNewPlay()` にあたる操作を行うのは一人だけでなければならないはずです。サーバ側でそれに当たる動作をするのが手っ取り早いと思います。(ちゃんとやるなら、今の `restartWithNewPlay()` にあたる処理をサーバ側の API にしてしまって、現行の `restartWithNewPlay()` 呼び出し箇所も API 呼び出しにしてしまうのがいいわけですが、それを考えだすとどういう API にするのか悩みそうなので、これは TODO でもいいと思います)

broadcast が必要なのはここの `"switchPlay"` だけではないかと思います。
https://github.com/akashic-games/akashic-cli/pull/641/files#diff-5ba39f7e8f7b5fe590720f5939dc95fabd452e66ecbd8439189fb4645d543d16R187

2021-01-05 04:42 UTC, xnv commented
https://github.com/akashic-games/akashic-cli/pull/641#issuecomment-753887440
> 今のままだとakashic-cli-scanのwatchAssetメソッドの仕様上scriptやtextの内容が更新されても反応しないようになってしまっているのですが、こちらscriptやtextの内容の更新にも対応できるようにしておいた方が良いでしょうか？(そもそもそれらの変更を反映していなかったのはgame.jsonの内容に影響がないからなのですが)

はい。そして #640 の [コメント](https://github.com/akashic-games/akashic-cli/pull/640#discussion_r551689103) で書いたとおり、watch する処理は serve 側に移した上でそれをすることになると思います (scan には関係ないスクリプトの中身を scan が  watch しているというのも奇妙ですし)。

2021-01-05 10:43 UTC, dera- commented on packages/akashic-cli-serve/src/client/operator/Operator.ts
> +			this.restartWithNewPlay();
あ、、確かに全員がその要求をするというかなり無駄のある処理になってしまいますね。。
こちらの処理はサーバー側で行うように修正します。(`restartWithNewPlay()`については一旦TODOコメントだけ入れておこうと思います)

2021-01-07 09:00 UTC, dera- commented on packages/akashic-cli-serve/src/server/index.ts
> +				// コンテンツに変更があったらplayを新規に作り直して再起動
ここの新規Playを作り直す処理でやっていることはクライアント側の`Operator#restartWithNewPlay`メソッドと同じです

2021-01-07 09:02 UTC, dera- commented on packages/akashic-cli-serve/src/server/index.ts
> +				// 先に対応するコンテンツのrunnerを全て停止させる
`Operator#restartWithNewPlay`では新規play作成後にrunnerの停止処理を行っていましたが、サーバー側では対応するコンテンツのrunnerを全て止める(サーバー側では対象のplayidが分からないためこのような止め方をしています)ためplay作成前に行うようにしました

2021-01-13 10:24 UTC, ShinobuTakahashi approved these changes

2021-01-15 03:01 UTC, xnv requested changes

2021-01-15 03:01 UTC, xnv commented on packages/akashic-cli-serve/src/server/domain/PlayStore.ts
> +	}
周辺のメソッドとの対称性のなさがひっかかります。他は `PlayEntity` を露出せず、 `playId` などをキーにしてその中身を返している一方、このメソッドは問答無用で `PlayEntity` を全部返しているからです。このメソッド自体が変というわけではないのですが、これを作るなら例えば上ので `getPlay()` は `getPlayEntity(playId: string)` などになる方が自然に思えます。

周辺との整合性を考えると、 `getPlayIdsFromContentId(): string[]` を作って、その戻り値で `getRunners()` を使う形がすっきりするように思います。

2021-01-15 07:33 UTC, dera- commented on packages/akashic-cli-serve/src/server/domain/PlayStore.ts
> +	}
あー、、確かに仰る通りこのメソッドだけPlayEntityを返すのは奇妙な感じがしますね。。
了解しました、そのように修正しようと思います。

2021-01-19 05:49 UTC, xnv approved these changes
コメントつけていますが approved.

2021-01-19 05:49 UTC, xnv commented on packages/akashic-cli-serve/src/server/index.ts
> +				io.emit("playBroadcast", { playId, message: { type: "switchPlay", nextPlayId: playId } });
えっと、クライアント側が手抜きになっていて現状だと意味ない感じですが、概念的にはこの処理は上の `forEach()` の中で、つまり `playId` ごとに起きるべきではないでしょうか。でないと「変更を検出したコンテンツを使っていた全ての play の参加者が、次は全員同じ play に接続してくる」動作になってしまうと思います。

`"playBroadcast"` の `playId` は「この `playId` に接続している人間に向けてのメッセージである」という意味だと思いますから、今作った play の ID ではなく、 `getPlayIdsFromContentId()` で得たそれぞれの play の ID が適当に思えます。

2021-01-19 13:27 UTC, dera- commented on packages/akashic-cli-serve/src/server/index.ts
> +				io.emit("playBroadcast", { playId, message: { type: "switchPlay", nextPlayId: playId } });
お、、ここのplayIdはそういう意味合いだったんですね。
であれば`getPlayIdsFromContentId()`で取得したplayIdを取っておいて、最後にplayId毎にemitするように修正しようと思います。

2021-01-20 07:47 UTC, dera- commented on packages/akashic-cli-serve/src/client/operator/Operator.ts
> +				if (this.store.currentPlay.playId === arg.playId) {
watchオプション実行時にサーバー側で対象のplayの数だけbroadcastする仕様になり、そのままだとその数だけplayを作り直すようになってしまうので、playidがクライアントのものと合致する時だけ作り直すようにしてみました(こちら問題があれば教えていただければと思います)。

2021-01-21 03:58 UTC, merged