watch game.json with watch option in akashic-cli-serve
akashic-games/akashic-cli pull request #660
Opened 2021-01-27 12:25 UTC by dera-

### 概要
* akashic-cli-serveのwatchオプションでgame.jsonが監視対象になっておらず、直接game.jsonが編集された時に新規playを作り直すようになっていなかったのでそのように修正した。

### やったこと
* game.jsonが編集された時`scanAsset()`は実行せず即新規playを作り直す処理を入れた(`scanAsset()`はアセットの変更をgame.jsonに反映させるものなので、この場合実行する必要はない)
*

2021-01-27 12:32 UTC, dera- commented on packages/akashic-cli-serve/src/server/domain/GameConfigs.ts
> +			awaitWriteFinish: true
この`awaitWriteFinish`オプションで、登録したハンドラが1つずつ順番に実行されるようになります。以前までファイル追加時にaddとchangeの両方のイベントが同時に発火するようになっていて、そのせいでgame.jsonを監視対象から外す処理も意味をなさなくなって結果playが二重起動されるという問題がありましたが、このオプションの付与によってその問題は無くなりました。

2021-01-28 10:25 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/server/domain/GameConfigs.ts
> +				watcher.add(gameJsonPath);
ここ、45行目と同じように `cb(err)` のエラー処理必要ないでしょうか？

2021-01-29 07:27 UTC, dera- commented on packages/akashic-cli-serve/src/server/domain/GameConfigs.ts
> +				watcher.add(gameJsonPath);
ここでコールバックを呼んでしまうとserve起動時に即playを作り直してしまうという二度手間が発生するのでコールバックを呼ぶ必要は無いと思ってます(それによってエラーが発生することはないですが、あまり無駄な処理は入れたくないという気持ちです)。
しかし、エラーを握りつぶすのは流石に違うと思いますので、エラー処理は入れておこうと思います(といってもエラー内容をログに吐くくらいになりますが)

2021-01-29 10:20 UTC, ShinobuTakahashi approved these changes

2021-02-01 06:51 UTC, xnv requested changes

2021-02-01 06:51 UTC, xnv commented on packages/akashic-cli-serve/src/server/domain/GameConfigs.ts
>  	import("@akashic/akashic-cli-scan/lib/scan").then(scan => {
見落としていた別件なんですがこれ await したいです。(でないと、 watchContent() が返ったあといつ監視が開始されるのかわからないので)

2021-02-01 06:51 UTC, xnv commented on packages/akashic-cli-serve/src/server/domain/GameConfigs.ts
> +				console.log("Reflect changes of game.json");
console を出すかどうかは callback 側の仕事であるべきに思えます。 game.json の変更か asset の変更かを区別してログを出すのであれば、 `cb` の引数を増やしませんか。

2021-02-01 06:51 UTC, xnv commented on packages/akashic-cli-serve/src/server/domain/GameConfigs.ts
>  		// watch開始時にgame.jsonのasstesの内容と実際のアセットの内容に誤差が無いかの確認を兼ねてscanAsset関数を実行する
今更なんですがそもそもこれ必要ですか？(起動された時点のコンテンツをいきなり信用しない理由がよくわからないような？)

2021-02-01 06:51 UTC, xnv commented on packages/akashic-cli-serve/src/server/domain/GameConfigs.ts
> +			awaitWriteFinish: true
順番に実行したとしても、 add と watch が両方来るなら

1. add に対する scan
2. add に対する cb()
3. change に対する scan
4. change に対する cb()

と無駄に cb() が連続で呼ばれて play が二重に再生成されませんか？

----

そもそもこのオプションは本当に「順番に実行する」というものなのでしょうか？　[README](https://github.com/paulmillr/chokidar#performance) を見る限り「ファイルサイズが一定時間変化しなくなるまで polling して add 通知を遅らせる」というようなものに見えます。順番に対する直接の言及はなさそうですし、  `Use with caution` とか書かれていて、気軽に目的外使用するオプションにもあまり見えません。

----

また仮に「順番に実行する」といっても、 chokidar は `scanAsset()` の処理がどこから非同期になるのかや、いつ完了するのかには感知できないのではありませんか？　そうなると game.json の unwatch/watch がどのタイミングで来るのかよくわからないように思います。最悪次のような処理順をたどる可能性がありそうです。

- add に対する scan に先立って game.json を unwatch する
- add に対する scan が呼ばれ、非同期処理なのですぐ return する
  - (この時点で、 add に対する処理は終わったように chokidar には見える)
- change に対する scan に先立って game.json を unwatch する (何も起きない)
- change に対する scan が呼ばれ、非同期処理なのですぐ return する
- add に対する scan が走る
- add に対する scan が終わってコールバックが呼ばれ、game.json の watch を再開させる
- change に対する scan が走る
  - この時、 game.json は watch されてしまっている

現実には `scanAssets()` の非同期処理が先にリクエストされて、 change 通知よりも先行するのかもしれませんが、仮にそうならそれは `scanAssets()` の内部の実装に依存していて、あまり望ましい状況ではなさそうです。

----

以上もろもろを考えるに、 chokidar の通知順序 (？) や監視対象をどうこうするのではなく、むしろ通知を受けたこちらの処理で、`scanAssets()` や  `cb()` を呼び出すかどうかを制御しませんか。具体的には、

- chokidar の通知が来た時はその時刻を「タイマーかけた時刻」「最後に通知が来た時刻」として記録しつつ、タイマーをかける (100ms とか？)
  - タイマーをすでにかけていたら「最後に通知が来た時刻」のみ更新する
- タイマーの通知が来たら、
  - 「タイマーかけた時刻」と「最後に通知が来た時刻」が一致するなら scan
  - しないなら、「最後に通知が来た時刻」からまた一定時間 (100ms とか ) が経過するまで分のタイマーをかける

というような形はどうでしょうか。これはつまり、 chokidar の通知が来た後、一定時間通知がなく落ち着くまでは、 scan やらを留保する、という方針です。これなら通知順がどうなろうが錯綜して複数同時に来ようが、 安定して動きそうに思います。

概念的にも、 100ms 以下などのタイムスパンで更新が連続する時に scan やプレイ再生成を連発するのは嬉しい動作ではないでしょうから、これは実現したい挙動に対して素直な実装であるように思います。

(ただし、scanAssets() 中の game.json の更新を無視するためには別途フラグが必要かもしれません)

2021-02-03 14:01 UTC, dera- commented on packages/akashic-cli-serve/src/server/domain/GameConfigs.ts
>  	import("@akashic/akashic-cli-scan/lib/scan").then(scan => {
了解しました、こちらawaitを利用するように修正します

2021-02-03 14:03 UTC, dera- commented on packages/akashic-cli-serve/src/server/domain/GameConfigs.ts
> +				console.log("Reflect changes of game.json");
確かにcallback側の責務に思えますね。。了解しました、cbにisGameJaon(ちょっと限定的すぎる気もしていますが)を追加してcallback側でログを吐く感じにしようと思います

2021-02-03 14:06 UTC, dera- commented on packages/akashic-cli-serve/src/server/domain/GameConfigs.ts
>  		// watch開始時にgame.jsonのasstesの内容と実際のアセットの内容に誤差が無いかの確認を兼ねてscanAsset関数を実行する
serve実行前に`akashic scan asset`し忘れるケースもあるかと思って用意したのですが、仮にあったとしてもこのオプションで担保すべきものではない気がしますね。こちらのreadyイベントの処理は削除しておこうと思います

2021-02-03 14:12 UTC, dera- commented on packages/akashic-cli-serve/src/server/domain/GameConfigs.ts
> +			awaitWriteFinish: true
ありがとうございます 🙇 
であれば、awaitWriteFinishオプションは使わずに、タイマーを利用してscanAssetやコールバック関数をイベント毎に間をおいて逐次的に実行する方針で修正しようと思います。
本来やりたいこととしては同期的に順番にscanAssetやコールバック関数を実行することなので、こちらの方がより意図にあった感じかと思います。
そして、順番に実行さえされればscanAssetメソッドによって編集されたgame.jsonに反応してさらに処理が走るということもなくなるかと思います。

2021-02-04 11:59 UTC, xnv reviewed
別で議論しましたが、4つ論点があり、

- (A) タイマーを重複でかけるとカオスになる
- (B) 重複でかけない場合、「通知された変更の種類 (assets か game.json か) 」を記憶しておかないと、最後の一回の変更内容に応じた処理しかできない
- (C) 「最後に通知された時刻から一定時間」経過を条件に scan/cb() をしたい
- (D) game.json の unwatch はなくせる (というかscanAssets()のタイミングに依存しないため、なくしたい)

なのですが、あまりにややこしいので、(C) を妥協して一定時間毎の処理で妥協すると、こんな感じになるのではないでしょうか。

```typescript
const ModTargetFlags {
  None = 0x0,
  GameJson = 0x1,
  Assets = 0x2
}

let mods = 0;
const watcherHandler(filePath) => {

  const handler = () => {
    const lastMods = mods;
    mods = 0;

    if (lastMods & ModTargetFlags.Assets) {
      scanAssets(..., (err) => {
          // scanAssets の過程で絶対に立つが、この直後 (このフラグ対して行う処理である) cb() 呼びだしを
         // どうせやるので、フラグを落とせる (というか落とさないと clearInterval() できない)
         mods &= ~ModTargetFlags.GameJson; 

         try {
           cb(err, lastMods);
         } finally {
           if (mods === ModTargetFlags.None) {
             clearInterval(timer);
             timer = null;
           }
         }
      });
    } else if (mods & ModTargetFlags.GameJson) {
      cb(null, lastMods);
    }
  };

  if (path is assets) 
    mods |= ModTargetFlags.Assets;
  if (path is game.json)
    mods |= ModTargetFlags.GameJson

  if (!timer) {
    timer = setInterval(handler, 1000);
  }
}
```

(C) まで本気でやるなら `setInterval()` を `setTimeout()` にし、chokidar からの通知時刻を使って動的に待ち時間を調整することになると思いますが、現実そこまでつめてもユーザ体験はそれほど変わらないでしょう。

2021-02-04 11:59 UTC, xnv commented on packages/akashic-cli-serve/src/server/domain/GameConfigs.ts
> +	await import("@akashic/akashic-cli-scan/lib/scan").then(scan => {
これ await にしちゃったのでもう then 使う必要もなくなってると思います。

2021-02-04 11:59 UTC, xnv commented on packages/akashic-cli-serve/src/server/domain/GameConfigs.ts
> +export async function watchContent(targetDir: string, cb: (err: any, isChangedGameJson: boolean) => void): Promise<void> {
- 別に internal な関数なんでなんでもいいっちゃいいんですが、 さすがに `isChangedGameJson: boolean` だと I/F として限定的すぎる (なぜ "コンテンツを watch する" 処理が「game.json の変更かどうか」に限ってわざわざ通知してくるのかよくわからない＋この値が false である時はどういう変更なのかも読み取れない) ので、 変更の種類 (assets なのか game.json なのか) を通知しませんか

2021-02-04 11:59 UTC, xnv commented on packages/akashic-cli-serve/src/server/domain/GameConfigs.ts
> +				timerSetTime = currentTime;
`timerSetTime` の更新と `setTimeout()` の呼び出しは常にセットであるべきに思います。現状だと `timerId` がある (すでに `setTimeout()` をかけている) 時には重複して `setTimeout()` をかけてしまいますが、これは期待動作ではないでしょう。

また記述的にも、「セットであるもの」の処理は近くに書きたいです (現状だと `setTimeout()` の呼び出しが `handler` の定義を挟んだ後に書かれていて「セットである」感じが読み取りにくいのが気になります)。

2021-02-04 11:59 UTC, xnv commented on packages/akashic-cli-serve/src/server/domain/GameConfigs.ts
> +					return;
```typescript
const ModTargetFlags {
  None = 0x0,
  GameJson = 0x1,
  Assets = 0x2
}

let mods = 0;
const watcherHandler(filePath) => {

  const handler = () => {
    const lastMods = mods;
    mods = 0;

    if (lastMods & ModTargetFlags.Assets) {
      scanAssets(..., (err) => {
          // scanAssets の過程で絶対に立つが、この直後 (このフラグ対して行う処理である) cb() 呼びだしを
         // どうせやるので、フラグを落とせる (というか落とさないと clearInterval() できない)
         mods &= ~ModTargetFlags.GameJson; 

         try {
           cb(err, lastMods);
         } finally {
           if (mods === ModTargetFlags.None) {
             clearInterval(timer);
             timer = null;
           }
         }
      });
    } else if (mods & ModTargetFlags.GameJson) {
      cb(null, lastMods);
    }
  };

  if (path is assets) 
    mods |= ModTargetFlags.Assets;
  if (path is game.json)
    mods |= ModTargetFlags.GameJson

  if (!timer) {
    timer = setInterval(handler, 1000);
  }
}
```

これほんとに動きます……？　上の重複タイマーの影響で動きそうな気もするんですが難しすぎるような……。

例えばファイル A の変更が通知され (これを時刻 0 とします) 、その 200ms 後にファイル B の変更が通知された (時刻 200) 場合、タイマーが完全に正確に呼ばれたとすると、

- 時刻 0: A のタイマーがかかり、 timerSetTime = 0 になる
- 時刻 200: B のタイマーが (重複して) かかり、 timerSetTime = 0, lastUpdateTime = 200 になる
- 時刻 1000: A が時刻 0 でかけた hanlder が呼ばれる
  - この時 timerSetTime != lastUpdateTime なので cb() は呼び出さない
  - タイマーを掛け直して、 timerSetTime = 1000, lastUpdateTime = 1000  -- (a)
- 時刻 1200: B が時刻 200 でかけた handler が呼ばれる
  - この時 timerSetTime, lastUpdateTime は (a) で設定されていて一致するので cb() を呼び出す -- (b)
  - timerId がクリアされる
- 時刻 2000: 時刻 1000 で掛け直したタイマーが呼ばれる
  - 時刻 1000 以降、別のファイル C の変更が通知されていなければ: timerSetTime, lastUpdateTime は (a) から更新されていないので一致し、cb() が呼ばれる -- (c)
  - でなければ: lastUpdateTime が更新されているのでさらにタイマーをかけなおす
    - さらに C の timer がどこかで呼ばれる

……という流れになりそうですが、既に「ファイル B の処理 (b) なのに、 A のために (a) がセットした時刻を参照している」時点でかなり chaotic な状況になってしまいそうです。

2021-02-08 16:21 UTC, dera- commented on packages/akashic-cli-serve/src/server/domain/GameConfigs.ts
> +	await import("@akashic/akashic-cli-scan/lib/scan").then(scan => {
そうでした。。こちらthenではなくモジュールを受けるための変数を用意しようと思います

2021-02-08 16:23 UTC, dera- commented on packages/akashic-cli-serve/src/server/domain/GameConfigs.ts
> +export async function watchContent(targetDir: string, cb: (err: any, isChangedGameJson: boolean) => void): Promise<void> {
了解しました、こちら代わりにファイルの種類を表すフラグを引数としようかと思います

2021-02-08 16:36 UTC, dera- commented
ありがとうございます。https://github.com/akashic-games/akashic-cli/pull/660#pullrequestreview-583085674 でお話しいただいたようにファイルの変更というよりアセット/game.jsonの変更という感じで変更の種類に着目して同じ種類の変更なら一度だけscanAssetもしくはcbを実行するように修正します

2021-02-17 07:05 UTC, xnv commented
このブランチを動かして TS のコンテンツを開き、TS のビルドをすると

-  .js ファイルがなくなったのを検出 → リロード → (.js がないので) エラー
-  game.json の変更を検出 → リロード

という流れで二度リロードがかかりました。前者はまあ不可避なのかもしれませんが、後者は妙な気がします (game.json は変化しないはず) 。またもし後者が誤発だった場合、 TS のビルド時のリロードが正しく走るか確認したいです。

2021-02-18 04:51 UTC, dera- commented
上記問題については想定外の挙動ではありますがserveが止まってしまうレベルの致命的なものではないためこのPR自体は一旦マージして、対応は別PRで行おうと思います。

2021-02-18 04:52 UTC, merged