initコマンドで存在しなしテンプレート名を指定した場合のメッセージ修正
akashic-games/akashic-cli pull request #672
Opened 2021-02-01 12:10 UTC by kamakiri01

## このpull requestが解決する内容

### 概要
`$ akashic init --type bad-template-name` のように、存在しないテンプレート名を指定した場合、
エラーメッセージ出力が直感的ではありません。
これを修正します。

## 破壊的な変更を含んでいるか?

- あり
export されている `listTemplates()` の型を `Promise<void>` から `Promise<Set<string>>` に変更しています。

2021-02-01 12:10 UTC, kamakiri01 commented on packages/akashic-cli-init/src/listTemplates.ts
> +			return Promise.resolve(new Set(templates));
取得したリストを外部から利用する手段が無かったため、破壊的変更ですがリストを Set のまま外に渡すよう変更しました。

2021-02-02 04:41 UTC, xnv requested changes

2021-02-02 04:41 UTC, xnv commented on packages/akashic-cli-init/src/listTemplates.ts
> +			return Promise.resolve(new Set(templates));
別コメントのとおりこの変更は不要になるのではないかと思いますが、もし必要であっても、破壊的変更にするぐらいなら、

- `Set` を返す関数 `collectTemplateNames()` を作る
- `listTemplates()` は `collectTemplatesNames()` を呼び出して `print()` するだけの関数にする

とするのはどうでしょうか。ほとんどコードも増えませんし。(list〜 と collect〜 という名前はまぎらわしいのもあり、list〜の方には「後方互換性のため念のため残している。新規の利用は非推奨」的なコメントをつけておきたいですが)

2021-02-02 04:41 UTC, xnv commented on packages/akashic-cli-init/src/init.ts
> +			return listTemplates(param).then(templates => {
これ、ここでやらなくても実質この後「実際に利用するテンプレートを探す」過程でほとんど同じことをしているように思います。単純に `readTemplateFile()` の中で、 `ENOENT` にかかった時にエラーメッセージを出すことはできないでしょうか？

2021-02-02 04:57 UTC, kamakiri01 commented on packages/akashic-cli-init/src/init.ts
> +			return listTemplates(param).then(templates => {
なるほど確かに…
テンプレート候補をリストとして持って判別させようかと思っていましたが、 `ENOENT` ハンドリングするだけで良さそうです。

2021-02-02 04:57 UTC, kamakiri01 commented on packages/akashic-cli-init/src/listTemplates.ts
> +			return Promise.resolve(new Set(templates));
確かにそうです。（ `collectTemplatesNames` 的な名前をぱっと思い付けなかったのもありますが…）
使わないコードを残すことはないので、この変更は不要にするつもりですが、次の方針の参考にします。

2021-02-03 10:08 UTC, kamakiri01 commented on packages/akashic-cli-init/src/init.ts
> +			return listTemplates(param).then(templates => {
すみません、 `readTemplateFile()` は `template.json` の有無を見ていますが、 `template.json` の存在が任意（ビルトインのテンプレートには `template.json` がそもそもない）なので、ここで判定するのは難しそうです。

`listTemplates` を互換性を維持しつつ修正する方向で検討します。

2021-02-24 04:13 UTC, xnv approved these changes

2021-02-24 04:13 UTC, xnv commented on packages/akashic-cli-init/src/listTemplates.ts
> +
不要な空行です。

2021-02-24 04:13 UTC, xnv commented on packages/akashic-cli-init/src/listTemplates.ts
> +
ここも。

2021-02-24 10:48 UTC, kamakiri01 commented on packages/akashic-cli-init/src/listTemplates.ts
> +
修正します。

2021-02-24 10:48 UTC, kamakiri01 commented on packages/akashic-cli-init/src/listTemplates.ts
> +
こちらも修正します。

2021-02-24 11:01 UTC, merged