Fix warning message of akashic-cli-stat
akashic-games/akashic-cli pull request #685
Opened 2021-02-16 01:46 UTC by ShinobuTakahashi

## 概要

akashic-cli-stat で、 `.aac` があると `.mp4` も必要という警告メッセージの削除。

2021-02-17 02:30 UTC, xnv requested changes

2021-02-17 02:30 UTC, xnv commented on packages/akashic-cli-stat/src/stat.ts
> -			param.logger.warn("AAC (.aac) is deprecated. Use MP4(AAC) (.mp4) instead.");
単に警告を消すだけでなく、 .mp4 と .aac の扱いを逆にしたいです。たとえば mp4 がない時 (`sizeResult.mp4AudioSize > 0` でない時) は `TOTAL SIZE (using mp4)` は表示しないようにしたいですし、ある時は警告したいです。

2021-02-17 02:30 UTC, xnv commented on packages/akashic-cli-stat/src/stat.ts
> +						size => { sizeResult.mp4AudioSize += size; })
こちらも。 .aac の側に↓のようなコメントがあり、それに対応するものをこの箇所に入れておきたいです。

> /* .aacファイルは存在すれば対応するが、deprecatedなのでファイルが存在しない場合でも警告を表示しない */

また逆に .aac の側には `No such file` の警告を入れておきたいです。

2021-02-17 03:55 UTC, ShinobuTakahashi commented on packages/akashic-cli-stat/src/stat.ts
> +						size => { sizeResult.mp4AudioSize += size; })
.aac と .mp4 の動作修正しました。

2021-02-17 03:55 UTC, ShinobuTakahashi commented on packages/akashic-cli-stat/src/stat.ts
> -			param.logger.warn("AAC (.aac) is deprecated. Use MP4(AAC) (.mp4) instead.");
.mp4 と .aac の扱いを逆にし、それに沿った動作や警告を出すよう修正しました。

2021-02-18 03:04 UTC, xnv approved these changes

2021-02-18 03:16 UTC, merged