Draw anchor position in entity tree
akashic-games/akashic-cli pull request #751
Opened 2021-04-28 12:39 UTC by kamakiri01

## このpull requestが解決する内容

### 概要
akashic serve で EntityTree を表示したとき、anchorX/Y位置を表示するようにします。

## 破壊的な変更を含んでいるか?

- なし

2021-04-28 12:40 UTC, kamakiri01 commented on packages/akashic-cli-serve/package.json
> +    "rxjs": "^6.5.3",
storybookの依存を暗黙に利用していたため、 install が通らなくなっていました。過去利用バージョンを追加しています。

2021-05-13 06:10 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/client/akashic/ServeGameContent.ts
> -			renderer.restore();
`restore()` しないと元の描画消えてしまわないでしょうか？

2021-05-13 06:57 UTC, kamakiri01 commented on packages/akashic-cli-serve/src/client/akashic/ServeGameContent.ts
> -			renderer.restore();
`restore()` は座標変換などのリセットなので、描画は消えないです。が、 `restore()` は残すべきですね…ここは戻します。
`renderer.end()` が内部的に `restore()` しているので顕在化していなかっただけのようです。

2021-05-13 10:10 UTC, ShinobuTakahashi commented on packages/akashic-cli-serve/src/client/akashic/ServeGameContent.ts
> -			renderer.restore();
ローカル環境で動かしてみたところ、`restore()` を復元させた場合、anchor 位置を指す描画(水色の輝点)がずれて描画されてしまいました。

<img width="480" alt="ss-1" src="https://user-images.githubusercontent.com/33408810/118111266-6ddab380-b41e-11eb-8f8b-4155a89b19f4.png">

2021-05-13 11:28 UTC, kamakiri01 commented on packages/akashic-cli-serve/src/client/akashic/ServeGameContent.ts
> -			renderer.restore();
確認ありがとうございます。直します。

2021-05-14 02:58 UTC, ShinobuTakahashi approved these changes

2021-05-14 03:00 UTC, xnv requested changes

2021-05-14 03:00 UTC, xnv commented on packages/akashic-cli-serve/src/client/view/molecule/EntityTreeDevtool.tsx
> +function stringifyDumoItemAnchor(e: EDumpItem): string {
- Dumo は Dump の typo ですかね。
- 引数型や他メソッドにあわせて `stringifyEDumpItemAnchor()` としたいです。

2021-05-14 03:00 UTC, xnv commented on packages/akashic-cli-serve/src/client/view/molecule/EntityTreeDevtool.tsx
> +	return `[${ax}:${ay}]`;
1:2 みたいな文字列になりますが、何かの比率みたいに見えます。確かにこのダンプ文字列は、できるだけコンパクトな表示になるように攻めた表現をしている箇所ではあるんですがアンカーポイントの文字列表現として一般的だったり直感的だったりするものってあまりないと思います。 素直に `anchor: (0, 0)` みたいな表現にしておきませんか。画面うるさくなると思うので 0, 0 の場合は空文字列にするという選択も考えたいです。

2021-05-14 03:11 UTC, kamakiri01 commented on packages/akashic-cli-serve/src/client/view/molecule/EntityTreeDevtool.tsx
> +function stringifyDumoItemAnchor(e: EDumpItem): string {
うっ、 `stringifyEDumpItemAnchor()` に直します。

2021-05-14 03:13 UTC, kamakiri01 commented on packages/akashic-cli-serve/src/client/view/molecule/EntityTreeDevtool.tsx
> +	return `[${ax}:${ay}]`;
ここ悩ましいと思っていて、前述される表記と同じ場合は「アンカーポイントの情報である」ことが一見して伝わらないので `[0.5]0.5]` はやや苦肉の策でした。
個人的には、`anchor: ` を付けるなら他の情報（座標やサイズなど）もラベルを付けたいです。
`(0.5, 0.5)` にする、でどうでしょうか。

2021-05-14 06:18 UTC, xnv commented on packages/akashic-cli-serve/src/client/view/molecule/EntityTreeDevtool.tsx
> +	return `[${ax}:${ay}]`;
いやあ…… `(0.5, 0.5)` だと座標と区別がつかないですよねえ。

この文脈で数値二つの組 (a, b) でもっとも自然なのは座標だと思うので、この表記は座標に譲りたいです。一方で、全部にラベルをつけるのは視覚的にうるさい＝視認性を下げるので避けたいと思っています (それは各要素の詳細として確認すべきことで、「ダイジェスト」であるツリーの一行をぎちぎちに詰めてやることではない認識)

ということで別案なんですけど、ユニコードの記号使って &#10011; (`&#10011;`) あたりを prefix としてつけるのはどうでしょうか。こんな感じで:

FilledRect \#2 (150, 100) &#9633;32x32 &#8894;30°  &#10011;(0.5, 0.5)

既存の要素でも、角度なら &#8894;`&#8894:` とかついてる方がわかりやすいように思いますし、何より記号部分に [title属性で tooltip](https://developer.mozilla.org/ja/docs/Web/HTML/Global_attributes/title) をつけると初見のユーザに対してもわかりやすそうです。(整数にあてるべき記号が思いつかなかったのが若干玉に瑕っぽいですが)

本気を出すならアイコンとか組み文字の画像を自力で作るんですが、そこまで労力を割くのはやりすぎかな、という気持ちでいます。

2021-05-14 11:43 UTC, kamakiri01 commented on packages/akashic-cli-serve/src/client/view/molecule/EntityTreeDevtool.tsx
> +	return `[${ax}:${ay}]`;
大筋で同意です。記号+tooltipは良いと思います。詳細を読みたい場合はconsoleにダンプするか、別機能としてエンティティ名をclickableにして要目ウインドウを出す…みたいなものがあっても良いかもしれません。

記号部分へのabbr付与は前後要素にアンダーバーの描画が接続して境界が分かりづらいため、値の部分にtooltipを出すようにするほうが読みやすそうです。

![image](https://user-images.githubusercontent.com/3122541/118265841-bb295480-b4f4-11eb-939e-7140696b37b8.png)

2021-05-14 11:47 UTC, kamakiri01 commented on packages/akashic-cli-serve/src/client/view/molecule/EntityTreeDevtool.tsx
> +				{stringifyEDumpItemAnchor(e)}&nbsp;
小手先感が強いですが、個々の項目の間がtsx上の改行箇所では埋まってしまうため、 `&nbsp;` で明示させるようにしています。

2021-05-17 02:54 UTC, xnv commented on packages/akashic-cli-serve/src/client/view/molecule/EntityTreeDevtool.tsx
> +				{stringifyEDumpItemAnchor(e)}&nbsp;
前後と空白ポリシー合わせたいです。 (`{`, `}` の直後・直前のスペース)

2021-05-17 02:57 UTC, xnv commented on packages/akashic-cli-serve/src/client/view/molecule/EntityTreeDevtool.tsx
> +	return <span>✛<abbr title="anchorX anchorY">({ax}, {ay}) </abbr></span>;
- `span` 自体に title をつければ十分ではありませんか？
- `abbr` はその名の通り略語 (DNA とか CSV とか) に使うものなので、その意味でも避けたい気がします。

2021-05-17 03:36 UTC, xnv commented on packages/akashic-cli-serve/src/client/view/molecule/EntityTreeDevtool.tsx
> +	return <span>✛<abbr title="anchorX anchorY">({ax}, {ay}) </abbr></span>;
追記: 見落としてたスクショ拝見しました。 `abbr` だと下線が出るんですね、なるほど……。何もないと tooltip の存在にすら気づきにくい、というのはそうかもしれません。とはいえ、普通の文中でもなく略語でもないところの下線で tooltip と分かるかと言うとそれはそれで難しいですよねえ。(個人的には hyperlink と誤認してなんかありそうな気はしちゃいますが、hover 状態でもないリンクに下線つけるのって割と昔のスタイルの感があります)

2021-05-17 04:17 UTC, kamakiri01 commented on packages/akashic-cli-serve/src/client/view/molecule/EntityTreeDevtool.tsx
> +	return <span>✛<abbr title="anchorX anchorY">({ax}, {ay}) </abbr></span>;
そうですね…。 `addr` に下線が付くのは「何かありそう」というシグニファイアになるとは思いますが、今風ではないかもしれません。スタイルで下線を消してしまう手もありますが、そうするとやはり tooltip の存在自体に気付けないのでは、という気はします。

EntityTree がマウスホバーで Entity を特定するUIなので、下線が無くてもユーザが `addr` に気付ける可能性はそこそこ高いとは思いますが、個人的には下線（or何かの導線）があるほうがフレンドリーかなと思います。

2021-05-19 04:00 UTC, xnv commented on packages/akashic-cli-serve/src/client/akashic/ServeGameContent.ts
> +				anchorEdge, anchorEdge, "rgba(0, 255, 255, 1)");
- 議論: scale が小さいとこの矩形も小さくなってしまう問題。
- 結論: この rect はグローバル座標系で描くべき。アンカーポイントのローカル座標を `mat` にかければ、アンカーポイントのグローバル座標がわかるので、 `restore()` してからその座標に矩形を描けばよい

```javascript
const mat = getMatrixFromRoot(e, camera || game.focusingCamera)._matrix;
...
renderer.restore();
const anchor = mat.multiplyPoint([e.width * e.anchorX, e.height * e.anchorY]);
renderer.fillRect(anchor.x - anchorEdge / 2, anchor.y - anchorEdge / 2, anchorEdge, anchorEdge, "color");
```

2021-05-19 04:00 UTC, xnv commented on packages/akashic-cli-serve/src/client/view/molecule/EntityTreeDevtool.tsx
> +				{ `#${e.id}`}&nbsp;
(nits) 空白落ちてます。

2021-05-19 04:05 UTC, xnv commented on packages/akashic-cli-serve/src/client/view/molecule/EntityTreeDevtool.tsx
> +	return <span>□<abbr title="width height">{formatNum(e.width)}x{formatNum(e.height)}</abbr></span>;
書けるっちゃ書けるんですけど念のためソースコード中は数値文字参照  (`&#8894;` とか) で書きませんか。それがどんな字なのかはコメントにしておきたいです。

2021-05-19 09:50 UTC, kamakiri01 commented on packages/akashic-cli-serve/src/client/akashic/ServeGameContent.ts
> +				anchorEdge, anchorEdge, "rgba(0, 255, 255, 1)");
ありがとうございます。

2021-05-19 09:50 UTC, kamakiri01 commented on packages/akashic-cli-serve/src/client/view/molecule/EntityTreeDevtool.tsx
> +				{ `#${e.id}`}&nbsp;
直します。

2021-05-19 09:57 UTC, kamakiri01 commented on packages/akashic-cli-serve/src/client/view/molecule/EntityTreeDevtool.tsx
> +	return <span>□<abbr title="width height">{formatNum(e.width)}x{formatNum(e.height)}</abbr></span>;
数値参照に直します。

2021-05-20 10:18 UTC, xnv approved these changes
コメントつけていますが approved.

2021-05-20 10:18 UTC, xnv commented on packages/akashic-cli-serve/src/client/view/molecule/EntityTreeDevtool.tsx
> +	const ax = e.anchorX == null ? "null" : e.anchorX.toString(), ay = e.anchorY == null ? "null" : e.anchorY.toString();
number の時は `formatNum()` 使いたいです。

2021-05-20 10:18 UTC, xnv commented on packages/akashic-cli-serve/src/client/akashic/ServeGameContent.ts
> +			const anchorY = e.anchorY == null ? 0 : e.anchorY;
`== null` って、 v2 のデフォルト値 (`undefined`) の時と、 v3 で明示的に `null` をつけた時ですよね (v3 のデフォルト値なら `0` が代入されるので)。どちらも「移動原点と回転原点がずれる」旧挙動で、 `0` とは動作が違う割に `0` と区別できないのが気になります。

あまり扱いに正解はなさそうですが、他のアンカーポイントとは違う色にするとかはどうでしょう。

2021-05-20 11:31 UTC, kamakiri01 commented on packages/akashic-cli-serve/src/client/akashic/ServeGameContent.ts
> +			const anchorY = e.anchorY == null ? 0 : e.anchorY;
確かに区別したいです。
どう描画すべきか悩ましいですが、 `x:0, y:0` に描画しつつ青一色を使うようにします。（別案としては矩形を2つ描画することもできそうですが画面が賑やかになりそうですね・・）

2021-05-20 11:31 UTC, kamakiri01 commented on packages/akashic-cli-serve/src/client/view/molecule/EntityTreeDevtool.tsx
> +	const ax = e.anchorX == null ? "null" : e.anchorX.toString(), ay = e.anchorY == null ? "null" : e.anchorY.toString();
確かに、直します。

2021-05-24 06:32 UTC, merged