akashic-cli-serveで背景画像を表示する機能を追加
akashic-games/akashic-cli pull request #76
Opened 2019-04-23 11:20 UTC by kamakiri01

## このpull requestが解決する内容

sandbox.config.jsに `backGroundImage: string` を追加し、ゲーム実行画面の背景に設置できるようにします。
右上のボタンで表示・非表示を切り替えることができます。

### 概要

## 破壊的な変更を含んでいるか?

- なし

2019-04-24 05:02 UTC, xnv requested changes

2019-04-24 05:02 UTC, xnv commented on packages/akashic-cli-serve/src/client/view/App.tsx
> +
不要な空行に思えます。

2019-04-24 05:02 UTC, xnv commented on packages/akashic-cli-serve/src/client/view/App.tsx
> +		console.log("this.props.store.sandboxConfig.backgroundImage", this.props.store.sandboxConfig.backgroundImage);
デバッグログなら削除でお願いしたいです。

2019-04-24 05:02 UTC, xnv commented on packages/akashic-cli-serve/src/client/store/storage.ts
> +	showBgImage: boolean;
`show` と `shows` が混在するので `shows` で統一したいです。

2019-04-24 05:02 UTC, xnv commented on packages/akashic-cli-serve/src/client/view/App.css
> +	z-index: -1;
z-index なしでも影響なかったりしませんか？

2019-04-24 05:02 UTC, xnv commented on packages/akashic-cli-serve/src/client/view/App.css
> +.bgImage {
周辺は kebab case になってるので合わせていただきたいです。

2019-04-24 09:53 UTC, kamakiri01 commented on packages/akashic-cli-serve/src/client/view/App.tsx
> +		console.log("this.props.store.sandboxConfig.backgroundImage", this.props.store.sandboxConfig.backgroundImage);
削除commitをpushしていませんでした 🙇

2019-04-24 09:53 UTC, kamakiri01 commented on packages/akashic-cli-serve/src/client/store/storage.ts
> +	showBgImage: boolean;
統一します。

2019-04-24 09:53 UTC, kamakiri01 commented on packages/akashic-cli-serve/src/client/view/App.css
> +	z-index: -1;
ツールバーに被ってしまうので残したいです。

2019-04-24 09:53 UTC, kamakiri01 commented on packages/akashic-cli-serve/src/client/view/App.css
> +.bgImage {
合わせます。

2019-04-25 03:14 UTC, xnv requested changes

2019-04-25 03:14 UTC, xnv commented on packages/akashic-cli-serve/src/client/view/App.css
> +		right: 0px;
他の箇所の 0 は単位省略してるので、合わせてもらえればと思います。

2019-04-25 03:14 UTC, xnv commented on packages/akashic-cli-serve/src/client/view/App.css
> +@media all and (-ms-high-contrast: none){
こ、これは……。

-ms-high-contrast でぐぐると真っ先に「使うな」って書かれてますが、妥当な方法でしょうか。 https://jeffreyfrancesco.org/weblog/2017042601/

単純に全プラットフォームで指定したらダメなんですかね。translateがまずそうですけど、 top 指定が使えないのも気になります。

2019-04-25 03:58 UTC, kamakiri01 commented on packages/akashic-cli-serve/src/client/view/App.css
> +@media all and (-ms-high-contrast: none){
うっっ…すみません
`_:-ms-lang(x)::-ms-backdrop, .bg-image { が妥当でしょうか。
https://qiita.com/feo52/items/932f57f9760d2b743d39

IE11を含む全プラットフォーム指定でレイアウトを崩さないCSSは、手元では作れませんでした…。

2019-04-25 03:58 UTC, kamakiri01 commented on packages/akashic-cli-serve/src/client/view/App.css
> +		right: 0px;
合わせます

2019-04-25 06:59 UTC, xnv commented on packages/akashic-cli-serve/src/client/view/App.css
> +@media all and (-ms-high-contrast: none){
恐ろしい hack ですね……。いえ、ひとまずそれで凌ぐのに異存はありませんが、知識なしに理解できる気がかなりしないので、コメントにその Qiita のページへのリンクを残しておいてほしいです。

2019-04-25 07:00 UTC, xnv approved these changes
(コメント追加してほしいなど) コメントつけましたが approved.

2019-04-25 07:00 UTC, xnv commented on packages/akashic-cli-serve/src/client/view/App.css
> +		transform: translateY(-50%);
インデントずれてます。

2019-05-07 04:51 UTC, kamakiri01 commented on packages/akashic-cli-serve/src/client/view/App.css
> +@media all and (-ms-high-contrast: none){
追加します。

2019-05-07 05:03 UTC, kamakiri01 commented on packages/akashic-cli-serve/src/client/view/App.css
> +		transform: translateY(-50%);
直します。

2019-05-07 05:32 UTC, merged