Support compress if zip extension with -o option of export-html
akashic-games/akashic-cli pull request #767
Opened 2021-06-08 06:24 UTC by ShinobuTakahashi

## 概要

export-html の output オプションの指定が `.zip` 拡張子の場合は、zip ファイルとして出力する。

2021-06-09 08:55 UTC, kamakiri01 approved these changes

2021-06-10 11:54 UTC, xnv requested changes

2021-06-10 11:54 UTC, xnv commented on packages/akashic-cli-export/src/html/exportHTML.ts
> +	const outputZip = param.output && !param.atsumaru ? path.extname(param.output) === ".zip" : false;
これのためだけに `atsumaru` オプションを渡すのは違和感があります。他にも `--atsumaru` かどうかで影響を受けるオプションがありますが、それらは呼び出し元で決定されているからです。

`param` (と  `p`) に「圧縮するか否か」の `compress?: boolean` オプションを設けて、呼び出し元で「 `--atsumaru` でなく、かつ末尾が `.zip` であるなら真」とかを渡しませんか。

2021-06-10 11:54 UTC, xnv commented on packages/akashic-cli-export/src/html/exportHTML.ts
> +			fs.renameSync(param.output, targetDir);
ユニークなディレクトリに移したいという処理だと思いますが、どうも処理が [上の mkdtemp()](https://github.com/akashic-games/akashic-cli/pull/767/files#diff-03a05a369dede93137d710888f0090bbe226bfd6013c39bb854da1b914fdf593R41) と重複していて気になります。

しかも `param.output` が例えば `./foo.zip` だったら、一度 `foo.zip/` というディレクトリを生成して出力したのち、それを適当にリネームし、 その後 `foo.zip` というファイルを作ってそこに保存する、という処理になっていて、なかなか厳しいややこしさに見えます。

よく考えると、やりたいことは「 (a) 絶対に重複しない一時ディレクトリにファイルを出力し、 (b) それを zip 圧縮して `param.output` に書き込む」なわけですが、この (a) は 「 `param.output` が指定されなかった時」の処理と全く同じなので、重複するのも宜なるかなという気がします。

----

そこで、こういう方針はどうでしょうか。

- 元の `promiseExportHtml()` は `promiseExportHtmlRaw()` として残す
   - この関数の出力先は必ずディレクトリ
- それを呼び出す関数 `promiseExportHtml()` を新設する
   - この関数は、追加で `compress` オプションも受け取り、それが真なら `param.output` を一時退避して (null にして) から `promiseExportHtmlRaw()` を呼び出す
   -  その結果得られた出力先パス (mkdtemp() で生成されたディレクトリ) の中身を、(退避しておいた本来の) `param.output` に圧縮して保存する

これだと

- 「ユニークなディレクトリ名」を作るのは `mkdtemp()` の一箇所だけで済みます
-   `promiseExportHtmlRaw()` の中では「出力先はディレクトリ」と決め打ちできるので、 [このあたり](https://github.com/akashic-games/akashic-cli/pull/767/files#diff-03a05a369dede93137d710888f0090bbe226bfd6013c39bb854da1b914fdf593R63-R74) の込み入ったチェックを増やさなくて済みます
-  特に全く同じ `mkdir(param.output)` をコピペする ([元のやつ](https://github.com/akashic-games/akashic-cli/pull/767/files#diff-03a05a369dede93137d710888f0090bbe226bfd6013c39bb854da1b914fdf593R49)・[増えたやつ](https://github.com/akashic-games/akashic-cli/pull/767/files#diff-03a05a369dede93137d710888f0090bbe226bfd6013c39bb854da1b914fdf593R69)) 必要もなくなります

2021-06-11 09:45 UTC, ShinobuTakahashi commented on packages/akashic-cli-export/src/html/exportHTML.ts
> +	const outputZip = param.output && !param.atsumaru ? path.extname(param.output) === ".zip" : false;
`compress` に変更し、呼び出し元で渡すよう修正しました。

2021-06-11 09:45 UTC, ShinobuTakahashi commented on packages/akashic-cli-export/src/html/exportHTML.ts
> +			fs.renameSync(param.output, targetDir);
ありがとうございます。`promiseExportHtml()`, `promiseExportHtmlRaw()` に修正しました。
ご指摘の方針で不要に増えたチェック処理等削ることができました。

2021-06-14 05:59 UTC, xnv approved these changes
コメント加えていますが approved.

2021-06-14 05:59 UTC, xnv commented on packages/akashic-cli-export/src/html/exportHTML.ts
> +		});
`throw` するだけなら後続で catch されるだけでしょうから、この部分はなくても動作に違いがなさそうです。

2021-06-14 07:54 UTC, ShinobuTakahashi commented on packages/akashic-cli-export/src/html/exportHTML.ts
> +		});
ありがとうございます。 仰る通り catch 部分がなくても動作に違いがなかったので削除しました。

2021-06-15 06:05 UTC, merged