新市場コンテンツ用のテンプレートを新規作成
akashic-games/akashic-cli pull request #77
Opened 2019-05-14 15:52 UTC by dera-

### 概要
* akashic-engineにて新市場コンテンツが作成されるケースが増えてきたので、akashic-cli-initで呼び出して使える新市場コンテンツ用のテンプレートを作ることにしました。

### やったこと
* 新市場コンテンツ用javascriptテンプレート(javascript-ichiba) の作成
  * コンテンツ自体はjavascriptテンプレートにラベルやスコア・制限時間の概念を追加しただけ
* テンプレートのzipファイル作成時にファイル名が`.`から始まるもの(今の所、`.eslintrc.json`のみ)が入っていない不具合があったので該当のファイルも入るように修正

2019-05-14 15:55 UTC, dera- commented on packages/akashic-cli-init/templates-src/javascript-ichiba/script/bootstrap.js
> +var main = require("./main.js");
セッションパラメーターの受け取りやRPGアツマール環境判定など、今までのテンプレートに無かった処理は、これまでテンプレートを使って開発しているユーザーのためにこちらのファイルに隠蔽して、main.jsでこれまで同様の書き換えができるようにしました。

2019-05-14 16:03 UTC, dera- commented on packages/akashic-cli-init/templates-src/javascript-ichiba/game.json
> +	"main": "./script/bootstrap.js",
今までmain.jsから起動していたのにbootstrap.jsから起動するように変更しました。
この辺りは名前的にも若干ユーザーの混乱を招くかもしれないという懸念はありますが、ゲーム部分記述用のファイルとしてのmain.jsの名前を変えるのも微妙なので一旦これで行きたいです

2019-05-14 16:06 UTC, dera- commented on packages/akashic-cli-init/templates-src/javascript-ichiba/script/bootstrap.js
> +	param.isAtsumaru = typeof window !== "undefined" && typeof window.RPGAtsumaru !== "undefined";
main.jsにできるだけ影響が出ないようにするために、起動引数にセッションパラメーターとRPGアツマールフラグを付与して渡してあげるようにしました。

2019-05-14 16:15 UTC, dera- commented on packages/akashic-cli-init/templates-src/javascript-ichiba/script/main.js
> +					window.RPGAtsumaru.experimental.scoreboards.setRecord(boardId, g.game.vars.gameState.score).then(function() {
RPGアツマールのAPIは若干長めではありますが、ラップする旨味が特になかったので剥き出しの状態になっている感じです。

2019-05-16 04:05 UTC, kamakiri01 approved these changes

2019-05-20 06:40 UTC, xnv requested changes

2019-05-20 06:40 UTC, xnv commented on packages/akashic-cli-init/templates-src/javascript-ichiba/script/main.js
> +	var time = 30; // 制限時間
デフォルト60秒ぐらいにしておきませんか。(新市場で現状来ていがちな値とそれほど乖離しない程度にしておくという意味で)

2019-05-20 06:40 UTC, xnv commented on packages/akashic-cli-init/templates-src/javascript-ichiba/script/main.js
> +		time = param.sessionParameter.totalTimeLimit;
ここもコメント欲しいです。「セッションパラメータで制限時間が指定されたらそれに合わせて動作する」ぐらいでいいので。

2019-05-20 06:40 UTC, xnv commented on packages/akashic-cli-init/templates-src/javascript-ichiba/game.json
> +	"main": "./script/bootstrap.js",
`_bootstrap.js` とか `shinichiba_bootstrap.js` とかでもいい気はしますね。

ついでに、 bootstrap.js の冒頭とかに「通常このファイルを編集する必要はありません。ゲームの処理は main.js に記述してください」とかコメントを加えておきたいです。

2019-05-20 06:40 UTC, xnv commented on packages/akashic-cli-init/templates-src/javascript-ichiba/script/main.js
> +	g.game.vars.gameState = { score: 0 };
ランキングモード ("ranking") に対応しないならこの処理は不要、ということを書いておきたいです。(RPGアツマールでスコアボード扱ってるところも)

2019-05-20 06:40 UTC, xnv commented on packages/akashic-cli-init/templates-src/javascript-ichiba/README.md
> +**javascript-game-sample-ichiba**はJavascriptで市場コンテンツを作る際のサンプルプロジェクトです。
「市場コンテンツ」は全体的に「ニコニコ新市場対応コンテンツ」にしたいです。

`ichiba` というのも `shinichiba` にしたいです。(`shin-ichiba` ?　とか迷いますが、少なくとも ichiba ではないはず)

2019-05-20 06:40 UTC, xnv commented on packages/akashic-cli-init/templates-src/javascript-ichiba/README.md
> +**javascript-game-sample-ichiba**はJavascriptで市場コンテンツを作る際のサンプルプロジェクトです。
あとこのコンテンツは ranking 用なので shinichiba-ranking かなあという気もします。

(あんまり細分化してもアレなので `shinichiba` でもいいと思うのですが、その場合はこの README の「利用方法」のところで、「作りたいゲームに応じて game.json の supportedModes 部分を編集してください」「マルチプレイの場合は "multi" にします」「"multi" の場合、main.js の game.vars.gameState.score を使う処理は不要なので、削除してください」というような、モード別の案内がほしいです。

2019-05-20 07:12 UTC, dera- commented on packages/akashic-cli-init/templates-src/javascript-ichiba/game.json
> +	"main": "./script/bootstrap.js",
了解しました、そのように修正しておきます。

2019-05-20 07:18 UTC, dera- commented on packages/akashic-cli-init/templates-src/javascript-ichiba/script/main.js
> +	var time = 30; // 制限時間
了解しました。コンテンツ的に60は長いかと思って30にしていたのですが、実際に送られる値に近い値にした方が親切な感じがしますね

2019-05-20 07:19 UTC, dera- commented on packages/akashic-cli-init/templates-src/javascript-ichiba/script/main.js
> +		time = param.sessionParameter.totalTimeLimit;
了解しました。追加しておきます。

2019-05-20 07:32 UTC, dera- commented on packages/akashic-cli-init/templates-src/javascript-ichiba/script/main.js
> +	g.game.vars.gameState = { score: 0 };
了解しました、コメントに記載しておきます。

2019-05-20 07:38 UTC, dera- commented on packages/akashic-cli-init/templates-src/javascript-ichiba/README.md
> +**javascript-game-sample-ichiba**はJavascriptで市場コンテンツを作る際のサンプルプロジェクトです。
ニコニコ新市場対応コンテンツと`shin-ichiba`(読みやすさで`shin-icchiba`の方が良いかなと思ってます)については了解しました。そのように文言を修正・統一していこうと思います。

それから、このテンプレートは新市場のランキングモードにしか対応していないので`shin-ichiba-ranking`と限定的にしてもいいのではと僕は思ってます。(マルチテンプレートを作る場合は別で`shin-ichiba-multi`といった感じのものを作ればいいのではと思ってます。)

2019-05-23 02:56 UTC, xnv approved these changes

2019-05-23 10:40 UTC, merged