テンプレートディレクトリを生成できるようにした
akashic-games/akashic-cli pull request #79
Opened 2019-05-15 12:09 UTC by dera-

### 概要
* 今までtemplate-srcにそのままzip化するためのテンプレートディレクトリを置いていましたが、各ディレクトリで重複する内容が多かったので、重複するものは1つにまとめて`npm run template`で各テンプレートディレクトリを出力するようにしました。

### 変更点
* template-srcに以下のディレトリを配置
  * game-～～
    * src(ts ファイルディレクトリ), audio, image, text, game.jsonというコンテンツとしてのリソースのみをここに置きました。
  * javascript-base
    * javascript プロジェクトで共通で利用するものをここに置きました。
  * typescript-base
    * typescript プロジェクトで共通で利用するものをここに置きました。
* build/generateTemplateSourceスクリプトの追加
  * template直下にテンプレートディレクトリを生成します。

2019-05-16 06:05 UTC, dera- commented on packages/akashic-cli-init/.gitignore
> +!template-list.json
template直下にテンプレートディレクトリを生成するようにしたので、template-list.json以外のものは全てignoreするようにしました

2019-05-16 06:08 UTC, dera- commented on packages/akashic-cli-init/build/generateTemplateSource.js
> +// typescriptテンプレートを作成
typescriptテンプレートディレクトリ作成でやっていることは割と単純で、game～～ディレクトリをjvascript～～にリネームしてコピー=>そのディレクトリにtypescript-baseに入っているファイル・ディレクトリをコピーくらしかやっていないです。

2019-05-16 07:36 UTC, dera- commented on packages/akashic-cli-init/build/generateTemplateSource.js
> +// javascriptテンプレートを作成
ここでは以下のようなことをやってます
1. game～～ディレクトリをjavascript～～にリネームしてコピー
2. javascript～～のビルド
3. javascriptテンプレートとして不要なファイル・ディレクトリの削除
4. javascript-baseに入っているファイル・ディレクトリをコピー

2019-05-16 07:37 UTC, dera- commented on packages/akashic-cli-init/build/generateTemplateSource.js
> +	execSync(`cp ${path.join(templatesSrcDirPath, "typescript-base", "tsconfig.json")} ${path.join(templatesDirPath, templateData[key]["js-dist"])}`);
ダーティー感ありますが、ビルドに必要なのでこの2つのファイルをtypescript-baseからコピーしてきています

2019-05-16 07:39 UTC, dera- commented on packages/akashic-cli-init/package.json
> +    "zip:js": "cd ./templates/javascript/ && bestzip ../../templates/javascript.zip ./ && cd .. && rm -rf javascript",
テンプレートディレクトリはzip化した後は不要になるので、ここで削除する処理も追加しました。
npmスクリプト内で削除処理入れるのはあまりよろしくない感じはありますが。。

2019-05-16 07:42 UTC, dera- commented on packages/akashic-cli-init/templates-src/game-default/src/main.ts
> +function main(param: g.GameMainParameterObject): void {
生成されるjavascriptファイルの可読性を保つために、テンプレート中のtypescriptファイルは型以外は可能な限りES5の書き方で書いています。

2019-05-16 07:55 UTC, dera- commented on packages/akashic-cli-init/templates-src/game-ichiba/src/bootstrap.ts
> +		param[key] = (originalParam as any)[key];
```
const param = {
    ...originalParam,
    sessionnParameter:~~,
    isAtsumaru:~~
};
```
という書き方をtypescript的にはすべきだと思いますが、その場合ビルド後のjsファイルの可読性が落ちる+ES5にはないObject.assignを使うものになってしまうので、このような書き方をしました。

2019-05-16 07:57 UTC, dera- commented on packages/akashic-cli-init/templates-src/javascript-base/README.md
>  # javascript-game-sample
これはpackage.jsonにも言えることですが、別のコンテンツなのに同じREADME.mdを使う用にしてしまったのですがこれは問題ないかを確認したいです。

2019-05-16 07:58 UTC, dera- commented on packages/akashic-cli-init/templates-src/javascript-base/package.json
> -  "main": "./script/main.js",
akashicコンテンツではmainは書かなくても問題ないですし、コンテンツによってエントリポイントが変わってしまうので削除しました。

2019-05-16 08:23 UTC, ndxbn commented on packages/akashic-cli-init/build/generateTemplateSource.js
> +	execSync(`cp ${path.join(templatesSrcDirPath, "typescript-base", "tsconfig.json")} ${path.join(templatesDirPath, templateData[key]["js-dist"])}`);
`rm -rf` とか、Windows で動かなさそう

2019-05-16 08:30 UTC, ndxbn commented on packages/akashic-cli-init/build/generateTemplateSource.js
> +	execSync(`cp ${path.join(templatesSrcDirPath, "javascript-base", ".eslintrc.json")} ${path.join(templatesDirPath, templateData[key]["js-dist"])}`);
`rm -rf` とか、Windows で動かなさそう

せめて、 [shelljs](https://github.com/shelljs/shelljs) を使うくらいのことはしたほうがいいと思います

2019-05-16 11:14 UTC, dera- commented on packages/akashic-cli-init/build/generateTemplateSource.js
> +	execSync(`cp ${path.join(templatesSrcDirPath, "javascript-base", ".eslintrc.json")} ${path.join(templatesDirPath, templateData[key]["js-dist"])}`);
ありがとうございます。Windows環境で動作させることを失念していました。shelljsを使うように修正します。

2019-05-16 14:22 UTC, ndxbn commented on packages/akashic-cli-init/build/generateTemplateSource.js
> +	execSync(`cp ${path.join(templatesSrcDirPath, "javascript-base", ".eslintrc.json")} ${path.join(templatesDirPath, templateData[key]["js-dist"])}`);
rimraf がすでに入ってるっぽいので、「ほんとに shelljs でいいの？rimraf の処遇考えたほうが良くない？」みたいなツッコミを @xnv 氏あたりから受けそうですが、さすがにそこまでは知らんので、おまかせしますねーー

2019-05-17 01:35 UTC, yu-ogi commented on packages/akashic-cli-init/build/generateTemplateSource.js
> +	execSync(`cp ${path.join(templatesSrcDirPath, "javascript-base", ".eslintrc.json")} ${path.join(templatesDirPath, templateData[key]["js-dist"])}`);
Node.js 上で動かすスクリプトなので `fs` を利用するのも一つの手かなと思いました。
https://nodejs.org/api/fs.html

2019-05-17 04:41 UTC, kamakiri01 commented on packages/akashic-cli-init/build/generateTemplateSource.js
> +	execSync(`cp ${path.join(templatesSrcDirPath, "javascript-base", ".eslintrc.json")} ${path.join(templatesDirPath, templateData[key]["js-dist"])}`);
同様の処理、export-htmlではshxを使っていますね https://github.com/akashic-games/akashic-cli-export-html/blob/master/package.json#L8

2019-05-17 07:36 UTC, ndxbn commented on packages/akashic-cli-init/build/generateTemplateSource.js
> +	execSync(`cp ${path.join(templatesSrcDirPath, "javascript-base", ".eslintrc.json")} ${path.join(templatesDirPath, templateData[key]["js-dist"])}`);
> 同様の処理、export-htmlではshxを使っていますね https://github.com/akashic-games/akashic-cli-export-html/blob/master/package.json#L8

補足

shx は shelljs を CLI から使えるようにする公式のラッパーなので、実質同じです。
他の akashic のモジュールでは shx （≒ shelljs ）を使っているよ、という情報提供でしょうか。しらんけど。

2019-05-20 06:09 UTC, xnv commented on packages/akashic-cli-init/templates-src/game-ichiba/src/parameterObject.ts
> +		totalTimeLimit?: number;
randomSeed や difficulty も加えておきたいです。
https://akashic-games.github.io/guide/ranking.html

2019-05-20 06:09 UTC, xnv commented on packages/akashic-cli-init/templates-src/game-ichiba/src/bootstrap.ts
> +declare const window: any;
`any` 避けたいです。一般論としてもそうですが、特にここで許すと `window` 以下何触ってもコンパイルを通ってしまうので……。せめて `RPGAtsumaru: any` しかないようにできないでしょうか。

2019-05-20 06:09 UTC, xnv commented on packages/akashic-cli-init/templates-src/game-ichiba/src/bootstrap.ts
> +	const param: any = {};
`{} as any as GameMainParameterObject` としておくと `as` 書くのがこの一箇所で済むかもしれません。

2019-05-20 06:09 UTC, xnv commented on packages/akashic-cli-init/templates-src/game-ichiba/src/main.ts
> +export function main(param: GameMainParameterObject): void {
`module.exports = main` と意味が違う記述になっていると思いますが意図通りでしょうか。

2019-05-20 06:09 UTC, xnv commented on packages/akashic-cli-init/build/generateTemplateSource.js
> +	execSync(`cp ${path.join(templatesSrcDirPath, "javascript-base", ".eslintrc.json")} ${path.join(templatesDirPath, templateData[key]["js-dist"])}`);
えっと。残る論点は「 rimraf と shelljs 重複してない？」でしょうか。rimraf 使ってるのって package scripts のとこなので、微妙に重複してないですよね……。(shx とこの使い方の rimraf なら完全に重複なんですが)

これのためにビルド用JSを shx 使うようにするのも回りくどい (あからさまに要らないプロセス起動が増える)ですし、package scripts の rimraf を shx にするのも牛刀割鶏って感じですし、若干重複感が微妙ですけど現状で妥当なんじゃないでしょうか。

2019-05-21 07:43 UTC, dera- commented on packages/akashic-cli-init/templates-src/game-ichiba/src/parameterObject.ts
> +		totalTimeLimit?: number;
追加しておきます

2019-05-21 07:44 UTC, dera- commented on packages/akashic-cli-init/templates-src/game-ichiba/src/bootstrap.ts
> +declare const window: any;
Window型を継承してプロパティとしてRPGAtsumaruを追加している型を新たに定義しようかと思います。

2019-05-21 07:45 UTC, dera- commented on packages/akashic-cli-init/templates-src/game-ichiba/src/bootstrap.ts
> +	const param: any = {};
ちょっと試してみようと思います

2019-05-21 07:48 UTC, dera- commented on packages/akashic-cli-init/templates-src/game-ichiba/src/main.ts
> +export function main(param: GameMainParameterObject): void {
補足を書くのを忘れていましたがここは意図通りですね。
`module.exports = main`にしたかったのですが、その場合tsだと外から参照できなかったのでこのように変更しました。おそらく`module.exports = main`のままでも参照する方法はあると思うのですがやり方が分からずという感じです。。

2019-05-21 11:39 UTC, dera- commented on packages/akashic-cli-init/templates-src/game-ichiba/src/main.ts
> +export function main(param: GameMainParameterObject): void {
上記方法ではなく従来通り`export = main;` にして利用側で`const main = require("./main")`を記述してビルドしたところrequireが見つからないと怒られました。
おそらく`@types/node`をインストールすれば問題は解決しそうですが、そのためだけにインストールするのもやりすぎ感あるので、requireが必要ないこちらの対応にしようかと思ってます

2019-05-22 06:00 UTC, dera- commented on packages/akashic-cli-init/build/generateTemplateSource.js
> +	execSync(`cp ${path.join(templatesSrcDirPath, "javascript-base", ".eslintrc.json")} ${path.join(templatesDirPath, templateData[key]["js-dist"])}`);
@xnv さんも仰ってますが、若干の重複はあるもののrimrafはnpm-scriptのみでshelljsはスクリプトファイル中でのみ使う用にしているので、どこで使うかさえきっちり切り分けられれば問題ないのではと僕は思ってます(具体的にどこかは忘れてしまったのですが、shelljsとrimrafをそのように使っているakashic-gamesのリポジトリもありますし)。
ですので、スクリプトファイルではshelljsを使う方向で行こうと思います。

2019-05-23 02:53 UTC, xnv requested changes

2019-05-23 02:53 UTC, xnv commented on packages/akashic-cli-init/templates-src/game-shin-ichiba-ranking/src/parameterObject.ts
> +export interface WindowWithRPGAtsumaru extends Window {
いや `Window` の他の要素にアクセスしてほしくなく (Akashic Engine の実行環境は `window` が存在することすら保証していません) 、例外的に「 `RPGAtsumaru` はあるかもしれない」という環境をかろうじて考慮したいだけなので、 `Window` を継承するのやめませんか。 `window.body` とか (何かの事情で意図してそうするのでもない限り) コンパイルが通らない方が嬉しいです。

2019-05-23 02:53 UTC, xnv commented on packages/akashic-cli-init/templates-src/typescript-base/tsconfig.json
> +    "lib": ["es5", "dom"],
必然この差分も要らないと思います。

2019-05-23 05:10 UTC, dera- commented on packages/akashic-cli-init/templates-src/game-shin-ichiba-ranking/src/parameterObject.ts
> +export interface WindowWithRPGAtsumaru extends Window {
了解しました。`Window`は継承せず`RPGAtsumaru`のみ持つように変更しました。(また、インターフェース名もRPGAtsumaruしか持ち得らない特殊なwindowという意味合いでRPGAtsumaruWindowという名前に変更しました)

2019-05-23 05:10 UTC, dera- commented on packages/akashic-cli-init/templates-src/typescript-base/tsconfig.json
> +    "lib": ["es5", "dom"],
`Window`が必要なくなったのでこちらも削除します

2019-05-24 07:13 UTC, kamakiri01 approved these changes

2019-05-28 07:13 UTC, xnv approved these changes

2019-05-30 05:19 UTC, merged