exportを行ったツールのexport時のバージョンとオプションが表示されるようにする対応
akashic-games/akashic-cli pull request #80
Opened 2019-05-16 15:14 UTC by dera-

# 概要
* exportされたコンテンツに不具合が発生した場合原因を絞り込みやすくするために、export-htmlとexport-zipでコンテンツのexport時のバージョンとオプションが表示されるようにする対応を行いました。
  * export-htmlはindex.htmlに、export-zipはgame.jsonに出力されるようにしました。

2019-05-17 04:52 UTC, kamakiri01 commented on packages/akashic-cli-export-html/src/app/cli.ts
> +			option: JSON.stringify(param)
paramのうち、 sourceとoutputは開発環境の情報になるため、省いても良いのではないかと思いました。

2019-05-17 06:38 UTC, dera- commented on packages/akashic-cli-commons/src/GameConfiguration.ts
> +export interface ExportZipInfo {
export-zipした時の情報(バージョンや実行オプション)を追加しました。ここで定義しておかないとexpot-zip側でgame.jsonにその情報が追記できないようになっていましたので。。
実際コンテンツで使われる値でもないので、わざわざここで定義すべきかどうか微妙ですが。。

2019-05-17 06:39 UTC, dera- commented on packages/akashic-cli-export-html/src/app/cli.ts
> +const ver = JSON.parse(fs.readFileSync(path.resolve(__dirname, "..", "package.json"), "utf8")).version;
利用するプロパティは先に定義しておくべきというlintエラーにひっかかったので移動しました。

2019-05-17 06:41 UTC, xnv commented on packages/akashic-cli-export-html/src/app/cli.ts
> +			option: JSON.stringify(param)
というか下手に入れると開発環境PCのフルパスが入り込みますね……。

2019-05-17 06:42 UTC, dera- commented on packages/akashic-cli-export-html/src/app/cli.ts
> +			option: JSON.stringify(param)
なるほど、確かにそうですね。。そちら除外する対応を行ってみます。

2019-05-17 06:45 UTC, dera- commented on packages/akashic-cli-export-html/templates/bundle-index.ect
> +<!-- And, execution option is <%- @exportOption %>. -->
export-htmlではこのような感じのコメントアウトでexport-html実行時の情報を表示しようかと考えてます。
これで問題なく情報が表示且つコンテンツが動くことは確認できましたが、他にいい感じの表示方法があれば教えていただきたいです。

2019-05-17 06:51 UTC, dera- commented on packages/akashic-cli-export-zip/src/cli.ts
> +			}
このコードを介さずに直接promiseExportZipが呼ばれた場合export-zip実行時のバージョンやオプションは取れなくなってしまいますが、今の所それが起きうるケースはexport-htmlをatsumaruオプションで実行した時だけでexport-html実行時の情報は取得できるので、そのケースの対応はしなくていいのではと考えていますが、必要な場合は教えていただければと思います。

2019-05-17 07:03 UTC, xnv requested changes

2019-05-17 07:03 UTC, xnv commented on packages/akashic-cli-export-html/templates/no-bundle-index.ect
> +<!-- And, execution option is <%- @exportOption %>. -->
直訳すると「このファイルがエクスポートされる時、akashic-cli-export-html のバージョンは vX.X.X です」みたいになっており、英文カタい気がするのですが、

```
Generated by akashic-cli-export-html@0.0.0.
Options: --strip --bundle --no-omit-empty-js
```

ぐらいではどうでしょう。(ref. [Javadoc の出力するコメント](https://codeday.me/jp/qa/20190304/322105.html))

オプションの形はこだわらないので `--` 作るのが手間だったら `{ "strip": true, bundle: "true" }` でもいいんですが。

2019-05-17 07:03 UTC, xnv commented on packages/akashic-cli-commons/src/GameConfiguration.ts
> +	option: any;
指摘出ていますが、実行時のオプションのうち、少なくとも cwd, source, output, exclude, injects あたりは出すべきでないと思います (全部精査してないので他にもあるかも) 。 boolean, number のものだけ出すのでもいいと思います。

変な値を入れ込んでトラブルにならないためにも、ここを `any` ではなくきちんと型をつけませんか。

2019-05-17 08:38 UTC, dera- commented on packages/akashic-cli-export-html/templates/no-bundle-index.ect
> +<!-- And, execution option is <%- @exportOption %>. -->
なるほど、javadocで使われている書き方なんですね。それで修正してみます。
ただ、オプションについては整形するのが若干手間だったので、json形式の書き方で行かせていただきたいです。オプションが増えてそれだと見づらくなる場合は整形することを検討してみようと思います。

2019-05-17 08:41 UTC, dera- commented on packages/akashic-cli-commons/src/GameConfiguration.ts
> +	option: any;
確かに、仰る通りですね。。こちら型を指定しておこうと思います。(型を指定しておくとoptionが増えた場合に都度修正が必要にばってしまいますが、事故が発生するよりは。。という感じですので。)

2019-05-20 10:30 UTC, xnv approved these changes
コメント加えましたが approved.

2019-05-20 10:30 UTC, xnv commented on packages/akashic-cli-export-html/src/app/cli.ts
> +			option: JSON.stringify(exportOption)
`exportParam` と `exportOption` があるの、かなり使い分けを読み取るのが難しいと思いますし、 `exportOption` は定義せずここに直接書いちゃえばいいんじゃないでしょうか。

2019-05-20 10:30 UTC, xnv commented on packages/akashic-cli-export-html/src/app/cli.ts
> +	// index.htmlに書き込むためのexport実行時の情報を作成する。また、開発環境の情報の削除も行う。
「開発環境の情報の削除を行う」のコメントは有用だと思いますが、ここでは単に `ExportZipInfo` の型に従っているだけだと思います。むしろ `ExportZipInfo` の定義のところにこそ、「このコマンドの実行時のオプション情報。エクスポート結果に埋め込む値であるため、実行環境のディレクトリの情報は持たせていないことに注意」のようなコメントがあると、将来の事故が防ぎやすいように思えます。

2019-05-21 08:16 UTC, dera- commented on packages/akashic-cli-export-html/src/app/cli.ts
> +			option: JSON.stringify(exportOption)
分かりました、そのように修正します。

2019-05-21 08:29 UTC, dera- commented on packages/akashic-cli-export-html/src/app/cli.ts
> +	// index.htmlに書き込むためのexport実行時の情報を作成する。また、開発環境の情報の削除も行う。
ここでは`ExportZipInfo`ではなく未定義なオブジェクトを使っています(`ExportZipInfo`とexporthtmlのオプションは完全に一致しませんし、ここでしか使わないものなので特に型定義もしていないです。)
ですので、index.htmlに書き込む情報であるという旨と開発環境の情報は除外しているという旨のコメントはここに残しておこうと思います

2019-05-22 03:09 UTC, kamakiri01 approved these changes

2019-05-22 05:31 UTC, merged