akashic-cli-init のテンプレートを追加
akashic-games/akashic-cli pull request #878
Opened 2021-10-13 02:52 UTC by yu-ogi

# このPullRequestが解決する内容
akashic-cli-init に次のテンプレートを追加します。
* `javascript-shin-ichiba-multi`
   * ニコ生向けのマルチプレイ JavaScript テンプレート
* `typescript-shin-ichiba-multi`
   * ニコ生向けの一人プレイ TypeScript テンプレート
* `javascript-atsumaru-multi`
   * アツマール向けのマルチプレイ JavaScript テンプレート
* `typescript-atsumaru-multi`
   * アツマール向けのマルチプレイ TypeScript テンプレート
* `javascript-atsumaru-ranking`
   * アツマール向けの一人プレイ JavaScript テンプレート
* `typescript-atsumaru-ranking`
   * アツマール向けの一人プレイ TypeScript テンプレート

2021-10-13 02:54 UTC, yu-ogi commented on packages/akashic-cli-init/build/generateTemplateSource.js
> +	return childProcess.execSync(command, { encoding: "utf-8" });
stdout の出力が ArrayBuffer になっていて解読が難しかったため文字列で出力するようにラップしました。

2021-10-13 02:56 UTC, yu-ogi commented on packages/akashic-cli-init/templates-src/game-shin-ichiba-ranking/game.json
> +		"nicolive": {
https://akashic-games.github.io/guide/shin-ichiba/shin-ichiba-intro.html

2021-10-15 03:00 UTC, xnv requested changes

2021-10-15 03:00 UTC, xnv commented on packages/akashic-cli-init/templates-src/game-atsumaru-multi/game.json
> +				"multi_admission"
これ [このへんの文書](https://akashic-games.github.io/guide/shin-ichiba/shin-ichiba-spec) が不親切な気がしていますが、 atsumaru では `"muti_admission"` がないので `"multi"` でお願いします。
https://akashic-games.github.io/guide/atsumaru.html#multi

2021-10-15 03:00 UTC, xnv commented on packages/akashic-cli-init/templates-src/game-atsumaru-ranking/game.json
> +				"ranking"
ranking もないので game-atsumaru-ranking は単に削除でお願いしたいです。

2021-10-15 03:00 UTC, xnv commented on packages/akashic-cli-init/templates-src/game-shin-ichiba-multi/game.json
> +{
ディレクトリ名、 shin-ichiba -> nicolive でお願いしたいです。

2021-10-15 03:00 UTC, xnv commented on packages/akashic-cli-init/templates/template-list.json
> +		"typescript-shin-ichiba-ranking": "typescript-shin-ichiba-ranking.zip",
shin-ichiba-ranking のみ、後方互換性のため nicolive-ranking nい読み替える……ような実装にしたいです。

2021-10-15 09:20 UTC, yu-ogi commented
こちら別作業を優先するため閉じます。

2021-10-15 09:20 UTC, closed without merging