feat(init): GitHub Enterprise でのテンプレート初期化に対応
akashic-games/akashic-cli pull request #881
Opened 2021-10-18 01:11 UTC by yu-ogi

## このPullRequestが解決する内容
* `-t ghe:<owner>/<repo>` により GitHub Enterprise からテンプレートを初期化できるようにします。
* akashic-cli-extra のテスト実行時にホームディレクトリに `.akashicrc` ファイルが生成される問題を修正します。

2021-10-18 01:15 UTC, yu-ogi commented on packages/akashic-cli-extra/src/config/config.ts
> +	const config = new AkashicConfigFile(validator, confPath);
別件ですがテスト実行するとホームディレクトリに .akashicrc が生成されてしまうので修正しました。

2021-10-18 01:15 UTC, yu-ogi commented on packages/akashic-cli-init/README.md
> -2. [Jasmine](http://jasmine.github.io "Jasmine")を使ったテスト
jasmine は使っていないため削除しました。

2021-10-18 01:17 UTC, yu-ogi commented on packages/akashic-cli-init/spec/cloneTemplateSpec.js
> +			"git clone --depth 1 https://github.com/akashic-games/akashic-template.git /path/to/dummy/dir"
git コマンドを直接利用するのではなくコマンドの文字列を比較するように修正しました。

2021-10-18 04:47 UTC, xnv requested changes

2021-10-18 04:47 UTC, xnv commented on packages/akashic-cli-init/README.md
> +akashic config set init.ghe.protocol ssh # 初回のみ。認証を必要としない場合は不要。
`init.github.protocol` でしょうか。

2021-10-18 04:47 UTC, xnv commented on packages/akashic-cli-init/src/InitParameterObject.ts
> +	param.githubProtocol =githubProtocol as GitProtocol;
空白欲しいです。

2021-10-18 04:47 UTC, xnv commented on packages/akashic-cli-init/src/InitParameterObject.ts
> +		const altVal = await altFunc;
関数でないものを `func` と呼ぶのは抵抗があります。むしろ `altFunc` こそ `altVal` と呼ぶ方が適当ではないでしょうか。

そうなるとここの `altVal` の方をなんと呼ぶか微妙ですが、まあ文脈的に await するものは一つしかないので `resolved` と呼んで `const resolved = await altVal;` とかでどうでしょうか。

他案:
- `const altVal = await altValPromise;` (Promise を明示する、仮引数名がやや長ったらしい)
-  `return (await altVal) || defaultVal;` (名前をつけずに済ませる)

2021-10-18 04:47 UTC, xnv commented on packages/akashic-cli-init/src/InitParameterObject.ts
> +		if (altVal) {
ここは `!= null` でなくてこう (空文字列でも `defaultVal` を採用する) でいいでしょうか。 `val != null` なのと非対称なのが気になりました。意図したものならコメントつけておきませんか。

2021-10-18 04:47 UTC, xnv commented on packages/akashic-cli-init/src/cli.ts
> +		"Type of template or a Git repository name (on github.com or GitHub Enterprise, requires git command)." +
長くなってきてしまったので、 `(on GitHub, requires git command)` だけにしてしまっても良さそうです。

2021-10-18 04:47 UTC, xnv commented on packages/akashic-cli-init/src/cloneTemplate.ts
> +	const gitBinPath = process.env.GIT_BIN_PATH ?? "git";
`completeInitParameterObject()` で補完してるのが `param` に渡ってきていませんか？

2021-10-18 05:59 UTC, yu-ogi commented on packages/akashic-cli-init/src/InitParameterObject.ts
> +		const altVal = await altFunc;
ああ、たしかに function では無かったです。こちら修正しました。 3228392

2021-10-18 06:00 UTC, yu-ogi commented on packages/akashic-cli-init/src/InitParameterObject.ts
> +		if (altVal) {
4e4e5b5 こちら `!= null` で比較するように修正しました。

2021-10-18 06:00 UTC, yu-ogi commented on packages/akashic-cli-init/src/cli.ts
> +		"Type of template or a Git repository name (on github.com or GitHub Enterprise, requires git command)." +
310d83b こちら修正しました。

2021-10-18 06:00 UTC, yu-ogi commented on packages/akashic-cli-init/src/cloneTemplate.ts
> +	const gitBinPath = process.env.GIT_BIN_PATH ?? "git";
321916a こちら修正しました。

2021-10-18 06:01 UTC, yu-ogi commented on packages/akashic-cli-init/src/InitParameterObject.ts
> +	param.githubProtocol =githubProtocol as GitProtocol;
8db47fd こちら修正しました。

2021-10-18 06:01 UTC, yu-ogi commented on packages/akashic-cli-init/README.md
> +akashic config set init.ghe.protocol ssh # 初回のみ。認証を必要としない場合は不要。
fadf7b5 こちら修正しました。

2021-10-18 07:15 UTC, dera- reviewed
そもそも今回のPRの目的について確認したいのですが、今回の変更でghe中のコンテンツをテンプレートとしてそのままコピーできるようになるという認識でよろしいでしょうか？(ちなみにgithub側ではもうそれが既にできているということで大丈夫ですかね？)

2021-10-18 07:15 UTC, dera- commented on packages/akashic-cli-init/src/InitParameterObject.ts
> +	 gitBinPath?: string;
これらのパラメータをコマンドから受け取る処理が見当たりませんでしたが、この辺りのパラメータの指定については今回のスコープに入っていないということでしょうか？

2021-10-18 07:28 UTC, yu-ogi commented on packages/akashic-cli-init/src/InitParameterObject.ts
> +	 gitBinPath?: string;
確かにコマンドから受け取ることはできませんが、環境変数 `GIT_BIN_PATH ` で受けるようにしています。なのでパラメータの指定ができないというわけではないです。
https://github.com/akashic-games/akashic-cli/blob/310d83b99afa087af0aebb5f3d7804ffe2ffdf0c/packages/akashic-cli-init/src/InitParameterObject.ts#L116

2021-10-18 07:30 UTC, yu-ogi commented
> そもそも今回のPRの目的について確認したいのですが、今回の変更でghe中のコンテンツをテンプレートとしてそのままコピーできるようになるという認識でよろしいでしょうか？(ちなみにgithub側ではもうそれが既にできているということで大丈夫ですかね？)

はい、そうです。関連PR (#869) のリンクを張り忘れていたので PullRequest の説明文に追記しておきました。

2021-10-18 07:33 UTC, dera- approved these changes

2021-10-19 04:41 UTC, xnv approved these changes

2021-10-19 04:47 UTC, merged