Change akashic init test to ts
akashic-games/akashic-cli pull request #926
Opened 2021-11-29 09:15 UTC by ShinobuTakahashi

## 概要

akashic-cli-init のテストファイルの修正
- js から ts ファイルへ
- async/await 化
-  lint 適応

2021-11-29 09:17 UTC, ShinobuTakahashi commented on packages/akashic-cli-init/spec/.eslintrc.js
> +	}
テストで内容が空の関数と、1行での記述を許可

2021-12-01 02:38 UTC, xnv commented
ts-jest を使ってるのと使ってないのが入り交じっちゃってきてる現状ですが、 ts-jest を使うリポジトリは src/__tests__/ にテストを置く形になってるので、これもそれに合わせませんか。

2021-12-01 02:59 UTC, xnv requested changes

2021-12-01 02:59 UTC, xnv commented on packages/akashic-cli-init/spec/cloneTemplateSpec.ts
> +const mockExec: any = child_process.exec;
jest.Mock が使えれば any よりは良さそうです。
https://hisa-web.net/archives/1021

2021-12-01 02:59 UTC, xnv commented on packages/akashic-cli-init/spec/BasicParametersSpec.ts
> +					expect(err).toBe("width must be a number");
このへん、例外が throw されないと何も expect() せず単に終了するテストになってしまっていませんか。 起きるべき例外がなければ `fail()` とかで明示的に失敗させたいです。

2021-12-01 02:59 UTC, xnv commented on packages/akashic-cli-init/spec/TemplateMetadataSpec.ts
> +			const mockFn = jest.fn<Promise<any[]>, [any]>(fetchRemoteTemplatesMetadata);
これなんで jest.fn が必要なんですっけ？

2021-12-01 04:01 UTC, xnv commented on packages/akashic-cli-init/spec/support/mockConfigFile.ts
> +export class MockTemplateFile extends AkashicConfigFile {
これ元々の名前がよく分からない (template-list.json で宣言されるテンプレートと紛らわしい) ので、 (元々 `require()` する側でそう名付けられていたように) `MockConfigFile` にしませんか。

2021-12-02 02:25 UTC, ShinobuTakahashi commented on packages/akashic-cli-init/spec/support/mockConfigFile.ts
> +export class MockTemplateFile extends AkashicConfigFile {
`MockConfigFile` に修正いました。

2021-12-02 02:25 UTC, ShinobuTakahashi commented on packages/akashic-cli-init/spec/TemplateMetadataSpec.ts
> +			const mockFn = jest.fn<Promise<any[]>, [any]>(fetchRemoteTemplatesMetadata);
テスト対象の関数の引数に違う型が渡された場合エラーとなるテストですが、TypeScriptなので引数に違う型を渡せないため、`jest.fn` で異なる型を渡せるようにしています。

2021-12-02 02:25 UTC, ShinobuTakahashi commented on packages/akashic-cli-init/spec/BasicParametersSpec.ts
> +					expect(err).toBe("width must be a number");
ありがとうございます。`fail()` は DoneCallback でしか使用できないので、`throw` で失敗するよう修正しました。

2021-12-02 02:25 UTC, ShinobuTakahashi commented on packages/akashic-cli-init/spec/cloneTemplateSpec.ts
> +const mockExec: any = child_process.exec;
ありがとうございます。相容れないデータ型のため 型アサーション時に `unknown` をはさみましたが jest.Mock へ修正できました。

2021-12-02 02:28 UTC, ShinobuTakahashi commented
テストファイルのディレクトリを `./spec` から `./src/__tests__` へ移動しました。

2021-12-02 04:32 UTC, xnv requested changes

2021-12-02 04:32 UTC, xnv commented on packages/akashic-cli-init/spec/TemplateMetadataSpec.ts
> +			const mockFn = jest.fn<Promise<any[]>, [any]>(fetchRemoteTemplatesMetadata);
うーんと、このテストは「 template-list.json の `formatVersion` の値が未知のもので、それを正しくエラーにできるか確認する」ものです。型が違うからエラーになるわけではないと思います (もし型がまずいなら、 `catch` 節で `err.message` の値が想定どおりにならずテスト失敗するはずです)。

元のテストが間違っていて、 `fetchRemoteTemplatesMetadata()` に `string` ではなく `URL` を渡してしまっていたかと思います (現実には内部的に `toString()` されて問題なかったのだと思いますが) 。この箇所も [上のテスト](https://github.com/akashic-games/akashic-cli/pull/926/files/83fcfbc10c5586ee3a05683f64aa314a38088d6e#diff-67117b94fb013704b8613b594ce00b7e6b18a9c06704b12502a16be416594047R28) 同様 `toString()` していただくべきに思いますし、またそうすれば `jest.fn()` はやはり不要なのではないでしょうか。

2021-12-02 06:30 UTC, ShinobuTakahashi commented on packages/akashic-cli-init/spec/TemplateMetadataSpec.ts
> +			const mockFn = jest.fn<Promise<any[]>, [any]>(fetchRemoteTemplatesMetadata);
すいません、問題の理解を根本的に間違っていました。
仰る通り、引数を `.toString()` して渡せば、`jest.fn` は不要でしたので修正しました。

2021-12-03 02:57 UTC, xnv commented on packages/akashic-cli-init/spec/BasicParametersSpec.ts
> +					expect(err).toBe("width must be a number");
うーん、 `throw` だと「投げる例外の内容がたまたま (問題の関数が投げてくるものと) 違う」ことに依存しているのがちょっとひっかかります。実害はほぼありませんが、 `Promise` 返してるので [`expect().rejects`](https://jestjs.io/ja/docs/asynchronous#resolves--rejects) で綺麗に扱えたりしませんかね。

2021-12-03 02:58 UTC, xnv approved these changes
コメント加えましたが approved.

2021-12-03 04:34 UTC, ShinobuTakahashi commented on packages/akashic-cli-init/spec/BasicParametersSpec.ts
> +					expect(err).toBe("width must be a number");
ありがとうございます。`expect().rejects.xxx()`で throw 使用せず正常/異常を扱えたので修正しました。

2021-12-03 11:16 UTC, kamakiri01 commented on packages/akashic-cli-init/src/__tests__/InitParameterObjectSpec.ts
> +import * as  path from "path";
空白が1つ多そうです。
https://github.com/akashic-games/akashic-cli/pull/926/files 以下でページ内検索で空白2つをキーワードにすると他の箇所も見つけられそうです。（この辺りeslintが拾って欲しいですが、検知しないみたいですね…）

lintに絡むのでコメントまとめてしまいますが、 `__tests__/.eslintrc.js` は使っていないように見えるので、root以下の `.eslintrc.js` に統一しても良さそうだなと思いました。

2021-12-03 11:20 UTC, kamakiri01 commented on packages/akashic-cli-init/src/__tests__/.eslintrc.js
> +		project: "tsconfig.json",
root直下の `.eslintrc.js` では `"./tsconfig.json" パス記述なので、特に事情が無ければ記法を揃えても良いかなと思いました。

2021-12-06 01:37 UTC, ShinobuTakahashi commented on packages/akashic-cli-init/src/__tests__/InitParameterObjectSpec.ts
> +import * as  path from "path";
ありがとうございます。不要な空白削除しました。

2021-12-06 01:37 UTC, ShinobuTakahashi commented on packages/akashic-cli-init/src/__tests__/.eslintrc.js
> +		project: "tsconfig.json",
`./tsconfig.json` へ揃えるよう修正しました。

2021-12-06 04:58 UTC, kamakiri01 approved these changes

2021-12-07 02:31 UTC, merged