Add confirm of access to unofficial URL in akashic-init
akashic-games/akashic-cli pull request #929
Opened 2021-12-01 05:18 UTC by ShinobuTakahashi

## 概要

akashic-init で オプション `-t` の値が `github:xxx`, `ghe:xxx` や `-r` の値に非公式な URL が指定された場合、その URL へのアクセスを許可するかプロンプトにてユーザ確認するようにします。

#916 へマージします

2021-12-01 06:12 UTC, ShinobuTakahashi commented on packages/akashic-cli-init/src/common/InitCommonOptions.ts
> +export const DEFAULT_TEMPLATE_REPOSITORY = "https://akashic-contents.github.io/templates/";
他ファイルでも参照するため、定数として大文字にしました。

2021-12-01 06:41 UTC, dera- commented on packages/akashic-cli-init/src/cli.ts
> +		if (param.repository === DEFAULT_TEMPLATE_REPOSITORY) {
これは非公式なURLな場合に入る想定の分岐ですよね？であれば条件式は`param.repository !== DEFAULT_TEMPLATE_REPOSITORY`のように思えます。あと、コメントも不要なように思えます。

2021-12-01 06:50 UTC, ShinobuTakahashi commented on packages/akashic-cli-init/src/cli.ts
> +		if (param.repository === DEFAULT_TEMPLATE_REPOSITORY) {
仰る通りです。デバッグで使用していたコードのままでした。修正しました。

2021-12-01 10:31 UTC, xnv requested changes

2021-12-01 10:31 UTC, xnv commented on packages/akashic-cli-init/src/cli.ts
> +					description: `Allow access to this URL(${url})? y/n`,
初見のユーザに背景が伝わるように情報を加えたいです。こんな感じですかね……。

```
(空行)
Attempting to connect to https://....
The template obtained here may cause arbitrary command execution (not by this command but by using the template).
You should not use this URL unless you trust its owners and contents.
Do you trust the owners and contents of this URL? (y/n)
```

内容全然違いますが参考: https://code.visualstudio.com/docs/editor/workspace-trust

2021-12-01 10:31 UTC, xnv commented on packages/akashic-cli-init/src/cli.ts
> +					default: "y"
n にしたいです。

2021-12-01 10:31 UTC, xnv commented on packages/akashic-cli-init/src/cli.ts
> +		}
全体的に validation が増えてきちゃいますが、こうなると集約したいです。 `completeInitCommonOptions()` など、 `complete〜()` の中で行いませんか。

2021-12-01 10:31 UTC, xnv commented on packages/akashic-cli-init/src/cli.ts
> +				const ret = await confirmAccessToUrl(param.type);
param.type だけだと URL にならないので、 URL にしてから表示したいです。
上の `param.type.match()` の箇所といい、 `cloneTemplate.ts` あたりから一部の処理を関数として切り出してきて使うのはどうでしょうか。

2021-12-03 02:37 UTC, ShinobuTakahashi commented on packages/akashic-cli-init/src/cli.ts
> +					description: `Allow access to this URL(${url})? y/n`,
ありがとうございます。説明文修正しました。

2021-12-03 02:37 UTC, ShinobuTakahashi commented on packages/akashic-cli-init/src/cli.ts
> +					default: "y"
デフォルト値 `n` へ修正しました。

2021-12-03 02:37 UTC, ShinobuTakahashi commented on packages/akashic-cli-init/src/cli.ts
> +		}
共通となる `repository` の値は -l オプションでも必ず入る`completeInitCommonOptions()` 中で行うようにし、 -t の `github`, `ghe` 値の validate は必要な値が揃った後の `completeInitParameterObject()`の中で行うように修正しました。

2021-12-03 02:37 UTC, ShinobuTakahashi commented on packages/akashic-cli-init/src/cli.ts
> +				const ret = await confirmAccessToUrl(param.type);
`clonetemplate.ts` に一部関数を作成、既存の`createGitUri()` をexport して使用し、URLで表示できるよう修正しました。

2021-12-03 02:39 UTC, ShinobuTakahashi commented on packages/akashic-cli-init/src/cli.ts
> -
InitParameterObject.ts の `completeInitParameterObject()` へ移動しました。

2021-12-03 02:43 UTC, ShinobuTakahashi commented on packages/akashic-cli-init/src/init/cloneTemplate.ts
> +}
良い名前が思いつかず、uri のパーツオプジェクトとしました。他良い名前があれば...

2021-12-07 04:11 UTC, xnv commented on packages/akashic-cli-init/src/init/cloneTemplate.ts
> +}
微妙なところですね。パーツ……やりたいことは git clone の対象の切り出しなので `parseCloneTargetInfo(...): CloneTargetInfo` ぐらいでどうでしょう。

2021-12-07 04:44 UTC, dera- approved these changes

2021-12-07 05:11 UTC, ShinobuTakahashi commented on packages/akashic-cli-init/src/init/cloneTemplate.ts
> +}
ありがとうございます。パーツより適切な名前かと思いますので、`parseCloneTargetInfo()`, `CloneTargetInfo` へ変更しました。

2021-12-08 09:17 UTC, xnv approved these changes
コメント加えていますが approved.

2021-12-08 09:17 UTC, xnv commented on packages/akashic-cli-init/spec/cloneTemplateSpec.js
> +});
listTemplateSpec.ts と同じように `beforeAll()` でやりませんか。

2021-12-08 09:17 UTC, xnv commented on packages/akashic-cli-init/src/init/InitParameterObject.ts
> +		const url = createGitUri(githubHost, githubProtocol, owner,  repo);
`repo` の前に空白が二つ入っています。

2021-12-08 09:18 UTC, xnv commented on packages/akashic-cli-init/src/common/InitCommonOptions.ts
> +						+ "Do you trust the owners and contents of this URL? (y/n)",
すいません、ここ私のコメントがまずかったんですが、デフォルト値示すために `y/N` にしたいです。

2021-12-08 09:37 UTC, ShinobuTakahashi commented on packages/akashic-cli-init/spec/cloneTemplateSpec.js
> +});
`beforeAll()` で spyOn するよう修正しました。

2021-12-08 09:37 UTC, ShinobuTakahashi commented on packages/akashic-cli-init/src/init/InitParameterObject.ts
> +		const url = createGitUri(githubHost, githubProtocol, owner,  repo);
ありがとうございます。空白削除しました。

2021-12-08 09:37 UTC, ShinobuTakahashi commented on packages/akashic-cli-init/src/common/InitCommonOptions.ts
> +						+ "Do you trust the owners and contents of this URL? (y/n)",
`y/N` へ修正しました。

2021-12-09 02:13 UTC, merged