何も変更を加えずにpublishするnpm-scriptを追加
akashic-games/akashic-cli pull request #94
Opened 2019-06-11 08:14 UTC by dera-

### 概要
* 現状publishに失敗した場合の再publish手段が用意されていなかったので、何も変更を加えずにpublishするスクリプト(`publish:empty`)をnpm-scriptに追加した

### やったこと
* `build/updateChangelog.js`でemptyという引数を受け取れるようにした

2019-06-11 08:16 UTC, dera- commented on build/updateChangelog.js
> +	addedLog = `\n## ${nextVersion}\n* Ignorable change to fix broken publish ${packageJson["version"]}\n`;
何も変更を加えてない場合lerna-changelogでは何も出力されないので、代わりに固定の文言をCHANGELOGに書き込むようにしました

2019-06-19 07:21 UTC, yu-ogi approved these changes

2019-06-19 12:04 UTC, xnv approved these changes

2019-06-24 07:55 UTC, dera- commented on build/updateChangelogAndPublish.js
> +	console.log("end to publish");
headless-driverに合わせて、今までnpm-scriptに書いていた内容をスクリプトファイルにまとめるようにしました。

2019-06-24 11:30 UTC, xnv requested changes

2019-06-24 11:30 UTC, xnv commented on package.json
> +    "publish:force-patch-all": "node build/updateChangelogAndRepublish.js patch",
`updateChangelogAndPlublish.js` と `updateChangelogAndRepublish.js` が非常に紛らわしいと思うのですが、そもそも publish と republish を区別するモチベーションはあるでしょうか？

感覚的には、従来の `"publish:patch"`, `"publish:minor"` などはそのままで、 `prepareRepublish.js` (ラベルをつけた空PRを作ってマージするだけ) を加えれば、

```
"publish:force-patch-all": "node build/prepareRepublish.js && npm run publish:patch"
```

と定義でき、簡潔かつ直観的ではありませんか。

2019-06-24 11:30 UTC, xnv commented on package.json
> +    "publish:force-patch-all": "node build/updateChangelogAndRepublish.js patch",
非常に素朴な話、1行で済んでいた npm scripts が 50 行超の JS ファイルになるというのは、できれば避けたいことだと思います。

2019-06-24 12:42 UTC, dera- commented on package.json
> +    "publish:force-patch-all": "node build/updateChangelogAndRepublish.js patch",
すみません、updateChangelog.jsは更新するモジュールがあるかどうかのチェックだけ消して(
republish時に引っかかってしまうため+この判定は変更がない場合にpublishまでの処理が進んでしまうのを止めるためのものだが無くても特に問題ない)それ以外は残しておこうと思います。そして、変更の無いPRだけ作るスクリプトを新たに用意しておきます。

2019-06-28 05:37 UTC, xnv approved these changes

2019-07-01 01:10 UTC, yu-ogi approved these changes

2019-07-02 07:01 UTC, merged