check operationPlugin script is root path or module name
akashic-games/akashic-cli pull request #941
Opened 2021-12-07 13:33 UTC by kamakiri01

## このpull requestが解決する内容

`akashic export zip` コマンドの対象コンテンツが Operation Plugin を利用しており、その script にルートスクリプトではなくモジュール名が指定されていた時、正常に export できない不具合を修正します。

## 破壊的な変更を含んでいるか?

- なし

2021-12-08 08:20 UTC, dera- approved these changes

2021-12-08 08:38 UTC, xnv commented on packages/akashic-cli-export/src/zip/convert.ts
> +				if (gamejson.moduleMainScripts?.[pluginRootOrModuleName]) {
もともと問題になった「モジュール名のみ」に関してはこのコードで扱えそうですが、よく考えると、 `@akashic-extension/foo-plugin/lib` などモジュール名の後にさらにパスが続く形式だと動作しなさそうです。

`plugin.script` の値は `require()` (Akashic Engine 内の `require()` ですが) に渡されるものなので、単純に `require.resolve()` でファイルパスを得ることはできないでしょうか？ (`moduleMainScripts` の更新時と同じような処理をやることになるので無駄といえば無駄ですが、モジュール内のサブディレクトリの index.js のハンドリングとか考えるとこれが一番簡単そうです)

ただしこの時、ゲームのディレクトリ (`param.source`) より上のディレクトリを検索しない (か、または検索して見つかっても使わない) 対応は必要になるかと思います。

また、この修正を確認するテストを追加がほしいです。

2021-12-13 12:04 UTC, kamakiri01 commented on packages/akashic-cli-export/src/zip/convert.ts
> +				if (gamejson.moduleMainScripts?.[pluginRootOrModuleName]) {
nodejs の `require.resolve()` を使うよう修正します。

2021-12-16 02:42 UTC, xnv requested changes

2021-12-16 02:42 UTC, xnv commented on packages/akashic-cli-export/src/zip/convert.ts
> +					pluginRootPath = pluginRoot.replace(/^\.\//g, "");
- 行頭の一箇所にしか引っかからないしそれしか変えたくないので `g` フラグは不要かと思います。
- というかこの `replace()` なくてもあとの `path.join()` がよろしく処理してくれそうな？

2021-12-16 02:42 UTC, xnv commented on packages/akashic-cli-export/src/zip/convert.ts
> +				let pluginRootPath: string;
`pluginRoot` と `pluginRootPath` の関係性が読み取りづらいように思います。これは `actualPluginRoot` とするのはどうでしょうか。

2021-12-16 02:42 UTC, xnv commented on packages/akashic-cli-export/src/zip/convert.ts
> +				if (pluginRoot.indexOf("./") === 0) {
大した影響はないと思いますが、一般論として、 indexOf() だと文字列全てを無駄に線形探索するのが気になります。 Node.js でしか動かないコードですし `.startsWith()` を使いませんか。

2021-12-16 02:42 UTC, xnv commented on packages/akashic-cli-export/src/zip/convert.ts
> +					const pluginModuleName = pluginRoot.replace(/\/$/, "");
この `replace()` なくても `require.resolve()` に影響はないのではないでしょうか。

2021-12-16 02:42 UTC, xnv commented on packages/akashic-cli-export/src/zip/convert.ts
> +					pluginRootPath = relativeRootPath;
replace 不要そうなこともあり、 "tmp" を持ち込むぐらいなら一行で書いちゃう方がクリーンそうです。

```typescript
actualPluginRoot = path.relative(param.source, require.resolve(pluginRoot, { paths: [param.source] }));
```

また、異常系として `startsWith("../")` が真になるケースはエラーにしたいです。(ゲーム外のスクリプトを require() で拾ってきてしまった状況)

2021-12-16 05:09 UTC, kamakiri01 commented on packages/akashic-cli-export/src/zip/convert.ts
> +					pluginRootPath = pluginRoot.replace(/^\.\//g, "");
省略して`path.join()` に任せるようにします。

2021-12-16 05:09 UTC, kamakiri01 commented on packages/akashic-cli-export/src/zip/convert.ts
> +				let pluginRootPath: string;
確かに tmp の指す意味が曖昧なので、リネームします。

2021-12-16 05:09 UTC, kamakiri01 commented on packages/akashic-cli-export/src/zip/convert.ts
> +				if (pluginRoot.indexOf("./") === 0) {
修正します。

2021-12-16 05:09 UTC, kamakiri01 commented on packages/akashic-cli-export/src/zip/convert.ts
> +					const pluginModuleName = pluginRoot.replace(/\/$/, "");
省略して `require.resolve()` に任せるようにします。

2021-12-16 05:10 UTC, kamakiri01 commented on packages/akashic-cli-export/src/zip/convert.ts
> +					pluginRootPath = relativeRootPath;
整理とエラー系処理追加します。

2021-12-17 04:49 UTC, xnv approved these changes
コメントつけていますが approved.

2021-12-17 04:49 UTC, xnv commented on packages/akashic-cli-export/spec/fixtures/simple_game_with_operation_plugins/game.json
> +
不要な空行です。

2021-12-17 04:49 UTC, xnv commented on packages/akashic-cli-export/src/zip/convert.ts
> +					actualPluginRoot = relativeRootPath;
もはや代入するだけですし、この変数もなくしていきなり `actualPluginRoot` に代入すればよさそうです。

2021-12-17 04:49 UTC, xnv commented on packages/akashic-cli-export/src/zip/convert.ts
> +					if (relativeRootPath.startsWith("../")) throw new Error("Operation plugin path should not start with ../ .");
ユーザが自分で「 `../` 」と書いたわけではないので、このエラーメッセージを見ても状況が伝わらなそうです。「npm モジュール名の指す先を探したら `../` になってしまった」という状況なので、エラーメッセージとしては ``` `${pluginRoot} refers outside of the game (${relativeRootPath})` ``` ぐらいがよいのではないでしょうか。

2021-12-17 08:29 UTC, kamakiri01 commented on packages/akashic-cli-export/src/zip/convert.ts
> +					actualPluginRoot = relativeRootPath;
確かにそうですね。直します。

2021-12-17 08:29 UTC, kamakiri01 commented on packages/akashic-cli-export/src/zip/convert.ts
> +					if (relativeRootPath.startsWith("../")) throw new Error("Operation plugin path should not start with ../ .");
使わせていただきます。

2021-12-20 12:18 UTC, merged