akashic-cli-initのjavascriptテンプレートの.eslintrc.jsonの修正
akashic-games/akashic-cli pull request #96
Opened 2019-06-11 11:34 UTC by dera-

### やったこと
* akashic-cli-initのjavascriptテンプレートの.eslintrc.jsonに以下のような改修を行いました
  * 全角スペースは以下の場合は使用することを許可
    * コメントアウト内
    * 文字列内
    * 正規表現内
    * テンプレートリテラル内
  * 未定義の変数の使用を禁止
    * ただし、`globals`に定義されているものやcommonjs, amdで定義されているものについては許可

2019-06-14 03:22 UTC, xnv requested changes

2019-06-14 03:22 UTC, xnv commented on packages/akashic-cli-init/templates-src/javascript-base/.eslintrc.json
> +    "self": false,
global や self って要らないのでは……？

2019-06-14 03:22 UTC, xnv commented on packages/akashic-cli-init/templates-src/javascript-base/.eslintrc.json
> +    "amd": true
commonjs の指定で module が使えるようになっているか確認したいです。 amd いらなそうです。

2019-06-14 07:41 UTC, dera- commented on packages/akashic-cli-init/templates-src/javascript-base/.eslintrc.json
> +    "self": false,
export後のjsファイルに対してeslintをかける場合に必要かと思ってましたが、そもそもその用途は無いとのことでしたのでこちら削除しておきます

2019-06-14 08:19 UTC, dera- commented on packages/akashic-cli-init/templates-src/javascript-base/.eslintrc.json
> +    "amd": true
上記と同様の理由でamdも入れてしまったので削除しました。
commonjsの指定で`module`, `expotrs`, `require` が使えるようになることを確認しましたのでこちらは書いたままにしておこうと思います。

2019-06-17 02:56 UTC, xnv approved these changes

2019-06-20 04:21 UTC, kamakiri01 approved these changes

2019-06-20 09:20 UTC, merged