Add inject engine files option to export html
akashic-games/akashic-cli pull request #983
Opened 2022-01-14 05:54 UTC by ShinobuTakahashi

## 概要

export html のオプションに指定した engineFiles を使用して export を行う `--inject-engine-files` を追加。
指定された engineFiles のファイル名が `engineFilesVx_x_x` にマッチしない場合はエラーとします。

2022-01-14 05:57 UTC, ShinobuTakahashi commented on packages/akashic-cli-export/src/html/cli.ts
> +	.option("--inject-engine-files <filePath>", "Use the injected engineFiles");
内容そのまま engineFIles を注入する `--inject-engine-files` とオプション名としました。

2022-01-14 12:01 UTC, dera- commented on packages/akashic-cli-export/src/html/convertNoBundle.ts
> +		if (matches) version = matches[0].slice(0, 1);
game.jsonに指定されているバージョンとengineFilesのバージョンが異なっていた場合engineFilesのバージョンが優先されるという仕様になっていますが、基本的にコンテンツはgame.jsonに指定されているバージョン前提で書かれていると思うのでengineFilesのバージョンが異なる場合はエラーにしたほうが良いのではという気がしています

2022-01-14 12:01 UTC, dera- commented on packages/akashic-cli-export/src/html/convertNoBundle.ts
> +		engineFilesVariable = path.basename(options.injectEngineFiles, ".js");
engineFilesのバージョンを取得する処理は関数に切り出せるように思えます。そうするとbundle時もno-bundle時も使いまわすことが可能になるかと思います

2022-01-17 07:15 UTC, xnv requested changes

2022-01-17 07:15 UTC, xnv commented on packages/akashic-cli-export/src/html/cli.ts
> +	.option("--inject-engine-files <filePath>", "Use the injected engineFiles");
もともと必ず同梱されるファイルを別のに "差し替える" 機能なので、  inject/注入する とはニュアンスが異なるように思います。現行ある `--inject` も、デフォルトでは何も出力されない場所に追加的に "注入する" オプションですし。

また通常のゲーム開発時に使う機能ではないこともあり、 `--debug-` を頭につけておきたいです。 `--debug-override-engine-files` とかですかね。(ほかの語彙としては replace, use あたりが浮かびます)

2022-01-17 07:15 UTC, xnv commented on packages/akashic-cli-export/src/html/cli.ts
> +			if (!/^engineFilesV\d_\d_\d+.*.js/.test(path.basename(options.injectEngineFiles))) {
- `.js` の `.` はエスケープしてください (`\.js`)。現状だと `.` (任意の1文字) 扱いされていそうです。
- 最後に `$` (行末) をつけたいです。 `engineFilesV0_0_0.jsfoo.txt` とかでもパスしていそうに見えます。
- 各 `\d` が一桁であることに依存しないでください。

総合すると `^engineFilesV\d+_\d+_\d+.*\.js$` ですかね。(未検証)

2022-01-17 07:15 UTC, xnv commented on packages/akashic-cli-export/src/html/convertUtil.ts
> +function loadScriptFile(fileName: string, templatePath: string, injectEngineFilesPath?: string): string {
- 引数の値によって別の引数が全く参照されなくなるのは、関数の切り方としてあまりクリーンではないと思います。
- また `injectEngineFilesPath` が指定されたファイルが存在しなかった場合、 [L221](https://github.com/akashic-games/akashic-cli/pull/983/files#diff-22299f7aa5d3da79d86da00e0ee9d9fedcc7464d3012559721607555e0777917R221) のエラーメッセージのファイル名が正しくない点も気になります。
   - 実際には `injectEngineFilesPath` の方は事前に存在確認が行われているので、このパスに入ることはあまりないわけですが、 (a) 存在確認後この箇所に到達するまでに削除されていない保証はありませんし、そうでないとしても (b) この関数単体の動作として正しいものではないでしょう)

もしこの分岐が必要なら、この関数を `loadScriptFile(filePath: string): string` に単純化して、 `path.resolve()` を呼び出し元に切り出しませんか。

2022-01-17 07:15 UTC, xnv commented on packages/akashic-cli-export/src/html/convertUtil.ts
> +	let preloadScripts = preloadScriptNames.map((fileName) => loadScriptFile(fileName, templatePath, injectEngineFilesPath));
`loadScriptFile()` の定義を見ると、 `inject〜` が指定されたら `fileName` の方は無視されるように見えます。 言い換えると、ここで `map()` しているということは、 `preloadScriptNames.length` の数だけ同じ内容のスクリプトが入っていそうですが、これは正しい実装でしょうか？

`injectEngineFilesPath` がある場合、ここで引数を変えるのではなく `preloadScriptNames` の値を変えるのが正道ではないでしょうか。

2022-01-17 07:15 UTC, xnv commented on packages/akashic-cli-export/src/html/convertUtil.ts
> +		if (matches) version = matches[0].slice(0, 1);
- ここで `version` を上書きする必要がある (＝引数で渡された `version` と違う値になる) のは一種の異常系なので、通すにしても警告したいです (「v2 のコンテンツなのに v3 の engineFiles を使おうとしている」みたいな状況でしか起きないはずです)。
- バージョンが一桁であることに依存してしまっています。 `/(\d+)_\d+_\d+/` で match して、 `match[1]` を使えば `slice()` ごと不要そうです。 (参考: https://developer.mozilla.org/ja/docs/Web/JavaScript/Guide/Regular_Expressions/Groups_and_Ranges#%E3%82%B0%E3%83%AB%E3%83%BC%E3%83%97%E3%81%AE%E4%BD%BF%E3%81%84%E6%96%B9)

2022-01-18 07:08 UTC, ShinobuTakahashi commented on packages/akashic-cli-export/src/html/cli.ts
> +	.option("--inject-engine-files <filePath>", "Use the injected engineFiles");
ありがとうございます。 `--debug-override-engine-files` へ変更しました。

2022-01-18 07:08 UTC, ShinobuTakahashi commented on packages/akashic-cli-export/src/html/convertNoBundle.ts
> +		if (matches) version = matches[0].slice(0, 1);
ありがとうございます。仰る通り、game.json の指定バージョン前提になるので engineFilesのバージョンと異なる場合はエラーとなるよう修正しました。

2022-01-18 07:08 UTC, ShinobuTakahashi commented on packages/akashic-cli-export/src/html/convertNoBundle.ts
> +		engineFilesVariable = path.basename(options.injectEngineFiles, ".js");
バージョン取得部分を関数に切り出し修正しました。

2022-01-18 07:09 UTC, ShinobuTakahashi commented on packages/akashic-cli-export/src/html/cli.ts
> +			if (!/^engineFilesV\d_\d_\d+.*.js/.test(path.basename(options.injectEngineFiles))) {
ありがとうございます。ご指摘いただいた正規表現で検証し修正しました。

2022-01-18 07:09 UTC, ShinobuTakahashi commented on packages/akashic-cli-export/src/html/convertUtil.ts
> +function loadScriptFile(fileName: string, templatePath: string, injectEngineFilesPath?: string): string {
仰る通りです。`loadScriptFile(filePath: string)` を単純化し、呼び出し元で `path.resolve()` を行うよう修正しました。

2022-01-18 07:09 UTC, ShinobuTakahashi commented on packages/akashic-cli-export/src/html/convertUtil.ts
> +	let preloadScripts = preloadScriptNames.map((fileName) => loadScriptFile(fileName, templatePath, injectEngineFilesPath));
`preloadScriptNames` は engineFile 名 一つのみ格納された変数でした。[L108](https://github.com/akashic-games/akashic-cli/blob/a9337a7bbf88b19a3762a97c0c34004110b51593/packages/akashic-cli-export/src/html/convertUtil.ts#L108)
`preloadScripts` を配列にするため `map` を使用していたと思われます。

`loadScriptFile()` の修正とあわせ `map`の使用をやめ単純に `loadScriptFile()` を呼ぶよう修正しました。

2022-01-18 07:09 UTC, ShinobuTakahashi commented on packages/akashic-cli-export/src/html/convertUtil.ts
> +		if (matches) version = matches[0].slice(0, 1);
ありがとうございます。正規表現と `slice()` 箇所修正しました。
また、`version` を上書きするのではなく、game.json とengineFiles のバージョンが異なる場合はエラーとなるようにしました。https://github.com/akashic-games/akashic-cli/pull/983#discussion_r784786573

2022-01-18 07:12 UTC, ShinobuTakahashi commented on packages/akashic-cli-export/src/html/convertBundle.ts
> +			throw "Unknown engine version: `environment[\"sandbox-runtime\"]` field in game.json should be \"1\", \"2\", or \"3\".";
catch 元で `logger.errror()` で出力しているため、`ERROR: Error: xxxxx` のような出力になるので、文字列のみthrow し `ERROR: xxxxx` の出力となるよう修正しました。

2022-01-20 07:49 UTC, dera- commented on packages/akashic-cli-export/src/html/convertNoBundle.ts
> +		engineFilesVariable = path.basename(options.injectEngineFiles, ".js");
あー、、すみません。行っておいて申し訳ないですが、バージョンを取得よりもバリデーションの関数として切り出した方が良い気がしてきましたね。engineFilesのバージョン情報はバリデーションに使うだけだと思いますし

2022-01-20 08:45 UTC, ShinobuTakahashi commented on packages/akashic-cli-export/src/html/convertNoBundle.ts
> +		engineFilesVariable = path.basename(options.injectEngineFiles, ".js");
確かにです。バリデーションの関数として切り出すよう変更しました。

2022-01-24 02:57 UTC, xnv requested changes

2022-01-24 02:57 UTC, xnv commented on packages/akashic-cli-export/src/html/cli.ts
> +		console.log("***val:", options.debugOverrideEngineFiles);
余計な console 出力が残っているようです。

2022-01-24 02:57 UTC, xnv commented on packages/akashic-cli-export/src/html/convertBundle.ts
> +			throw "Unknown engine version: `environment[\"sandbox-runtime\"]` field in game.json should be \"1\", \"2\", or \"3\".";
うーん……これ気にはなるんですが、そのままにしておきませんか。ここだけ変えても他の throw は変わりませんし、全部の throw を変えたとしてもなお Error が飛ぶ可能性はなくなりません (ファイル書き込み失敗とか null 参照とか)。その割に、どこかで catch した時に「Error じゃないものが来る」可能性を現実的に考慮する必要が生じます。

やるなら `logger.error()` の方で「 `instanceof Error` が真なら `message` プロパティを出力する」とかの方が網羅的ではないかと思います。

2022-01-24 02:57 UTC, xnv commented on packages/akashic-cli-export/src/html/convertNoBundle.ts
> +			path.join(jsDir, options.debugOverrideEngineFiles)
これ `DebugOverrideEngineFiles` がカレントディレクトリにないとか、絶対パスの時に正しく動くのでしょうか？

2022-01-24 02:57 UTC, xnv commented on packages/akashic-cli-export/src/html/convertUtil.ts
> +		// 実行途中でファイル名を変更されない限りこのパスに入ることはないが念の為。
このコメントは正しいでしょうか。実行途中でファイル名が変わっても起動時に渡された `overrideEngineFilesPath` には影響していないのでは？

2022-01-24 03:42 UTC, xnv commented on packages/akashic-cli-export/src/html/convertUtil.ts
> +export function validateEngineFileAndGameJsonVersion(overrideEngineFilesPath: string, gameJsonVersion: string): void {
- `gameJsonVersion` は `expectedMajorVersion` にしたいです。以下がきになるためです:
   - この関数レベルでは game.json に書かれていたことは関係ない点
   - 「game.json のバージョン」のように読める点
-  この箇所では `override` であることは関係ないと思います。また path であることもこの処理と関係ないので 呼び出し元で `basename()` して「ファイル名をチェックする関数」にしませんか。
- またそれらに合わせて名前も変えたいです。

総合すると `valdiateEngineFilesName(filename: string, expectedMajorVersion: string): void` でどうでしょうか。

2022-01-24 06:35 UTC, ShinobuTakahashi commented on packages/akashic-cli-export/src/html/convertUtil.ts
> +export function validateEngineFileAndGameJsonVersion(overrideEngineFilesPath: string, gameJsonVersion: string): void {
仰る通りです。引数含め `valdiateEngineFilesName()` へ修正しました。

2022-01-24 06:35 UTC, ShinobuTakahashi commented on packages/akashic-cli-export/src/html/convertUtil.ts
> +		// 実行途中でファイル名を変更されない限りこのパスに入ることはないが念の為。
仰る通り `overrideEngineFilesPath` には影響ありませんでした。そして、ファイル名の形式チェックは cli.ts で行っているためこのパスには入る事がないため削除しました。

2022-01-24 06:35 UTC, ShinobuTakahashi commented on packages/akashic-cli-export/src/html/convertNoBundle.ts
> +			path.join(jsDir, options.debugOverrideEngineFiles)
ご指摘の通り、絶対パス指定時に意図しないパスへコピーしていました。修正しました。

2022-01-24 06:35 UTC, ShinobuTakahashi commented on packages/akashic-cli-export/src/html/cli.ts
> +		console.log("***val:", options.debugOverrideEngineFiles);
ありがとうございます。削除しました。

2022-01-24 06:35 UTC, ShinobuTakahashi commented on packages/akashic-cli-export/src/html/convertBundle.ts
> +			throw "Unknown engine version: `environment[\"sandbox-runtime\"]` field in game.json should be \"1\", \"2\", or \"3\".";
確かに仰る通り、Error じゃないのを考慮する必要があります。 `logger` の方でやるのも筋だと思いますので、この修正を戻しました。

2022-01-25 03:23 UTC, xnv commented
テストコードの追加をお願いしたいです。 (コンテンツ自体は `spec/fixture/` の下のを使い回せそうなので、適当なダミーの engineFiles を指定して、bundle/非bundle 時でそれぞれ出力のファイル構成をチェックするぐらいの確認ができると良さそうです)

2022-01-25 09:25 UTC, ShinobuTakahashi commented on packages/akashic-cli-export/spec/fixtures/engineFilesV3_1_99.js
> +dummy-engineFilesV3_1_99
`mock-fs` で engineFiles のテスト対応しようと思いましたが、色々試してみたものの上手くいかず実ファイルを置きました。

2022-01-26 04:40 UTC, xnv approved these changes

2022-01-27 05:33 UTC, dera- approved these changes

2022-01-28 01:37 UTC, merged