Enable strict for init
akashic-games/akashic-cli pull request #999
Opened 2022-02-02 03:55 UTC by ShinobuTakahashi

## 概要

akashic-cli-init で strict を有効化します。

2022-02-03 02:45 UTC, xnv requested changes

2022-02-03 02:45 UTC, xnv commented on packages/akashic-cli-init/src/init/cloneTemplate.ts
> +export function createGitUri(host: string | null, protocol: GitProtocol, owner: string, repo: string): string {
必要でしょうか？　呼び出し元を見ても不要そうに見えますし、必要だとしても呼び出し元がやるべきことに思えます。型の上で null を許したところで、動作上は必ず `throw` する処理に入るわけで、であれば型的にもマッチしないようにしておくべきでしょう。

2022-02-03 02:45 UTC, xnv commented on packages/akashic-cli-init/src/init/TemplateConfig.ts
> +		formatVersion: "0",
`formatVersion: formatVersion ?? "0",` としておきたいです。

`"0"` 決め打ちするのは、現バージョンでは正しい (valid な値が `null`, `undefined`, `"0"` しかなく、ここでは valid なことを確認済みで、あとは正規化したら `"0"` しかありえない) んですが。将来 `"1"` を作った時にこの箇所の修正が必要になってしまいます。

2022-02-03 02:45 UTC, xnv commented on packages/akashic-cli-init/src/common/InitCommonOptions.ts
> +			opts.logger!.warn("Misused -r, --repository options. Use -t option for Github repository");
この箇所だと `logger` はないことがありうると思います。(呼び出し元で `logger` がない時を考慮する処理が、この呼び出しの後にある)

そもそも `validateInitCommonOptions()` という大振りな名前をやめて `validateRepositoryValue(repository: string, logger: Logger)` みたいににしませんか。(「オプション丸ごと全部引数にとって一部しか使わない関数」が多すぎて、オプションの変数が実質グローバル変数みたいなことになってしまい、それで全部リライトしたのが以前の init なので、その轍を踏みたくないです)

2022-02-03 02:45 UTC, xnv commented on packages/akashic-cli-init/src/__tests__/support/mockPrompt.ts
> +export function mock(config: {width: number | null; height: number | string; fps?: number}): void {
height の対応が不要なのがよくわからないのですが、これはどういう背景で必要なんでしょうか？

2022-02-03 02:45 UTC, xnv commented on packages/akashic-cli-init/src/__tests__/listTemplatesSpec.ts
>  			};
この辺、そもそも「元の関数をそのまま呼び出すが、引数の `configFile` だけ差し替える」ようなことはできないでしょうか？

2022-02-04 01:49 UTC, ShinobuTakahashi commented on packages/akashic-cli-init/src/__tests__/listTemplatesSpec.ts
>  			};
すいません、ここ書いたの私ですが、そのまま関数通すと validation の中でリポジトリURLが非公式な URL のためコマンドプロンプトの入力で止まってしまうので、`completeInitCommonOptions()` を mock してました。
コマンドプロンプトの入力箇所を mock すれば良いだけだったので、この箇所修正しました。

2022-02-04 01:49 UTC, ShinobuTakahashi commented on packages/akashic-cli-init/src/__tests__/support/mockPrompt.ts
> +export function mock(config: {width: number | null; height: number | string; fps?: number}): void {
下記で width に null が渡されたケースのテストを行ってるため、width のみ null 許容しています。
https://github.com/akashic-games/akashic-cli/blob/30f9a33f6ae68192d7cf4afa5bbe850c48c35ed9/packages/akashic-cli-init/src/__tests__/BasicParametersSpec.ts#L42

2022-02-04 01:49 UTC, ShinobuTakahashi commented on packages/akashic-cli-init/src/common/InitCommonOptions.ts
> +			opts.logger!.warn("Misused -r, --repository options. Use -t option for Github repository");
ありがとうございます。`validateRepositoryValue(logger: Logger, repository?: string)`  へ修正しました。

2022-02-04 01:49 UTC, ShinobuTakahashi commented on packages/akashic-cli-init/src/init/TemplateConfig.ts
> +		formatVersion: "0",
`formatVersion ?? "0"` へ修正しました。

2022-02-04 01:49 UTC, ShinobuTakahashi commented on packages/akashic-cli-init/src/init/cloneTemplate.ts
> +export function createGitUri(host: string | null, protocol: GitProtocol, owner: string, repo: string): string {
仰る通り、null の場合は必ず throw 処理に入ります。`InitParameterObject.gheHost` の型を `string` にし、省略時は 空文字とするように修正し、この箇所の変更を戻しました。

2022-02-04 03:49 UTC, xnv commented on packages/akashic-cli-init/src/__tests__/support/mockPrompt.ts
> +export function mock(config: {width: number | null; height: number | string; fps?: number}): void {
ユーザ入力によって null がありうるなら、 height も fps も null を許容する (か事前にチェックする) べきに思えます。そうでないなら、単にテスト項目を変えたいですね……。

2022-02-07 03:19 UTC, ShinobuTakahashi commented on packages/akashic-cli-init/src/__tests__/support/mockPrompt.ts
> +export function mock(config: {width: number | null; height: number | string; fps?: number}): void {
height, fps も null を許容するよう修正しました。

2022-02-08 04:51 UTC, xnv commented on packages/akashic-cli-init/src/init/InitParameterObject.ts
> +	gheHost?: string;
全体的に、無効な値を空文字列 (や 0 や -1) にするのはやめませんか。 `null` なり `undefined` で明示的に扱いたいです。なぜなら、そもそも strict にしたい理由の一つは、「無効な値」を型の上で明示的に扱うことだからです。

strict でないコードでは、「型上 string だが実際には無効な値 (null)」ということがありえます。ここで "無効な値" を空文字列にしてしまうと、 strict にしてさえも「型上は string だが実際には無効な値 (空文字列)」ということが起き、strict する価値が薄くなってしまいます。

2022-02-08 04:51 UTC, xnv commented on packages/akashic-cli-init/src/common/InitCommonOptions.ts
> +async function validateRepositoryValue(logger: Logger, repository?: string ): Promise<void> {
export する関数でもなく、呼び出し箇所も限られるので、省略可能である必要はないと思います。もし undefined が渡るなら、 `?` で省略を許すのではなく、明示的に `string | undefined` と書きたいです。(それは省略とは別物なので)

2022-02-10 01:46 UTC, ShinobuTakahashi commented on packages/akashic-cli-init/src/init/InitParameterObject.ts
> +	gheHost?: string;
ありがとうございます。仰る通りです。無効値の空文字をやめ明示的に null を型にするよう修正しました。

2022-02-10 01:46 UTC, ShinobuTakahashi commented on packages/akashic-cli-init/src/common/InitCommonOptions.ts
> +async function validateRepositoryValue(logger: Logger, repository?: string ): Promise<void> {
仰る通りです。引数の型を `string | undefined` へ修正しました

2022-02-10 01:49 UTC, ShinobuTakahashi commented on packages/akashic-cli-init/src/init/init.ts
> +			param.gheHost!,
17行目の `completeInitParameterObject()` で `gitType === "ghe"` で `gheHost` が null の場合はエラーとなるため非nullアサーションをつけてます。

2022-02-10 09:48 UTC, kamakiri01 approved these changes

2022-02-14 06:41 UTC, xnv approved these changes
コメント加えていますが approved.

2022-02-14 06:41 UTC, xnv commented on packages/akashic-cli-init/src/__tests__/InitParameterObjectSpec.ts
> +			const items = await mockConfigfile!.getItem(ITEM_KEY);
今更ですが、「 `beforeAll()` で入れて `afterAll()` で削除するもの」は 、型上は「 ` | null` にしない」方が自然ではないでしょうか。初期化の時に `let mocConfigFile: config.AkashicConfigFile = null!;` で `!` をつければ後の箇所は不要に思えます。

というのも、現状全部の箇所に `!` をつけられているわけですが、それって結局のところ「全箇所絶対に null でない」ものとしてコードを書いているのと同じだからです。むしろこの書き方だと「どこかには `!` をつけずに null チェックする箇所があるかもしれない」という (余計な) 心配も生じます。

2022-02-14 06:41 UTC, xnv commented on packages/akashic-cli-init/src/init/init.ts
> +			param.gheHost!,
この旨 `//` コメントで書いておきませんか。(本当はもうちょっと上手い型上でのハンドリングを考えられると良さそうですが、それはさておき)

2022-02-14 07:35 UTC, ShinobuTakahashi commented on packages/akashic-cli-init/src/init/init.ts
> +			param.gheHost!,
コメント追加しました。

2022-02-14 07:35 UTC, ShinobuTakahashi commented on packages/akashic-cli-init/src/__tests__/InitParameterObjectSpec.ts
> +			const items = await mockConfigfile!.getItem(ITEM_KEY);
確かに仰る通りです。`beforeAll()` で必ず代入するので、コメントを追加し非 null 型へ修正しました。

2022-02-16 05:29 UTC, ShinobuTakahashi commented
最新の commons, extra を取り込み CI が通ることを確認。

2022-02-16 05:29 UTC, merged